### ISSUE TITLE
Making Fhir engine a singleton per process per db name

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#100]
Following discussions between @yigit @florina-muntenescu @jingtang10, we decided to make fhir engine a singleton per process + db name to avoid racing conditions when updating the db

- [x] Modify FhirEngine's API so that it's impossible to create another instance if there is already one (i.e. caching). At the moment in the referende app this is ensured by the initialization code in `FhirApplication.kt` using `by lazy`. But we want to be in the engine itself
- [x] Mark the `inMemory()` API as internal since we're only using it in tests and definitly don't want users to actually create in-memory db
- [x] Simplify the initialization code and remove the db name option (it's not used anywhere anyway)

**Comment by deepankarb** [comment]
For reference, an example multiple instance design: https://github.com/firebase/firebase-android-sdk/blob/a23223a84de07c1797ca4b1b4ac2095c3d04c800/firebase-common/src/main/java/com/google/firebase/FirebaseApp.java
