### ISSUE TITLE
Public releases cannot be used due to internal dependency issue

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1005]
**Describe the bug**
Depending on our public libraries in an android app throws a build error.

```
6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find android-fhir:common:unspecified.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/android-fhir/common/unspecified/common-unspecified.pom
       - https://repo.maven.apache.org/maven2/android-fhir/common/unspecified/common-unspecified.pom
       - https://jcenter.bintray.com/android-fhir/common/unspecified/common-unspecified.pom
     Required by:
         project :app > com.google.android.fhir:data-capture:0.1.0-beta01
```

**Component**
SDC library

**To Reproduce**
1. Create a new android project
2. Add dependency on the data capture lib: `implementation("com.google.android.fhir:data-capture:0.1.0-beta01")`
3. Build app

**Expected behavior**
App should build.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - Android version: 12

**Additional context**
NA

**Would you like to work on the issue?**
Yes

See discusions on stackoverflow about this issue:

https://stackoverflow.com/questions/54831685/how-to-publish-and-use-gradle-plugin-with-dependencies-on-local-project
https://stackoverflow.com/questions/53353379/publishing-artifact-directly-including-gradle-submodules

Solutions:
1. Create and publish a common module and depend on that one as if it's an external dependency
2. Use the shadow plugin to include the `:common` module source code in the maven publish tasks
3. Remove the common module and put those files back into the separate modules

**Comment by jingtang10** [comment]
https://github.com/johnrengelman/shadow/issues/44

**Comment by jingtang10** [comment]
https://petrakeas.medium.com/publish-a-multi-module-java-android-library-to-maven-central-github-ci-automation-at-2021-4f98a311df2a

**Comment by jingtang10** [comment]
Discussed this with @yigit. Mainly focused on 2 approaches (I think approach 3 is a no-go):

1. Create a new common library and publish to maven
2. Use shading and create a jarjar (e.g. using the gradle java shadow plugin) to include the common utilities in the calling site

Approach 1
Pros
- how things are normally done according to @yigit 
- no code duplication
Cons
- maintainance cost of maintaining another lib, albeit small

Approach 2:
Pros
- zero maintainance cost
Cons
- not clear how to set this up easily (java shadow plugin doesn't seem to work smoothly with android)
- code will be duplicated if multiple libraries (e.g engine+sdc) share the same utility functions

Overall @yigit's recommendation is to do 1.

**Comment by yigit** [comment]
for API tracking (which we kind of need now anyways), we can consider using:

https://github.com/Kotlin/binary-compatibility-validator

sample integration (a bit old though); https://github.com/dropbox/Store/pull/97
