### ISSUE TITLE
Catalog app, implement single choice workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1006]
**Is your feature request related to a problem? Please describe.**
1. User click on single choice component.
2. It launches single choice screen with questionnaire, which demonstrate single choice uses.
3. click on navigation back key in action bar, it takes user back on landing page.

Design single choice questionnaire json.
Write api to fetch single choice questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Datacapture, custom style does not get applied to the single choice options.
https://github.com/google/android-fhir/issues/1007

**Comment by varunkuar8789** [comment]
Lebal
