### ISSUE TITLE
SDC Catalog App Crashes 

### ISSUE THREAD

**Issue by Manikant25** [google/android-fhir#1009]
**Describe the bug**
App crashes on clicking item "Neonate Record from New South Wales.."

**Component**
 SDC gallery app

**To Reproduce**
1. Go to 'SDC App'
2. Click on 'Neonate Record from New South Wales..'
3. See error

**Expected behavior**
It should have open questionaire like other items.

**Screenshots**
Logs
<img width="1792" alt="Screenshot 2022-01-10 at 1 10 06 AM" src="https://user-images.githubusercontent.com/55659857/148698057-9a497d46-3a75-4cf3-8bfe-7a9038eb6dfb.png">

**Smartphone (please complete the following information):**
 - Motorola G51
 - Android 11

**Additional context**
Nope

**Would you like to work on the issue?**
Not now

**Comment by epicadk** [comment]
The error is due to `Mismatching question type DATETIME and answer type dateTime for vitaminKDose1`
