### ISSUE TITLE
Add m3 dependency to the demo apps and data capture module.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1012]
**Is your feature request related to a problem? Please describe.**
1. Add m3 dependency to the reference apps and datacapture library.
2. Add material componnet dependency `com.google.android.material:material:1.5.0-alpha04` or later version.
3. Update android compile sdk version from 30 to 31
4. Update android target sdk version from 30 to 31

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Anshul-9923** [comment]
@santosh-pingle I understood the issue. Can you please assign me this issue?
