### ISSUE TITLE
Catalog app, implement modal workflow

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1019]
**Is your feature request related to a problem? Please describe.**
1. User click on modal component.
2. It launches modal screen with questionnaire, which demonstrate single choice uses.
3. click on navigation back key in action bar, it takes user back on landing page.

Design modal questionnaire json.
Write api to fetch modal questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm 

To show the modal, it requires minimum 10 options. In figma it has only 6 options, could you please add 4 more options to the list?

**Comment by shelaghm** [comment]
I've updated the figma. Will send you link directly. Curious to learn more about why there's a minimum of 10 options for a modal? Since it reduces the amount of screen space, it seems a little surprising.

**Comment by santosh-pingle** [comment]
<img width="438" alt="Screen Shot 2022-01-13 at 9 18 58 PM" src="https://user-images.githubusercontent.com/86107848/149362840-c3f2fdd0-0a14-4967-97cb-dc773e45cef1.png">
