### ISSUE TITLE
Catalog app, implement dropdown component workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1025]
**Is your feature request related to a problem? Please describe.**
1. User click on dropdown component.
2. It launches dropdown screen with questionnaire, which demonstrate dropdown uses.
3. click on navigation back key in action bar, it takes user back on landing page.

Design dropdown questionnaire json.
Write api to fetch dropdown questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm 
I am thinking not to have first field which is name(input type EditText) in the questionnaire screen, and just to add drop down questionnaire item which is relationship. As this workflow is mainly design for drop down questionnaire view.

Please let me know your input on it.

**Comment by santosh-pingle** [comment]
When item get clicked from drop down list, it shows blue color background on click. At this moment I tried to find the way to change it but not sure about the option, I need to look into it further.

**Comment by shelaghm** [comment]
@santosh-pingle 
1. Yes, let's remove text field above. 
2. Can you upload a screenshot of what it looks like on click? If it is the default material blue background it might be okay.
