### ISSUE TITLE
Catalog app, custom style does not get applied to modal content.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1027]
**Describe the bug**
Below component gets shown on modal/dialog.
1. open-choice
2. radio buttons
3. check boxes
But none of above mentioned component accepts custom style in modal.

To fix this issue below changes are required
In `OptionSelectDialogFragment` use MaterialAlertDialogBuilder and pass attribute which reference themeOverlay of MaterialAlertDialog.

**Component**
SDC library, Catalog app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
#1026

**Comment by santosh-pingle** [comment]
#1019

**Comment by jingtang10** [comment]
the first thing to work out is if we want to provide a version of these widgets that are not in an modal dialog. @shelaghm @kevinmost until this is resolved i think this is blocked.

i think @shelaghm made an argument to not use modal dialogs for these widgets.

**Comment by shelaghm** [comment]
@jingtang10 @santosh-pingle @kevinmost 

Yes, let's align on the use of modals for these widgets. My perspective is that the modal adds a step/click and that on small phones it can reduce the amount of choices we can display on the screen, so I recommend we move away from modals. Modals are great for decision dialogs, so we will likely want to still have a dialog/modal functionality, just not for this specific use case of choice selections. However, I don't know all the background of how we landed on modals, so feel free to chime in with other perspectives. What do you all think?

I imagine the default view for checkboxes / radio buttons would be something like this:
<img width="344" alt="Screen Shot 2022-01-18 at 15 12 11" src="https://user-images.githubusercontent.com/86378921/150033603-663ebd2a-4cce-4eb7-87ed-6c4dc5964e70.png">

**Comment by jingtang10** [comment]
@juanchazo fyi
