### ISSUE TITLE
Mismatch between setting questionnaireResponse.questionnaire and validating it

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1028]
**Describe the bug**
In QuestionnaireResponseValidator.kt we check if questionnaire.url == questionnaireResponse.questionnaire whereas in the QuestionnaireViewModel we set  questionnaireResponse.questionnaire to questionnaire.id

**Component**
 SDC library

**To Reproduce**
1. Answer a questionnaire which has a different id and url
2. Save the questionnaire response
3. Pass both the questionnaire and the response to the fragment

url - Canonical identifier for this questionnaire, represented as a URI (globally unique)
id - Each resource has an id element which contains the "logical id" of the resource assigned by the server responsible for storing it. The location of a resource instance is an absolute URI constructed from the server base address at which the instance is found, the resource type and the Logical ID, such as http://test.fhir.org/rest/Patient/123 (where 123 is the Logical Id of a Patient resource).

**Comment by joiskash** [comment]
Work around is to set the url to be Questionnaire/"id"

**Comment by jingtang10** [comment]
yes we should set the url rather than id when generating the questionnaire response.

see https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Editing.20a.20questionnaire.20response/near/265556798.
