### ISSUE TITLE
initialExpression extension for advanced form behaviour

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1033]
**Is your feature request related to a problem? Please describe.**
When rendering a Questionnaire via the data capture library, I need to be able to use an expression to set an initial value - see [SDC Expressions](http://build.fhir.org/ig/HL7/sdc/expressions.html)

**Describe the solution you'd like**
SDC Library support for initialExpression extension using FHIRPath

For example:
* Set a value to current date - %today()
* Set name of the first patient - %patient.name.where(use='official').given.first()
* Set the gender of the patient - %patient.gender

For other examples, see [sample questionnaire](http://build.fhir.org/ig/HL7/sdc/Questionnaire-questionnaire-sdc-profile-example-form-behavior.html)

**Describe alternatives you've considered**
CQL or Questionnaire population

**Comment by RaaziaTarique** [comment]
In order to implement this issue, the approach that I am going to use will be as follows.

1.  Check if the expression starts with `today()`, then inside this will check if days are being added to or subtracted from `today()` if yes then perform the operation else return current date.
2.  Try to fetch answer based on provided resource and expression if not succeeded then fetch answer using definition if provided.
3. Use `FhirPath` to evaluate expressions.

Currently, `FHIRLexar` is only able to recognize expressions without `where()` and any function call.
I have one question should I handle every possible expressions mentioned here http://hl7.org/fhirpath on SDK side?

CC: @f-odhiambo @ndegwamartin @maimoonak @jingtang10 @Tarun-Bhardwaj

**Comment by RaaziaTarique** [comment]
> In order to implement this issue, the approach that I am going to use will be as follows.
> 
> 1. Check if the expression starts with `today()`, then inside this will check if days are being added to or subtracted from `today()` if yes then perform the operation else return current date.
> 2. Try to fetch answer based on provided resource and expression if not succeeded then fetch answer using definition if provided.
> 3. Use `FhirPath` to evaluate expressions.
> 
> Currently, `FHIRLexer` is only able to recognize expressions without `where()` and any function call. I have one question should I handle every possible expressions mentioned here http://hl7.org/fhirpath on SDK side?
> 
> CC: @f-odhiambo @ndegwamartin @maimoonak @jingtang10 @Tarun-Bhardwaj

After Exploring the FhirPathEngine further, I came to know that it has multiple overloaded methods for evaluating FhirPath expressions. So, I modified the approach that I proposed before as follows,

1.  Get answers using FhirPathEngine evaluate method `List<Base> evaluate(Base base, String path) throws FHIRException`
2.  If above method is not able to evaluate expression then will evaluate expression using `List<Base> evaluate(Base base, ExpressionNode ExpressionNode) throws FHIRException`
3.  If unable to evaluate to expressions using above mentioned methods then fetch answer using definition if provided.

@jingtang10 CC: @f-odhiambo

**Comment by jingtang10** [comment]
Looking through the code of FHIRPathEngine https://github.com/hapifhir/org.hl7.fhir.core/blob/b075c5695ffa7267ef7010f8e560731d20a90383/org.hl7.fhir.r4/src/main/java/org/hl7/fhir/r4/utils/FHIRPathEngine.java#L502 the code for `evalute(Base,String)` and `evaluate(Base,ExpressionNode)` are pretty similar - are you sure your step 1 and 2 will generate different results?

**Comment by RaaziaTarique** [comment]
@jingtang10 I checked the methods, they are actually almost identical and doing the same job. I can modify step one to use only this method `List<Base> evaluate(Base base, String path) throws FHIRException` and pass resource from provided resources if any and then use definition if there's no answer found using expression.

**Comment by RaaziaTarique** [comment]
Related to the expressions that are not currently supported, I posted a query here https://chat.fhir.org/login/#narrow/stream/179255-questionnaire/topic/FHIRPATH.20SDC.20implementation
<img width="886" alt="Screenshot 2022-03-18 at 2 21 32 PM" src="https://user-images.githubusercontent.com/89384079/159010501-0e029da7-8d14-49c1-9c9e-6641dc7f61f8.png">
@jingtang10  CC: @f-odhiambo @shoaibmushtaq25

**Comment by delcroip** [comment]
Dear, 

I just realized that initialExpression is part of the [populate questionnaire](http://build.fhir.org/ig/HL7/sdc/populate.html), if this is not supported, then does the SDK support [Observation-based Population](http://build.fhir.org/ig/HL7/sdc/populate.html#observation-based-population) or [StructureMap based population](http://build.fhir.org/ig/HL7/sdc/populate.html#structuremap-based-population) ?

thanks again for your work

best regards

**Comment by fredhersch** [comment]
> Dear,
> 
> I just realized that initialExpression is part of the [populate questionnaire](http://build.fhir.org/ig/HL7/sdc/populate.html) and not a extension to be managed by the form filler, if this is not supported, then does the SDK support [Observation-based Population](http://build.fhir.org/ig/HL7/sdc/populate.html#observation-based-population) or [StructureMap based population](http://build.fhir.org/ig/HL7/sdc/populate.html#structuremap-based-population) ?
> 
> thanks again for your work
> 
> best regards

We currently support Expression Based population - https://github.com/google/android-fhir/wiki/Structured-Data-Capture-Library#questionnaire-population

This extension allows for adding an expression as part of the population e.g. time.now() versus setting the value of a field that was previously collected

**Comment by delcroip** [comment]
@fredhersch does it means that this issue can be closed ?

(all the related work will be usefull for other expressions)

**Comment by jingtang10** [comment]
this issue can be closed after two things:

- [ ] the issue Raazia is fixing. which is that in some cases we're not providing the context to fhir path engine correctly, causing it unable to evaluate expressions such as `today()`.
- [ ] we will also need a follow up PR to handle the population context properly using the launch context and population context extensions.
