### ISSUE TITLE
Support for answerExpression extension

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1039]
**Is your feature request related to a problem? Please describe.**
Issue: #979 

When building a data collection questionnaire, there is often a need to filter the options in a drop down list based on the selected answer to an earlier list. For example: Country > State > City - see #979 

**Describe the solution you'd like**
Enable dynamic filtering of answerOptions using answerExpression with FHIRPath - see [here](http://build.fhir.org/ig/HL7/sdc/expressions.html)

In the scenario in issue #979, where there are Country > State > City, each of which the answerOptions comes from a valueSet, the following should happen:

- If country is USA
- Populate the State lists with ValueSet of states from USA
- When changing the value of the State, the City list is updated

**Describe alternatives you've considered**
Using nested set of enableWhen components

**Other information**
For Ux example of dynamically updating lists see issue #979

**Comment by f-odhiambo** [comment]
Update on this ticket 
We are unable to find any example questionnaires as this expression is still in draft from FHIR side.
http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-answerExpression.html ,
http://hl7.org/fhir/R4/versions.html#std-process

**Comment by Tarun-Bhardwaj** [comment]
@fredhersch @jingtang10 is there sample questionnaire that can be used in order to unblock this issue?

**Comment by jingtang10** [comment]
@fredhersch i think the example with country/state/city in the original description of this issue doesn't quite match the exampel given in here http://build.fhir.org/ig/HL7/sdc/expressions.html#answerExpression for answerExpression.

From what we can see (discussed with @f-odhiambo @RaaziaTarique @maimoonak) the way this works is very similar to candidateExpression (see #1038), but answerExpression has very low maturity level. So we should definitely seek some clarity on fhir chat. 1) what's the diff between answerExp and canddiateExp and 2) with the maturity level being 0 is it worth implementing this.

**Comment by RaaziaTarique** [comment]
@jingtang10 I posted the query to zulip chat and got this reply https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/expression.20library/near/282944010
<img width="869" alt="Screenshot 2022-05-19 at 9 55 25 PM" src="https://user-images.githubusercontent.com/89384079/169393817-171af148-81c2-4d6e-9f36-8f55c62c0c9a.png">
CC: @f-odhiambo @maimoonak

**Comment by fredhersch** [comment]
Thanks @RaaziaTarique @jingtang10 I've actually posted a follow up question on the FHIR chat to get some input. I see the point on the maturity level - thanks for flagging that - let's see what comes back. 

I suppose we could use candidateExpression for the first set of options and constrain them to only select from the set provided (is this possible?).

What I don't understand is how you would then populate the next set of drop-down's based on the answer to the first drop-down. That is really what we are trying to achieve here.

Thoughts?

**Comment by fredhersch** [comment]
@RaaziaTarique @jingtang10 @pld - I posted this on [FHIR Chat](https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/expression.20library) and get the following response from Lloyd Mackenzie.

<img width="883" alt="Screen Shot 2022-05-23 at 1 49 26 PM" src="https://user-images.githubusercontent.com/34733/169751938-adfcfa18-bf5a-4090-804b-501e90c897c8.png">

**Comment by fredhersch** [comment]
@Tarun-Bhardwaj Should this be closed? I think answerExpression was covered in a different issue.

cc: @jingtang10

**Comment by Tarun-Bhardwaj** [comment]
As per chat with @maimoonak , closing the issue as it is resolved.
