### ISSUE TITLE
Add ability to validate the min/max for Date on a FHIR Questionnaire 

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#1040]
**Is your feature request related to a problem? Please describe.**
Add ability to limit the date input values to either the minimum or maximum date allowed for a given use case e.g. 
1. A task should not start before a certain date 
2. When adding DOB, the DOB should be less than the current day/today 
3. When scheduling you can validate when a given task should be done or assigned to a given practitioner 

**Describe the solution you'd like**
1. To be able to resolve expressions such as today() in the min-max value extension
2. To use the min-max value extension in the actual date picker pop-up. at the moment the pop-up dialogue allows the user to put in any date and the error message only kicked in once the user has input a date.

**Describe alternatives you've considered**
1.  It would be much better if the date picker already doesn't allow the user to input a date outside the allowed range.

**Additional context**
A detailed use case is defined on this ticket https://github.com/opensrp/fhircore/issues/845 on OpenSRP FHIR Core repo

**Would you like to work on the issue?**
@RaaziaTarique

**Comment by RaaziaTarique** [comment]
@f-odhiambo, yes I can work on this issue.

**Comment by f-odhiambo** [comment]
Updated from @aurangzaibumer 

Had a technical discussion with @maimoonak 

1. if I get a direct value, will directly use it in calendar constraint
2. if I get an extension inside an extension that is cqf-caluclated value then we have to process it through fhir path engine and get the desired result and apply it on calendar constraints.
4. Was  able to get the valueDate from the minValue and maxValue expression (as extensions) with values in the questionnaire (that  have been applied on the calendar constraint of the date picker) now I have to do research on how it can be done through cqf-calculated value just like Maimoona suggested
