### ISSUE TITLE
Catalog, text field component workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1043]
**Is your feature request related to a problem? Please describe.**

1. User click on text field component.
2. It launches text field screen with questionnaire, which demonstrate text field uses.
3. Click on navigation back key in action bar, it takes user back on landing page.
4. Design text field questionnaire json.

Design text field questionnaire json.
Write api to fetch textfield questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
To show a lable, helper text, icon in the edit-text-input is not supported yet by datacapture. These are feature request changes. Also, it is required to check how these generic values will be passed to the datacapture in questionnaire.

**Comment by santosh-pingle** [comment]
@shelaghm 

Datacapture also provide text field view for type decimal, text. We also need to include those.

**Comment by santosh-pingle** [comment]
<img width="440" alt="Screen Shot 2022-01-17 at 4 18 35 PM" src="https://user-images.githubusercontent.com/86107848/149756532-f2c9ddf1-8e54-4d8f-833a-23aca838d7be.png">
<img width="436" alt="Screen Shot 2022-01-17 at 4 20 53 PM" src="https://user-images.githubusercontent.com/86107848/149756546-18bf73aa-c6c8-409f-9f20-cf5323d9d454.png">

**Comment by santosh-pingle** [comment]
Existing edit text view expects below changes in the view component in the datacapture module, also it requires to pass these generic values in the questionnaire.

1. Currently, it does not support the label, helper, hint texts.

**Comment by shelaghm** [comment]
@santosh-pingle What's an example of a decimal data type? 
> Datacapture also provide text field view for decimal, text data types. We also need to include those views.

Feedback on screenshots: 
The padding between elements should be 24px, so 24 pixels between the title and the text field, and 24px between each text field.

**Comment by santosh-pingle** [comment]
#1087
