### ISSUE TITLE
Catalog, date picker component workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1045]
**Is your feature request related to a problem? Please describe.**

1. User click on date picker component.
2. It launches date picker screen with questionnaire, which demonstrate date picker uses.
3. Click on navigation back key in action bar, it takes user back on landing page.
4. Design date picker questionnaire json.

Design date picker questionnaire json.
Write api to fetch date picker questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
(Below items are feature changes in datacapture module in date picker view.)
1. Currently, there is no provision to show subtitle text (texts which are shown below question item text) e.g `First day of most recent period`.
2. Existing view does not support label. (date text on input text field)
3. It does not show helper text. (date format text below input text field)
4. It does not accept date as keyboard input. (user can not enter date by typing on soft keyboard.)

**Comment by shelaghm** [comment]
@santosh-pingle Thanks for adding what's not possible to do yet. 
1. I think the light blue color (looks like Blue 50, secondary color) on the top bar should be white (FFFFFF), with Grey 900 (#202124) text
2. The selected day circle should to be Blue 600 (#1A73E8) (primary color) with white text.
3. Is there a way to make this widget more full width, so that it only has 24px padding on each side?

**Comment by santosh-pingle** [comment]
> @santosh-pingle Thanks for adding what's not possible to do yet.
> 
> 1. I think the light blue color (looks like Blue 50, secondary color) on the top bar should be white (FFFFFF), with Grey 900 (#202124) text
> 2. The selected day circle should to be Blue 600 (#1A73E8) (primary color) with white text.
> 3. Is there a way to make this widget more full width, so that it only has 24px padding on each side?
> 4. "2022" should say "Select date" instead
> 
> ![Date picker 5](https://user-images.githubusercontent.com/86378921/150037937-9f7306b9-5c07-4f62-bd3f-36b0404c781b.png)

@shelaghm 
To make this change possible, datacapture library need to include material date picker, created issue #1109 for library change, and once this widget get added, custom style can be applied to it. I was just trying with these changes, created issue #1108, please refer for more details.
