### ISSUE TITLE
Catalog, update component icons with shadows.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1047]
**Describe the bug**

Below component icons does not show shadow in the component list.

1. datepicker
2. defaultLayout
3. modal
4. paginatedLayout
5. rangePicker
6. readOnlyLayout
7. reviewLayout
8. timePicker.

**Component**
 reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm 
Thanks for sharing icons.
But when I open these icons in the android studio, I am not sure whether I see shadow/elevation in the preview.
Can you please confirms once whether shared icon has shadow?

Just for reference I am attaching some screenshots of icons when they were opened in the android studio preview.


<img width="698" alt="Screen Shot 2022-01-18 at 11 38 02 AM" src="https://user-images.githubusercontent.com/86107848/149881732-e9e929a6-e8c2-44c3-bedd-46ed28120278.png">
<img width="422" alt="Screen Shot 2022-01-18 at 11 38 26 AM" src="https://user-images.githubusercontent.com/86107848/149881754-a177d560-118c-4d93-8794-22d3695b47a5.png">
<img width="577" alt="Screen Shot 2022-01-18 at 11 38 39 AM" src="https://user-images.githubusercontent.com/86107848/149881939-95f75f9f-754a-4d0c-9b58-df957b01362f.png">
<img width="420" alt="Screen Shot 2022-01-18 at 11 38 55 AM" src="https://user-images.githubusercontent.com/86107848/149881948-758fdf9e-4fcf-4288-8aa8-ca3217e4b148.png">

**Comment by shelaghm** [comment]
@santosh-pingle I re-designed the icons so they no longer have any shadows. So these look correct. Thanks for checking with me.

**Comment by Tarun-Bhardwaj** [comment]
Design has been updated by Shelagh hence closing the bug.
