### ISSUE TITLE
Datacapture, open choice input text field does not open soft keyboard on user click.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1048]
**Describe the bug**

1. Open that SDC Gallery app.
2. Click on General health assessment questionnaire item, it opens questionnaire/survey screen.
3. Click on `please select your gender`, it opens modal.
4. Click on other radio button option, it shows input text field with text `enter custom option`
5. Click on text input field, it does not show soft keyboard on click to enter the text as input.

**Component**
SDC library, SDC gallery app

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/86107848/149887687-e619cd56-5dee-44e7-98ff-33b9dd5ef9ce.mov

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4, Emulator Pixel XL API 30
 - Android version: 11
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@kevinmost

**Comment by Anshul-9923** [comment]
@santosh-pingle I understood the issue and want to work on this issue. Can you please assign me this issue?

**Comment by santosh-pingle** [comment]
@Anshul-9923 thanks for showing interest, let me connect you with @jingtang10

**Comment by Anshul-9923** [comment]
@santosh-pingle Can I start working on the issue?

**Comment by Anshul-9923** [comment]
@epicadk Can you please assign me this issue?

**Comment by santosh-pingle** [comment]
https://github.com/google/android-fhir/pull/1296
