### ISSUE TITLE
FHIR parser parses Patient model that the backend doesn't accept

### ISSUE THREAD

**Issue by elviasiv** [google/android-fhir#1053]
I'm trying to push an update to my Patient model in the API. 

The problem is that when I `GET` the patient using `Postman` I get the results I want to:

![image](https://user-images.githubusercontent.com/35890452/150353093-7d26293a-f5ff-4c3b-a70d-45c446b335f4.png)

but when I `GET` the patient from my app, it goes through parser and this is the result I get:

![image](https://user-images.githubusercontent.com/35890452/150353782-fdbe0486-aa4e-4a11-8b1d-44fa0807ee9c.png)

Now if I try to update some of the fields and push for `UPDATE`, it just doesn't accept the format. For exmaple, FHIR `Patient` model has id as an object, but the API needs id as a string or API needs `resourceType` but FHIR Patient model doesn't have that field and so on.

This is the parser that I'm trying use:

![image](https://user-images.githubusercontent.com/35890452/150354437-b4d7ad0d-0adb-495e-901b-2bcb4bdbe51e.png)

I tried changing the parser to many different outcomes, but the result is the same. Now the `value.string()` is the correct one (before going through the parser) I need, but I cannot assign it to the `Patient` model that I get.

So the question is am I even doing this right? Do I need to make my own `Patient` model that fits what I get from API?

Any bit helps, I can provide more info on whatever is needed.

**Comment by epicadk** [comment]
If you also want to store the data on android you could use the [fhir engine](https://github.com/google/android-fhir/tree/master/engine). If not then this may be the wrong place for this issue. Try asking https://github.com/hapifhir/hapi-fhir or chat.fhir.org

**Comment by jingtang10** [comment]
Thanks @elviasiv for raising this issue. can you share the actual error message when you say it doesn't accept the format?

what modifications have you made? if you fork the repo can you share your branch?

@aditya-07 @anita-vadverao fyi

**Comment by elviasiv** [comment]
Hey @jingtang10 thanks for replying! I currently fixed the issue temporarily by creating my own `Patient` model and parsing everything with Gson, so in order to get correct errors I'll need to redo everything back to FHIR patient.

But general errors I got was pretty much wrong format of the data I'm trying to send. For example - the FHIR parsed patient data has `ID` as an object while the API accepts ID only as a string.

**What it accepts:**

![image](https://user-images.githubusercontent.com/35890452/151997610-b15c7de4-90de-4b07-b9ff-e6fd28853e61.png)

**What parser gives me:**

![image](https://user-images.githubusercontent.com/35890452/151997755-9d2c14e9-48d4-4ef1-8f97-bbace98f4633.png)

I changed the object ID to string just for experimenting and the next error was that it asked for `resourceType` field, but the parsed data doesn't have that field (there is a similar one in ID object though).

I haven't made any modifications to FHIR `Patient` model or to the lib

**Comment by jingtang10** [comment]
Are you able to share the actual branch? It's very difficult to see what you have done without seeing the code.

Thanks

**Comment by Tarun-Bhardwaj** [comment]
@elviasiv , could you please share the actual branch so that it can help us move ahead with the fix?

**Comment by elviasiv** [comment]
@Tarun-Bhardwaj I apologise for being inactive for so long, it's been a busy month! 

Yes, I still have this issue, however I solved it with making my own `Patient` model that fits what the back-end accepts.

Due to the sharing of the branch, I cannot as the code is company code and I don't have branch of it on github. However I can provide parts of the code if that would help.

As I proceeded to work further, I got the same issue regarding the `HeartRate`. The one that is being generated in code is not accepted in the back-end. I'm thinking of solving it the same way I did with patient, just make my own `HeartRate` model. Fixing the `Patient` part would most likely solve `HeartRate` as well.

**Comment by Tarun-Bhardwaj** [comment]
@elviasiv , what version of FHIR are you using? R4 or some earlier version? Providing parts of code would be helpful.

**Comment by jingtang10** [comment]
looking at your code again - i think the issue was that you were serializing the patient resource using gson lib. the correct way of doing this to talk to a fhir server is to use hapi's serialization library.

@williamito i wonder if we need to document this somewhere as well.

@elviasiv i'll close this for now. feel free to reopen if there's additional issues.
