### ISSUE TITLE
[Roadmap] fhirengine-beta-01 | ERD 31.01.22 

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1054]
The beta release of the FHIREngine represents stable and tested library with accompanying documentation. Significant changes to API design are not planned, but may happen.

New features included:

* UUID refactoring #784 
* PUT/POST approaches for sync #1021 
* Add versioning for sync #806 
* Service Oriented Architecture approach for FHIREngine (remove dependency on FHIR server) #702

**Comment by omarismail94** [comment]
closing as obsolete
