### ISSUE TITLE
Add launchContext Extension

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1061]
Add support for LaunchContext expression Extension for advanced form behaviour - [see here](http://build.fhir.org/ig/HL7/sdc/expressions.html#other-extensions)

The launch context allows information to be passed into the execution environment based on the context in which the Questionnaire is being evaluated. For example, what patient, what encounter, what user, etc. is "in context" at the time the questionnaire response is being completed. Note that this context could potentially change if a questionnaire is edited after it was initially created, which means that if launchContext elements drive calculatedExpression elements rather than initialExpression elements, they'll be updated to reflect the new user.

Launch context information is passed to the QuestionnaireResponse evaluation process by the launching application. It will pass whatever contexts it is aware of. SDC systems SHOULD support all four of the contexts defined in this specification (e.g. Patient, Encounter, Location, User), but are free to support others. The selected contexts mirror those used by the SMART on FHIR specification.

The resource corresponding to each context will be made available at the indicated launch context name as if the value had been set in a variable. It is not allowed to define names that are already reserved by the base specification or by other variables in the questionnaire.

**Comment by delcroip** [comment]
https://github.com/google/android-fhir/blob/63accbfa6ceb03fe10c4928056af4aa047772ac4/demo/src/main/java/com/google/android/fhir/demo/EditPatientViewModel.kt#L54

here it seems that the patient id can be set for populate

**Comment by jingtang10** [comment]
#1844 fixed this
