### ISSUE TITLE
Sample App improvements to showcase local Fhir resources

### ISSUE THREAD

**Issue by pankajkatoch** [google/android-fhir#107]
- [ ] Show search results for `Observations` referred by a given `Patient`
- [x] When no objects available from sync, import json bundle as local Fhir resources [Removed]
- [ ] Use the sync button in the toolbar to actually sync results from external Fhir Resources
- [x] Remove dependence on `CqlLoader` for firing the sync.
- [x] Remove `SamplePatients.kt` if it's no longer needed.

**Comment by Syed-Affan-Hameed** [comment]
Hi @jingtang10 please assign me this issue, I would like to work on it ASAP..

**Comment by Anshul-9923** [comment]
@jingtang10 I would like to work on this issue, can you please assign it to me?

**Comment by jingtang10** [comment]
@Anshul-9923 thanks for your interest. Will you be able to take a look at: https://github.com/google/android-fhir/issues/218

This issue is obsolete. I'm going to close this.

**Comment by jingtang10** [comment]
If you leave a comment in 218 I'll assign it to you. Thanks @Anshul-9923
