### ISSUE TITLE
Sample App UI Toolbar, Menu and Spinner fixes

### ISSUE THREAD

**Issue by pankajkatoch** [google/android-fhir#108]
- [ ] Use a loading spinner instead of the Snackbar
- [x] Remove/fix `About` button functionality.
- [ ] Use Sync button in the toolbar correctly to sync with external hapi server

**Comment by aditya-07** [comment]
These issues are not present in the current codebase.

> * Use a loading spinner instead of the Snackbar
> * Remove/fix `About` button functionality.

**Comment by jtournier23** [comment]
Can we close this one marking it as "not reproducible" or is there something else left to be worked on?

**Comment by jingtang10** [comment]
Obsolete
