### ISSUE TITLE
Catalog, implement workflow when submit questionnaire button get clicked.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1081]
**Is your feature request related to a problem? Please describe.**

1. Click on Submit questionnaire button.
2. It opens screen with questionnaire response json string.
3. Click on Close button, it opens landing page screen. 

Collect questionnaire response json string.
Design and implement fragment to show questionnaire json output string
Navigate back to landing page on close button click.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
#1088

**Comment by santosh-pingle** [comment]
@shelaghm 

In android default font style is `sans-serif`, and it is also called as `roboto`
https://stackoverflow.com/questions/34444616/how-to-use-roboto-in-xml-layout/34445295
But in the figma it is mentioned `Google sans` and at some places `Roboto`, are these sans-serif font family?

In the catalog app as of now we have kept android default font style `sans-serif`.
`<item name="android:fontFamily">sans-serif</item>`

please provide your input on it.

**Comment by santosh-pingle** [comment]
<img width="430" alt="Screen Shot 2022-02-01 at 3 02 18 PM" src="https://user-images.githubusercontent.com/86107848/151944147-3030dc33-5ac9-4d0b-8e7b-a7ac674df048.png">
<img width="426" alt="Screen Shot 2022-02-01 at 3 02 39 PM" src="https://user-images.githubusercontent.com/86107848/151944178-51f69d91-3bab-4b5b-8c4a-a39020aa8a06.png">

**Comment by shelaghm** [comment]
thanks @santosh-pingle I'll get back to you on the font styles. Having two fonts is too complicated for this gallery app. (for internal health apps we typically use both Google Sans and Roboto combined, which is why they are both used in figma) I need to update the font styles and will let you know when it's ready.
