### ISSUE TITLE
Remove dependency on flexbox layout

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1082]
**Describe the Issue**

As @FikriMilano demonstrated in PR https://github.com/google/android-fhir/pull/586 we can use constraint layout's flow for horizontal layout instead of flexbox. We should remove the dependency on flexbox in our widgets. https://github.com/google/android-fhir/search?q=flexbox&type=code

**Would you like to work on the issue?**

@FikriMilano ?

**Comment by FikriMilano** [comment]
Sure @jingtang10

**Comment by jingtang10** [comment]
Thanks for your continued contribution! really appreciate it!

**Comment by FikriMilano** [comment]
Will migrate the AutoCompleteWidget from FLexBoxLayout to Constraint Layout Flow

**Comment by FikriMilano** [comment]
cc @f-odhiambo

**Comment by f-odhiambo** [comment]
This ticket may have been completed by @aditya-07, we can perhaps close it for now CC @Tarun-Bhardwaj @FikriMilano
