### ISSUE TITLE
Catalog, date time picker component workflow.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1085]
**Is your feature request related to a problem? Please describe.**

1. User click on date time picker component.
2. It launches date time picker screen with questionnaire, which demonstrate date time picker uses.
3. Click on navigation back key in action bar, it takes user back on landing page.

Design date time picker questionnaire json.
Write api to fetch date time picker questionnaire json file name.
Apply custom style at application side.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm 
As of now, datacapture does not have time picker implementation, but it has implementation for date time picker (datetime type).As result, we are showing datetime picker component workflow instead of time picker workflow.
May be we need to change icon drawable and text in the component list.

cc @jingtang10

**Comment by santosh-pingle** [comment]
<img width="429" alt="Screen Shot 2022-01-28 at 12 32 37 PM" src="https://user-images.githubusercontent.com/86107848/151502405-14f4450c-75eb-44f5-8d01-d785fa82a00c.png">
<img width="427" alt="Screen Shot 2022-01-28 at 12 32 50 PM" src="https://user-images.githubusercontent.com/86107848/151502421-3b8d51b9-ce5f-41a8-b505-3693cbbc75b5.png">
<img width="430" alt="Screen Shot 2022-01-28 at 12 33 06 PM" src="https://user-images.githubusercontent.com/86107848/151502449-80e60977-2686-4f3d-839e-24008728e172.png">

**Comment by shelaghm** [comment]
@santosh-pingle Keep this as Date Time picker. Let's keep icon drawable as is, but change the name of this widget/component to "Date time picker. When we fix some of the theming, need to double check that the colors are legible, right now it's hard to see the selected state for this. Ideally what's light blue now should be a darker blue #600

**Comment by shelaghm** [comment]
one more question, does the manual keyboard entry of time switch to this view? 
![Time picker 2](https://user-images.githubusercontent.com/86378921/152285241-372adaa2-816a-4b67-819d-95ea12c7192d.png)

**Comment by santosh-pingle** [comment]
@shelaghm 
To match this look and feel, it is required to add material time picker to the datacapture module. Created issue #1116
