### ISSUE TITLE
DataCapture, restrict the user from accepting value after decimal point in integer textfield widget.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1087]
**Is your feature request related to a problem? Please describe.**

Datacapture support decimal and integer type.
For decimal and integer input field, soft keyboard is shown with decimal point.
As decimal input textfield already allows user to provide value after decimal point, same should not be happened when type is integer(integer input edit text view).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by samiali12** [comment]
if this issue is not resolved, please assign it to me.

**Comment by santosh-pingle** [comment]
@samiali12 thanks for showing interest, let me connect you with @jingtang10

**Comment by santosh-pingle** [comment]
Marking it as fixed, if user enters decimal point then it starts showing error.
