### ISSUE TITLE
Use 'choice' widgets to save to fields besides those of type <code>

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1098]
**Is your feature request related to a problem? Please describe.**
As part of a registration form, I would like to save a patient's address and specifically, their country of origin. To reduce the chances of human error, I would like to use a 'choice' widget such as a drop-down as opposed to a 'string' widget. The drop-down takes an array of valueCoding objects as it's list of options. However, a patient's country is defined as a string in the FHIR spec. As a result, upon saving the questionnaire, the app crashes with an error saying a Coding was passed when a String was expected.

**Describe the solution you'd like**
Unless there is some other way to accomplish this, it would be nice for the app to convert the Coding into a String by possibly using the display property as the valueString.

**Describe alternatives you've considered**
The simplest alternative is just using a string widget and letting the user type out the country every single time they want to register a patient. However, this is not ideal as it would lengthen the registration process and opens the possibility for human error.

**Additional context**
The error is: java.lang.IllegalArgumentException: method org.hl7.fhir.r4.model.Address.setCountryElement argument 1 has type org.hl7.fhir.r4.model.StringType, got org.hl7.fhir.r4.model.Coding

I think this is a fairly common use case. If there is an alternative means to accomplish this with a 'choice' widget, then please let me know.

**Would you like to work on the issue?**
I'm not sure who can work on this but if I could get a response as soon as possible even just to verify that this is an actual problem, that would be great.

**Comment by jingtang10** [comment]
@KhumboLihonga can you share you questionnaire snippet if you have one?

This seems an important issue to me. If this is something the current widget doesn't support we should fix it.

We probably should also ask on FHIR chat about this.. not sure if they have a view on how this should be handled.

**Comment by KhumboLihonga** [comment]
Thanks, following up.

**Comment by jingtang10** [comment]
As a result of the conversation in the link above, I think we have the following options:

1. Simply use [answer options](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.answerOption) (instead of answer value set) in the questionaire item. This means that the questionnaire might be a bit bloated as this needs to be done inline of the questionnaire item. The benefit is that this is something we already support so doesn't require another release.
2. Use an answer value set to represent the countries. This is more reusable. But according to lloyd and brian in the fhir chat thread, it seems we need to use the code instead of the display field to populate the UI, which is fine. So this is something we'd need to fix in the library.

@KhumboLihonga do you have a pref regarding these 2 options? Or is there anything that I missed?

**Comment by KhumboLihonga** [comment]
I have a preference for solution 1 because this problem is not specific to just a list of countries. Besides the countries, we have another list of districts that exhibits the same problem. Solution 2 is great and there probably should be a value set to represent countries but I feel like solution 1 gives us more flexibility for wherever else we might encounter this problem.

**Comment by jingtang10** [comment]
@KhumboLihonga can you try option 1 then if that's your preference? I don't think we ever tested different answer option types so we need to add some tests at the very least, but potentially will have a few bugs to fix.

**Comment by KhumboLihonga** [comment]
@jingtang10 I checked out the [PR](https://github.com/google/android-fhir/pull/1399) meant to fix the issue you linked above and tested option 1. The the app doesn't crash and the drop down is displayed correctly. The Coding that will be generated in the QuestionnaireResponse can be extracted using a structure map. In addition, I'm assuming that when populating a drop-down using the initial expression extension, we can also use a string value to do so. So I think this is an ideal solution.

**Comment by f-odhiambo** [comment]
@Tarun-Bhardwaj Looks like the issue can be closed CC @KhumboLihonga @jingtang10

**Comment by jingtang10** [comment]
Thanks all!
