### ISSUE TITLE
Performance profiling - Sync Optimization 

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#1099]
Explore the Sync API to be able to push an  enhancement for Sync Optimization

1. Reduce the time it takes to sync resources on the app
2. Define an appropriate sync filter for FHIR resources based on the config, user credentials or location hierarchy (Sync by Team or Sync by Location )

**Comment by epicadk** [comment]
Blocked by https://github.com/google/android-fhir/issues/825 ?

**Comment by f-odhiambo** [comment]
> Blocked by #825 ?

Yup

**Comment by pld** [comment]
We can close this, will replace with more specific issues as they arise
