### ISSUE TITLE
DataCapture, date picker custom style

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1108]
**Is your feature request related to a problem? Please describe.**

To apply the custom style to date picker dialog as per figma style, it is required that datacapture should have support for material date picker. 

Once material date picker is updated to the datacapture module, it is possible to have date picker which was mentioned in figma.
Also, custom style can be applied to the header of the date picker.

We can refer below code snippet to apply the custom style to date picker where header is customised according to the figma.

Add `<item name="materialCalendarTheme">@style/ThemeOverlay.App.DatePicker</item>` to the `@style/Theme.MyQuestionnaire` at catalog or `Theme.Questionnaire` at datacapture.

Try below code to customise date picker header
```
<style name="ThemeOverlay.App.DatePicker" parent="@style/ThemeOverlay.MaterialComponents.MaterialCalendar">
        <item name="materialCalendarHeaderLayout">@style/Widget.App.MaterialComponents.MaterialCalendar.HeaderLayout</item>
        <item name="materialCalendarHeaderTitle">@style/Widget.App.MaterialComponents.MaterialCalendar.HeaderTitle</item>
        <item name="materialCalendarHeaderSelection">@style/Widget.App.MaterialComponents.MaterialCalendar.HeaderSelection</item>
        <item name="materialCalendarHeaderToggleButton">@style/Widget.App.MaterialComponents.MaterialCalendar.HeaderToggleButton</item>
    </style>
    <style name="Widget.App.MaterialComponents.MaterialCalendar.HeaderLayout" parent="Widget.MaterialComponents.MaterialCalendar.HeaderLayout">
        <item name="android:background">?attr/colorSurface</item>
        <item name="android:textColor">@color/grey_800</item>
    </style>
    <style name="Widget.App.MaterialComponents.MaterialCalendar.HeaderTitle" parent="Widget.MaterialComponents.MaterialCalendar.HeaderTitle">
        <item name="android:textColor">?attr/colorOnSurface</item>
    </style>
    <style name="Widget.App.MaterialComponents.MaterialCalendar.HeaderSelection" parent="Widget.MaterialComponents.MaterialCalendar.HeaderSelection">
        <item name="android:textColor">?attr/colorOnSurface</item>
    </style>
    <style name="Widget.App.MaterialComponents.MaterialCalendar.HeaderToggleButton" parent="Widget.MaterialComponents.MaterialCalendar.HeaderToggleButton">
        <item name="android:tint">?attr/colorOnSurface</item>
    </style> 
```

<img width="437" alt="Screen Shot 2022-02-03 at 4 08 00 PM" src="https://user-images.githubusercontent.com/86107848/152328977-bec2688b-44f6-4c7b-a9d7-bf18bbce6af7.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Anshul-9923** [comment]
@santosh-pingle I would like to work on this issue. Can you please assign it to me?

**Comment by santosh-pingle** [comment]
@Anshul-9923 thanks for showing interest, this issue has dependency on issue 1109, let me connect you with @jingtang10
