### ISSUE TITLE
Data capture, add subtitle text to the questionnaire item view.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1113]
**Is your feature request related to a problem? Please describe.**

As per new ux/ui guideline mentioned in the figma, it is expected to show subtitle text below the questionnaire text.

Action items
- Add subtitle text to the questionnaire item in the questionnaire json to be shown in the form.
- Add textview to show subtitle text in all sdc questionnaire widgets.

We can refer below design guideline, where `select one` is considered as subtitle text.    

  

<img width="539" alt="Screen Shot 2022-02-04 at 11 43 42 AM" src="https://user-images.githubusercontent.com/86107848/152481435-dea12f52-56cf-4d3a-8813-c17e9aa52f1a.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
related discussion: https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Hints.20for.20questions

**Comment by santosh-pingle** [comment]
@jingtang10 
If nested display item is used to show subtitle along with question text, then it also creates separate questionItemViewItem to display another question item, and its conflict.
e.g 
```
"item": [
    {
      "linkId": "1",
      "text": "Have you taken a pregnancy test?",
      "type": "boolean",
      "item": [
        {
          "linkId": "1-select-one",
          "text": "Select one",
          "type": "display"
        }
      ]
    }
  ]
```

It creates 2 questionItemViewItems, where 2nd questionItemView item is not required in this case.

**Comment by santosh-pingle** [comment]
It is possible to hide/disable nested display questionnaire item. 
But then developer has to explicitly add hidden extension or make it disable.

**Comment by santosh-pingle** [comment]
<img width="435" alt="Screen Shot 2022-03-09 at 1 28 07 PM" src="https://user-images.githubusercontent.com/86107848/157400980-b51dfac9-6a61-43e3-9001-8973d953e5a2.png">

**Comment by santosh-pingle** [comment]
> It is possible to ~hide/~ disable nested display questionnaire item. ~But then developer has to explicitly add hidden extension or make it disable.~ Nested display questionnaire item is only added to provide subtitle text to parent question. Therefore, it must not create questionnaire item view item for nested display item. If nested display item not enabled then view item will not be created.
> 
> If display item is present in group item then it should not be considered nested display item for subtitle text, this special case need to be handled.

Approach 2 : 
Do not include nested display item to QuestionnaireItemViewItemList at the time of questionnaire state creation.
