### ISSUE TITLE
Datacapture, add label, leading icon and helper text to the textfields in sdc widgets.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1115]
**Is your feature request related to a problem? Please describe.**
As per new ux/ui guideline mentioned in the figma, it is expected to show label, leading icon and helper text to the text field in sdc widgets.
Textfields are used in sdc widgets such as `QuestionnaireItemEditTextViewHolderFactory` `QuestionnaireItemDropDownViewHolderFactory` `QuestionnaireItemDatePickerViewHolderFactory` ` QuestionnaireItemDateTimePickerViewHolderFactory` `QuestionnaireItemDateTimePickerViewHolderFactory` open choice type, 

Action items :

- Add helper text, label, leading icons to the questionnaire item in the questionnaire json.
- Update textfields for label, helper text and icons

We can refer below screenshots. 

<img width="708" alt="Screen Shot 2022-02-04 at 1 05 04 PM" src="https://user-images.githubusercontent.com/86107848/152490071-ca61029e-22e4-4d1f-99a8-cee5c8a97e46.png">

<img width="613" alt="Screen Shot 2022-02-04 at 1 04 47 PM" src="https://user-images.githubusercontent.com/86107848/152490223-10957a99-9b61-4aeb-bb9d-05f65c98ebd0.png">

<img width="353" alt="Screen Shot 2022-02-04 at 1 01 30 PM" src="https://user-images.githubusercontent.com/86107848/152490257-5db9df7d-7d7c-4abe-9d00-4c8973cbc1c0.png">
25506fe9.png">

<img width="540" alt="Screen Shot 2022-02-04 at 1 04 11 PM" src="https://user-images.githubusercontent.com/86107848/152490358-03e10dd6-6f3b-4564-bed7-0e2dc786b414.png">

<img width="618" alt="Screen Shot 2022-02-04 at 12 59 47 PM" src="https://user-images.githubusercontent.com/86107848/152490414-4a8c4f53-ad8c-4294-a53f-916d848c5dfb.png">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Manikant25** [comment]
Thanks for detailed description, Can you assign it to me?

**Comment by santosh-pingle** [comment]
@Manikant25 thanks for showing interest, let me connect you with @jingtang10

**Comment by santosh-pingle** [comment]
This is just master ticket to track below tickets.
#1239, #1226, #1225, #1224, #1223, #1115

**Comment by santosh-pingle** [comment]
Closing this issue as referenced pr are merged.
