### ISSUE TITLE
For searching patient in demo, it is taking 4-5 seconds

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#1121]
**Describe the bug**
For searching patient in demo, it is taking 4-5 seconds

**Component**
demo app

**Precondition**
demo is configured with Happi server 
Data used : "synthea_sample_data_fhir_r4_sep2019"

**To Reproduce**
1. Go to 'FHIR Engine' app
2. Click on '+' and add patient
3. On Registered patient list, search for patient added in step 2
4. Observe behavior

**Expected behavior**
Search for patient should not take more than 1 sec

**logs**
[logcat.txt](https://github.com/google/android-fhir/files/8015602/logcat.txt)

**Smartphone (please complete the following information):**
 - Device: Lenovo tab
 - Android version: 10

**Additional context**
Total patient: 2364

**Comment by jingtang10** [comment]
obsolete
