### ISSUE TITLE
If device is not connected to internet and launch app first time, it gives "Sync:Unknow state" error instead of internet connection error

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#1122]
**Describe the bug**
If device is not connected to internet and launch app first time, it gives "Sync:Unknow state" error instead of internet connection error

**Component**
Demo app

**Precondition**
demo is configured with Happi server
Data used : "synthea_sample_data_fhir_r4_sep2019"
device is not connected to internet

**To Reproduce**
1. Go to 'demo app'
2. Keep device idle for 1-2 min and observe sync status toasts

**Expected behavior**
It should show Internet connectivity failure error instead of "Unknown state"

**Logs**
[unknown_state_logs.txt](https://github.com/google/android-fhir/files/8015719/unknown_state_logs.txt)

**Smartphone (please complete the following information):**
 - Device: Lenovo tab
 - Android version: 10

**Comment by jingtang10** [comment]
obsolete with santosh's latest change.
