### ISSUE TITLE
Creating patient without adding mandatory field city and country

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#1131]
**Describe the bug**
Able to add patient without adding mandatory field city and country

**Component**
Demo App

**To Reproduce**
1. Go to 'Demo App'
2. Click on '+'
3. Add all patient (mandatory fields) details except city and country and click on submit
4. Observe behavior

**Expected behavior**
Patient should not get created without adding city and country(mandatory field)

**video**
https://user-images.githubusercontent.com/64417713/152964847-8cbc7f2b-5ae9-4e11-824b-e0857a6f0aa1.mp4

**Smartphone (please complete the following information):**
 - Device: Lenovo tab
 - Android version: 10

**Comment by Anshul-9923** [comment]
@anita-vadverao I would like to work on this issue. Can you please assign me this issue.
