### ISSUE TITLE
Added patient on device1, App kill required to updated patient list on device2

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#1133]
**Describe the bug**
Added patient on device1, App kill required to updated patient list on device2

**Component**
demo app

**Precondition**
Patient added on device1

**To Reproduce**
1. On device2, Go to 'demo app'
2. Search for the patient added on device1
3.Observe behavior
4. Kill app and relaunch
5. Search for patient added on device1
6. Observe behavior

**Expected behavior**
Patient should get reflected on device2 without app kill

**Smartphone (please complete the following information):**
 - Device: Lenovo tab
 - Android version: 10

**Comment by Tarun-Bhardwaj** [comment]
@PallaviGanorkar , could you please try and recreate this bug with a gap of 3 to 4 minutes before using the second device.

**Comment by PallaviGanorkar** [comment]
This is expected behavior as Sync API is called in application when
1. on every launch
2. after launch poll is configured on every 15min.
