### ISSUE TITLE
Sync time is not updating in hamburger menu after manual sync with server and toast message shows older time

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1135]
**Describe the bug**
There are 2 related issues after manual sync with server
1. Sync time is not updating in hamburger menu after manual sync with server. 
2. Also the toast message is shows old last updated time 

**Component**
reference app

**To Reproduce**
1. Install Demo Application on Android phone
2. Launch App
3. wait for some time
4. open hamburger menu
5. Notice last Sync time
6. Now click on Sync button below
7. Now Observer behavior -  
       1. Sync time is not updated in hamburger menu. 
       2. toast message with older time 

**Expected behavior**
1.Sync time should be updated in hamburger menu after manual sync with server 
2.toast message should also show the 

**Screenshots**
![SyncTimeInHamburgerMenu](https://user-images.githubusercontent.com/13957417/153015957-9182a779-3897-462c-b53a-076b3863a49a.png)
![LatestTimeInToast](https://user-images.githubusercontent.com/13957417/153016018-a5616b23-4d9b-4223-89a2-f6b04fe38706.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 11
 - Build number: 00WW_2_410_SP01

**Comment by epicadk** [comment]
related to #846 both issues can be handled in a single pr.
