### ISSUE TITLE
Use gradle build action v2

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1137]
this lgtm. Btw, it is probably worth keeping an eye on v2 of gradle build action.

https://github.com/gradle/gradle-build-action

We recently migrated AndroidX to that, it is still WIP though but handles some caching etc for you.

_Originally posted by @yigit in https://github.com/google/android-fhir/pull/1136#pullrequestreview-876415953_

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 , are there any dates we have in mind to upgrade to Gradle build action v2?

**Comment by omarismail94** [comment]
Closing as we use gradle/gradle-build-action@v2 now.
