### ISSUE TITLE
Add test orchestrator

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1138]
**Describe the Issue**
See #1125 

**Would you like to work on the issue?**
@stevenckngaa

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 , is there something that needs to be done for this issue or can this be closed based on the comments from @stevenckngaa  above?

**Comment by Tarun-Bhardwaj** [comment]
Closing the issue as per the last comments from Steven.
