### ISSUE TITLE
After device restart, On click "FHIR Engine Sample App", it gets crashed

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#1140]
**Describe the bug**
After device restart, On click "FHIR Engine Sample App", it gets crashed

**Component**
Demo App

**To Reproduce**
1. Restart device
2. Device automatically connected to internet
3. Click on "FHIR Engine sample app"
4. Observe behavior

**Expected behavior**
App should not get crashed

**Logs**
[crash.txt](https://github.com/google/android-fhir/files/8031290/crash.txt)

**Smartphone (please complete the following information):**
 - Device: Samsung M01
 - Android version: 10

**Comment by santosh-pingle** [comment]
@anita-vadverao 
Is this issue consistent on Samsung M01, is it crashed all time?
do you see same crash on other device as well?

**Comment by PallaviGanorkar** [comment]
Not able to reproduce this crash Nokia 3.4 also

**Comment by jingtang10** [comment]
obsolete
