### ISSUE TITLE
Changes to patient details not propagated to list view immediately

### ISSUE THREAD

**Issue by vvikramraj** [google/android-fhir#1145]
**Describe the bug**

**Component**
reference app

**To Reproduce**
1. Launch demo app
2. Choose a patient from the list (observe name and age)
2. Edit name/age/both of patient. Hit SUBMIT.
3. Observe that the changes reflect on the patient detail fragment.
4. Navigate to the patient list page.
5. Changes are not reflected in the list page.

Navigating to the patient detail fragment of same or a different patient and returning to the list page causes the changes made in step 3 to reflect.

**Expected behavior**
Changes are propagated immediately to the list page as well.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel3 emulator
 - Version 28

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Issue was fixed.
