### ISSUE TITLE
Syncing across devices does not fetch expected resources.

### ISSUE THREAD

**Issue by vvikramraj** [google/android-fhir#1148]
**Describe the bug**
Syncing across devices does not fetch expected resources.

**Component**
Core library

**To Reproduce**
1.On device 1(Pixel 2), I created a patient and sync-ed with the server.
2. On device 2(Pixel 3), I launched the app, and sync-ed patients. The patient created on device 1 did not get downloaded on device 2.

Upon inspection, I noticed that the patient was created at 13:07:01.
![QpKxvgy82uC2jn5](https://user-images.githubusercontent.com/95918405/153180856-bee33f9f-3c98-4791-bfa1-ba5779fc6e12.png)

 The sync request from device 2 was searching for records updated after a later timestamp causing this behavior.
![8iYUC69s7nEMwRC](https://user-images.githubusercontent.com/95918405/153180967-ec5f9b3a-3186-48e2-9e2f-9d25848f71ad.png)

**Expected behavior**
Client should sync for records since last synced time instead of current time.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by vvikramraj** [comment]
Upon investigation, I discovered that this might have to do with [City/Country not being enforced](https://github.com/google/android-fhir/issues/1143). After I dropped the `address-city` query param, I am able to fetch the patient records that had been created on the first device - all the records created did not have City/Country populated.
![8NyY282rdnYg5fz](https://user-images.githubusercontent.com/95918405/153364941-5a92ba49-3223-4f33-8b9b-e6403826b832.png)
![Aok865ACKRfAkfu](https://user-images.githubusercontent.com/95918405/153364963-8ccbe4e8-ed30-4f60-9857-377af94e7261.png)

**Comment by vvikramraj** [comment]
The documentation has been updated to drop `address-city` from the initial-URL as opposed to setting the value to an empty string. Applying that resolved the problem.

**Comment by jingtang10** [comment]
thanks for filing and investigating this anyway - good to have the flow tested.
