### ISSUE TITLE
Deleted patients are not removed from client as part of syncing

### ISSUE THREAD

**Issue by vvikramraj** [google/android-fhir#1149]
**Describe the bug**
Deleted patients are not removed from client as part of syncing

**Component**
Core library

**To Reproduce**
1. Upload patients to FHIR server.
2. Sync patients to device.
3. Remove patients from FHIR server/restart instance with a different patient set.
4. Syncing patients to device does not remove the deleted patients.

Syncing changes to a deleted patient does fail on the server as expected.

**Expected behavior**
Patients no longer available on the server should be deleted from the client upon syncing.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Tarun-Bhardwaj** [comment]
@vvikramraj , could you please confirm if this issue still exists or if this can be closed?

**Comment by vvikramraj** [comment]
@Tarun-Bhardwaj , this issue does exist.

**Comment by Tarun-Bhardwaj** [comment]
closing the issue based on the last comment from Vikram.
