### ISSUE TITLE
Using Android FHIR SDK with GCP 

### ISSUE THREAD

**Issue by omarismail94** [google/android-fhir#1163]
**Is your feature request related to a problem? Please describe.**

Figure out a way to link SDK to GCP FHIR Store, and populate findings on [this](https://github.com/google/android-fhir/wiki/Using-FHIR-Engine-with-Google-Cloud-Healthcare-API) page

**Describe the solution you'd like**

Can authenticate and talk to GCP FHIR Store. Upload and download data.

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.
Assigned to me

**Comment by jingtang10** [comment]
@fredhersch fyi

**Comment by omarismail94** [comment]
Done with https://cloud.google.com/blog/topics/healthcare-life-sciences/build-fhir-patient-data-android-apps-with-open-health-stack-and-google-cloud
