### ISSUE TITLE
Implement FhirEngineDal

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#1168]
**Is your feature request related to a problem? Please describe.**

 Currently the methods of the FhirEngineDal are not implemented

**Describe the solution you'd like**

Implement the methods

**Describe alternatives you've considered**

NA

**Additional context**

There is a possible issue here. The FhirDal class methods are not suspend and we'll need to use either a GlobalScope or runBlocking to call the corresponding fhir engine functions.

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

Yes

**Comment by epicadk** [comment]
Will work on this after it is approved by the code owners

**Comment by Tarun-Bhardwaj** [comment]
CC: @ktarasenko

**Comment by ktarasenko** [comment]
Sure, please go ahead
