### ISSUE TITLE
Stop using OnConflictStrategy.REPLACE in the database

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1172]
I would actually recommend we go with a local UUID instead as the key (can even ignore resource type). We can have a server id in addition to that  to be used for server communications. FYI room 2.4 adds out of the box support for UUID (and saves it as a byte array). And for conflcits, we can simply ignore, it is super super unlikely to happen :)

Also, keep in mind, sqlite ID (which i assume it referes to the auto-generated primary key), is a bit tricky to use. More specifically, if we ever do "insert(onConflict=REPLace)", sqlite will "Delete" the existing item and insert the new one, with a new id. this also means all fkey relationships will be deleted.  (not different for UUID except it wouldn't be changing so with defferred fkey checks, we can handle that)
Hence, we should also make sure to never use `onConflict=REPLACE` (instead implement a custom upsert in a transaction).

_Originally posted by @yigit in https://github.com/google/android-fhir/issues/98#issuecomment-1023685036_

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 @aditya-07 is this still a high priority bug?

**Comment by fredhersch** [comment]
@jingtang10 is this still open?

**Comment by omarismail94** [comment]
Jing, Yigit, and I discussed this a couple of weeks ago and will close this. As we always re-index the tables after inserting or updating a resource, we don't face the issue of sqlite deleting an existing item and inserting a new one, with a new id, as that is what we do when we re-index
