### ISSUE TITLE
FhirPathEngine should use existing ValidationSupport instead of init again

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1173]
**Describe the Issue**

The line where we are [generating FhirPathEngine ](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt#L76) creates a new instance of DefaultProfileValidationSupport which occupies more than 17MB. If this is init into app anywhere again it keep multiplying and causes a performance lag. The method getValidation context into FhirContext does it automatically hence this should use validationSupport from FhirContext.

Impact on app. 
Around 500MB performance impact was noticed in profiling with doing this.

Before
![Screenshot from 2022-02-05 01-35-38](https://user-images.githubusercontent.com/4829880/154071570-88f3f3e2-a09e-4de7-b206-7373fd8d404d.png)

After
![Screenshot from 2022-02-14 21-32-39](https://user-images.githubusercontent.com/4829880/154071689-4994128a-204d-4a7b-b6af-4661cb647a1d.png)

**Would you like to work on the issue?**

yes

**Comment by jingtang10** [comment]
@maimoonak do you have a proposed fix for this?

**Comment by maimoonak** [comment]
Done in #1328

**Comment by Tarun-Bhardwaj** [comment]
Closing the issue as per discussion with Maimoona.
