### ISSUE TITLE
Forward compileSdk and targetSdk from 30 to 31 for room 2.4 support

### ISSUE THREAD

**Issue by wantingzhang77** [google/android-fhir#1179]
**Describe the Issue**
We want to update to room 2.4 for UUID support. However our current compile Sdk and target Sdk, 30 does not compile with room 2.4.
So the compile sdk and target sdk will need to be updated to 31 to support room 2.4.

**Would you like to work on the issue?**

**Comment by jingtang10** [comment]
@santosh-pingle this is also needed for material 3.
