### ISSUE TITLE
Data Capture - soft keyboard of widget type 'decimal' does not have a decimal point

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1181]
**Describe the bug**
In a questionnaire, when a field set to type 'decimal' receives focus, the soft keyboard appears but it has not decimal point to select from.

**Component**
SDC gallery app

**To Reproduce**
1. Create a questionnaire with a field with the type set to 'decimal'
2. Open the questionnaire in the app
3. Set focus on the field
4. The numeric soft keyboard will appear but without the decimal point

**Expected behavior**
A numeric keyboard should appear with a decimal point option.

**Screenshots**
This is what the soft keyboard looks like on a field set to type 'decimal':
![Screenshot_20220218-164945_mwcore](https://user-images.githubusercontent.com/90775548/154705854-9b04f7c3-cf81-4bfd-bac4-352afa005e10.jpg)

This is what the soft keyboard should look like (screenshot taken from the Radio android app):
![Screenshot_20220218-164458_Radio](https://user-images.githubusercontent.com/90775548/154705992-accb9168-98e5-431d-b6c9-5ab41ea1e7f5.jpg)

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
In the Data Capture Gallery app, you can view this in the "Neonate record from New South Wales, Australia" questionnaire. The birth weight field is a decimal but exhibits the same problem.

**Would you like to work on the issue?**
I don't know who can look into this but I would appreciate if someone looked into this as soon as possible.

**Comment by arinmodi** [comment]
i want to work on this, can please assign me ?
