### ISSUE TITLE
Data Capture - add functionality to skip pages entirely in a paginated questionnaire

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1187]
**Is your feature request related to a problem? Please describe.**
When using a paginated questionnaire, there are times where no fields on a certain page need to be filled in. For example, if on page 1, a user specifies that a patient has no guardian, then the user doesn't have to fill in the guardian details on page 2. As a result, the user just has to press next to move on to page 3.

**Describe the solution you'd like**
As per the above example, I would like to be able to skip page 2 entirely and move from page 1 to page 3.

**Describe alternatives you've considered**
I've tried to add the 'enableWhen' attribute on the page item but this just makes the page blank and I still need to press next to get to page 3.

**Additional context**
I've attached a video showing what happens when I used 'enableWhen' on the second page:
https://user-images.githubusercontent.com/90775548/155086316-f9d6187e-13ee-4b97-8afa-7a52c5e7ed09.mp4

**Would you like to work on the issue?**
I don't know who can look into this but I would appreciate if someone looked into this as soon as possible.

**Comment by jingtang10** [comment]
can you share @KhumboLihonga an example questionnaire that demonstrates this issue?

**Comment by KhumboLihonga** [comment]
@jingtang10 here you go

[skip-page-example-questionnaire.txt](https://github.com/google/android-fhir/files/8488911/skip-page-example-questionnaire.txt)

**Comment by pld** [comment]
Would have logic to skip a set of elements in a Questionnaire handle this requirement?

**Comment by KhumboLihonga** [comment]
@jingtang10 just wondering where are we on this issue?
