### ISSUE TITLE
Test OOM in evaluateMeasure tests 

### ISSUE THREAD

**Issue by ktarasenko** [google/android-fhir#1193]
**Describe the bug**

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Tarun-Bhardwaj** [comment]
@ktarasenko , did you get a chance to progress on this issue?

**Comment by ktarasenko** [comment]
Yes, json parser is leaking memory. Finalizing the discussions on possible solutions in #1280

**Comment by ktarasenko** [comment]
closing, tracking duplicated issue #1336
