### ISSUE TITLE
Core library - QuestionnaireResponse generated from Questionnaire using definition based extraction fails to sync

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1196]
**Describe the bug**
When submitting a questionnaire to create a new patient using definition based extraction, the resulting QuestionnaireResponse is created without a patient id reference. As a result, on syncing, the QuestionnaireReponse fails to sync as the server response with an error 400 i.e. bad request.

**Component**
Core library

**To Reproduce**
1. Create a questionnaire using definition based extraction to extract the Patient data
2. Save the questionnaire
3. QuestionnaireResponse is generated that fails to sync

**Expected behavior**
I expect the Patient resource to be created with no errors.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
The issue was originally posted [here](https://github.com/opensrp/fhircore/issues/1028). After speaking with the ONA team, I was asked to post the issue here for assistance.

**Would you like to work on the issue?**
I don't know who can look into this but I would appreciate if someone looked into this as soon as possible.

**Comment by Tarun-Bhardwaj** [comment]
Closing this issue as it should get fixed as part of #784
