### ISSUE TITLE
Data capture - add support for the 'text' field type to render multiline text input

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1197]
**Is your feature request related to a problem? Please describe.**
It's always frustrating when I need to verify a long line of text that has been written such as an address, in a single line text entry field. It means I have to scroll horizontally to verify that what I entered is correct.

**Describe the solution you'd like**
I would prefer if there was a multi line text entry field so I can verify the field at a glance without scrolling.

**Describe alternatives you've considered**
I've tried to use the 'text' type as specified in the FHIR documentation but this renders the same single line field.

**Additional context**
When using [this ](https://formdesigner.helsenorgelab.no/)form builder, it renders the 'string' and 'text' types differently as shown below.
<img width="960" alt="146510573-255efcc9-3242-4a4c-96c6-073505630e83" src="https://user-images.githubusercontent.com/90775548/155337401-8e96c0ed-833e-450c-af3e-d851528e7ffd.png">

However, when using the SDK, the 'string' and 'text' types are both rendered as single line fields as shown below.
![146510602-ab76effb-9582-4b78-ba63-ef9a40fd5d0a](https://user-images.githubusercontent.com/90775548/155337609-200ffbdd-4027-4047-a512-38b920f84a78.png)

**Would you like to work on the issue?**
I don't know who can look into this but I would appreciate if someone looked into this as soon as possible.

**Comment by jingtang10** [comment]
@KhumboLihonga so sorry for the delay.

The behaviour of the multiline text field itself should allow multi-line. If you start typing and create new lines, the widget should expand automatically to allow multi-line.

The only thing that gave you the impression that the widget was single line was the fact that it initially only has one line so it looks the same as the single line widget.

I've sent out a PR to change the initial look. #1517

**Comment by KhumboLihonga** [comment]
@jingtang10 no worries. I think when I wrote this issue the single line wasn't expanding. But with the new releases, I noticed the expansion which is great as we have some sections where the user will have to potentially type a lot of text. 

I think the PR will make this functionality a lot more obvious so I'll keep an eye out on it, thanks.
