### ISSUE TITLE
Support entry format in the SDC widgets

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1198]
**Is your feature request related to a problem? Please describe.**

See the definition of the extension here: https://build.fhir.org/extension-entryformat.html
and the use in SDC here: http://hl7.org/fhir/uv/sdc/2019May/rendering.html#additional-display-content

We should support this extension and display the string whenever available. In the case of this being absent - we might want to also display a format string for things like date or time in the relevant widgets.

It's worth mentioning that because this entry format field is not a regex - it's a readable string. there is no reliable way for us to use this string to actually validate the input from the user. So it's important we communciate this expecation in the document we have.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
@PallaviGanorkar

**Comment by PallaviGanorkar** [comment]
This functionality is implemented in PR https://github.com/google/android-fhir/pull/1276
