### ISSUE TITLE
Data Capture - date picker immediately pops up when navigating in a paginated questionnaire

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1208]
**Describe the bug**
When filling in fields in a paginated questionnaire, if you press next when the next page has a date field focused, the date picker immediately pops up before the user even has a chance to see what the field is asking for.

**Component**
SDC library

**To Reproduce**
1. Open the first page of a paginated questionnaire
2. Fill in details
3. Press next to open the next page which should include a date field
4. The date picker should pop up

**Expected behavior**
The date picker should not pop up even if the field initially has focus.

**Screenshots**
https://user-images.githubusercontent.com/90775548/155729129-1a0df988-faae-4c5a-826d-91f06d5759c9.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Would you like to work on the issue?**
I don't know who can look into this but I would appreciate if someone looked into this as soon as possible.

**Comment by PallaviGanorkar** [comment]
This issue is fixed in PR https://github.com/google/android-fhir/pull/1275
