### ISSUE TITLE
Investigate moving Room from KAPT to KSP

### ISSUE THREAD

**Issue by kevinmost** [google/android-fhir#1243]
**Describe the Issue**

This should improve build times

**Comment by jingtang10** [comment]
@yigit @stevenckngaa FYI

**Comment by yigit** [comment]
ideally this should just work :)
Aside from possible bugs, the only big difference in KSP is that, it is more strict about nullability (which also makes the generated code better).
Also, please make sure we use the latest room (2.4.x) as we had some bug fixes in patch releases.
