### ISSUE TITLE
"Pruning" data for optimizing amount of FHIR resources on device

### ISSUE THREAD

**Issue by mberg** [google/android-fhir#1244]
**Is your feature request related to a problem? Please describe.**

FHIR generates a lot of resources compared to more traditional digital health tools that have an entity-event data model.  To help support use cases where we want to store patient data for 1000's of patients on a device we will want to develop strategies for optimizing what resources should be stored on device and what resources can be kept in cloud.  Note: We have to work in contexts where devices may be offline for long periods of time and it won't be able to fetch patient data.

**Describe the solution you'd like**

The ability to configure logic for different strategies of what data should be kept on device in the long term.

For example, it would probably be possible to delete QRs off the device after a few days (edit data window) assuming the key data from that QR was extracted to patient resources.

I think how this is configured can depend on the connectivity and expected usage patterns.

For example, if the device is intended to support a large facility (lots of patients) but with good connectivity - we can take a strategy where we don't store data perhaps from prior care plans which can be fetched on demand.  In this case, only the most active data would be stored on device.  In some clinical work flows if you just need to look up a patient, potentially almost all data can be stored in the cloud outside of the patient data and potentially an observation or two representing the patients status.

**Comment by jingtang10** [comment]
this is handled in #1487 which is included in the next release

@mberg - i'm closing this because with the purge api this becomes an app decision. please feel free to reopen if the api doesn't meet you needs.
