### ISSUE TITLE
Add a Wrapper For fhirPath expressions, cqf-calculatedValue, cqf-library and cqf-expression.

### ISSUE THREAD

**Issue by RaaziaTarique** [google/android-fhir#1246]
**Is your feature request related to a problem? Please describe.**
FhirPathEngine, DataRenderer and related classes to evaluate fhirPath expressions, cqf-calculatedValue, cqf-library and cqf-expression will be used multiple time in the project so it's better to have central wrapper for these classes.

Following issues which may use this wrapper in the future:

https://github.com/google/android-fhir/issues/1040 (This wrapper is a Pre-Requisite)
https://github.com/google/android-fhir/issues/1033
https://github.com/google/android-fhir/issues/1059

**Describe the solution you'd like**
Add a wrapper in the common module.

**Describe alternatives you've considered**

**Additional context**
@jingtang10 proposed this solution in the SDK ticket discussion call held on 18th March, 2022 CC: @f-odhiambo 

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
as a first step to speed up development, i think it's ok to create this new api as an internal api in the `datacapture` module. as a next step we can move it to the `common` module (which will require a separate release).

**Comment by fredhersch** [comment]
@RaaziaTarique @jingtang10 has the approach here been resolved? Thanks

**Comment by f-odhiambo** [comment]
**Updates on this** 
1. Min/Max validation Works for Date but not other data types  - https://github.com/google/android-fhir/pull/1442
2. calculated-expression  -  https://github.com/google/android-fhir/pull/1380
3. calculated-value  - https://github.com/google/android-fhir/pull/1442
4. Implement calculated-expression extension  1059 | variables -> https://github.com/google/android-fhir/pull/1328 
5. CQF Expression not implemented yet - Needs a discussion

**Comment by jingtang10** [comment]
#1442 has comments to be addressed.

**Comment by maimoonak** [comment]
The expressions support has a long list https://build.fhir.org/ig/HL7/sdc/expressions.html. Some of the expressions discussed in current thread are below 

- Date picker restrict -> https://github.com/google/android-fhir/issues/1040 -> PR UNDER REVIEW    https://github.com/google/android-fhir/pull/1442
- Initial expression ->    https://github.com/google/android-fhir/issues/1033 -> PR MERGED -> https://github.com/google/android-fhir/pull/1228
- Variable support -> https://github.com/google/android-fhir/issues/1059 -> PR APPROVED -> https://github.com/google/android-fhir/pull/1328
- Calculated expression -> https://github.com/google/android-fhir/issues/971 -> PR AWAITING PR 1328 (variables work) -> https://github.com/google/android-fhir/pull/1380
- Calculated value -> PR READY -> https://github.com/google/android-fhir/pull/1442
- Answer expression -> https://github.com/google/android-fhir/issues/971 -> PR UNDER REVIEW -> https://github.com/google/android-fhir/pull/1480
- EnableWhen expression -> https://github.com/google/android-fhir/issues/819 -> PR MERGED (long ago) -> https://github.com/google/android-fhir/pull/1294
Candidate expression -> https://github.com/google/android-fhir/issues/1038 -> AWAITING PR 1480 (overlaps functionality)
- CQF Expression -> very vast range http://hl7.org/fhir/R4/extension-cqf-expression.html -> not implemented yet and no specific issue or use case exists/linked - Needs a discussion

**Comment by f-odhiambo** [comment]
@fredhersch See summery above on the related fhirpath expression tickets

**Comment by jingtang10** [comment]
I think as a tracking issue this issue can be closed as the only item left is 1038.
