### ISSUE TITLE
Implement slider step value extension

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#1260]
**Current issue**
By default, the slider step increment is 10. It should be controllable from the questionnaire. This required implementation of an extension: http://build.fhir.org/extension-questionnaire-sliderstepvalue.html

**Describe the feature**
When using the slider, I should be able to control the steps increment

**Component**
Core library, SDC library, reference app, or SDC gallery app

**Expected behavior**
For example, when specifying a question like, how many previous pregnancies have you had, the slider should step up in increments of 1 (default is 10) - see screenshot of current behaviour below)

**Screenshots**
![image](https://user-images.githubusercontent.com/81236549/160058256-134d374a-78f6-47b0-98ff-83fb9361177e.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Assigning this bug to @santosh-pingle since he is already working on catalog app changes.

**Comment by santosh-pingle** [comment]
To fix this issue SDC library should start supporting slider step value extension.
At this moment it is not implemented in sdc library.
http://build.fhir.org/extension-questionnaire-sliderstepvalue.html

**Comment by fredhersch** [comment]
Thanks @santosh-pingle is this an issue you can pick up?

**Comment by santosh-pingle** [comment]
Sure, I will work on it.

**Comment by fredhersch** [comment]
Any update here @santosh-pingle

**Comment by santosh-pingle** [comment]
@fredhersch I have not started implementation yet as occupied with other issues, please let me check with @Tarun-Bhardwaj and @jingtang10

**Comment by fredhersch** [comment]
@jingtang10 @shelaghm I think this should be higher priority. At the moment, the slider control is effectively not useful. Can we review this? Perhaps this is could be a "help wanted" issue?

**Comment by shelaghm** [comment]
Based on internal accessibility research, the usability of the slider is enhanced by pairing the slider with a text field. 
I strongly recommend adding a text field with the slider. I've pasted a link to the research in our internal chat. 
<img width="410" alt="Screen Shot 2022-08-29 at 10 58 47" src="https://user-images.githubusercontent.com/86378921/187267308-069ef863-b1b9-4862-ac71-afb1e3f18537.png">

**Comment by shelaghm** [comment]
How to clear selection/answer for the slider? Do we have a pattern for this?

**Comment by santosh-pingle** [comment]
looking into it.

**Comment by santosh-pingle** [comment]
> Based on internal accessibility research, the usability of the slider is enhanced by pairing the slider with a text field. I strongly recommend adding a text field with the slider. I've pasted a link to the research in our internal chat. <img alt="Screen Shot 2022-08-29 at 10 58 47" width="410" src="https://user-images.githubusercontent.com/86378921/187267308-069ef863-b1b9-4862-ac71-afb1e3f18537.png">

@shelaghm 
Can you please provide more details on `the usability of the slider is enhanced by pairing the slider with a text field`, what are the use case you would like to implement here?
Use cases like
-  Show current slider value in the input text field?

**Comment by fredhersch** [comment]
Will put this on hold until after Ux testing to determine prioritisation.
cc: @santosh-pingle @shelaghm

**Comment by shelaghm** [comment]
Thanks @fredhersch for the prioritization. 

@santosh-pingle the primary use case for adding the slider text box is for accessibility best practises. Sliders are hard to interact with for people who are visually impaired and who use screen readers, it is also challenging for anyone who has motor control limitations. Having the text box also makes it easier for other people who know what number they want to enter to be able to just type in the answer instead of fiddling with the slider. 

The slider and the number in the box should match each other. So if you move the slider, the number should update in the text box. Likewise, if you enter text in the box, it should update on the slider.

**Comment by santosh-pingle** [comment]
> Will put this on hold until after Ux testing to determine prioritisation.
> 
> To do:
> 
> * Hide slider example from SDC category app
> * Update the wiki documentation  to indicate level of support for sliders
> 
> cc: @santosh-pingle @shelaghm

Sure.
I will not create PR for local changes of slider-step extension implementation, until this issue get prioritised.
Once issue get prioritised then start working on use case which @shelaghm has asked regarding textfield paring to slider.

I will create PR for temporary change to hide slider component workflow in catalog app.
