### ISSUE TITLE
 New patient is not creating sometime

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1265]
**Describe the bug**
New Patient is not creating some time after click on "Submit button"

**Component**
 SDC library, reference app

**To Reproduce**
1. install and launch demo app '...'
2. Click on '.+.' on Dashboard to add new Patient 
3. Enter all Patient  details
4. Click on submit button
5. See error : Submit button is clicked but new patient is not added and app stays on add patient screen

**Expected behavior**
On Click of Submit button new Patient is not added

**Screenshots**
Video

https://user-images.githubusercontent.com/13957417/160419016-c55741d9-d826-4582-a214-d50402b5fadd.mp4

[log.txt](https://github.com/google/android-fhir/files/8363634/log.txt)

 and logs are attached below

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4 and  emulator configuration API 30 and Pixel XL
 - Android version: 11
 - Build number:00WW_2_410_SP02

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
@PallaviGanorkar can you please attach the logcat?

**Comment by Tarun-Bhardwaj** [comment]
@PallaviGanorkar , could you please check if this is still reproducible?

**Comment by PallaviGanorkar** [comment]
Tried to reproduce it around 20 time,  this issue is not reproducible. 
Though creating patient is taking time if there is large data in database, but patient is added. So closing this issue.
