### ISSUE TITLE
FHIR R4 Time Zone format requires Android API 24 or higher

### ISSUE THREAD

**Issue by pankajkatoch** [google/android-fhir#128]
The timezone format currently supported by FHIR Search, FHIRPath etc. currently is a subset of ISO8601:

`yyyy-mm-ddThh:mm:ss[Z|(+|-)hh:mm]`

In Android [`SimpleDateFormat`](https://developer.android.com/reference/java/text/SimpleDateFormat) shows 'X' pattern for ISO 8601 only be supported in API Level 24+ (Nougat+) only.

This is required for Sync implementation to work correctly. Otherwise in API 21 it throws exception `java.lang.IllegalArgumentException: Unknown pattern character 'X'` while using
`SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX", Locale.US)`

Related to Issue #110

**Comment by jingtang10** [comment]
have you looked into java8's time library? https://developer.android.com/studio/write/java8-support-table

**Comment by jingtang10** [comment]
We already use java8 here: https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt

**Comment by jingtang10** [comment]
@pankajkatoch can you confirm if this is fixed by PR #136?

**Comment by pankajkatoch** [comment]
@jingtang10 PR #136 was still raising an exception in both API 21 and API 28: `java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: YearOfEra`

It required a Time Zone Id to work.
Raised PR #156
