### ISSUE TITLE
Custom widget that opens a new activity to collect answer

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1287]
**Is your feature request related to a problem? Please describe.**
Create a custom widget that sends an intent to open a new activity (we can probably just pick a URL ourselves). In the new activity the developer should be able to use the activity result API to return the picked answer.

**Describe the solution you'd like**
A custom widget in the contrib folder of the sdc library

**Describe alternatives you've considered**
@soura-b fyi

**Additional context**
Na

**Would you like to work on the issue?**
Na

**Comment by santosh-pingle** [comment]
looking into it

**Comment by jingtang10** [comment]
from @jjtswan

- Code to create a custom questionnaire widget that has a read-only textbox displaying a default answer, with a button next to it which would trigger your activity to select the facility.
- Example of how to bind that widget into an example questionnaire

**Comment by santosh-pingle** [comment]
Custom widget view context can be used to launch the activity, but we also need to read activity result back, therefore view context is not enough to just start the activity.
We need to find the way to use ActivityResult api in sdc to read result from activity.
We need to define ActivityResult api and pass reference to custom widget from QuestionnaireFragment to custom widget to start the activity and read the result back.

**Comment by jingtang10** [comment]
> Custom widget view context can be used to launch the activity, but we also need to read activity result back, therefore view context is not enough to just start the activity.
> We need to find the way to use ActivityResult api in sdc to read result from activity.
> We need to define ActivityResult api and pass reference to custom widget from QuestionnaireFragment  to start the activity and read the result back.
> 
> Currently, referring ActivityResult api reference.

Do you have a branch to share?

You're saying we need to change the widget interface to include activity context?

**Comment by santosh-pingle** [comment]
> > Custom widget view context can be used to launch the activity, but we also need to read activity result back, therefore view context is not enough to just start the activity.
> > We need to find the way to use ActivityResult api in sdc to read result from activity.
> > We need to define ActivityResult api and pass reference to custom widget from QuestionnaireFragment  to start the activity and read the result back.
> > Currently, referring ActivityResult api reference.
> 
> Do you have a branch to share?
> 
> You're saying we need to change the widget interface to include activity context?

Considering this option.

**Comment by santosh-pingle** [comment]
#1313
