### ISSUE TITLE
FHIR R4 Time Zone format requires Android API 24 or later

### ISSUE THREAD

**Issue by pankajkatoch** [google/android-fhir#129]
The timezone format currently supported by FHIR Search, FHIRPath etc. currently is a subset of ISO8601:

`yyyy-mm-ddThh:mm:ss[Z|(+|-)hh:mm]`

In Android [`SimpleDateFormat`](https://developer.android.com/reference/java/text/SimpleDateFormat) shows 'X' pattern for ISO 8601 only be supported in API Level 24+ (Nougat+) only.

This is required for Sync implementation to work correctly. Otherwise in API 21 it throws exception `java.lang.IllegalArgumentException: Unknown pattern character 'X'` while using
`SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX", Locale.US)`

Related to Issue #110

**Comment by jingtang10** [comment]
this is a duplication of #128
