### ISSUE TITLE
Date picker questionnaire with required field true does not show calendar icon.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1292]
**Describe the bug**
Create questionnaire json with type `date` and `required` true, when date picker get render it does not show calendar icon, calendar icon get overlapped with error mark. 

**Component**
SDC library

**To Reproduce**
1. Open demo app
2. Click on + icon to add patient
3. See date of birth question
4. Error is shown on date text field, and it does not show calendar icon to launch the date picker.

**Expected behavior**

**Screenshots**

<img width="432" alt="Screen Shot 2022-04-14 at 12 45 44 PM" src="https://user-images.githubusercontent.com/86107848/163334131-c846cdaa-4501-4564-93d9-8e07ce7cfea8.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@PallaviGanorkar @shelaghm cc @jingtang10

**Comment by santosh-pingle** [comment]
It seems calendar icon need to be shown as start icon in input text field, so that it can not be overlapped by error icon when error message is shown.

**Comment by jingtang10** [comment]
> It seems calendar icon need to be shown as start icon in input text field, so that it can not be overlapped by error icon when error message is shown.

either this, or we don't show the error icon for date/time input boxes where there is the calendar button.

**Comment by shelaghm** [comment]
I recommend we don't know the error icon and we show the calendar icon instead on the right side. 
Internal material design guidelines recommend this approach.
