### ISSUE TITLE
Cleanup Sync.kt to provide only WorkManager based sync apis.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#1307]
**Describe the Issue**
Presently there are a lot of overlapping ways/apis in the `Sync.kt` available for the developer application to sync data with the remote server.

Expected changes:
1. It should have a simple interface with two api : One for immediate Onetime sync and other for periodic sync.
2. The developer app should be able to listen-in to the state of ongoing sync via `Flow`.

**Would you like to work on the issue?**

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 do you think fixing this issue would impact #1469?
