### ISSUE TITLE
Submit button not visible when Questionnaire occupies more space than single screen

### ISSUE THREAD

**Issue by kashyapj2793** [google/android-fhir#131]
Currently testing how the datacapture lib behaves when items in the sample questionnaire are duplicated. When the questionnaire view goes over one screen the submit but does not appear.

Refer to video in issue #132

**Comment by kashyapj2793** [comment]
@jingtang10 Can you please review the latest changes in the kj/sdc-binding-bug branch. I have added the submit button as part of the recycler view. It will be the last member in the view. It solves this problem

**Comment by jingtang10** [comment]
@fredhersch can you please comment on what the UI should be in the case where the questionnaire is long and need scrolling? should the submit button always be at the bottom of the screen, or only appears when the user scrolls to the bottom of the screen?

**Comment by fredhersch** [comment]
I suggest we position the save button in the toolbar in the top right. See this sample here

![Register patient](https://user-images.githubusercontent.com/34733/103646208-45383e00-4f94-11eb-8e27-37ed02999de3.jpg)

**Comment by kashyapj2793** [comment]
I have positioned the button on the top right as suggested by Fred. I Changed the questionnaire_fragment linearLayout to a constraintLayout to do this. One thing to note is that since this is a fragment which is a part of the datacapturegallery activity the submit button is just below the app label but is in line with the Questionnaire title
![Submit_button_top_right](https://user-images.githubusercontent.com/48797364/103742150-5f1f6280-5020-11eb-83eb-9c07f7e80c0d.jpeg)

**Comment by jingtang10** [comment]
@kashyapj2793 with the change made to the main activity now, will you be able to rebase this and move the submit button to the app bar?

**Comment by kashyapj2793** [comment]
Sure Ill rebase and work on this :)

**Comment by jingtang10** [comment]
thanks :) something like this may work: https://material.io/components/app-bars-top/android#regular-top-app-bar?

**Comment by kashyapj2793** [comment]
![Screenshot_20210121-172017.jpg](https://user-images.githubusercontent.com/48797364/105347506-04cff580-5c0d-11eb-9ee8-7178cefe42ca.jpg) @fredhersch @jingtang10

**Comment by fredhersch** [comment]
@kashyapj2793 This looks good to me. Is it possible to show the submit button with different styling (just border outline for example) to see how it sits on the toolbar? Thanks!

**Comment by kashyapj2793** [comment]
Sorry @fredhersch this automatically got closed after I merged the pull request linked to the issue, but I see that you have created another issue to address the comment above. Just linking it here for reference #163
