### ISSUE TITLE
DropDown widget Espresso tests flaky 

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1323]
**Describe the bug**
https://github.com/google/android-fhir/runs/6130147669?check_suite_focus=true

**Component**
SDC lib

**To Reproduce**
1. Run `QuestionnaireItemDropDownViewHolderFactoryEspressoTest.kt` locally in Android Studio

**Expected behavior**
Passes every time

**Actual results**
`shouldSetDropDownValueToAutoCompleteTextView ` fails frequently (but not all the time)

**Screenshots**

https://user-images.githubusercontent.com/28757340/165289316-d96de6a8-7eb1-4917-906f-3d604f5a7cb3.mp4

**Smartphone (please complete the following information):**
 - Device: PIxel 6
 - Build number: SP2A.220505.002
 - Android version: 12
 - API Level: 32
 
**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by jingtang10** [comment]
this is effectively blocking all PRs going in. I've observed this locally where the test case `shouldSetDropDownValueToAutoCompleteTextView` doesn't pass... the expected value is Coding 3 but sometimes it's just empty...

**Comment by PallaviGanorkar** [comment]
I have run QuestionnaireItemDropDownViewHolderFactoryEspressoTest on below device 15 - 20 times on each device, but could not reproduce this issue, device configuration as below
1. Nokia 3.2 Device, API level - 30
2. Nexus 5X Emulator, API level - 24
3. Pixel 4 Emulator, API level - 24
4. Pixel XL Emulator, API level - 27

**Comment by jingtang10** [comment]
@PallaviGanorkar yesterday 13:48 BST: `But now I am able to reproduce this issue on Pixel 5 with API 32 emulator`
