### ISSUE TITLE
Investigate binary size of SDC library

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1331]
**Describe the Issue**
The SDC library binary size seems very large due to the mlkit dependencies required by the QR code reader. There might be afew solutions:

1. move the QR code reader to the catalog app
2. investigate if proguard can strip out the dependency
3. create a new release (`com.google.android.fhir:data-capture-contrib` or something similar) for the QR reader

**Would you like to work on the issue?**
NA

**Comment by jingtang10** [comment]
Before we make a decision, would be nice to gather some facts:
- how big is the sdc lib at the moment?
- how much does the QR code reader add to the library size?
- Is it easily strippable by proguard if developer is building an app?
- if not strippable by proguard, can we make it so it is?
- if not in the sdc lib, does it make sense to create a separate binary for contrib widgets, or shall we just put the code in catalog app as an example, so developers will need to copy and paste the example.

**Comment by kevinmost** [comment]
Looks like the QR reader adds ~7.3MB to the download size of the release APK, and ~13.4MB to the on-device install size.

Presumably it could be stripped by Proguard (~3MB downloaded -> ~8MB installed comes from the `.so` file, which could just be excluded in Gradle as well). However, as an application developer, I find it much more annoying to maintain a Proguard/Gradle excludes list, versus bringing in another library.

I think that moving this to its own Gradle module, maybe in `contrib/datacapture/barcode` would be a good start. Maven coords could be something like `com.google.android.fhir:contrib-data-capture-barcode:0.1.0-beta03`

**Comment by kevinmost** [comment]
By the way, I did the above investigation with [this cool Gradle plugin](https://github.com/spotify/ruler). Just sent a PR (#1421) to integrate it.

**Comment by jingtang10** [comment]
@ekigamba @f-odhiambo @pld FYI

Thanks so much @kevinmost for the investigation and for sending the PR 🙏
