### ISSUE TITLE
[$apply] Adding the new Plan Definition, CarePlan and Task Resources as test cases. 

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#1334]
**Is your feature request related to a problem? Please describe.**
- This is related to the `$apply` implementation. Adding these files helps us test the `$apply` further against real-life situations. 
- Here is the list of resources to use https://github.com/opensrp/fhir-resources/tree/main/ecbis

**Expected Outcome**
- [ ] The CarePlan & Tasks should be generated as part of the `$apply` test cases. 

**Would you like to work on the issue?**
- @dubdabasoduba

**Comment by jingtang10** [comment]
@dubdabasoduba any progress here?

@vitorpamplona did we decide if this is still needed?

**Comment by vitorpamplona** [comment]
Those test cases started my journey in running the CQL Compiler on Android. With the Translator 2.0.0, we should be able to run those test cases. Without 2.0.0, we need to adapt the PlanDefinitions to remove conditionals (which need to be turned into CQL and compiled).

**Comment by Tarun-Bhardwaj** [comment]
@vitorpamplona , is there an ETA by when we can close this issue?

**Comment by fredhersch** [comment]
@vitorpamplona Is this still an open issue?

**Comment by vitorpamplona** [comment]
Fixed on: https://github.com/google/android-fhir/pull/1603
