### ISSUE TITLE
Workflow test OOM

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1336]
**Describe the bug**
As an example see https://github.com/google/android-fhir/runs/6162537814?check_suite_focus=true

```
com.google.android.fhir.workflow.FhirOperatorTest > evaluateIndividualSubjectMeasure FAILED
    java.lang.OutOfMemoryError at FhirOperatorTest.kt:172
```

**Component**
Workflow library

**To Reproduce**
1. Run unit tests on github actions (create any PR and wait for checks results, or just check github actions results page)

**Expected behavior**
Tests pass

**Screenshots**
NA

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by jingtang10** [comment]
reopening - we should close after we re-enable this test.

**Comment by Tarun-Bhardwaj** [comment]
Issue is obsolete now, hence closing.
