### ISSUE TITLE
Use DateFormat.SHORT in the sdc lib

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1348]
**Is your feature request related to a problem? Please describe.**
See this doc: https://developer.android.com/reference/android/icu/text/DateFormat

Note: `SHORT is completely numeric, such as 12.13.52 or 3:30pm`

I think that is something that we might want to use in the text input box for date and time pickers, especially if (and that's a big if @aditya-07 @shelaghm) we allow the user to actually input text directly.

I think the short numeric format might just make more sense for input, and also for data entry in general. I can't imagine people being keen to use month names while inputing dates.

**Describe the solution you'd like**
Use https://developer.android.com/reference/android/icu/text/DateFormat and specifically use the DateFormat.SHORT format

**Describe alternatives you've considered**
current solution. But we get things like "1 May 2022" in the text input, which in my opinion is kinda strange.

**Additional context**
NA

**Would you like to work on the issue?**
Yeah

**Comment by shelaghm** [comment]
+1 to using short/numeric only dates.
