### ISSUE TITLE
`answerOption.valueString` crashes SDC library

### ISSUE THREAD

**Issue by vadi2** [google/android-fhir#1360]
**Describe the bug**
Loading a questionnaire with `answerOption.valueString` instead of `answerOption.valueCoding` as the library [expects](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt#L28-L29) causes a crash. valueStrings and other types are perfectly legitimate options [per the spec](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.answerOption.value_x_), however.

**Component**
SDC library & reference app.

**To Reproduce**
1. Add Questionnaire below to the app
2. View Questionnaire

**Additional context**
Sample questionnaire:

```json
{
  "resourceType": "Questionnaire",
  "id": "3141",
  "url": "http://example.org/fhir/Questionnaire/1",
  "title": "Questionnaire with answerOption.valueString",
  "status": "draft",
  "item": [
    {
      "linkId": "FIRSTBC",
      "type": "choice",
      "text": "Indicate if this is first breast cancer or new cancer on contralateral or ipsilateral breast:",
      "answerOption": [
        {
          "valueString": "Primary tumor"
        },
        {
          "valueString": "New ipsilateral"
        },
        {
          "valueString": "New contralateral"
        }
      ]
    }
  ]
}
```

**Comment by vadi2** [comment]
An example where a valueInterger would be useful:

```json
        {
          "linkId": "EORTC-QLQ-Q29-Q30",
          "type": "group",
          "text": "For the following questions please select the number between 1 and 7 that best applies to you, with 1 = Very poor and 7 = Excellent.",
          "item": [
            {
              "linkId": "EORTCQLQC30_Q29",
              "type": "choice",
              "text": "How would you rate your overall health during the past week?",
              "required": true,
              "answerOption": [
                {
                  "valueInteger": 1
                },
                {
                  "valueInteger": 2
                },
                {
                  "valueInteger": 3
                },
                {
                  "valueInteger": 4
                },
                {
                  "valueInteger": 5
                },
                {
                  "valueInteger": 6
                },
                {
                  "valueInteger": 7
                }
              ]
            },
```

**Comment by jingtang10** [comment]
thanks very much for raising this @vadi2 - @santosh-pingle is working on this

**Comment by jingtang10** [comment]
this is related (but different) to #1098. @santosh-pingle please also see the fhir chat discussion: https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Answer.20value.20set.20and.20answers.20as.20string

**Comment by santosh-pingle** [comment]
@jingtang10 
Can you please confirm whether `QuestionnaireResponse` will always have answerOption type as Coding, if type in `Questionnaire` Item is `choice`?

**Comment by jingtang10** [comment]
I think one consequences of this issue is that if we have a string/integer/date/time/whatever questionnaire item with answer options, we should render it using a "choice" widget such as dropdown, instead of a text input. at the moment we pick the widget using the questionnaire type (e.g. if it's a string, we have text input, if it's date, we have a date picker) but it seems we need to have some logic to override that and say if any questionnaire item has answer options, we probably should use dropdown.

@vadi2 is this what other form fillers do?
