### ISSUE TITLE
FHIR Engine sort by DateTime property not working

### ISSUE THREAD

**Issue by ekigamba** [google/android-fhir#1363]
**Describe the bug**
Performing a FHIR Engine search with sort on a DateTime property does not work

**Component**
Core library

**To Reproduce**

Run the following query inside code and you notice that the result is neither sorted nor filtered by the `Patient.meta.lastUpdated` date time
```
fhirEngine.search<Patient> {

        sort(DateClientParam("_lastUpdated"), Order.ASCENDING)
        filter(DateClientParam("_lastUpdated"), {
          value = of(DateTimeType(Date(lastRecordUpdatedAt)))
          prefix = ParamPrefixEnum.GREATERTHAN_OR_EQUALS
        })

        //sort(DateClientParam("_lastUpdated"), Order.ASCENDING)
        count = batchSize
      }
```

**Expected behavior**
The result should respect the filter and sort by `_lastUpdated`. The debugged query should use `DateTimeIndexEntity` instead of `DateIndexEntity` because the `_lastUpdated` field is stored inside the `DateTimeIndexEntity` table

**Screenshots**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Would you like to work on the issue?**
Yes but I need help understanding how the current search API logic works and how this was supposed to work

**Comment by ekigamba** [comment]
@aditya-07 Kindly help me out on this bug. We implemented a workaround that currently enables us to run the raw query as is 

```
SELECT a.serializedResource, b.index_to
      FROM ResourceEntity a
      LEFT JOIN DateTimeIndexEntity b
      ON a.resourceType = b.resourceType AND a.resourceId = b.resourceId AND b.index_name = '_lastUpdated'
      WHERE a.resourceType = 'Patient'
      AND a.resourceId IN (
      SELECT resourceId FROM DateTimeIndexEntity
      WHERE resourceType = 'Patient' AND index_name = '_lastUpdated' AND index_to > ?
      )
      ORDER BY b.index_from ASC
      LIMIT ?
```

I need to understand how and when the `DateTimeIndexEntity` table is supposed to be used and how the search API was designed to make such decisions

**Comment by aditya-07** [comment]
@ekigamba The index table to search is decided by the type of `ClientParam` passed in the filter api. In the code snippet above, DateIndexEntity is being searched because filter is called upon `DateClientParam("_lastUpdated")`. You should pass `DateTimeClientParam("_lastUpdated")` for it to search in `DateTimeIndexEntity`. 

Additionally, the last updated value that we are indexing is not the local update datetime, but the value from Resource.Meta that is assigned by the server and is stored in the `DateTimeIndexEntity` table.

**Comment by ekigamba** [comment]
@aditya-07 I can't seem to find this class anywhere

- Link to hapi-fhir docs https://hapifhir.io/hapi-fhir/apidocs/hapi-fhir-base/ca/uhn/fhir/rest/gclient/package-summary.html
- Screenshots searching for the class on AS
![Screenshot from 2022-05-05 12-07-11](https://user-images.githubusercontent.com/31766075/166893537-7d198398-39eb-4348-895b-5d75474498c4.png)
![Screenshot from 2022-05-05 12-07-02](https://user-images.githubusercontent.com/31766075/166893546-9b703d81-dda7-4f79-af18-053d7119abe6.png)


Could you help out? It might be a dependency issue

**Comment by aditya-07** [comment]
@ekigamba Updated my comment above. `DateTimeClientParam` doesn't exits :(  and  `DateClientParam` has to be used.

**Comment by ekigamba** [comment]
Thanks @aditya-07 . I will try and use this to fix the issue

**Comment by ekigamba** [comment]
@jingtang10 Here is the research document https://docs.google.com/document/d/1ALYulBGNwSg-Agqbx4qcgOaAVtUg70GXL_mOTnN5v1s/edit?usp=sharing. Kindly review

**Comment by ekigamba** [comment]
The agreed approach was:

Perform a join of both **DateIndexEntity** and **DateTimeIndexEntity** tables for any sorting by date/datetime. Since any search parameter would only have records in one of these tables, one of the joins would be invalid so take no effect.

cc @jingtang10, @aditya-07
