### ISSUE TITLE
 Definition based extraction for Extensions

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1381]
**Describe the bug**
 Definition based extraction for Extensions does not work since extraction is done using reflection. So in the example below from the [spec](http://build.fhir.org/ig/HL7/sdc/extraction.html#definition-extract) ":foo" will not exist in any object in HAPI.

> NOTE: Rather than specifying the id of an element that actually appears in a snapshot, it is also possible to 'extend' an id to walk further into the data types of the specified element. For example, a definition might be http://hl7.org/fhir/Patient#Patient.name.given even though the referenced profile's snapshot only contains Patient.name, not Patient.name.given. However, for more complex references (e.g. referring to a particular extension or a particular repetition), it will be necessary to define a distinct profile where slicing ensures that a single element id corresponds to the desired element. I.e. you would need to use http://somewhere.org/SomePatient#Patient.name.given:foo where 'foo' was a slice that referred to the first middle name in order to tie to a definition that specific.

**Component**
SDC library

**To Reproduce**

1. Use the [registration questionnaire](http://build.fhir.org/ig/WorldHealthOrganization/smart-anc/Questionnaire-ANCA.html) with the SDC
2. Extract resources from the Questionnaire Response
3. The Encounter will not contain the extension [Encounter.contactNumber](http://build.fhir.org/ig/WorldHealthOrganization/smart-anc/StructureDefinition-anc-encounter.html#Encounter.contactNumber)

**Expected behavior**
Expect the Encounter to contain the property contactNumber

cc: @jingtang10 @fredhersch

**Comment by PallaviGanorkar** [comment]
@joiskash 
1. How do I  get access to this profile?
2. What is expected value for extension Encounter.contactNumber?

**Comment by joiskash** [comment]
The profile is a link in the description, putting the link here for easy access https://build.fhir.org/ig/WorldHealthOrganization/smart-anc/StructureDefinition-anc-encounter.html#Encounter.contactNumber

**Comment by joiskash** [comment]
@PallaviGanorkar Please use this questionnaire to test the code. Thanks for pointing out the issues in the WHO ANC registration questionnaire. We should raise an issue on the IG Github repo.
[patient-registration.txt](https://github.com/google/android-fhir/files/9281524/patient-registration.txt)

**Comment by PallaviGanorkar** [comment]
@joiskash , As discussed , I was trying to test item with link Id "linkId": "tribe" b but the "definition" field is missing for this item. So not code not able to do definition based  extraction for this extension
Please do the needful here.

**Comment by joiskash** [comment]
Sorry, please find the updated one here
[patient-registration-with-extention-definitions.txt](https://github.com/google/android-fhir/files/9308534/patient-registration-with-extention-definitions.txt)
 
Also you can refer to http://build.fhir.org/ig/WorldHealthOrganization/smart-anc/StructureDefinition-who-patient-definitions.html#Patient.extension:religion
