### ISSUE TITLE
Dark theme support in catalog app.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1388]
**Is your feature request related to a problem? Please describe.**

Catalog app has below values for dark theme in night mode.
```
      <item name="colorPrimary">@color/blue_300</item>
      <item name="colorSecondary">@color/blue_300_38</item>
      <item name="android:colorBackground">@color/grey_900</item>
      <item name="colorError">@color/red_300</item>
      <item name="colorSurface">@color/grey_900</item>

      <item name="colorOnPrimary">@color/grey_900</item>
      <item name="colorOnBackground">@color/grey_200</item>
      <item name="colorOnSurface">@color/grey_200</item>
      <item name="colorOnError">@color/grey_900</item>
```
It need to be checked whether it gives desired output when theme mode get switched to the dark mode.

Also check whether extra material3 theme attributes for light and dark theme mode need to be defined when it supports material3. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm

**Comment by shelaghm** [comment]
@santosh-pingle Please check-out [ figma link](https://www.figma.com/file/xC9sMEdb18Yx1HmXJYIK32/Myco-Modules?node-id=2418%3A112841) for dark theme color attributes.

**Comment by santosh-pingle** [comment]
https://github.com/google/android-fhir/pull/1431
