### ISSUE TITLE
Modal widget in catalog app show blue color background.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1402]
**Describe the bug**

Below changes are seen after updating questionnaire theme as material3 theme.

- Modal widget in catalog app has blue color background.
- Also  on user click answer option does not show selected background.

**Component**
SDC library, reference app,

**To Reproduce**

**Expected behavior**
Show blue container background color.

**Screenshots**

<img width="353" alt="Screen Shot 2022-05-19 at 3 09 04 PM" src="https://user-images.githubusercontent.com/86107848/169263828-73233ac7-f475-4d4e-b132-2e95f4282cb6.png">

<img width="351" alt="Screen Shot 2022-05-19 at 3 09 25 PM" src="https://user-images.githubusercontent.com/86107848/169263853-d9a52173-738f-4894-a772-88fac82db090.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Working on it.

**Comment by shelaghm** [comment]
@santosh-pingle While you are fixing this issue, can you also look at the padding of the checkboxes so they have 12px padding around the checkbox icon. Screenshot for reference. Thanks!
<img width="679" alt="Screen Shot 2022-05-24 at 22 56 48" src="https://user-images.githubusercontent.com/86378921/170190268-4e67a4ea-66d4-435a-bed7-a280451ccef7.png">

**Comment by shelaghm** [comment]
@santosh-pingle Need to change the selected state BG color so it's not the same as the modal. Quick fix is to set the container color to white. @shelaghm to create M3 theming that works.

**Comment by santosh-pingle** [comment]
https://github.com/google/android-fhir/pull/1431
