### ISSUE TITLE
Generating careplan using workflow library.

### ISSUE THREAD

**Issue by parthfloyd** [google/android-fhir#1403]
**Describe the bug**
When trying to generate a careplan using the generateCarePlan method from FhirOperator.kt, it fails with an Notimplemented error.

**Component**
Workflow library

**To Reproduce**
1. Creating the patient, plandefinition and encounter resource in fhir engine. (Used dummy data from the test files)
2. Using the generateCarePlan method with the respective id of the resources saved.

**Expected behavior**
To return the careplan object.

**Additional context**
- I tried running it on the demo application, on the master branch.
- The patient, plandefinition & encounter resources - [patient-plandef-encounter.txt](https://github.com/google/android-fhir/files/8727816/patient-plandef-encounter.txt).
- Stack Trace:
kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
        at com.google.android.fhir.workflow.FhirEngineDal.read(FhirEngineDal.kt:33)
        at org.opencds.cqf.cql.evaluator.plandefinition.r4.PlanDefinitionProcessor.apply(PlanDefinitionProcessor.java:117)
        at com.google.android.fhir.workflow.FhirOperator.generateCarePlan(FhirOperator.kt:188)
        at com.google.android.fhir.demo.ScreenerViewModel$saveScreenerEncounter$1.invokeSuspend(ScreenerViewModel.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

cc: @jingtang10

**Comment by vitorpamplona** [comment]
Depends on Issues #1189 #1334 #1365 #915 and PRs: #1326 #1273 as well as: 
- [FasterXML's 525](https://github.com/FasterXML/jackson-dataformat-xml/issues/525)
- [CQL's 746](https://github.com/cqframework/clinical_quality_language/issues/746)
- [CQL's 640](https://github.com/cqframework/clinical_quality_language/issues/640)
- [CQL's 742](https://github.com/cqframework/clinical_quality_language/issues/742)
- [CQL's 745](https://github.com/cqframework/clinical_quality_language/pull/745)
- [CQL's 748](https://github.com/cqframework/clinical_quality_language/pull/748)

**Comment by parthfloyd** [comment]
I tried out the **generateCarePlan** method again after the **FhirEngineDal.read** method was implemented.
It failed with a different **NotImplementedError**, in the **PlanDefinitionProcessor.java of CQL-Evaluator**.

Precisely, **URI Definition & Questionnaire Definition Evaluation** is not yet implemented in the **resolveDefinition** method of PlanDefinitionProcessor. For now the method only supports "PlanDefinition" & "ActivityDefinition".

### The Plan Definitions I tested with:
1. [Child Routine Visit Plan Definition](https://github.com/google/android-fhir/blob/2fc900f63aba36f48fa31fc0f0760bf47aac59b2/workflow/testdata/child-visit-schedule-resources/child_routine_visit_plan_definition.json) 
2.  [Plan Definiton Emcare](https://github.com/WorldHealthOrganization/smart-emcare/blob/develop/input/resources/plandefinition/plandefinition-emcare.json)

### The Error Stack Trace Respectively:
1. [stack-trace-uri-definition-evaluation.txt](https://github.com/google/android-fhir/files/8778272/stack-trace-uri-definition-evaluation.txt) 
2. [stack-trace-questionnaire-definition-evaluation.txt](https://github.com/google/android-fhir/files/8778273/stack-trace-questionnaire-definition-evaluation.txt)

The Patient & Encounter resource: [patient-encounter-resource.txt](https://github.com/google/android-fhir/files/8778282/patient-encounter-resource.txt)
### References:
1. [PlanDefinitionProcessor.java Github reference](https://github.com/DBCG/cql-evaluator/blob/master/evaluator.plandefinition/src/main/java/org/opencds/cqf/cql/evaluator/plandefinition/r4/PlanDefinitionProcessor.java)
2. [CQL Evaluator Github](https://github.com/DBCG/cql-evaluator)

cc: @jingtang10

**Comment by jingtang10** [comment]
reformatting vitor's comment:

Depends on Issues

- #1189
- #1334
- #1365 
- #915 
- #1374 
- #656 

and PRs

- #1326 
- #1273

as well as

- https://github.com/FasterXML/jackson-dataformat-xml/issues/525 
- https://github.com/cqframework/clinical_quality_language/issues/746 and PR https://github.com/cqframework/clinical_quality_language/pull/748
- https://github.com/cqframework/clinical_quality_language/issues/640 and PR https://github.com/cqframework/clinical_quality_language/pull/745
- https://github.com/cqframework/clinical_quality_language/issues/742 disucssion https://github.com/DBCG/cql-evaluator/discussions/90
