### ISSUE TITLE
[Documentation] Upload the child visit Plan Definition & expected CarePlan & Tasks sample resource for $apply testing. 

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#1413]
**Describe the issue to be researched**
- We would like to be able to generate CarePlans & Tasks among other resources from a Plan Definition.  
- This issue is to upload the Plan Definition and the expected CarePlan & Tasks samples to the extracted from the plan definition. 

**Describe the goal of the research**
- This will help in ironing out the `$apply` functionality. 

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
@dubdabasoduba is this same or different from #1334?

Also please address the comment in the PR #1412.

**Comment by dubdabasoduba** [comment]
Closing this since it's a duplicate
