### ISSUE TITLE
SDC catalog app: Not enough padding between title and dropdown / DateTime

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1417]
**Describe the bug**
The padding should be 24px between title and dropdown element.

**Component**
SDC gallery app

**To Reproduce**
1. Go to SDC catalog app
2. Click on dropdown

![Screenshot_20220524-145621](https://user-images.githubusercontent.com/86378921/170189415-d6a48ef4-c721-4e94-a595-f1cbcac10a30.jpg)

<img width="413" alt="Screen Shot 2022-05-24 at 22 53 00" src="https://user-images.githubusercontent.com/86378921/170189698-ab6c8c4f-dfe8-4983-97a2-43072bae2eae.png">

**Comment by shelaghm** [comment]
Same issue on DateTime picker 
![Screenshot_20220524-145927](https://user-images.githubusercontent.com/86378921/170191137-e9661dff-d022-4c98-afac-e4e8ee8fa444.jpg)

**Comment by santosh-pingle** [comment]
In progress.

**Comment by jingtang10** [comment]
@shelaghm 1) how big should the gap be between the last input widget of the previous question and the question title of the next question 2) if there's subtext to a question title, how big should the gap be between the question title and the subtext, and the subtext and the input widget below the subtext?

@santosh-pingle these things determine if you should implement the gap on the question title, or on the subtext, or the input widget. beacuse if there's no question title, for example, or no subtext, you still want things to look uniform.

**Comment by shelaghm** [comment]
<img width="927" alt="Screen Shot 2022-06-21 at 15 50 35" src="https://user-images.githubusercontent.com/86378921/174910128-39ca721f-740a-4f11-972a-7c679d6b4c26.png">
This mockup should help answer the question.
