### ISSUE TITLE
[Search] Make the _lastUpdated search parameter configurable. 

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#1420]
**Is your feature request related to a problem? Please describe.**
- Currently, when we sync data from the server we use the `_lastUpdated` attribute to sync the latest resources. 
- However, on subsequent syncs, the server will return resources that specifically match the timestamp provided for the `_lastUpdated` parameter. e.g 
    - https://turn-fhir.smartregister.org/fhir/Group?_count=100&&code=35359004&_sort=-_lastUpdated&_lastUpdated=2022-05-01T18:41:15.835+03:00
- When the `gt` prefix is added to the timestamp the the server would return all the resources with a timestamp >= to the paramater value provided e.g 
     - https://turn-fhir.smartregister.org/fhir/Group?_count=100&&code=35359004&_sort=-_lastUpdated&_lastUpdated=gt2022-05-01T18:41:15.835+03:00

**Describe the solution you'd like**
- [ ] Update the [ResourceParamsBasedDownloadWorkManager](https://github.com/google/android-fhir/blob/745e2e3145e1a7749604ab5412932e27898aea8b/engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt#L53-L55) to be able to use both options for the `_lastUpdated` sync parameter e.g in the example above support both `_lastUpdated=gt2022-05-01T18:41:15.835+03:00` & `_lastUpdated=2022-05-01T18:41:15.835+03:00`
- [ ] The current functionality can remain as the main defualt one. 
- [ ] The configuration for the request parameter should be easliy usable and well documented. 

**Additional context**
- More information can be found [here](https://www.hl7.org/fhir/search.html#lastUpdated).

**Comment by f-odhiambo** [comment]
Added a query on Zullip too https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Actual.20Date.20created.20vs.20lastUpdated

CC @fredhersch @jingtang10 @Tarun-Bhardwaj
