### ISSUE TITLE
Issue using Appium to test application using SDC

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1425]
**Is your feature request related to a problem? Please describe.**
Our team is trying to use Appium to test applicaiton that use the SDC. [Appium ](http://appium.io/docs/en/commands/element/find-elements/) In the documentation, it is recommended to have unique identifiers for UI elements. Currently the SDC reuses layouts based on widget type. That results in the same resource id for each drop down, edit text etc. 

**Describe the solution you'd like**
Set the content description of a view using a combination of linkIds and View.toString() so that each view can be uniquely identified by Appium.

**Describe alternatives you've considered**
No other alternative

cc : @jjtswan

**Comment by Tarun-Bhardwaj** [comment]
@joiskash , are you still facing this issue?

**Comment by joiskash** [comment]
This has been resolved!

**Comment by joiskash** [comment]
cc: @jingtang10 We are still facing this issue. I thought we had resolved it by adding unique ids to the views.

**Comment by jingtang10** [comment]
@joiskash can you provide more context? is this still an issue?

**Comment by joiskash** [comment]
We can close this issue. We are not really using Appium anymore. We can reopen this if anyone else faces this issue.
