### ISSUE TITLE
Multiple choice selected state in material 3.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1432]
**Describe the bug**

@shelaghm 
After adding material 3 theme color, we are seeing color ui issues when multiple choice options get selected.

#1424 

<img width="430" alt="Screen Shot 2022-06-01 at 5 22 30 PM" src="https://user-images.githubusercontent.com/86107848/171398876-50f66947-12b7-4877-b1de-918326ffb80c.png">

<img width="435" alt="Screen Shot 2022-06-01 at 5 23 00 PM" src="https://user-images.githubusercontent.com/86107848/171398903-832b4a54-0c96-411b-abfe-ed6511604383.png">

<img width="430" alt="Screen Shot 2022-06-01 at 5 24 31 PM" src="https://user-images.githubusercontent.com/86107848/171398943-7b194224-3475-4ba3-8fc1-53be4a505565.png">

<img width="433" alt="Screen Shot 2022-06-01 at 5 25 03 PM" src="https://user-images.githubusercontent.com/86107848/171399439-a86687af-aaea-448e-9864-08dad429f768.png">

**Component**

SDC library, reference app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@shelaghm can you please revise figma ui design as per material 3

**Comment by shelaghm** [comment]
@santosh-pingle

Please take a look at the figma / screenshot for the selected state values. These surface selection colors are based on the M3 design guidelines and uses an opacity of 12% for a selected state. 

The other change is that the dialog/modal card is also set at 11% opacity.
<img width="1140" alt="Screen Shot 2022-06-01 at 14 29 35" src="https://user-images.githubusercontent.com/86378921/171505199-430a93d7-34c5-43b3-9c58-24b21f22254e.png">
