### ISSUE TITLE
SDC: Include 'text' attribute in QuestionnaireResponse

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1439]
**Is your feature request related to a problem? Please describe.**
I have a scenario where I need to record the weight and the height of a patient. With these two values, I need to show the patient's MUAC assessment in a 'display' widget. I want to save the text of the 'display' widget to our server using structure map based extraction but the items in a QuestionnaireResponse only include the 'linkId' and the 'answer' properties.

**Describe the solution you'd like**
I would like the QuestionnaireResponse to also include the text attribute as is shown in the [specification](https://www.hl7.org/fhir/questionnaireresponse.html).

**Describe alternatives you've considered**
The alternative is creating a 'string' widget and setting the initial value as the MUAC assessment result and making it read-only. This feels quite verbose and I can't style the text if need be.

**Additional context**
N/A

**Would you like to work on the issue?**
I don't know who could look into this but I'd really appreciate the help.

**Comment by jingtang10** [comment]
thanks for raising this @KhumboLihonga - am i right in saying you would like for the questionnaire response generated by structured data capture library to include the text field? what's the use of this? isn't the text field just going to be a copy of the text field of the questionnaire resource? can you just access the questionnaire? thanks

**Comment by KhumboLihonga** [comment]
- am i right in saying you would like for the questionnaire response generated by structured data capture library to include the text field? -> Yes, you are right.
- what's the use of this? -> in my scenario, the given weight and height combination will enable a specific display item that shows the MUAC assessment for those two values. We want to be able to record this assessment as an observation.
- isn't the text field just going to be a copy of the text field of the questionnaire resource? -> Yes, it will.
- can you just access the questionnaire? -> When using structure map based extraction, don't we just receive the QuestionnaireResponse as the source? Can I also access the Questionnaire resource?

If there's a better way to handle this, please let me know.

**Comment by f-odhiambo** [comment]
> * am i right in saying you would like for the questionnaire response generated by structured data capture library to include the text field? -> Yes, you are right.
> * what's the use of this? -> in my scenario, the given weight and height combination will enable a specific display item that shows the MUAC assessment for those two values. We want to be able to record this assessment as an observation.
> * isn't the text field just going to be a copy of the text field of the questionnaire resource? -> Yes, it will.
> * can you just access the questionnaire? -> When using structure map based extraction, don't we just receive the QuestionnaireResponse as the source? Can I also access the Questionnaire resource?
> 
> If there's a better way to handle this, please let me know.

@jingtang10 any feedback on this approach? CC @Tarun-Bhardwaj @KhumboLihonga

**Comment by fredhersch** [comment]
@maimoonak @KhumboLihonga is this issue merfed with #971? Can we close this OR are there still open questions?

cc: @jingtang10 @Tarun-Bhardwaj @f-odhiambo

**Comment by f-odhiambo** [comment]
I think we can close this and mark as DONE

**Comment by KhumboLihonga** [comment]
Apologies for the late response, but yes we can close this.
