### ISSUE TITLE
Subtitle text not behaving as expected

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1450]
Case 1: The text "Correct!" appears twice, once incorrectly above the question "Cats are better than dogs", and once correctly based on the `enableWhen` element.
```json
{
  "resourceType": "Questionnaire",
  "status": "active",
  "item": [
    {
      "linkId": "2",
      "text": "Demographic Information",
      "type": "group",
      "item": [
        {
          "linkId": "2.1",
          "text": "Cats are better than dogs",
          "type": "boolean"
        },
        {
          "linkId": "2.1.1",
          "text": "Correct!",
          "type": "display",
          "enableWhen": [
            {
              "question": "2.1",
              "operator": "=",
              "answerBoolean": true
            }
          ]
        }
      ]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/7772901/172480010-6735ffef-38ba-4021-8e1b-f379d0c2edf7.png)

Case 2: When `enableWhen` is a child of the item, the "Correct!" text never appears. It still shows up incorrectly above the question, like in Case 1.
```json
{
  "resourceType": "Questionnaire",
  "status": "active",
  "item": [
    {
      "linkId": "2",
      "text": "Demographic Information",
      "type": "group",
      "item": [
        {
          "linkId": "2.1",
          "text": "Cats are better than dogs",
          "type": "boolean",
          "item": [
            {
              "linkId": "2.1.1",
              "text": "Correct!",
              "type": "display",
              "enableWhen": [
                {
                  "question": "2.1",
                  "operator": "=",
                  "answerBoolean": true
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
![image](https://user-images.githubusercontent.com/7772901/172480399-901adc08-139c-4c43-ab6c-813336332687.png)

This is using the published version of `com.google.android.fhir:data-capture:0.1.0-beta03`.

**Comment by jingtang10** [comment]
@PallaviGanorkar can you take a look at this please

**Comment by santosh-pingle** [comment]
https://github.com/google/android-fhir/pull/1222

**Comment by PallaviGanorkar** [comment]
Case 1: Reproducible in version com.google.android.fhir:data-capture:0.1.0-beta03, but in latest code base its not reproducible, its working fine.

**Comment by williamito** [comment]
For Case 2, I did not understand that it was considered subtitle text because the text "Correct!" is rendered the same as the other text on the questionnaire. The intended use would be more clear if the text styling was different.

That said, I think it is difficult to understand when something would be considered a subtitle vs a new text element. Can you describe how the rendering logic works based on the JSON structure for documentation purposes?

As an alternative, maybe we could use the [displayCategory](http://hl7.org/fhir/R4/extension-questionnaire-displaycategory.html) extension to make the rendering style decisions more explicit.

**Comment by williamito** [comment]
In addition, the display of "Correct!" does not appear to respect the enableWhen.

<img width="225" alt="image" src="https://user-images.githubusercontent.com/7772901/179696580-0326dadc-5b2e-4ecf-8fd9-a028c33d89fa.png">

re: formatting based on JSON structure, the top level text "Demographic Information" looks the same as "Cats are better than dogs". I would expect the contents of a "text" field of a "group" type to be a section header and render differently than a question text.

**Comment by jingtang10** [comment]
> For Case 2, I did not understand that it was considered subtitle text because the text "Correct!" is rendered the same as the other text on the questionnaire. The intended use would be more clear if the text styling was different.
> 
> That said, I think it is difficult to understand when something would be considered a subtitle vs a new text element. Can you describe how the rendering logic works based on the JSON structure for documentation purposes?
> 
> As an alternative, maybe we could use the [displayCategory](http://hl7.org/fhir/R4/extension-questionnaire-displaycategory.html) extension to make the rendering style decisions more explicit.

i agre with this. maybe we should use display category.

maybe we should use "instructions" http://hl7.org/fhir/R4/valueset-questionnaire-display-category.html

**Comment by jingtang10** [comment]
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Hints.20for.20questions

**Comment by shelaghm** [comment]
> re: formatting based on JSON structure, the top level text "Demographic Information" looks the same as "Cats are better than dogs". I would expect the contents of a "text" field of a "group" type to be a section header and render differently than a question text. 

@williamito @jingtang10 @santosh-pingle This is a great call out. I agree they should render differently. From what I'm aware of we don't have a "section header" text style. I have some old mocks where we have this type of text rendering above a question. See below
I'd recommend we use the Large Body - Roboto text style. @santosh-pingle any questions/issues with implementing this type of section header text style?

<img width="1273" alt="Screen Shot 2022-07-21 at 06 01 59" src="https://user-images.githubusercontent.com/86378921/180220222-175ac5fb-5efe-4510-89ed-59339120cecf.png">

**Comment by shelaghm** [comment]
> i agre with this. maybe we should use display category.
> maybe we should use "instructions" http://hl7.org/fhir/R4/valueset-questionnaire-display-category.html

@jingtang10 @williamito 

The "subtitle text" usually instructions that accompany the questions. I think changing it to "instructions" might be the most clear.

**Comment by santosh-pingle** [comment]
Looking into it. thanks!

**Comment by santosh-pingle** [comment]
> > re: formatting based on JSON structure, the top level text "Demographic Information" looks the same as "Cats are better than dogs". I would expect the contents of a "text" field of a "group" type to be a section header and render differently than a question text.
> 
> @williamito @jingtang10 @santosh-pingle This is a great call out. I agree they should render differently. From what I'm aware of we don't have a "section header" text style. I have some old mocks where we have this type of text rendering above a question. See below I'd recommend we use the "Title Medium - Roboto 16 Medium" text style. @santosh-pingle any questions/issues with implementing this type of section header text style?
> 
> <img alt="Screen Shot 2022-07-21 at 06 01 59" width="1273" src="https://user-images.githubusercontent.com/86378921/180220222-175ac5fb-5efe-4510-89ed-59339120cecf.png">

I am on it.

**Comment by santosh-pingle** [comment]
> > i agre with this. maybe we should use display category.
> > maybe we should use "instructions" http://hl7.org/fhir/R4/valueset-questionnaire-display-category.html
> 
> @jingtang10 @williamito
> 
> The "subtitle text" usually instructions that accompany the questions. I think changing it to "instructions" might be the most clear.

We can provide implementation. thanks!

**Comment by santosh-pingle** [comment]
> > > i agre with this. maybe we should use display category.
> > > maybe we should use "instructions" http://hl7.org/fhir/R4/valueset-questionnaire-display-category.html
> > 
> > 
> > @jingtang10 @williamito
> > The "subtitle text" usually instructions that accompany the questions. I think changing it to "instructions" might be the most clear.
> 
> We can provide implementation. thanks!

looking into it.
