### ISSUE TITLE
Error handling for questionnaire rendering

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#1473]
**Is your feature request related to a problem? Please describe.**
We should triage all the exceptions we through during questionnaire rendering and figure out if we do want to throw exceptions or handle errors in a more lenient way - so that we don't get client applicaitons crashing all the time.

This is more of a triage and design task, there will be some code change at the end, but I think those things will be easy to do.

One artifact to produce as part of this issue is a design that says, for example: for malformed questionnaires, we will know an illegal state exception, but for questions missing a link id, we will log a warning etc etc... 

This will invovle talking with implementers.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
@santosh-pingle

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 would you be able to add more context on this issue please?

**Comment by santosh-pingle** [comment]
@Tarun-Bhardwaj @jingtang10 
Can you please provide more details.

**Comment by jingtang10** [comment]
@joiskash @maimoonak fyi
