### ISSUE TITLE
The checkbox is very close to the left edge

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1477]
**Describe the bug**
The checkbox is very close to the left edge.

![unnamed](https://user-images.githubusercontent.com/86107848/176110003-7806da4b-0100-40a9-812b-a8fa93c7c713.png)

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
in progress.

**Comment by santosh-pingle** [comment]
<img width="433" alt="Screen Shot 2022-06-28 at 12 11 56 PM" src="https://user-images.githubusercontent.com/86107848/176111081-f1ccd3f6-c15e-4271-a91e-654395ece481.png">

**Comment by santosh-pingle** [comment]
in progress.

**Comment by santosh-pingle** [comment]
@shelaghm 

Can you please share radio button drawable icon which has left padding 18dp for both selected and unselected state, so that I can try these drawable icons.
(root cause is when button drawable get drawn on canvas it assigns zero value to the left bound, therefore it appears very close to left edge.)

**Comment by shelaghm** [comment]
Shared icons on chat. Icons are exported so they are all 24px. You'll notice there's slight white space around the icons, this is so that it is consistent across the whole icon set. 
This means the padding is 16px, not 18px. See visual below and hopefully this works for you?
<img width="752" alt="Screen Shot 2022-09-22 at 15 35 39" src="https://user-images.githubusercontent.com/86378921/191863633-5aa53501-6b3c-4c27-905c-c7de3e711b65.png">

**Comment by santosh-pingle** [comment]
@shelaghm 
16/18 dp left padding is not present in shared icons. 
Can you please share icons which has 16/18 dp left padding in icon itself.
May be you have to design new icons such way that it will have left padding in it.

16/18 dp left padding is missing from icon.  
<img width="422" alt="Screen Shot 2022-09-23 at 12 21 53 PM" src="https://user-images.githubusercontent.com/86107848/191906505-db820e09-e567-401d-a39c-0a1315592e70.png">

**Comment by shelaghm** [comment]
@santosh-pingle Does the 16px padding need to be on the icons? In the code can you specify the 16px padding around the icon? I think that's how it is typically done.

**Comment by santosh-pingle** [comment]
> @santosh-pingle Does the 16px padding need to be on the icons? In the code can you specify the 16px padding around the icon? I think that's how it is typically done.
@shelaghm 
My understanding was the same.
But in radio button/checkbox when you give padding, it get applied around the text. Icons always get drawn with `zero left padding/ start bound `.
Therefore, it is required to apply left padding/start bound on icons itself.

**Comment by shelaghm** [comment]
@Santosh Pingle ah, got it. I added new icons with padding included. Shared on chat.

**Comment by narendra-keda** [comment]
To add padding before the RadioButton icon, you can use a drawable with padding as the button for the RadioButton. Here's how you can do it:  First, create a new drawable resource file padded_icon.xml in the res/drawable directory:

<?xml version="1.0" encoding="utf-8"?>
<inset xmlns:android="http://schemas.android.com/apk/res/android"
    android:drawable="@android:drawable/btn_radio"
    android:insetLeft="10dp" />

// This will do the task. But it will also change the icon.

So Either use your own radio button icon selector, or create like below.
(1) Add two drawables btn_radio_on and bin_radio_off.
(2) create new selector resource with below code.

<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@drawable/btn_radio_on" android:state_checked="true" android:state_window_focused="false" />
    <item android:drawable="@drawable/btn_radio_off" android:state_checked="false" android:state_window_focused="false" />

    <item android:drawable="@drawable/btn_radio_off" android:state_checked="false" />
    <item android:drawable="@drawable/btn_radio_on" android:state_checked="true" />

</selector>

(3) use this selector resource as drawable in padded_icon.xml.

(4) use padded_icon.xml as button in radiobutto.
