### ISSUE TITLE
Batch Download of resources.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#1491]
**Describe the bug**
Define a useful way for developer apps to be able to sync resources efficiently using available FHIR apis and also be able to figure out  resources that need to be purged because user doesn't have access to them anymore or they are deleted from the server.

**Component**
Core library, reference app,

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by fredhersch** [comment]
@aditya-07are you working on this?

**Comment by omarismail94** [comment]
Closing as we do this now with BundleDownloadRequest
