### ISSUE TITLE
Performance Benchmarking of FhirEngine module.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#1492]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
closing this since it's too generic.

**Comment by jingtang10** [comment]
also because we already added the benchmark modules
