### ISSUE TITLE
Create new attribute to allow developers to override minLines in an multiline text widget

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1518]
Would this change allow the developer application to change the minLines ? Maybe minLines should be part of a new multi-line text style?

_Originally posted by @aditya-07 in https://github.com/google/android-fhir/pull/1517#discussion_r933206201_

**Comment by jingtang10** [comment]
@aditya-07 FYI

**Comment by santosh-pingle** [comment]
looking into it!
