### ISSUE TITLE
SDC: Add progress bar for paginated questionnaire

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1523]
**Is your feature request related to a problem? Please describe.**
Feature request from Ona. https://github.com/opensrp/fhircore/issues/1384
Problem: users don't know how far along they are when completing a multi-page questionnaire

**Describe the solution you'd like**
A visual progress bar at the top of the questionnaire. Use determinate indicators. [Material design Implementation guide here](https://material.io/components/progress-indicators/android#using-progress-indicators)

**Describe alternatives you've considered**
We could also do "1 of 13" in text only. I think this is less useful than a visual progress bar.

**Screenshot**
<img width="1022" alt="Screen Shot 2022-08-02 at 13 15 25" src="https://user-images.githubusercontent.com/86378921/182465216-c8305d1c-91a2-47fd-9c3e-73accb535a0f.png">

**Would you like to work on the issue?**
Yes, I'll add designs

**Comment by jingtang10** [comment]
related to #1539

**Comment by shelaghm** [comment]
Move forward with visual progress bar and also make progress bar track scroll progress on a single page questionnaire.

**Comment by Tarun-Bhardwaj** [comment]
@nsabale7 , would you like to work in this fix?

**Comment by nsabale7** [comment]
> @nsabale7 , would you like to work on this fix?

Sure @Tarun-Bhardwaj, I can take this

**Comment by shelaghm** [comment]
Question: do we want to add page 1 of 3 next to next/back buttons on a paginated.
