### ISSUE TITLE
SDC catalog - Add behavior tab (to show skip logic and calculations behavior)

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1524]
**Is your feature request related to a problem? Please describe.**
We need an additional tab to demonstrate SDC behavior such as calculations and skip logic

**Describe the solution you'd like**
Add a 3rd tab to the navigation bar. 

**Describe alternatives you've considered**
@jingtang10 and I have discussed adding this to "components", but behavior feels distinct of how multiple components might behave and interact. It also doesn't fit in layouts. 

**Additional context**
See figma file posted in chat. 
![SDC - landing - behaviors](https://user-images.githubusercontent.com/86378921/182474909-986344e4-0ab2-4aac-8e36-6fda7fc772e1.png)

**Comment by PallaviGanorkar** [comment]
@shelaghm Could you please provide icons for Behaviors, Calculations and Skip logic.

**Comment by PallaviGanorkar** [comment]
@shelaghm Please find attached screen shot, here Behaviors icon looks smaller compare to Components and Layouts icon,
I have used icon from suggested link  https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Acalculate%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

![Screenshot_20220907_163026](https://user-images.githubusercontent.com/13957417/188863515-187b0dd7-26d0-4c15-9878-54b2a380d9b0.png)

**Comment by PallaviGanorkar** [comment]
One thing I observed here, there is transparent area present in all four sides of Behavior icon which is not in Layouts icon and Components icon has it on right and top border. So can we update Behavior icon as required.

**Comment by shelaghm** [comment]
@PallaviGanorkar So I think you've implemented the behavior icon correctly, there should be transparent padding /border around the icon. Instead we need to fix the other two icons so they are consistent. 

Attaching some screenshots from my figma that shows the padding around the icons. All icons should be 24px 
<img width="326" alt="Screen Shot 2022-09-08 at 07 11 13" src="https://user-images.githubusercontent.com/86378921/189145045-298be22c-7b7d-4eb5-b212-cb8518e7de8c.png">
<img width="178" alt="Screen Shot 2022-09-08 at 07 10 19" src="https://user-images.githubusercontent.com/86378921/189145051-547e7f60-2f3e-4790-98e9-0d1dcc505550.png">
<img width="294" alt="Screen Shot 2022-09-08 at 07 10 12" src="https://user-images.githubusercontent.com/86378921/189145058-8097755b-a57e-4afc-b3ae-b820d721ab02.png">

Can you update the other two icons with these two below?

Component icon https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Awidgets%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

Turns out the layout icon I was using isn't open source, so let's also also switch to an open source icon while we are making the changes. https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alist_alt%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

Thanks!
