### ISSUE TITLE
SDC catalog app: show calculation behavior

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1525]
**Is your feature request related to a problem? Please describe.**
Demonstrate how the calculation functionality in SDC library works by adding it as a widget in the new behavior tab. 

**Describe the solution you'd like**
Show an example of a common calculation that developers might do along with a message of the result of the calculation.

**Describe alternatives you've considered**
Open to other ideas for the calculation example to show or additional feedback we'd like to show to users on the result of the calculation.

**Additional context**
Designs WIP, open to input and feedback
<img width="986" alt="Screen Shot 2022-08-02 at 14 18 53" src="https://user-images.githubusercontent.com/86378921/182475931-8ab0d2f1-9072-4502-9efb-e7027be29f62.png">

**Comment by PallaviGanorkar** [comment]
This feature is implemented in PR #1380 . So, closing this issue

**Comment by PallaviGanorkar** [comment]
info is not displayed in grey box, So need to confirm with owner before closing issue
