### ISSUE TITLE
SDC catalog app: Show enable when (skip logic) behavior

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1526]
**Is your feature request related to a problem? Please describe.**
Demonstrate to developers how the SDC skip logic behavior works.

**Describe the solution you'd like**
Add skip logic as a widget in the behavior tab. Skip logic should show a realistic example of how skip logic works. Example: By selecting yes on the first question, the second question appears. If no is selected, the question does not appear.

**Additional context**
Open to feedback on what we should show. Designs are WIP. 
<img width="758" alt="Screen Shot 2022-08-02 at 14 28 27" src="https://user-images.githubusercontent.com/86378921/182476595-a3f7f595-b10d-4bdf-9894-f47f9a411299.png">

**Comment by PallaviGanorkar** [comment]
@shelaghm Informative UI for skip logic behavior at the bottom of screen, It will be the part of app or need to add component in SDC?

**Comment by shelaghm** [comment]
@PallaviGanorkar the informative UI was intended to show up in the SDC Catalog app, but not in deployment apps. The idea behind the grey box is to help visualize the skip behavior that's "invisible" on screen, but can be found in the code. In the library itself the skip logic informative UI would not be displayed. 

@jingtang10 Curious to hear your thoughts?

**Comment by jingtang10** [comment]
yeah i agree this grey box can be a thing in the catalog app.

no need to implement it in the sdc lib.

**Comment by jingtang10** [comment]
for 2. releated ticket: https://github.com/google/android-fhir/issues/1528 but i don't think they're the same now...

**Comment by shelaghm** [comment]
@jingtang10 
Yes, this is the same grey box as the `help text box`. We don't need to use the icon for this box, so can remove that if it adds a lot of complexity
Yes, I suggest we use terminology that aligns with FHIR, so lets update this component to `enable when` as you suggested

**Comment by shelaghm** [comment]
@PallaviGanorkar will look into if we can use dynamic text to replace the `Help` header text. If that's not possible, then we use a simpler text box such as option 1 described by Jing above.

**Comment by shelaghm** [comment]
Skip logic text in box: "If Yes is selected, a follow-up question is displayed. If No is selected, no follow-up questions are displayed."

**Comment by PallaviGanorkar** [comment]
@shelaghm  I have used info icon from https://fonts.google.com/icons?selected=Material%20Icons%3Ainfo%3A
Please let me know if any change required in icon

**Comment by PallaviGanorkar** [comment]
@shelaghm Please find attached screenshot below, info grey box is displayed at the bottom of screen as other UI on the screen is rendered from SDC lib and i don't have reference to particular UI component from Catalog App

![Skip_Logic_info](https://user-images.githubusercontent.com/13957417/194289481-7f774ea6-e40a-47ff-94c8-3e3ad75dd708.png)

**Comment by shelaghm** [comment]
@PallaviGanorkar this looks good to me!

**Comment by PallaviGanorkar** [comment]
@shelaghm Setting icon on the right top of the screen, is there any functionality expected on click of this icon?

**Comment by shelaghm** [comment]
@PallaviGanorkar the settings/gear icon is used to display `error states`
I don't believe we want to show error states for this screen as skip logic is a behavior and there's no error state associated with it. We can remove the gear icon from this screen unless there's some other functionality we want to show under the gear icon?
@jingtang10 @santosh-pingle what do you think?

**Comment by jingtang10** [comment]
@shelaghm sgtm! thanks.

just to summarise - we are putting this in the catalog app (instead of using the help item control and rewrite the questionnaire) because of the "skip logic" title in the grey box. if we want to just reuse the help item control, the title would not be configurable to "skip logic".

pallavi has already done this in her latest udpate for the pr.

and the gear icon has been removed.

**Comment by shelaghm** [comment]
Sounds good. Thanks for the update!
