### ISSUE TITLE
Add dropdown list support in the sdc library

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#153]
This should make use of the extension item control: http://hl7.org/fhir/uv/sdc/2019May/rendering.html#control-appearance

**Comment by kashyapj2793** [comment]
Suppose there is not item-control extension, would this be the default widget for choice questions?

**Comment by jingtang10** [comment]
I think it makes sense for this to be default as opposed to radio button. We can also define a heuristic that says if the number of items is less than 3 or 4 we use radio button instead. But we don't have to do that now. Default to this is fine. FYI @fredhersch .

**Comment by jingtang10** [comment]
Perhaps use this as an example as well: https://www.hl7.org/fhir/questionnaire-example-bluebook.html

It's a good exmaple becuase it doesn't use valuesets for the choices questions.
