### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by Chandra-Sekhar-Bala** [google/android-fhir#1533]
**Is your feature request related to a problem? Please describe.**
Issue templates are a bit old, and for first-timers a bit confusing.

**Describe the solution you'd like**
Update issue templates like modern templates. And it's easy to understand and fill.

**Additional context**
Something like this.
<img width="269" alt="issue" src="https://user-images.githubusercontent.com/57448981/182703976-4758254f-62c8-4148-be71-2546eeb2832a.png">

**Would you like to work on the issue?**
Yes

**Comment by Tarun-Bhardwaj** [comment]
To be revisited at a later date.
