### ISSUE TITLE
Overlapping of views in paginated layout

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1536]
**Describe the bug**
When moving across the pages in paginated layout questionnaire, view gets overlapped.

**Component**
SDC library

**To Reproduce**
1. Use large paginated questionnaire with choice type questions.
2. Move across pages and answering some questions
3. We see overlapping text

**Screenshots**
![Screenshot_20220804-182645](https://user-images.githubusercontent.com/82660329/182855375-675370c8-eee8-42fa-a6ed-a0515a5ef87d.jpg)
![Screenshot_20220804-182634](https://user-images.githubusercontent.com/82660329/182855381-0c84cbfe-2a61-44ab-8b13-c379c1a782d8.jpg)

**Smartphone (please complete the following information):**
 - Device: All

**Comment by PallaviGanorkar** [comment]
@nsabale7 Could you Please attach questionnaire json if possible?

**Comment by nsabale7** [comment]
@PallaviGanorkar 
[anc-visit-questionnaire.zip](https://github.com/google/android-fhir/files/9369674/anc-visit-questionnaire.zip)

**Comment by PallaviGanorkar** [comment]
@nsabale7 I have tried to reproduce this issue with attached  questionnaire json. But could not reproduce this issue on Device Nokia 3.4 API 30 and emulators Pixel 5 API 32, Pixel 5 API 27, Nexus 5X API 24.

Please find attached video for more details.
[emul_Pixel5_API32_2022-08-18-133332.webm](https://user-images.githubusercontent.com/13957417/185344987-8b368469-3b3b-4e22-8fdc-4450dff0ad27.webm)


Could you please provide more details about device and build you are using?

**Comment by nsabale7** [comment]
@PallaviGanorkar Even I was not able to reproduce this issue on current master and beta04. We can close this issue for now.

**Comment by PallaviGanorkar** [comment]
As per above discussion, not able to reproduce this issue on current master and beta04 on multiple devices and emulators . So closing this issue.
