### ISSUE TITLE
Open choice/Drop Down view issue

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1537]
**Describe the bug**
When multiple open choice/drop down questions are present in single page, answers get mismatched.

**Component**
SDC library

**To Reproduce**
1. Use below questionnaire
[patient-registration.zip](https://github.com/google/android-fhir/files/9260187/patient-registration.zip)

**Screenshots**
https://user-images.githubusercontent.com/82660329/182856609-65f5e784-f865-4bb8-a07a-0f14a81de664.mp4

**Comment by aditya-07** [comment]
@nsabale7 Can you confirm if the issue is still there? I am not able to reproduce the issue on master, beta03 or beta04.
if yes, can you please add the sdc commit where you are seeing this issue.

**Comment by nsabale7** [comment]
@aditya-07 I was able to reproduce this issue on master, beta04.
Attaching couple of videos for your reference.

1. Pixel 4a(13)
Issue found on master
https://user-images.githubusercontent.com/82660329/185320399-450600b3-2007-49b2-a344-6f8deaca883d.mp4

2. Infinix (11)
Issue found on beta04
https://user-images.githubusercontent.com/82660329/185321993-5d1fb92e-4518-4035-9b2f-3d0fcaf7db2d.mp4

As previous attached questionnaire had custom views, I am attaching new questionnaire.
[paginated_layout_questionnaire.zip](https://github.com/google/android-fhir/files/9368333/paginated_layout_questionnaire.zip)
