### ISSUE TITLE
Use navigation library for the sdc gallery app

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#154]
https://developer.android.com/guide/navigation/navigation-getting-started

**Comment by s-ayush2903** [comment]
I would like to work on this issue(if allowed), I have knowledge of Jetpack navigation patterns and have implemented in some of mine mini applications. Also, do we have some mockups that I need to follow while implementing the navigation pattern. 
Thanks

**Comment by jingtang10** [comment]
if you want to take this issue, please first try the application in the module `datacapturegallery`. the navigation pattern is fairly simple (for now).

**Comment by Prakhar-Agarwal-byte** [comment]
@jingtang10 I have tried the `datacapturegallery` application can I work on this issue, please?

**Comment by epicadk** [comment]
I have tried the `datacapturegallery` too. I can work on this.

**Comment by s-ayush2903** [comment]
@epicadk You should've atleast commented here before starting, I had uncommitted work for this issue since the day I commented here to work : (

**Comment by epicadk** [comment]
> @epicadk You should've atleast commented here before starting, I had uncommitted work for this issue since the day I commented here to work : (

Oops sorry. I'll thought since you didn't respond to @jingtang10 you weren't working on it. I had started a few hours before I commented but I was having connectivity issues where I stay. If you are done I'll close the pr it's WIP anyways . Sorry 😥.

**Comment by s-ayush2903** [comment]
Nope don't close it, go ahead with your PR :v:

**Comment by epicadk** [comment]
> Nope don't close it, go ahead with your PR ✌️

Thanks and sorry. I'll be sure to keep it in mind next time.

**Comment by epicadk** [comment]
Okay I realize @Prakhar-Agarwal-byte was working on the issue too. I'll close it if you are working on it.

**Comment by jingtang10** [comment]
Thanks everyone. Appreciate the participation.

With this issue since @epicadk has opened a PR I'm happy to assign this to @epicadk. But going forward please make sure to communicate your intention, any questions, the action plan, and critically any design considerations before starting working on a PR.

@s-ayush2903 and @Prakhar-Agarwal-byte if you already have done a bit of work but haven't sent out the PR perhaps a good way to collaborate on this is for you to leave a review on @epicadk 's PR.

Many thanks!
