### ISSUE TITLE
Initial expression extension on a 'choice' item with valueString answer options causes app to crash

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1541]
**Describe the bug**
When an item is using the type 'choice' and the answer options array is comprised of valueString objects, it crashes the app when using initialExpression extension.

**Component**
Demo app

**To Reproduce**
1. Update the file 'new-patient-registration-paginated.json' to use an item of the type 'choice' for the country attribute.
2. Run the demo app
3. Tap on a patient
4. Tap on the edit button
5. The app will crash with the error: Caused by: java.lang.IllegalArgumentException: Mismatching question type CHOICE and answer type string for PR-address-country

**Expected behavior**
The item should populate with the appropriate string selected

**Screenshots**
N/A

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
Support for the string type for a choice widget was added in this [PR](https://github.com/google/android-fhir/pull/1399). The updated item would look like this:
```
{
              "extension": [
                {
                  "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-initialExpression",
                  "valueExpression": {
                    "language": "text/fhirpath",
                    "expression": "Patient.address.country",
                    "name": "patientCity"
                  }
                }
              ],
              "linkId": "PR-address-country",
              "definition": "http://hl7.org/fhir/StructureDefinition/Patient#Patient.address.country",
              "type": "choice",
              "answerOption": [
                {
                  "valueString": "Kenya"
                }
              ],
              "required": true,
              "text": "Country",
              "_text": {
                "extension": [
                  {
                    "extension": [
                      {
                        "url": "lang",
                        "valueCode": "sw"
                      },
                      {
                        "url": "content",
                        "valueString": "Nchi"
                      }
                    ],
                    "url": "http://hl7.org/fhir/StructureDefinition/translation"
                  }
                ]
              }
            }
          ]
        }
```

**Would you like to work on the issue?**
Maybe the author of the [PR](https://github.com/google/android-fhir/pull/1399) can look into resolving this

**Comment by Gental-Giant** [comment]
@f-odhiambo Kindly take a look at this

**Comment by f-odhiambo** [comment]
@Gental-Giant This is related to https://github.com/google/android-fhir/issues/1098 . It seems like the usage of the wrong type. A choice can not have a string value. So if he matched `valueCoding` it should work. @KhumboLihonga  can you test the working JSON and update the ticket?

**Comment by KhumboLihonga** [comment]
When using valueCoding option and the initial expression expression is linked to a coding object, everything works fine. However, in our case we want to populate a choice item with a [district](https://www.hl7.org/fhir/datatypes-definitions.html#Address.district) which is stored as a string. 

We are doing this so that the user doesn't have to type out the district for every patient that they are registering. Instead, they would just select the district from a drop-down or auto-complete item which is far more efficient and less prone to errors.

As per the FHIR [spec](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.answerOption), a valueString answerOption should be supported and this support was added in this https://github.com/google/android-fhir/pull/1399.

**Comment by PallaviGanorkar** [comment]
This issue will be fixed in PR https://github.com/google/android-fhir/pull/1560 as this Issue replicates #1542

**Comment by PallaviGanorkar** [comment]
closing this issue as PR #1560 is merged
