### ISSUE TITLE
Click

### ISSUE THREAD

**Issue by Jeli-09** [google/android-fhir#1544]
**Describe the bug**

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by aditya-07** [comment]
@Jeli-09 Can you please describe the issue you are facing in more detail.
