### ISSUE TITLE
Double selection of a dropdown

### ISSUE THREAD

**Issue by Itskiprotich** [google/android-fhir#1554]
**Describe the bug**
When filling a questionnaire with an input type choice drop-down, the answer is not automatically picked on the first selection, it requires a second selection for it to update on the input field.

**Component**
SDC library
 
**Expected behavior**
Upon selection of an answer from the drop-down list, the answer should be automatically updated on the input field.

**Screenshots** 
[device-2022-08-11-122529.webm](https://user-images.githubusercontent.com/26279422/184105258-1745b205-0498-46d8-874f-ac167bd4247d.webm)

**Smartphone (please complete the following information):**
 - Device:All

**Additional context**
N/A

**Comment by williamito** [comment]
Did this occur after upgrading to beta04? I have also reproduced this behavior on that version.

**Comment by Itskiprotich** [comment]
Yes, I'm experiencing it on beta04
