### ISSUE TITLE
[Form Validation] Hidden Required fields should not be validated

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#1579]
**Describe the bug**
- Currently, when a field on the Questionnaire is hidden the Required validation check is still applied to it. 
- This means the user will get an error prompting them to fill all required fields. The user is however not able to fill in the field since it's hidden. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a Required field in a questionnaire. 
2. Fill up the questionnaire and try to submit it. 
3. An error asking the user to confirm that all the fields were filled up will be thrown. 

**Expected behaviour**
- [ ] All visible required fields should be validated
- [ ] All hidden required fields should not be validated on submission. 

**General Implementation Idea**
- [ ] We should not validate any field when the value of the hidden extension is set to `true`
    - This means we first check for the hidden extension and then run validation on the field.  

**Assumption**
- Skip Logic also uses the hidden extension to also hide/show fields. 

**Screenshots**
https://user-images.githubusercontent.com/4817531/188339502-7f9d17a0-7292-4412-ba86-bc97687e985d.mp4

Hidden field JSON
```json
{
  "linkId": "83943853-d9c9-46ad-da39-2cc55e93b974",
  "type": "integer",
  "text": "Birth weight",
  "required": true,
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden",
      "valueBoolean": true
    }
  ]
}
```

**Smartphone (please complete the following information):**
 - Device: Emulator & Xiaomi 11T Pro
 - Android version: 10 & 12 

Related SDK Issue
- https://github.com/google/android-fhir/issues/1579

**Comment by maimoonak** [comment]
Done in PR #1610 . The validator would not perform any validation on hidden fields.
