### ISSUE TITLE
Input of one datepicker view get updated to another date picker view in layout.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1580]
**Describe the bug**
If number of date pickers are added to the layout/form, and input is given to the one date picker view then same value get updated to the another random date picker from the layout.
Please refer attached video and questionnaire json for more information.

https://user-images.githubusercontent.com/86107848/188381513-f8c6d2ef-31e9-49aa-aed9-b831eceb18b0.mov

```
{
  "resourceType": "Questionnaire",
  "item": [
    {
      "linkId": "1",
      "text": "When was your last menstrual period? (LMP)",
      "type": "date"
    },
    {
      "linkId": "1-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "2-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "3-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "4-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "5-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "6-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "7-most-recent",
      "text": "First day of most recent period",
      "type": "display"
    },
    {
      "linkId": "2",
      "text": "When was your last menstrual period? (LMP)-1",
      "type": "date"
    },
    {
      "linkId": "3",
      "text": "When was your last menstrual period? (LMP)-2",
      "type": "date"
    },
    {
      "linkId": "4",
      "text": "When was your last menstrual period? (LMP)-4",
      "type": "date"
    },
    {
      "linkId": "5",
      "text": "When was your last menstrual period? (LMP)-5",
      "type": "date"
    },
    {
      "linkId": "6",
      "text": "When was your last menstrual period? (LMP)-6",
      "type": "date"
    },
    {
      "linkId": "7",
      "text": "When was your last menstrual period? (LMP)-7",
      "type": "date"
    }
  ]
}
```

**Component**
SDC library

**To Reproduce**

**Expected behavior**
Input of one date picker should not be updated to the another date picker view.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@aditya-07 
Is this same kind of issue of #1537 which you already provided fix.

**Comment by santosh-pingle** [comment]
Same issue is also present in datetime picker view.

**Comment by santosh-pingle** [comment]
cc @jingtang10 @Tarun-Bhardwaj

**Comment by aditya-07** [comment]
@santosh-pingle Yes, it looks like the issue might be because of the check here https://github.com/google/android-fhir/blob/3a5891424937aefe3ee08fa1d1bd991e6e9a8158/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt#L106

**Comment by aditya-07** [comment]
@santosh-pingle Also check Date time picker as the same issue might be present there as well.

**Comment by jingtang10** [comment]
for the purpose of the video can you please remove the text display questions? it makes it so much easier to see.

**Comment by santosh-pingle** [comment]
> @santosh-pingle Also check Date time picker as the same issue might be present there as well.

yes, its present, I already mentioned in the previous comment. thanks!
