### ISSUE TITLE
Boolean choice component can appear before single choice component in catalog app.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1585]
**Describe the bug**

In the catalog app, boolean choice is shown after the single choice component.
**Component**
 SDC gallery app

**Expected behavior**
It is expected to show boolean choice component before single choice component.

**Screenshots**

<img width="433" alt="Screen Shot 2022-09-08 at 11 36 21 AM" src="https://user-images.githubusercontent.com/86107848/189047117-321157c2-f211-43d6-8b95-055909b09c8d.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
Sounds good 👍
