### ISSUE TITLE
In Date view if typed input is invalid then appropriate error message should be displayed.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1589]
**Describe the bug**
While user is typing date input until typed date input is valid, it shows ` missing answer for required field` as error message.

**Component**
SDC library

**Expected behavior**
It is expected that while user is typing date input until it is valid date, then it should show invalid input.

**Screenshots**

<img width="433" alt="Screen Shot 2022-09-08 at 12 12 14 PM" src="https://user-images.githubusercontent.com/86107848/189052886-74fb81f2-eb85-4775-b67f-6f88356313a3.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
Some thoughts 
- I agree the error message should be updated 
- While the user is typing it should display the hint text / date format text below. 
- The flyover text should say Date. 
- The error shouldn't appear while they are typing. Not exactly sure how we can do this, but it is frustrating to see errors too early and before people have completed the field. 

What do you think @santosh-pingle @jingtang10?

**Comment by jingtang10** [comment]
> Error message: "Date format needs to be dd/mm/yy"

sounds good to me

**Comment by shelaghm** [comment]
Discussion w/ Jing: 
- Difficult to define when people are typing or are done typing
- Don't show error message if nothing has been typed. 

Decision: always validate as users type

**Comment by PallaviGanorkar** [comment]
@shelaghm If date field have "required": true attribute, in this case both error messages are displayed like,
"Missing answer for required field"
"Date format needs to be dd/mm/yy"

out of these which message should be displayed in UI on priority?

**Comment by shelaghm** [comment]
@PallaviGanorkar Prioritize the date format "Date format needs to be dd/mm/yy" No need to show missing answer.

If nothing has been entered, then can show "missing answer" instead? I'm not sure if this is possible to show different error messages based on if anything has been typed in the box or not?
