### ISSUE TITLE
In the catalog app Slider question text needs to be changed, as currently supported step value is 10.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1590]
**Describe the bug**
In the catalog app for slider view workflow, `How many times have you been pregnant?` is shown as question text, but current implementation only supports 10 as step value, as result value change in the multiple of 10 number when get changed which is not fair. 

**Component**
SDC gallery app

**Expected behavior**
It is expected to change question text until sdc start supporting step value which will be provided in the questionnaire.

**Screenshots**

<img width="436" alt="Screen Shot 2022-09-08 at 12 23 35 PM" src="https://user-images.githubusercontent.com/86107848/191913406-8664ca16-ad35-4f3b-a2b9-da998ea9e735.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
@santosh-pingle is this the right screenshot for this issue?

**Comment by shelaghm** [comment]
I don't think changing the question should be prioritized. Instead I think we should fix the slider component so it works as described in this issue https://github.com/google/android-fhir/issues/1260

**Comment by shelaghm** [comment]
Short term fix is to change the question. 

Q for @jingtang10 what priority is fixing the slider functionality?

**Comment by santosh-pingle** [comment]
Looking into it.
