### ISSUE TITLE
Submit menu is shown in the application bar for layout page in the catalog application.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1593]
**Describe the bug**
Catalog app can style sdc library submit button to mark it as visible or gone, and can use it to submit the form.
Catalog app also shows submit menu in the application bar for default and paginated layout. 

**Component**
SDC gallery app

**Expected behavior**
It is expected to remove submit menu from application bar. 

**Screenshots**
<img width="428" alt="Screen Shot 2022-09-08 at 12 54 14 PM" src="https://user-images.githubusercontent.com/86107848/189060816-75cf1efa-dbac-467c-b12f-c3300582bdf0.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
I agree.
