### ISSUE TITLE
Entered input gets cleared in the Integer type textfield after a certain range of value.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1594]
**Describe the bug**
In the catalog app, when textfield workflow get opened and user start providing input for ID textfield, after certain range of input value it shows blank text field and there after only shows new typed input value.

**Component**
SDC gallery app

**Expected behavior**
It is expected to show typed input.

**Screenshots**

https://user-images.githubusercontent.com/86107848/189062476-c66b2f49-9987-4c29-8469-0c603516e26e.mov

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
Discussed
- Use multi-line text to fix this issue. 
- Also need to specify a range, validate range.

**Comment by FikriMilano** [comment]
Blocked by https://github.com/google/android-fhir/issues/1718

**Comment by FikriMilano** [comment]
@jingtang10 did your PR handle this ticket as well? https://github.com/google/android-fhir/pull/1873

**Comment by santosh-pingle** [comment]
Issue was fixed.
