### ISSUE TITLE
Autocomplete chip is empty if display text not specified

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1604]
**Describe the bug**
I have an answerOption with a bunch of codes without display text, e.g.

```json
"answerOption":
[
  {
    "valueCoding":
    {
      "code": "LA11231-0",
      "system": "http://loinc.org"
    }
  },
  {
    "valueCoding":
    {
      "code": "LA24366-9",
      "system": "http://loinc.org"
    }
  },
...
```

When using autocomplete, it searches on all the `code` text which I believe is reasonable, but when I select one the chip itself is empty.

**Component**
SDC Library

**To Reproduce**
Load a questionnaire with answerOption items without `display` values.

**Expected behavior**
The `code` is used to fill the chip text if `display` is missing, since that's what was shown while doing the autocomplete.

**Screenshots**

https://user-images.githubusercontent.com/7772901/189761145-9ad52a3a-2701-43e5-888e-c0ab6dfce546.mp4

**Comment by santosh-pingle** [comment]
looking into it.
