### ISSUE TITLE
Use generic examples in SDC catalog app

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1605]
**Is your feature request related to a problem? Please describe.**
Many components use ANC specific examples based on WHO ANC questionnaires, which is not be relevant for all audiences and can be confusing for some implementers. 

**Describe the solution you'd like**
Update the copy to be very generic and label each button with what it is called in the FHIR SDK.

**Describe alternatives you've considered**
Alternative is to use a sample health questionnaire that is even more generic and applicable to most healthcare contexts.

I have a figma with suggested copy changes. Screenshot of one example below

<img width="203" alt="Screen Shot 2022-09-12 at 17 13 57" src="https://user-images.githubusercontent.com/86378921/189780229-d9304f3a-cda8-4925-bd6e-14651f1217cf.png">

**Comment by shelaghm** [comment]
Make slightly less generic: 
- Add a title for questions

**Comment by shelaghm** [comment]
Proposed changes for 
DatePicker, DateTime Picker, Multiple choice, boolean choice, dropdown and slider (If we bring it back to life)  @santosh-pingle I'll post figma link on chat so you can copy directly 

<img width="1387" alt="Screen Shot 2022-09-28 at 15 31 13" src="https://user-images.githubusercontent.com/86378921/192901150-2d0f57c6-7a6c-4be1-b35d-d9482a4fbb32.png">
<img width="1246" alt="Screen Shot 2022-09-28 at 15 30 26" src="https://user-images.githubusercontent.com/86378921/192901168-cd828e6b-078a-4764-9958-44fe80a3ea64.png">
<img width="897" alt="Screen Shot 2022-09-28 at 15 44 56" src="https://user-images.githubusercontent.com/86378921/192903537-ec8536d1-0c94-4646-88bb-8a2478febece.png">
<img width="897" alt="Screen Shot 2022-09-28 at 15 44 56" src="https://user-images.githubusercontent.com/86378
<img width="1157" alt="Screen Shot 2022-09-28 a
<img width="403" alt="Screen Shot 2022-09-28 at 15 59 59" src="https://user-images.githubusercontent.com/86378921/192903588-a3a59aaa-a13f-43b4-b0f3-bf7be279f861.png">
t 15 55 43" src="https://user-images.githubusercontent.com/86378921/192903581-74de7699-af75-43f3-9c52-b8f04bf88b61.png">
921/192903560-77ff49ad-cd66-402c-a4fc-a86d26f36e3d.png">

**Comment by santosh-pingle** [comment]
looking into it.

**Comment by santosh-pingle** [comment]
@shelaghm Are generic texts updated for single choice, modal, open, and autocomplete widgets in figma?

**Comment by santosh-pingle** [comment]
<img width="453" alt="Screen Shot 2022-12-28 at 4 36 02 PM" src="https://user-images.githubusercontent.com/86107848/209802791-5fa92964-ba81-4962-83ff-9231e47879ec.png">
<img width="430" alt="Screen Shot 2022-12-28 at 4 35 28 PM" src="https://user-images.githubusercontent.com/86107848/209802803-41edd2e7-789b-4873-861a-474d0a32a1d7.png">
<img width="450" alt="Screen Shot 2022-12-28 at 4 35 13 PM" src="https://user-images.githubusercontent.com/86107848/209802817-703fcad7-8240-4e24-97d3-86a393bdc32a.png">
<img width="409" alt="Screen Shot 2022-12-28 at 4 38 05 PM" src="https://user-images.githubusercontent.com/86107848/209804460-7309acaa-d61a-4bb0-af48-f4d028845848.png">
<img width="423" alt="Screen Shot 2022-12-28 at 4 37 52 PM" src="https://user-images.githubusercontent.com/86107848/209804482-a854608e-65ba-4812-9568-dd89d2622205.png">

<img width="423" alt="Screen Shot 2022-12-28 at 4 37 52 PM" src="https://user-images.githubusercontent.com/86107848/209804545-646cd18b-1f96-49d9-905e-fda6e92532fd.png">

**Comment by shelaghm** [comment]
@santosh-pingle Looks great! Thanks for updating

**Comment by shelaghm** [comment]
@santosh-pingle I think we can leave the other widgets as is for single choice, modal, open, and autocomplete.

**Comment by jingtang10** [comment]
I don't like the state question because in different countries you might have states/provices/perfectures/counties... can we make it as culture-neutral as possible? we can just use the text in the top screenshot.

**Comment by shelaghm** [comment]
@jingtang10 Yes, let's change it to something more neutral. Which text/screenshot are you referring to?

**Comment by jingtang10** [comment]
@shelaghm

Question title ==> maybe change this to `Select an option from below`
Select one

Option 1
Option 2
Optoin 3
...
