### ISSUE TITLE
Make sure all the data types for particular Search Parameter Types are indexed properly in the engine database.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#1607]
A related issue to this is that Encounter.CLASS search does not work. This is because fhirType "Coding" is missing from the tokenIndex function in ResourceIndexer.kt. We need to add these lines.

```
 "Coding" -> {
        val coding = value as ICoding
        listOf(TokenIndex(searchParam.name, searchParam.path, coding.system ?: "", coding.code))
      }
```

cc: @aditya-07

_Originally posted by @joiskash in https://github.com/google/android-fhir/issues/1306#issuecomment-1237711713_

See https://www.hl7.org/fhir/search.html#ptypes for the list of data types to be handled per search parameter type.

**Comment by PallaviGanorkar** [comment]
Few data types are not implemented for Search Parameter Type, Details are available here,

<google-sheets-html-origin><style type="text/css"></style>

Supported Data Types | Implemented
-- | --
Number
integer | Yes
dcimal | Yes
  |  
Date
date | Yes
dateTime | Yes
instant | Yes
Period | Yes
Timing | Yes
string | Yes
  |  
String
HumanName | Yes
Address | Yes
contact details / phone numbers |  
  |  
Token
Coding |  
CodeableConcept | Yes
Identifier | Yes
ContactPoint |  
code | Yes
boolean | Yes
uri |  
string |  
  |  
Reference
Reference | Yes
CanonicalType | Yes
UriType | Yes
  |  
Composite
Not Yet Implemented
  |  
Quantity
Money | Yes
Quantity | Yes
  |  
uri
uri | Yes
url |  
  |  
Special
_filter |  
Location | Yes
  |  

Supported Data Types	Implemented
Number	
integer	Yes
dcimal	Yes
	
Date	
[date](https://www.hl7.org/fhir/datatypes.html#date)	Yes
[dateTime](https://www.hl7.org/fhir/datatypes.html#dateTime)	Yes
[instant](https://www.hl7.org/fhir/datatypes.html#instant)	Yes
[Period](https://www.hl7.org/fhir/datatypes.html#Period)	Yes
[Timing](https://www.hl7.org/fhir/datatypes.html#Timing)	Yes
string	Yes
	
String	
[HumanName](https://www.hl7.org/fhir/datatypes.html#HumanName)	Yes
[Address](https://www.hl7.org/fhir/datatypes.html#Address)	Yes
contact details / phone numbers	
	
Token	
[Coding](https://www.hl7.org/fhir/datatypes.html#Coding)	
[CodeableConcept](https://www.hl7.org/fhir/datatypes.html#CodeableConcept)	Yes
[Identifier](https://www.hl7.org/fhir/datatypes.html#Identifier)	Yes
[ContactPoint](https://www.hl7.org/fhir/datatypes.html#ContactPoint)	
[code](https://www.hl7.org/fhir/datatypes.html#code)	Yes
[boolean](https://www.hl7.org/fhir/datatypes.html#boolean)	Yes
[uri](https://www.hl7.org/fhir/datatypes.html#uri)	
[string](https://www.hl7.org/fhir/datatypes.html#string)	
	
Reference	
Reference	Yes
CanonicalType	Yes
UriType	Yes
	
Composite	
Not Yet Implemented	
	
Quantity	
Money	Yes
Quantity	Yes
	
uri	
[uri](https://www.hl7.org/fhir/datatypes.html#uri)	Yes
[url](https://www.hl7.org/fhir/datatypes.html#url)	
	
Special	
[_filter](https://www.hl7.org/fhir/search_filter.html)	
[Location](https://www.hl7.org/fhir/location.html#search)	Yes
