### ISSUE TITLE
Add the openhie hiv ig case report questionnaire to the gallery app

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#161]
https://openhie.github.io/hiv-ig/Questionnaire-hiv-case-report-questionnaire.json.html

**Comment by litlfred** [comment]
Noting that this questionnaire does not yet have the SDC definition based extract information in it.   Will you need this for the gallery app?

**Comment by jingtang10** [comment]
@litlfred Not for now. We're yet to prototype extraction. So this should be sufficient.

**Comment by jingtang10** [comment]
@litlfred Carl -- when it's ready can you post it to this issue I just created: https://github.com/google/android-fhir/issues/176?

Thanks!

**Comment by fredhersch** [comment]
@jingtang10 Here is updated questionnaire with vietnamese translations (using google translate)

[Questionnaire-case-reporting-questionnaire-vn.zip](https://github.com/google/android-fhir/files/6265171/Questionnaire-case-reporting-questionnaire-vn.zip)

**Comment by aditya-07** [comment]
> @jingtang10 Here is updated questionnaire with vietnamese translations (using google translate)
> 
> [Questionnaire-case-reporting-questionnaire-vn.zip](https://github.com/google/android-fhir/files/6265171/Questionnaire-case-reporting-questionnaire-vn.zip)

Updated the json with ` "answerOption": [
                {
                  "valueString": "Positive",
                  "valueCoding": {
                    "code": "Positive"
                  }
                },
                {
                  "valueString": "Negative",
                  "valueCoding": {
                    "code": "Negative"
                  }
                }
              ]` to avoid crash.

Adding the updated json here [questionnaire-case-reporting-questionnaire-vn.json.zip](https://github.com/google/android-fhir/files/6496063/questionnaire-case-reporting-questionnaire-vn.json.zip)

**Comment by jingtang10** [comment]
@aditya-07 to merge the new questionnaire into the existing `openhie-hiv-case-report` with the new translations. I think the questionnaire @fredhersch provided also stops at section 12 and is missing the later sections.
