### ISSUE TITLE
Support for answerOptions as images/icons

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1614]
**Is your feature request related to a problem? Please describe.**
Be able to use images (e.g icons) for radio buttons

**Describe the solution you'd like**
As a developer I can use images to represent radio button options. These should work as radio button itemControls

See an example of using the "answerOption and rendering-xhtml" from the SDC spec [here](https://build.fhir.org/ig/HL7/sdc/examples.html#using-answeroption-and-rendering-xhtml)

Example shows two ways to use <img> tags to display images: (1) with embedded data and (2) using contained Binary resources

**Need to define the best approach for Android**

**Comment by fredhersch** [comment]
@shelaghm can you add an example UI for this control. Ty.

**Comment by shelaghm** [comment]
<img width="981" alt="Screen Shot 2022-09-20 at 16 45 02" src="https://user-images.githubusercontent.com/86378921/191383980-f80e4c58-b44f-46d3-a53f-e6696fd31291.png">

I have two options for this, do you have a preference for showing the "radio checkbox" or not?
I like both options :)

**Comment by fredhersch** [comment]
I think this might be better achieved using the [itemAnswerMedia Extension](http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-itemAnswerMedia.html)

This is similar to the [ItemMedia Extension](http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-itemMedia.html) implemented

Both are currently DRAFT

cc: @jingtang10

**Comment by fredhersch** [comment]
@FikriMilano Are you interested in picking this up as it is very similar to the itemMedia Extension, but for answerOptions. 

cc: @f-odhiambo

**Comment by PallaviGanorkar** [comment]
@shelaghm @jingtang10  
Out of above 2 options for UI, which is final for implementation, whether to show the "radio checkbox" or not?

**Comment by shelaghm** [comment]
@PallaviGanorkar I think we should show the radio checkbox, because it makes it clear what type of a selection it is.

**Comment by PallaviGanorkar** [comment]
> @PallaviGanorkar I think we should show the radio checkbox, because it makes it clear what type of a selection it is.

Yes, Thanks @shelaghm

**Comment by jingtang10** [comment]
can we focus on using the item answer media extension?

not sure how well the xhtml extension will work on andorid - maybe we should do a little bit more exploration there. but for now, let's get the item answer media extension working with the data field (in its examples they're using the url field).

**Comment by PallaviGanorkar** [comment]
@shelaghm I have 2 queries for display image for item answerOptions
1. change in shape of given image required?
2.  Change in color to match app there is required?
Please find the find the screen shot below for more details, here I am rendering binary data as BitmapDrawable.(FYI, its all dummy data  i am using here)
![itemAnswerMedia](https://user-images.githubusercontent.com/13957417/203775211-1e98bf6d-2f72-4b8d-9894-80e1fc77c776.png)

cc: @jingtang10

**Comment by shelaghm** [comment]
@PallaviGanorkar 

1. Can you say more about what you mean about change shape? The shape of it being a square or do you mean something else?
2. Changing color to app default is a nice to have. This would only be relevant when developers are uploading BitmapDrawable, so for icons and vector graphics that is a nice feature. But I also imagine developers would upload jpgs/pngs where that functionality isn't possible. What do you think?

**Comment by jingtang10** [comment]
discussed with @PallaviGanorkar. just really quickly: 1) i think we might need to scale the image whilst preserving the aspect ratio. 2) we should do some testing to see if it's possible for the questionnaire to provide an icon with transparent background so it works with different application theme and style.

**Comment by PallaviGanorkar** [comment]
@shelaghm I am using 48x48 image size here, Please let me know if you have other opinion about it

**Comment by shelaghm** [comment]
48x48 is a good size @PallaviGanorkar

**Comment by PallaviGanorkar** [comment]
@jingtang10 As discussed tested image/png icons with transparent background and it works fine. Please find attached screen shot for details,
![itemAnswerMedia_with_transparent_background](https://user-images.githubusercontent.com/13957417/207136805-55effd85-47a4-41fd-b5f6-6404d5ccf481.png)

**Comment by PallaviGanorkar** [comment]
Could not find direct way to decode base64 SVG image, there is suggestion to use libraries. 
@jingtang10 is it okay to use libraries?  then i will look into it for more suitable one for this

**Comment by jingtang10** [comment]
thanks you for this this is great @PallaviGanorkar
