### ISSUE TITLE
Add support for Attachment itemControl type

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1621]
**Is your feature request related to a problem? Please describe.**
As a user, I want to add an image to a patient record as part of an encounter (e.g. attaching image of a consent signature to a record)

**Describe the solution you'd like**
Provide support for the item-type-attachment within the SDC Library of the SDK.

- This would create an button that allows a user to select a file OR capture an image directly from a camera 
- On submit, the media attachment - which can be any binary data - is stored as an Attachment value type

See [https://hl7.org/fhir/codesystem-item-type.html#item-type-attachment](https://hl7.org/fhir/codesystem-item-type.html#item-type-attachment)

Additionally, there should be validation on the media types and file-size of the item being uploaded. Propose this is by default set to:

- File size: 1mb
- Media types: jpg, png, .mp3, .mp4, pdf

@shelaghm can you provide a Ux flow for this

cc: @joiskash @dubdabasoduba @f-odhiambo

**Comment by f-odhiambo** [comment]
@FikriMilano you can check out this ticket and give some feedback on the implementation plan and LOE 

CC @Tarun-Bhardwaj @fredhersch

**Comment by f-odhiambo** [comment]
@fredhersch what should happen if the file is > 1MB? Should we restrict the file type also to jpg, png, .mp3, .mp4, pdf?

**Comment by f-odhiambo** [comment]
@shelaghm can you share  a UX/UI for this flow?

**Comment by shelaghm** [comment]
@fredhersch @f-odhiambo @FikriMilano 

UX designs for this flow. Let me know your feedback
1. I suggest having two buttons, one for `take photo` and one for `select file` as we can open the corresponding native UI based on this initial selection. 
2. `Take photo` opens the Android native camera UI. If it is their first time using the camera in this app, they'll also need to grant the application permission to access the camera. 
3. `Select a file` opens the Android native camera roll. Alternatively it can open `file folders`, but I think most common scenario will be accessing the camera roll, so I suggest we default to that view. If it is their first time accessing the camera roll in this app, they'll also need to grant the application permission to access the camera roll. 
4. Do we know the average photo size in MB? Trying to reduce the size of a photo is very frustrating, so I suggest we increase the size limit to something that is going to cover most photos. 
5. See error messages at the bottom for file size and file format.

<img width="1132" alt="Screen Shot 2022-09-26 at 16 28 35" src="https://user-images.githubusercontent.com/86378921/192398310-cbd6a7dc-a795-4f5d-bb9e-bfe0f8fd8a81.png">
<img width="530" alt="Screen Shot 2022-09-26 at 16 28 26" src="https://user-images.githubusercontent.com/86378921/192398322-2c79dd09-0d39-4af5-b752-9a466d4c1f25.png">

**Comment by FikriMilano** [comment]
Thanks @shelaghm, cool design.

@fredhersch @f-odhiambo 
1. When a user finishes taking a photo and it's shown in the thumbnail, does that photo also get saved into the app as a file?
2. For `Select a file` opens the Android native camera roll. That does make sense if the expected attachment is an image. 
3. Perhaps, the case where `Select a file` opens `file folders` is when the expected attachment is a document or audio. Does this makes sense?
4. Let's say the user wants to get a photo from `file folders` then tap `Select a file`, how will the app knows it supposed to open the `file folders` instead of the Android native camera roll? I'm thinking additional buttons might help?
5. The 1 MB limitation will be a major problem for a photo, and compressing the photo before populating it might be bad for performance, so I would suggest increasing the limit.

**Comment by ndegwamartin** [comment]
I think it might be worthwhile exploring the impact of image compression on the UX. 

We can have a workflow such that the app accepts the various image formats but internally converts the image to a [WEBP format ](https://developer.android.com/reference/android/graphics/Bitmap.CompressFormat#WEBP)which can either be a lossy or lossless compression. This format significantly reduces the file size for storage/network whilst maintaining the quality of the image.

**Comment by shelaghm** [comment]
@FikriMilano Re: #4 Good point. I added a 3rd button in screenshot below. I suggest we have 3 different buttons developers can choose from, and that it will be up to them to select the appropriate buttons to display in their app depending on what users are uploading. I suspect that take photo and upload photo will be most common.

<img width="503" alt="Screen Shot 2022-09-28 at 15 23 09" src="https://user-images.githubusercontent.com/86378921/192899242-c1e9fe96-de20-4c29-9565-51b823e948d9.png">

**Comment by FikriMilano** [comment]
@shelaghm Thanks, that works.

**Comment by FikriMilano** [comment]
@fredhersch @shelaghm @f-odhiambo 

**Re: 3.** Yes, we need 3 buttons. It's another method suggested by @shelaghm which is to get a photo from the Android Native camera roll.

**Re: 4.** Perhaps showing the appropriate buttons depending on the expected Attachment is a better way to go instead of configuring it?

My suggestion is:
- If the expected Attachment is an image, then show the `Take Photo`, `Upload Photo`, `Select File` buttons.
- If the expected Attachment is a pdf, mp3, mp4, then **only** show the `Select File` button.

**Comment by FikriMilano** [comment]
@fredhersch @f-odhiambo @ndegwamartin 

I did some research on the image compression in Android.

I was able to compress a JPG image with a size of 2 MB, to WEBP image with the size of ~250 KB. 
The difference is not noticeable.
It takes ~7 seconds.

Should we proceed with the compression?

**Comment by joiskash** [comment]
> 

I think the application should be in control of compression.

**Comment by fredhersch** [comment]
> > 
> 
> I think the application should be in control of compression.

@joiskash interested in why you feel this way? Especially given the context, would

would it make sense to make this the default and then give application the option to override it?

> @fredhersch @f-odhiambo @ndegwamartin
> 
> I did some research on the image compression in Android.
> 
> I was able to compress a JPG image with a size of 2 MB, to WEBP image with the size of ~250 KB. The difference is not noticeable. It takes ~7 seconds.
> 
> Should we proceed with the compression?

Thanks @FikriMilano 

- Is this lossy or lossless compression?
- When you say the difference is not noticeable .. what do you mean? for saving the image? or something else?

@joiskash can you elaborate? Would it make sense to set compression by default but give application the ability to override?

cc: @jingtang10

**Comment by joiskash** [comment]
Yes If it is lossless compression then I do not have any problems. But in the case of lossy compression, it would be good to allow the application to have control. Eg: There are some 3rd party face recognition software that do not work very well with lossy compression.

**Comment by shelaghm** [comment]
> 3\. Number of buttons - Do we need to have 3 options? I would have thought that camera or file upload would take care of the common use cases. It assumes the person is able to find a photo using the file system. cc: @shelaghm

@fredhersch @FikriMilano 
I assume the most common use cases would be to upload a photo or pick from camera roll. What other files do we imagine people would upload? I wouldn't want to optimize for a rare use case of uploading a pdf or audio file at the detriment of making it more challenging to upload a photo.

My hesitation with only having two buttons and using `Upload file` to replace `Upload photo` is that the UI for selecting a file/photo using the native Android file UI is overwhelming and the term `file` is also very tech centered. If we need to only have two buttons I'd suggest changing the 2nd button label to `upload ` so it could work for either use case. I still prefer having 3 buttons that developers can opt to use in their deployment depending on the file format, with the recommendation that they select max two buttons to show in their app.

**Comment by Tarun-Bhardwaj** [comment]
@FikriMilano , could you please advise an ETA by when the PR can be ready for review?

**Comment by FikriMilano** [comment]
@Tarun-Bhardwaj PR will be ready in 2 weeks.

Sorry, I was on exam leave for the past 2 weeks.

**Comment by FikriMilano** [comment]
Separate tickets to track mimeType and maxSize:
- mimeType https://github.com/google/android-fhir/issues/1674
- maxSize https://github.com/google/android-fhir/issues/1675

**Comment by FikriMilano** [comment]
I will be on exam leave for some weeks, will continue the work after I come back.
@f-odhiambo @jingtang10

**Comment by fredhersch** [comment]
@jingtang10 did you end up picking this up? Or is it still pending? Thanks

**Comment by FikriMilano** [comment]
I'm resuming on this
cc @fredhersch

**Comment by FikriMilano** [comment]
@shelaghm just so you're aware https://github.com/google/android-fhir/pull/1680#discussion_r1029176840 
Thanks.

**Comment by shelaghm** [comment]
@FikriMilano sorry I missed this earlier, I've responded with an icon to use.

**Comment by FikriMilano** [comment]
Thanks @shelaghm 
There are actually some other comments from @jingtang10 that needs your input. 
It's regarding the use of other icons, strings and the uploaded image scales. 

To make it easier, I've added all necessary screenshots and compiled these for you.

Icons:
- Audio file https://github.com/google/android-fhir/pull/1680#discussion_r1029193201
- Camera https://github.com/google/android-fhir/pull/1680#discussion_r1029193286
- Image file https://github.com/google/android-fhir/pull/1680#discussion_r1029193426
- Video file https://github.com/google/android-fhir/pull/1680#discussion_r1029193497
- File https://github.com/google/android-fhir/pull/1680#discussion_r1029193570
- Delete https://github.com/google/android-fhir/pull/1680#discussion_r1029193638

String:
- "Take Photo" https://github.com/google/android-fhir/pull/1680#discussion_r1029194402

Uploaded image scale:
- https://github.com/google/android-fhir/pull/1680#discussion_r1029297464

**Comment by jingtang10** [comment]
@shelaghm what's still needed in the widget is the design for preview after a photo is taken and/or a file is selected. @FikriMilano has built this out in his PR (please see the screenshots he attached) without much guidance which is great.

but one issue: it's likely we will need to extend this widget to allow for repeated attachments. in that case, how do we handle displaying mutiple previews of files/photos attached? i would very much love a design that is more or less consistent betweeen single/multiple attachment cases. so for example, the current delete button probably won't work well in the multiple attachment case, but a `x` at the end of each attachment might work well. but if the user has attached images and documents, how do we display them together?

these are tough design questions, so i suggest we handle these in a separate ticket, but i just wanted to highlight this hear.

**Comment by shelaghm** [comment]
@jingtang10 @FikriMilano 

First off, all icons look great, thanks for linking to all the comments (so helpful) thank you!

See design mocks below for some options of what multiple attachments can look like. I like option A the most because we can show thumbnails of the image, but by constraining the thumbnail size they look cohesive and we can show several on the screen in a list. Option B is if we cannot do thumbnails or for file types where there's no image to preview. 
C is what it looks like with thumbnails at 140x200 pixel ratio and showing different aspect ratios. I think C looks messier and not ideal for showing multiple images on one page. 

What do you two think? 
<img width="1085" alt="Screenshot 2023-01-03 at 15 10 49" src="https://user-images.githubusercontent.com/86378921/210456857-1c870e83-b6d2-4291-b11d-de570ce3dec8.png">

**Comment by shelaghm** [comment]
One more mockup - this pattern can work well for combining different document types
<img width="465" alt="Screenshot 2023-01-03 at 15 21 27" src="https://user-images.githubusercontent.com/86378921/210457526-44ad7c16-347f-4bd9-8f2b-9f1c42d2b060.png">

**Comment by joiskash** [comment]
Super excited for this feature! Looks really good!

**Comment by FikriMilano** [comment]
@shelaghm Thanks, these looks awesome!

@jingtang10 I think the combo list works best for us, we can handle it in a separate ticket.

cc @f-odhiambo
