### ISSUE TITLE
Entry format extension has no effect on a date item

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1623]
**Describe the bug**
Setting the entry format on a date item has no effect.

**Component**
SDC library

**To Reproduce**
1. Open the catalog app
2. Select date picker
3. The format on the UI is shown as 'dd/MM/y'
4. But the item in the [questionnaire](https://github.com/google/android-fhir/blob/7c964fa9108eac37b8d40488fcf61d40055dd52e/catalog/src/main/assets/date_picker_questionnaire.json#L8) has an entry format of 'yyyy-mm-dd'

**Expected behavior**
I expect when I select a date using the date picker, it should appear in the format set in the entry format extension.

**Screenshots**
Below is what the date item looks like with the entry format set to 'yyyy-mm-dd':
![Screenshot_20220922-163113_Structured Data Capture Catalog](https://user-images.githubusercontent.com/90775548/191775358-44224cb4-85b9-448e-a97f-90e8b85f71bf.jpg)

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
N/A

**Comment by Gental-Giant** [comment]
@f-odhiambo Kindly take a look.

**Comment by shelaghm** [comment]
Is this because the device date format overrides the extension? what do you think @jingtang10?

**Comment by jingtang10** [comment]
@PallaviGanorkar can you please take a look at this?

**Comment by PallaviGanorkar** [comment]
Sure @jingtang10

**Comment by PallaviGanorkar** [comment]
@jingtang10  As per current implementation, Date entry format hint is displayed from locale date format, entry format defined in Questionnaire is not considered. Please confirm, what is expected behavior?

**Comment by jingtang10** [comment]
Thanks @KhumboLihonga for creating this issue. @PallaviGanorkar yes that's right - we do not consider the entry format extension right now.

The issue with the entry format extension, however, is that it's not really "computable". In the spec (https://build.fhir.org/ig/HL7/sdc/rendering.html#entryFormat) it says this: 

```
This provides a string that helps to guide entry of formatted text and often appears directly "behind" the control to be filled. For example, "nnn-nnn-nnnn" for a North American phone number, "YYYY-MM-DD" for a date, "nnnn nnnn nnnn nnnn" for certain types of credit card numbers, etc.
```

The keyword here is "guide". the entry format extension is guiding the user to input. But not necessarily used as validation. The FHIR questionnaire is a standard for all platforms. My question is how can we interpret this string in Android and be consistent with other langauges / APIs people might use to interpret entry format? Is this guaranteed to be universally consistent? Someone might use the same questionnaire in a .NET environment, or in Python, or in other langauges with other date libraries. Do we know that the entry format string is going to be generating the same validation result?

If we have confidence here, we can probably use entry format extension. But otherwise I'm not so sure.

**Comment by KhumboLihonga** [comment]
@jingtang10 Thanks for clarifying this. I assumed it was being used because it is included in the catalog app date picker [questionnaire](https://github.com/google/android-fhir/blob/6956c79f1d63581fe616ff1d41b41a08800e0468/catalog/src/main/assets/component_date_picker.json#L8). I think it would be good to remove the extension from there to avoid further confusion.

Well, the reason I shared this issue is that when using the catalog app, the date format is automatically set to dd/MM/y as shown in the screenshot above (and is the preferred format for us). However, when using questionnaires in our app on the same phone, the date format is automatically set to M/d/yy as shown below. So I figured the entry extension may be responsible for this but now I have no idea. Any thoughts?

![Screenshot_20221020-110127_Tingathe](https://user-images.githubusercontent.com/90775548/196906864-d4ab9a18-7156-4b29-9e27-3cb57a833da3.jpg)

**Comment by PallaviGanorkar** [comment]
@KhumboLihonga  Have you changed your device locale by any chance?

**Comment by KhumboLihonga** [comment]
@PallaviGanorkar No, I haven't. These two screenshots is me switching from the catalog app to our app. Also, the language of the phone is set to English (United Kingdom) so I expect the catalog app format i.e. `dd/MM/y` to be used.

**Comment by PallaviGanorkar** [comment]
@KhumboLihonga Which SDC lib version you are using?

**Comment by KhumboLihonga** [comment]
1. In our gradle, we are using `org.smartregister:data-capture:0.1.0-beta05-preview-SNAPSHOT` in the FHIR Core [app](https://github.com/opensrp/fhircore)
2. When trying to edit the date, the format is `m/d/yy` which is incorrect

@f-odhiambo @Gental-Giant could this issue be FHIR Core related?

**Comment by PallaviGanorkar** [comment]
As Discussed @KhumboLihonga , Both date Picker and Input box hint show same date format i.e. US locale format though device Setting has UK locale which is incorrect. On other hand catalog app shows correct UK local date format.
So, @KhumboLihonga  could you please conform, other app is not setting locale at app level?

**Comment by KhumboLihonga** [comment]
@PallaviGanorkar Thank you for your assistance. Yes, it's being set at the application level. I'll close this issue.
