### ISSUE TITLE
Make submit button a different colour to the toolbar

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#163]
In the questionnaire with submit button on toolbar. Can we show the submit button with different styling (just border outline for example).

**Comment by varunvjha** [comment]
Can I work on this issue?

**Comment by jingtang10** [comment]
Hi Varun - thanks for your interest. Can you clone the repo locally and try to run the datacapturegallery app first. Once you've done that and you're clear what to do I can grant write access.

**Comment by varunvjha** [comment]
Sure. I'd love to do that.

**Comment by jingtang10** [comment]
@fredhersch after reviewing https://material.io/components/app-bars-top/android#using-top-app-bars I could not find any example with an example of a button with a border in the top app bar. Do we definitely still want this?

Also, can you please share the original mock here for Varun's reference?

**Comment by fredhersch** [comment]
You are right @jingtang10 . The goal is to show the submit button in a different colour! That will be sufficient. I will update the issue.

**Comment by fredhersch** [comment]
@varunvjha let's make the submit button #eee on the dark toolbar background. Thanks

**Comment by jingtang10** [comment]
@fredhersch I cannot see an example in the spec for the top action bar that has a button with a different background color. I wonder if we should use https://material.io/components/buttons-floating-action-button#usage for the submit button?

**Comment by fredhersch** [comment]
@jingtang10 What happens if you try and set the background of the button to a different colour? Not sure the FAB is the right component .. will have to do some research!

**Comment by mberg** [comment]
I don't think we want to go with a FAB for form submission.  Once we get paginated forms we'll want to make it super clear where the form ends and where you are supposed to submit!  With OpenSRP we went with an approach where we put submit in the top header and also as a button on the page.  Let me get Roger (lead designer on OpenSRP) added to the repo so he can weigh in.

**Comment by jingtang10** [comment]
thanks @mberg - can you or Roger post some screenshots? I think we will probably end up having the option to have the button inside or outside.

**Comment by masterishaan19** [comment]
Is this issue still open ?? Can I work on this ??

**Comment by jingtang10** [comment]
this is open but i think we need to do some product and UX work here first.

**Comment by Manikant25** [comment]
@jingtang10  Can I work on it?

**Comment by Prakhar-Agarwal-byte** [comment]
@jingtang10 I want to work on this. Please assign it to me.

**Comment by Ana2k** [comment]
@jingtang10 if this issue is still open can you please assign this issue to me? I think I can fix this issue.

**Comment by sakets3010** [comment]
> this is open but i think we need to do some product and UX work here first.

@jingtang10 while you're at it, you might also wanna change the border colors (usually the secondary color in colors.xml) of outline styled text fields for dark mode. Attaching screenshots for reference (see how the edit text fields become visible when clicked upon but not other wise)

![1616401616010](https://user-images.githubusercontent.com/63781668/111962110-e9536f00-8b17-11eb-9ecc-5e462697c916.jpg)
![Screenshot_2021-03-22-14-02-15-842_com google android fhir datacapture gallery](https://user-images.githubusercontent.com/63781668/111962166-fcfed580-8b17-11eb-8d58-5ee679cda2e6.jpg)

**Willing to work on the above and the button implementation if you are done deciding the type of implementation you require.**

**Comment by epicadk** [comment]
@sakets3010 please use the markdown `<img>` tag or `<table>` tag so that it is easier to view the images.

**Comment by sakets3010** [comment]
> @sakets3010 please use the markdown `<img>` tag or `<table>` tag so that it is easier to view the images.

@epicadk thanks for pointing out,hope it looks better now.

**Comment by jingtang10** [comment]
> > this is open but i think we need to do some product and UX work here first.
> 
> @jingtang10 while you're at it, you might also wanna change the border colors (usually the secondary color in colors.xml) of outline styled text fields for dark mode. Attaching screenshots for reference (see how the edit text fields become visible when clicked upon but not other wise)
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/63781668/111962110-e9536f00-8b17-11eb-9ecc-5e462697c916.jpg"> <img alt="" width="200" src="https://user-images.githubusercontent.com/63781668/111962166-fcfed580-8b17-11eb-8d58-5ee679cda2e6.jpg">
> 
> **Willing to work on the above and the button implementation if you are done deciding the type of implementation you require.**

Thanks for reporting this @sakets3010. Can you please create a separate issue with screenshots? By the way I'm not seeing this behavior on my device.

**Comment by jingtang10** [comment]
We have not had clear direction on this one. @fredhersch @rowo. Plus, the current look and feel is consisten with material guidelines. I'm going to close this. Please feel free to reopen with a mock. Thanks!

**Comment by sakets3010** [comment]
> > > this is open but i think we need to do some product and UX work here first.
> > 
> > 
> > @jingtang10 while you're at it, you might also wanna change the border colors (usually the secondary color in colors.xml) of outline styled text fields for dark mode. Attaching screenshots for reference (see how the edit text fields become visible when clicked upon but not other wise)
> > <img alt="" width="200" src="https://user-images.githubusercontent.com/63781668/111962110-e9536f00-8b17-11eb-9ecc-5e462697c916.jpg"> <img alt="" width="200" src="https://user-images.githubusercontent.com/63781668/111962166-fcfed580-8b17-11eb-8d58-5ee679cda2e6.jpg">
> > **Willing to work on the above and the button implementation if you are done deciding the type of implementation you require.**
> 
> Thanks for reporting this @sakets3010. Can you please create a separate issue with screenshots? By the way I'm not seeing this behavior on my device.

@jingtang10 sure,i will mention the device name in a separate issue.
