### ISSUE TITLE
Change "Show/hide error state" setting to clearer UI, e.g. toggle

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1635]
**Is your feature request related to a problem? Please describe.**
It's not super clear whether show error state is turned on or off in the current UI. Given it has 2 states, using a toggle would be less ambiguous.

**Describe the solution you'd like**
Change UI from a button with changing text to an on/off toggle.

**Describe alternatives you've considered**
Any other unambiguous ui would work, e.g. dropdown.

**Would you like to work on the issue?**
Not sure on difficulty, but if someone can point me to the code I can take an initial look?

**Comment by shelaghm** [comment]
Could we use a checkbox? Sometimes toggles are also confusing if they are on or off. 
Screenshot below.
<img width="412" alt="Screen Shot 2022-09-29 at 14 47 06" src="https://user-images.githubusercontent.com/86378921/193148054-f93b383e-9b7c-4a46-b1f5-5a58cb3e8418.png">

**Comment by rajeshvelicheti** [comment]
fragment_model_bottom_sheet.xml

**Comment by kartikeysaran** [comment]
Hi, 
I'd love to contribute by working on this issue. If no one is currently working on it, would it be alright for me to take a shot at it? It seems like a good first issue to get started with.

**Comment by jingtang10** [comment]
suggest we lose the x button to be more aligned with https://m3.material.io/components/bottom-sheets/overview
