### ISSUE TITLE
Open choice UI hides "Add another answer" button, the text of which is misleading

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1636]
**Describe the bug**
With the current UI, the **Other** option just looks like one of the multi-choice options. There's no visible sign that the user needs to take additional action to actually provide an answer, nor that they have to scroll if the list of options already fills the screen. Also the text of "Add another answer" implies I've already provided at least one. If all I've selected is "Other" I've technically not provided any usable answer yet. In the recording below when I try to save after only selecting "Other" nothing happens.

**Component**
SDC Library

**To Reproduce**
1. Open Catalog app
2. Select **Open choice**
3. Tap dropdown, scroll down to the bottom to find **Other**
5. Select **Other**

**Expected behavior**
Some visible hint or instruction that the user needs to take additional action to actually provide an answer.

**Screenshots**

https://user-images.githubusercontent.com/7772901/192636844-22fb6efa-c4fd-4938-9ff2-76274109f20f.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4

**Comment by shelaghm** [comment]
Related to [#816](https://github.com/google/android-fhir/issues/816)

**Comment by santosh-pingle** [comment]
looking into it.

**Comment by santosh-pingle** [comment]
It requires to make `Add another answer` button visible on clicking other option.

**Comment by shelaghm** [comment]
When I interact with this the button is visible if you have to scroll down to see it, but it isn't discoverable to the user because there's no indication that the button is now there.
