### ISSUE TITLE
Support minValue maxValue in the sdc library

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#164]
See http://build.fhir.org/ig/HL7/sdc/behavior.html

> minValue	question (where type='date', 'dateTime', 'time', 'decimal', 'integer')
> This extension is used for questions with simple quantitative types. The extension allows establishing the lower bound for an answer. For example, ensuring that birth dates are >= 1990-01-01 or an integer is greater than or equal to 0. (Note that the integer and decimal types both allow negative numbers if not constrained.) This extension can be used together with the cqf-calculatedValue extension to establish a dynamic limit. For example, ensuring that a date of birth will result in a maximum age by setting minValue with an expression of 'today() - 18 years'.
> 
> The minValue SHALL be less than or equal to the maxValue, if both are specified. If min and/or max are calculated values, care should be taken to ensure that they cannot ever conflict. I.e. It should never be possible for calculated max to be less than calculated min. If this does occur, systems SHALL prohibit a value from being specified for the element for so long as the conflict exists. If the question is required, this may mean that it is not possible to mark the QuestionnaireResponse as "completed".
> 
> maxValuebquestion (where type='date', 'dateTime', 'time', 'decimal', 'integer')
> This extension is used for questions with simple quantitative types. The extension allows establishing the upper bound for an answer. For example, ensuring that birth dates are >= 1990-01-01 or an integer is greater than or equal to 0. (Note that the integer and decimal types both allow negative numbers if not constrained.) This extension can be used together with the cqf-calculatedValue extension to establish a dynamic limit. For example, ensuring that a date of birth will result in a minimum age by setting maxValue with an expression of 'today() - 18 years'.
> 
> The minValue SHALL be less than or equal to the maxValue, if both are specified. If min and/or max are calculated values, care should be taken to ensure that they cannot ever conflict. I.e. It should never be possible for calculated max to be less than calculated min. If this does occur, systems SHALL prohibit a value from being specified for the element for so long as the conflict exists. If the question is required, this may mean that it is not possible to mark the QuestionnaireResponse as "completed".

cqf-calculatedValue support is out of scope

**Comment by jingtang10** [comment]
@kunjan8794 are you interested in taking this?

**Comment by kunjan8794** [comment]
Surely, I'll take this up. Thanks 👍🏻

**Comment by jingtang10** [comment]
Awesome :) There are a few different data types to support (see comment above) but you can certainly start with one type (e.g. integer) and send a pr.
