### ISSUE TITLE
Demo app - create patient does not work

### ISSUE THREAD

**Issue by williamito** [google/android-fhir#1641]
**Describe the bug**
When creating a patient, a toast appears saying the patient was created but it never shows up in the list.

**Component**
Reference app

**To Reproduce**
1. Create a patient
2. Try to find the patient in the list

**Expected behavior**
The patient is in the list

**Screenshots**

https://user-images.githubusercontent.com/7772901/192872866-90fcea3f-5482-4c6e-8d4d-ff06179dbfcf.mp4

**Smartphone (please complete the following information):**
 - Device: Pixel 4

**Additional context**
Tested on master branch as of this commit: https://github.com/google/android-fhir/commit/ddb32caa5def83fd53beb93476a118f72df8a8dc

**Comment by PallaviGanorkar** [comment]
@williamito This is expected behavior of demo app, Patient created with City  "NAIROBI" are only appears in the demo app patient list on dashboard and also in search result.

**Comment by williamito** [comment]
Why is this the intended behavior for the "New Patient" button of the demo app? A user without context like myself would just assume the demo/sdk is broken. 

Can we hardcode the appropriate address block to new patients created in the demo so this works in a more expected way?

```json
"address": [
    {
      "city": "NAIROBI",
      "country": "Kenya "
    }
]
```

**Comment by williamito** [comment]
After more thought I do think the current design is confusing as it's easy for a new developer to not realize the default behavior, but I understand the correct instructions to make it work as expected is to put `Nairobi` in the City field and it will show up as expected in the patient list. In the interim I will add this detail to the wiki page for the Demo app.

**Comment by aditya-07** [comment]
@williamito @jingtang10 Would it make more sense to remove city filer from the Patients Page in the Demo app?

**Comment by Itskiprotich** [comment]
My suggestion here, will it make sense to have the City field hidden with a prefield NAIROBI value? Alternatively, we can use the managingOrganization as a filter. (With the assumption that we have a dummy organization in place
)

**Comment by santosh-pingle** [comment]
@shelaghm

**Comment by santosh-pingle** [comment]
Existing demo app also creates patient with city value other than NAIROBI.
While showing patients it uses city value NAIROBI as condition.

**Comment by jingtang10** [comment]
My suggestion here is that we want to separate the different screens more clearly in the demo app - at the moment it's doing too much and trying to be a reference implementation. but what we really want is demonstration of individual features and how to use different apis.

I suggest we separate patient list and sync functionality altogether in separate screens. @santosh-pingle is already working on this in #2414. For this reason I think this issue is obsolete and can be closed.
