### ISSUE TITLE
Date acceptance and formatting issue in Date Picker and DataTime Picker

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1647]
**Describe the bug**

**Component**
SDC library

**To Reproduce**
1. Go to layout tab in catalog app
2. Click on default layout/ or paginated layout
3. enter invalid date for birth date. eg. month value greater than 12 or year as 00, etc
4. click on "Sumbit" button
5. see response, birth is parsed wrong in response

**Expected behavior**
UI should not allow to enter invalid date as its health care related and parsed date is not correct then will cause problem in real life use cases

**Screenshots**
video is attached below for more details

**Smartphone (please complete the following information):**
 - Device: Nexus 5x API level 24 emulator (on all devices)
 - Android version:API level 24

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

[date_acceptance_n_format_issue.webm](https://user-images.githubusercontent.com/13957417/193280911-e2c278fa-b6db-4c20-bbe7-0d855b11e6db.webm)

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 , do we need to include this issue in the backlog or should this be closed?
