### ISSUE TITLE
SDC: Tests for ProgressBar in QuestionnaireFragment

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1650]
**Describe the Issue**
Write androidTest in sdc module to test progress bar feature in QuestionnaireFragment. 

**Requires**
Setup QuestionnaireFragment test suite in sdc module.

cc: @santosh-pingle

**Comment by jingtang10** [comment]
@nsabale7 any update on this one?

**Comment by nsabale7** [comment]
@jingtang10 

> @nsabale7 any update on this one?

No updates, but i will raise PR soon.
