### ISSUE TITLE
Modify the way dynamic answerOptions are loaded

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1657]
**Is your feature request related to a problem? Please describe.**
The answerOptions loading is done via callback in `QuestionnaireItemViewItem`. There are 2 callbacks for resolving answerValueSet and resolveAnswerExpression. This should be updated to handle the dynamic answer option loading in a better way.
See comment in PR #1480

**Comment by jingtang10** [comment]
i think this is already obsolete after we changed the way we evaluate answer options and moved everything to the view model: https://github.com/google/android-fhir/blob/99c5b9c505950d3a9fa39732ad32d1d85ab80a96/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt#L360
