### ISSUE TITLE
SDC | Unexpected behaviour on saving a questionnaire after loading it using a filled QR.

### ISSUE THREAD

**Issue by parthfloyd** [google/android-fhir#1664]
**Describe the bug**
The Questionnaire Response generated on save after rendering a Questionnaire with QR is erroneous.

**Component**
SDC library

**To Reproduce**
1. Render a questionnaire in SDC
2. Fill the form and save the Questionnaire Response
3. Render again using same questionnaire and saved QR.
4. Now save the questionnaire response again, this will be erroneous.
5. On loading again using same Questionnaire and last generated QR, the form filler will act weird.

**Expected behavior**
Form filler should behave the same on step 5 as on step 3.
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by parthfloyd** [comment]
cc: @jingtang10

**Comment by jingtang10** [comment]
can you please post the questionnaire and questionnaire responses please?

**Comment by parthfloyd** [comment]
Questionnaire: 
[mvp-questionnaire-enable-when.txt](https://github.com/google/android-fhir/files/9767270/mvp-questionnaire-enable-when.txt)


Questionnaire Response on first save: [questionnaire_response_first_save.txt](https://github.com/google/android-fhir/files/9767261/questionnaire_response_first_save.txt)

Questionnaire Response on second save: 
[questionnaire_response_second_save.txt](https://github.com/google/android-fhir/files/9767294/questionnaire_response_second_save.txt)
