### ISSUE TITLE
Ux testing build

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1668]
**Describe the Issue**

**Would you like to work on the issue?**

**Comment by santosh-pingle** [comment]
@shelaghm 
Prefix is missing from given questionnaire form, I am adding number prefix to every question item. e.g 1. 2. 3. and so on.

**Comment by santosh-pingle** [comment]
Prefix is missing from given questionnaire form.
I am adding number prefix to every question item. 
e.g 1.  2.  3.  ...

**Comment by santosh-pingle** [comment]
Sdc module is not able to render the instructions from shared questionnaire form.
It is required to edit the shared questionnaire form to update the instructions as per instructions code.

Attaching screenshots for reference
<img width="855" alt="Screen Shot 2022-10-17 at 1 45 39 PM" src="https://user-images.githubusercontent.com/86107848/196124913-8d419566-e1c1-4553-8a66-368ee6345b0e.png">

**Comment by santosh-pingle** [comment]
For Q.2 and Q.3 app get crashed, as these question has type quantity and uses min and max extension, where it throws exception ``` java.lang.IllegalArgumentException: Cannot compare different data types: Quantity and integer
        at com.google.android.fhir.MoreTypesKt.compareTo(MoreTypes.kt:49) ```

Integer type is updated for Q.2, Q.3

**Comment by santosh-pingle** [comment]
Q5(What city does the client live in?) to use the "Autocomplete" widget 
Working on it.

**Comment by santosh-pingle** [comment]
Q11 to be the "slider" widget.
Working on it.

**Comment by santosh-pingle** [comment]
@shelaghm 
Would you like to add instructions to instruct the user to input the value in the range of 1900 -2022 for question "What year were they born?"

<img width="1417" alt="Screen Shot 2022-10-17 at 5 19 56 PM" src="https://user-images.githubusercontent.com/86107848/196170577-af5d2846-6219-4b37-aa9d-dee4bd902df0.png">

**Comment by santosh-pingle** [comment]
@shelaghm 
Would you like to modify below instructions

- Type the name “Orange Flower”  => Type the name e.g “Orange Flower”
-  Type the phone number “98 87 76 65 => Type the phone number e.g “98 87 76 65"
-  Select 4 May 2020 => e.g 4 May 2020

**Comment by santosh-pingle** [comment]
Q. 9 "Does the client have any of the following symptoms?" is not rendered as open choice view.
=> modifying extension in questionnaire json.

**Comment by shelaghm** [comment]
> @shelaghm Would you like to modify below instructions
> 
> * Type the name “Orange Flower”  => Type the name e.g “Orange Flower”
> * Type the phone number “98 87 76 65 => Type the phone number e.g “98 87 76 65"
> * Select 4 May 2020 => e.g 4 May 2020

@santosh-pingle leave these instructions as is. For this specific usability test we want participants to enter these specific names and numbers, so they don't accidentally enter anyone's real names or phone number

**Comment by shelaghm** [comment]
@santosh-pingle can you also make it a paginated questionnaire? Thank you!

**Comment by Tarun-Bhardwaj** [comment]
@santosh-pingle , is this issue only for testing or does it include any development as well?

**Comment by santosh-pingle** [comment]
@Tarun-Bhardwaj 
Questionnaire json changes are only for ux testing build, these changes will not be part of sdc code repository.

**Comment by santosh-pingle** [comment]
> Enter a year between 1900 and 2022

@shelaghm 
I will make changes to support the paginated layout as well.

**Comment by santosh-pingle** [comment]
@shelaghm 
shared ux testing build which supports questionnaire in default and pagination layout.

**Comment by shelaghm** [comment]
amazing, thanks so much @santosh-pingle

**Comment by santosh-pingle** [comment]
Ux testing build is delivered, so closing the ticket.
