### ISSUE TITLE
Workflow | evaluateLibrary not working on android as in the test case.

### ISSUE THREAD

**Issue by parthfloyd** [google/android-fhir#1681]
**Describe the bug**
The evaluateLibrary functions keeps running forever and not returning the results in the android app, however it is working fine in the test case.

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**
Clone the repository [Android-fhir-fork for workflow-eval-library](https://github.com/parthfloyd/android-fhir/tree/workflow-eval-library) // Make sure it's the `workflow-eval-library` branch
1. Run the test case `evaluateImmunityCheck()` in `FhirOperatorLibraryEvaluateJavaTest.kt` 
2. It should be working fine and evaluating correctly.
3. Run the demo app
4. Wait for sync to finish and click on the (+) icon on bottom right (to open add patient questionnaire). 
5. The app crashes after a while after being stuck on the `evaluateLibrary` method in `getQuestionnaireJson()` function of `AddPatientViewModel.kt`.

**Expected behavior**
The method should behave similarly to the test case.

I am not sure if the change is required in the workflow library or some change is required by the implementors in the android app to run this method.

cc: @jingtang10

**Comment by parthfloyd** [comment]
Commit which contains the changes done to the demo app & workflow test to evaluate the library: https://github.com/google/android-fhir/commit/d5166216906b84fd4cfc89df17c43ca984a0838a

**Comment by jingtang10** [comment]
can you share info on the environment in which you're running the test case? android api level, device info (emulator vs real) etc.

**Comment by parthfloyd** [comment]
> can you share info on the environment in which you're running the test case? android api level, device info (emulator vs real) etc.

- tested in both pixel 5 emulator (API 31) & Samsung A53 device.

**Comment by parthfloyd** [comment]
Line where the app's getting stuck.
[AddPatientViewModel.kt (Line:2003)](https://github.com/parthfloyd/android-fhir/blob/d5166216906b84fd4cfc89df17c43ca984a0838a/demo/src/main/java/com/google/android/fhir/demo/AddPatientViewModel.kt#L2003)

@jingtang10 @omarismail94

**Comment by aditya-07** [comment]
@parthfloyd The issue is that the `FhirOperator` functions are getting called on the main thread causing ANR and crash.
We would make some changes to the `FhirOperator` to fix it.
 In the mean while, you can  use the attached `.patch` file to get it working.
[1681_issue.patch.zip](https://github.com/google/android-fhir/files/9910141/1681_issue.patch.zip)

**Comment by jingtang10** [comment]
@parthfloyd have you tried aditya's fix? is this working for you now?

**Comment by parthfloyd** [comment]
@jingtang10 Yes I had integrated Aditya's fix and it is working!

**Comment by jingtang10** [comment]
thanks for the update
