### ISSUE TITLE
Review button doesn't validate the last page of a paginated questionnaire

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1682]
**Describe the bug**
In a paginated questionnaire that uses the entryMode [extension](http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-entryMode) set to `prior-edit`, the active page needs to be valid before moving to the next page. When used in conjunction with the review [functionality](https://github.com/google/android-fhir/pull/1310), the next button turns into a review button on the final page of the paginated questionnaire. And when this review button is tapped, no validation takes place on this page. An example of this is shown in the video below.

**Component**
SDC Library

**To Reproduce**
N/A

**Expected behavior**
I expect the review button to validate the last page before allowing the user to proceed to the review page.

**Screenshots**
In the video below, the user is first tapping the next button on each page to show the validation erros before entering the required information. Once this is done, the next button is tapped to proceed to the next page. But on the final page (with the heading CHW Assignment), on tapping the review button, no validation is done.

https://user-images.githubusercontent.com/90775548/196958350-565fba78-db0c-4035-b7bd-6cd9803116f5.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
Here is the [questionnaire](https://github.com/google/android-fhir/files/10174766/sample-questionnaire-review-button-not-validating.txt) being used in the video:

**Comment by Gental-Giant** [comment]
@f-odhiambo Can you take a look and advice?

**Comment by jingtang10** [comment]
@KhumboLihonga which version of the sdc lib are you using?

**Comment by KhumboLihonga** [comment]
@jingtang10  `org.smartregister:data-capture:0.1.0-beta05-preview4-SNAPSHOT`

**Comment by jingtang10** [comment]
i see this is opensrp's fork. can you try depending on beta06 of the sdc lib?

**Comment by KhumboLihonga** [comment]
@LZRS Could you look into updating this

**Comment by KhumboLihonga** [comment]
@jingtang10 we tried using beta06 as per https://github.com/opensrp/fhircore/pull/1836 but it's still not working as shown in the video below.

https://user-images.githubusercontent.com/90775548/201872774-fa4a34fb-ba08-4799-88de-0edf4734d7c1.mp4

**Comment by aditya-07** [comment]
@KhumboLihonga @jingtang10 [PR-1671](https://github.com/google/android-fhir/pull/1671) would solve this issue. Its not merged yet.

**Comment by KhumboLihonga** [comment]
@jingtang10 thanks for verifying this. Is there an ETA on when this could get resolved?
