### ISSUE TITLE
enableWhenExpression logic based on empty item disply issue

### ISSUE THREAD

**Issue by delcroip** [google/android-fhir#1692]
[questionnaire-emcare.b23.classification.txt](https://github.com/google/android-fhir/files/9888116/questionnaire-emcare.b23.classification.txt)
**Describe the bug**
I have an Item with an enableWhenExpression based on an other item (hidden, value will come from initialExpression), the item is well hidden BUT its choice are not

**Component**
demo app

**To Reproduce**
1. change the test questionnaire with the attachment
2. run the app, app patient (trigger questionnaire)
3. you can see Yes/No without label

**Expected behavior**
choice option should not been shown without the question

**Screenshots**
![Screenshot from 2022-10-28 13-54-58](https://user-images.githubusercontent.com/4052505/198581370-54bf253b-0f12-4d57-92ab-074ea95c38ee.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 (emulated) + other devices
 - Android version: API 30

**Would you like to work on the issue?**
no, I don't have the skill for it

**Comment by jingtang10** [comment]
Hey @delcroip - thanks for raising this. I took a look at the questionnaire but am not sure what's going on. You have the following questions (link ids):

- "timestamp"
- "Severe Pneumonia or Very Severe Disease"
- "EmCare.B23.DE03"
- "Pneumonia"
- "EmCare.B23.DE06"

The first two are hidden. The third depends on the second. The fourth is shown and the fifth depends on the fourth.

Which question is the problem? What's the intended behavior?

Can you also construct a minimum questionnaire by removing questions/information that's not related to the issue being raised here? That'll help us debug.

On a separate note I wonder if you want to make link ids a bit more succinct - they seem to be a mixture of IDs and descriptions at the moment.

**Comment by delcroip** [comment]
This was the simpler version of the questionnaire... Normally nothing is displayed because the "'code" linkid shoud be displayed based on the "description" linkid that have initial Expression (as it was not working, it should be null)

But you can see the answers without the label

**Comment by jingtang10** [comment]
thanks patrick - i understand this questionnaire might have already been simplified. but it's still confusing to debug as there're 5 questions and i'm not certain which ones i'm looking at - can you please create a minimal questionnaire that has just enough information to highlight the problem being raised here.

can you clarify in link-id terms which questions are not behaving as expected? there're two choice type questions and two boolean type questions. so when you say choice type question i'm not sure which one is the issue at hand.

thanks!

**Comment by delcroip** [comment]
I think I found the issue ...  I am really sorry it 100% on my side ... I assume the yes/know where from the yes/no question BUT the app shows boolean as Yes/ No too

the question with text as id should be hidden and it was not the case

**Comment by jingtang10** [comment]
no problem - glad this is resolved patrick. please don't hold back from raising issues here in the future.
