### ISSUE TITLE
Difficulty using Github artifacts as local maven 

### ISSUE THREAD

**Issue by divyaramnath-13** [google/android-fhir#1701]
**Describe the Issue**
The github artifacts don't have the same format (missing build number) as described in https://github.com/google/android-fhir/wiki/Contributing#use-unreleased-github-build-for-developmenttesting-only.
This causes issues when using local maven artifacts

**Would you like to work on the issue?**
Please assign the issue accordingly

**Comment by omarismail94** [comment]
@divyaramnath-13 fix will be live when the PR linked gets merged

**Comment by divyaramnath-13** [comment]
Got it, thank you!
