### ISSUE TITLE
Read-only summary/review page

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1704]
**Is your feature request related to a problem? Please describe.**
The review page currently has an "EDIT" button that allows the user to go back to the questionnaire. But there is a need for just having a read-only review/summary page in certain use cases. 

**Describe the solution you'd like**
Create a new setting to allow for the review/summary mode to be readonly

**Describe alternatives you've considered**
We could also render the normal questionnaire and make all questions readonly. But that seems to be unnecessary. Why do we render the widgets if they can never be editted anyway?

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by jingtang10** [comment]
Hi @shelaghm do you have any input regarding this?

**Comment by shelaghm** [comment]
Some questions:
- How would someone access the read-only/summary page? Is something they land on after completing the questionnaire? OR something they can see after a questionnaire is completed and they access the completed questionnaire from the patient card?

Some suggestions:
1. I agree to visualize in a similar dense layout as the review page, not render the normal questionnaire. This is easier to parse, especially when you can't edit anything.
2. Keep the layout the same as the` review page`, but remove the edit button 
3. Adjust the labels on the navigation buttons. In this case maybe only have "close"?

Screenshot below of mockup. WDYT @jingtang10 ?

<img width="948" alt="Screen Shot 2022-11-10 at 14 19 46" src="https://user-images.githubusercontent.com/86378921/201218147-5ba2ae9e-95ad-43ed-b7ed-5c4be659bf2d.png">

**Comment by jingtang10** [comment]
thanks @shelaghm - the mocks look great.

i think the read-only thing may just be a totally different mode for questionnaire. because if it's read-only then there's no point taking the user through the actual questionnaire. so basically when the user opens the questionnaire the library will decide to do the following.

1. normal questionnaire (which will take the user through the pages, with an optional review page at the end), or
2. read-only questionnaire (which is just the review mode without edit button)

does this make sense?

@Prakhar-Agarwal-byte @joiskash @nsabale7 @f-odhiambo for visibility.

**Comment by shelaghm** [comment]
That makes sense to me @jingtang10 

@joiskash @nsabale7 @f-odhiambo It would be helpful to hear about your use case for using read-only so we can make this this component is meeting your needs. Do you have any context to add? Thanks!

**Comment by parthfloyd** [comment]
@shelaghm For Em Care we are going to use read-only mode questionnaires to show users previously filled questionnaires of closed consultations (Hence user may only require to see the questionnaire view similar to review mode without the option to edit it)

**Comment by joiskash** [comment]
@shelaghm we currently do not have a use case that requires this. But the conversation above seems reasonable to me.  I have nothing more to add

**Comment by shelaghm** [comment]
Thanks for the feedback @parthfloyd and @joiskash. Very helpful
