### ISSUE TITLE
No "other" category in gender section in "Add Patient"

### ISSUE THREAD

**Issue by LCB2021029-Badri** [google/android-fhir#1712]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Smarshal21** [comment]
noice issue

**Comment by Smarshal21** [comment]
@LCB2021029-Badri can i work on this ???

**Comment by santosh-pingle** [comment]
@LCB2021029-Badri 

Could you please provide more details to reproduce the issue?

-  steps to reproduce the issue
-  screenshot or video as reference

**Comment by santosh-pingle** [comment]
@aditya-07 @omarismail94 @jingtang10 
Could please update project of this issue to [Android FHIR SDK](https://github.com/orgs/google/projects/6)

**Comment by LCB2021029-Badri** [comment]
@fredhersch @pld @mberg @aditya-07 @omarismail94 @jingtang10  could you please assign this issues to me i would like to work on this issue

**Comment by LCB2021029-Badri** [comment]
https://user-images.githubusercontent.com/96579549/201611569-755d919d-98f8-4b79-ab98-67fe6f0c93d4.mp4

**Comment by santosh-pingle** [comment]
@LCB2021029-Badri 
Please feel free to work on this issue.

**Comment by jingtang10** [comment]
Thanks for raising this @LCB2021029-Badri - we should fix this as a priority!
