### ISSUE TITLE
QuestionnaireResponse Validator should not throw exception when questionnaire url is null

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1713]
**Describe the bug**
QuestionnaireResponse validator [asserts condition](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseValidator.kt#L61) where it is expected that questionnaire.url = questionnaireResonse.questionnaire. This condition is not covering all use cases and throws exception needlessly where this is not true. A questionnaire.url can be null (most of questionnaire have do not have any url), it could be something like http://my-fhir-server/fhir.com/Questionnaire/1234, Or it could be simply Questionnaire/12345, etc. The validation should not force this condition unless all cases are covered.

**Component**
SDC library

**To Reproduce**
1. Any questionnaire without url
2. Set QuestionnaireResonse.questionnaire = Questionnaire/q-id
3. Submit
4. IllegalArgument exception as questionnaire.url is null but QuestionnaireResonse.questionnaire has a valid value

**Expected behavior**
Should not throw exception if questionnaire.url is nul

**Comment by jingtang10** [comment]
one question @maimoonak, the spec here does use canonical type: https://hl7.org/fhir/R4/questionnaireresponse-definitions.html#QuestionnaireResponse.questionnaire but you said in the description "it could be simply Questionnaire/12345" which i think should be of reference type. do we know that we can reference questionnaires from the questionnaire response using reference type?

**Comment by jingtang10** [comment]
Actually can you take a look at this discussion thread: https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Referring.20to.20Questionnaire.20without.20a.20canonical.3F

**Comment by jingtang10** [comment]
this answer seems to be no according to lloyd's response in that thread.

**Comment by fredhersch** [comment]
@f-odhiambo @maimoonak Is there any more work to do on this issue? Or can it be closed based on the comments above?
