### ISSUE TITLE
Slider max value should be updated from the questionnaire.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1715]
**Describe the bug**
Slider max value is always shown 100.
It does not updates the max value limit as per value mentioned in the questionnaire.

**Component**
SDC library

**Expected behavior**
Max value of the slider should be read from the questionnaire.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: pixel xl emulator
 - Android version: api 30
 - Build number: na
 - Version na

**Additional context**
100 as max value is hard coded in the code.

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
@jingtang10 We'll need this fixed this week for UX testing

**Comment by santosh-pingle** [comment]
looking into it.
