### ISSUE TITLE
Reduce font size of question title in the review mode.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1716]
**Describe the bug**
Font size of question title is need to be changed as per ux design request.
It need to be updated to title medium.

**Component**
SDC library

**Expected behavior**
Title medium font should be applied to question title in the review mode.

**Screenshots**

<img width="399" alt="Screen Shot 2022-11-14 at 3 28 36 PM" src="https://user-images.githubusercontent.com/86107848/201631123-49afd6b1-79d1-4480-a9b9-c30d55104367.png">

**Smartphone (please complete the following information):**
 - Device: pixel xl emulator
 - Android version: api 30
 - Build number: na
 - Version na

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by shelaghm** [comment]
Thanks @santosh-pingle!

**Comment by santosh-pingle** [comment]
looking into it.

**Comment by santosh-pingle** [comment]
@shelaghm 
Review mode was also showing help button if it was present in questionnaire json, in my opinion it is not required so removed it.

**Comment by santosh-pingle** [comment]
looking into it 
In review mode if question item is not answered, then it is shown `No answer`. There is suggestion to show this text in red color and add error icon.
For more details see link https://github.com/google/android-fhir/pull/1737#issuecomment-1331343726
