### ISSUE TITLE
Questionnaire Progress does not work as exepcted after coming back to edit mode from review mode.

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1719]
**Describe the bug**
The progress bar of the questionnaire glitches after you navigate back to edit mode from review mode

**Component**
SDC library

**To Reproduce**
1. Open questionnaire
2. Go to review mode 
3. Go back to edit mode
4. Navigate the questionnaire and look at the progress bar

**Expected behavior**
Progress bar should work as expected.

**Screenshots**

https://user-images.githubusercontent.com/48797364/201861445-bea4bb5e-127f-4d75-a405-23559d28a3d1.mp4

**Smartphone (please complete the following information):**
 - One plus 7T pro

**Additional context**

**Would you like to work on the issue?**
@nsabale7

**Comment by nsabale7** [comment]
This issue seems to be resolved by PR #1738 and can be closed.
