### ISSUE TITLE
Add/Edit patient screen UI broken in demo app

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1725]
**Describe the bug**
Add/Edit patient screen UI broken in demo app, there gap between UI item is increased

**Component**
SDC library, rSDC gallery app

**To Reproduce**
1.. Launch'Demo'
2. Click on '+' to add new patient / select any patient from patient list to and click on edit
3. Scroll up and down
4. See error : 1. Space is more in label and the edit box for same label eg: First Name and its EditText box, Phone Number and its EditText box, etc 2. Scroll at the bottom of screen, there is no margin in parent bottom and last Edit text.

**Expected behavior**
there should be proper margin in Ui components on screen
**Screenshots**
[AddPatient_or_EditPatient_screenBroken.webm](https://user-images.githubusercontent.com/13957417/202093426-77ab1d2c-b178-4923-9f21-ff46d3913066.webm)

**Smartphone (please complete the following information):**
 - Device: Pixel5 emulator
 - Android version: API 32

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Issue is reproducible on catalog app as well.
@PallaviGanorkar  thanks for raising this issue.

**Comment by santosh-pingle** [comment]
looking into it.
