### ISSUE TITLE
Initial and initial expression not working on dropdown items with the type 'reference'

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1735]
**Describe the bug**
When using a dropdown item with the type 'reference', the initial value set always defaults to 'Not Answered'. In addition, when trying to select an option from the list, the selected option resets to 'Not Answered' as shown in the video below.

**Component**
SDC library

**To Reproduce**
N/A

**Expected behavior**
I expect the initial value set to be selected by default

**Screenshots**
When using a checkbox, the item works as expected as shown below:
https://user-images.githubusercontent.com/90775548/204476003-3d705ed1-f547-490f-bcb8-a2690f2bbaa5.mp4

However, when using a dropdown, the item does **not** work as expected as shown below:
https://user-images.githubusercontent.com/90775548/204475957-26bb4e50-4899-41a5-9328-5d7ba5bcc233.mp4

**Smartphone (please complete the following information):**
- Device: Samsung A12
- Android version: 11
- Build number: RP1A.200720.012.A127FXXU4AUK1
- Version: 30

**Additional context**
Here is the [questionnaire](https://github.com/google/android-fhir/files/10111167/sample-questionnaire.txt) used in the video above.

What led me to this issue is when I was trying to implement initial expression while using [answer expression](https://github.com/google/android-fhir/pull/1480).

**Would you like to work on the issue?**
Possibly the person who added support for the reference type can look into this

**Comment by omarismail94** [comment]
Thanks @KhumboLihonga ! Will take a look at this and triage to the right person. This was never working before right? Just want to make sure this is an uncaught issue vs a regression

**Comment by KhumboLihonga** [comment]
@omarismail94 This was my first time attempting to do this so I'm not sure. I would think its an uncaught issue since using the reference type was only recently included.

**Comment by omarismail94** [comment]
@KhumboLihonga  I have a PR #1740  ready for review to fix the issue

 Here is a video showing the fix:

https://user-images.githubusercontent.com/44980219/204923047-345896a9-58bc-4ac6-a949-b469afe8ad3a.mp4

**Comment by KhumboLihonga** [comment]
@omarismail94 I've had a chance to check out the PR and it looks great. Thanks for the quick fix.
