### ISSUE TITLE
Control submit button visibility using a fragment argument

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1748]
**Is your feature request related to a problem? Please describe.**
At the moment we control the visibility of the submit button using styling. But perhaps we should control it a bit more explicitly using a fragment arguement. I worry that we're using a style attribute to control a very important functional behavior of the sdc library.

**Describe the solution you'd like**
Create a new fragment argument

**Describe alternatives you've considered**
- current approach

**Additional context**
NA

**Would you like to work on the issue?**
maybe

**Comment by jingtang10** [comment]
@santosh-pingle fyi

**Comment by jingtang10** [comment]
@williamito fyi

**Comment by Hbkharsh** [comment]
can i get assigned?

**Comment by jingtang10** [comment]
#1872

**Comment by jingtang10** [comment]
@santosh-pingle you might still need to remove the style declarations in the style files.

**Comment by jingtang10** [comment]
> can i get assigned?

please take an issue labelled with good first issue. thanks!
