### ISSUE TITLE
Prototype definition based extraction

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#176]
http://build.fhir.org/ig/HL7/sdc/extraction.html#definition-based-extraction

**Comment by jingtang10** [comment]
Tagging @litlfred here. He will provide information on the definition-based extaction for the openhie HIV case reporting questionnaire.

**Comment by litlfred** [comment]
@jingtang10 I don't think we have those mappings yet for HIV (will check with Jose) but we do have some initial mappings for the Covid Case Report form (which uses the same data pipeline) if you are eager to look at something.  Those are here:
  https://docs.google.com/spreadsheets/d/162-dTdpdEQjtt8Q-GXUVEqdC0lLAdp9-zqvFHxUPDlI/edit#gid=0
and Elliot will pull them into the Covid questionnaire soon:
  https://openhie.github.io/covid-ig/
