### ISSUE TITLE
By default, disable items if all items they are depending on have also been disabled

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1765]
**Is your feature request related to a problem? Please describe.**
Let's say there are 3 items - item 1, item 2 and item 3. Item 3 is enabled based on the response of item 2, and item 2 is enabled based on the response of item 1. Let's say item 1 is answered to enable item 2, and item 2 is answered to enable item 3. If the user decides to change item 1 in such a way that hides item 2, item 3 is still visible to the user.

**Describe the solution you'd like**
Since item 2 has been hidden, and item 3 solely depends on item 2, I expect item 3 to also be hidden.

**Describe alternatives you've considered**
The alternative is to make item 3 dependent on both item 2 and item 1 but this quickly gets complicated in bigger questionnaires.

**Additional context**
Here is a [video](https://user-images.githubusercontent.com/90775548/207032126-fd664740-2150-4ec1-b5e1-ac06489f003f.mp4)  showing this issue and the [questionnaire](https://github.com/google/android-fhir/files/10207411/disabled-fields-sample.txt) that was used

**Would you like to work on the issue?**
Not sure who can look into this

**Comment by santosh-pingle** [comment]
yes, it should hide all dependent questionnaire items and clear the captured answers from questionnaire response.

**Comment by jingtang10** [comment]
Thanks for raising this @KhumboLihonga.

In some cases we might not want to clear answers to disabled questions, e.g.:
- disabled questions might still be used for other calculations?
- you might want to keep the input values in case the user re-enable the disabled questions

As a result, I'm not so sure this is the intended behaviour. I do feel this might have unintended consequences and I do want to keep as close to the standard as possible. We should double check with the SDC community first.

**Comment by KhumboLihonga** [comment]
@jingtang10 thanks for following up on this. Will be waiting to hear what the findings are.

**Comment by jingtang10** [comment]
please see the discussion here https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Enablewhen.20dependency
