### ISSUE TITLE
Add NSW Health Neonate Health Record Questionnaire to the gallery app

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#177]
https://www.hl7.org/fhir/questionnaire-example-bluebook.json.html

Notes:
- Includes some basic skip logic (enableWhen)
- Provides answerOptions in place of ValueSet for drop downs (for Sex and Vitamin K given questions)

**Comment by jingtang10** [comment]
The questionnaire has been added to the application in the PR linked above (#171).

But trying to render it will crash the app because of the lack of support for CHOICE type questions.

**Comment by jingtang10** [comment]
enable when is going to be handled in #165 
drop down with value set is handled in #153 

closing this issue.
