### ISSUE TITLE
Definition Based Extraction: Support code type for itemExtractionContext extension value.

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#1770]
**Describe the bug**
Currently during definition based extraction, the value for itemExtractionContext extension is cast as Expression. As per the [SDC FHIR IG](http://hl7.org/fhir/uv/sdc/STU3/StructureDefinition-sdc-questionnaire-itemExtractionContext.html) value can be of type valueCode.

**Component**
SDC library

**Comment by joiskash** [comment]
![image](https://user-images.githubusercontent.com/48797364/209115864-825838f3-f7b5-44a4-881c-fa917af5e976.png)
http://build.fhir.org/ig/HL7/sdc/extraction.html#definition-based-extraction

**Comment by PallaviGanorkar** [comment]
@nsabale7  could you please provide profile/StructureDefinition having value for extension as type valueCode for testing purpose

**Comment by nsabale7** [comment]
[anc-reg.txt](https://github.com/google/android-fhir/files/10336298/anc-reg.txt)

**Comment by PallaviGanorkar** [comment]
@joiskash Please provide sample questionnaire where we have to update existing resource

**Comment by PallaviGanorkar** [comment]
As Discussed with @jingtang10 , Updating existing resource implementation will be take take under #1791

**Comment by jingtang10** [comment]
> As Discussed with @jingtang10 ,  Support itemExtractionContext extension to update existing resource will be implemented under #1791 

#1799 you mean?
