### ISSUE TITLE
SDC | Bug, unable to select boolean choice on a specific case when loading using questionnaire response

### ISSUE THREAD

**Issue by parthfloyd** [google/android-fhir#1784]
**Describe the bug**
A boolean which is hidden due to enable when condition, when it is shown using appropriate condition. Then the user is unable to select the choice.

**Component**
SDC

**To Reproduce**
1. On Master branch apply the patch 
[reselecting_enable_when_boolean_loading_via_questionnaire_response.txt](https://github.com/google/android-fhir/files/10330578/reselecting_enable_when_boolean_loading_via_questionnaire_response.txt)
(Change extension to .patch on download)
2. Run the app, Go to new questionnaire (+ icon n patient list)
3. In questionnaire,  Select yes of "Unconscious or Lethargic"
4. This will enable next question, the user is unable to make a selection on it

**Expected behavior**
The user should be able to select the choice and save.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**
After applying patch: Questionnaire is at file: assets/new-patient-registration-paginated.json & QuestionnaireResponse is on line: 84

cc: @jingtang10

**Comment by omarismail94** [comment]
Thanks Parth! I can reproduce this issue as well on my physical device as well. Will debug

**Comment by omarismail94** [comment]
Quick finding: when I revert the changes you added in `AddPatientFragment`, I can click on the next question when I seelct yes for "Unconscious or Lethargic". What's interesting is if I press the submit button at the bottom, nothing happens, but if I press the Submit button in the header, the patient gets saved

**Comment by parthfloyd** [comment]
@omarismail94 indeed, also interestingly that `questionnaireResponseString`doesn't have item data for the "unconscious" question. 

QuestionnaireResponseString = 
`{
  "resourceType": "QuestionnaireResponse",
  "item": [
    {
      "linkId": "EmCare.B7.DE08b",
      "text": "Unconscious or Lethargic",
      "answer": [
        {
          "valueBoolean": false
        }
      ]
    }
  ]
}`

**Comment by omarismail94** [comment]
Hey @parthfloyd ! @jingtang10  and I looked at this today and found the issue.

When a questionnaireResponse is not given by the user, the SDK creates one based on the each `Questionnaire.QuestionnaireItemComponent`. If a user supplies, a questionnaireResponse, the SDK just parses that response. The SDK does not check if there each questionnaireItem  maps to a questionnaireResponseItem (Jing and I are thinking whether it should as the standard is lenient).

For now, you have to list each questionnaireItem in the questionnaire in the questionnaireResponse as well. You do not need an answer for each one, you just need to have the linkId. I set the `questionnaireResponseString` to the JSON below and the App lets me select answered from the enabled question

```
{
  "resourceType": "QuestionnaireResponse",
  "item": [
    {
      "linkId": "EmCare.B7.DE08b",
      "text": "Unconscious or Lethargic",
      "answer": [
        {
          "valueBoolean": false
        }
      ]
    },
    {
      "linkId": "EmCare.B7.DE08"
    }
  ]
}
```

**Comment by jingtang10** [comment]
@parthfloyd does this fix work for you?

@kunjan8794 fyi

**Comment by jingtang10** [comment]
@parthfloyd will you please test if PR #1881 fixes your issue?
