### ISSUE TITLE
Start using sdc submit button in the demo app.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1792]
**Describe the bug**
SDC module submit button is visible in demo app, but it does not perform submit operation.
To submit the form user has to click on submit menu which is currently present in the app menu bar.

**Component**
reference app

**To Reproduce**
1. Go to the demo app
2. Click on `+` icon to add patient
3. Now, it shows submit button at the bottom and in the app bar.

**Expected behavior**
Form should be submitted on click event of sdc submit button.
Remove app bar submit menu.

**Screenshots**

<img width="411" alt="Screenshot 2023-01-05 at 10 32 21 AM" src="https://user-images.githubusercontent.com/86107848/210705325-ebbafbd8-359f-46e3-b16b-8eb593521221.png">

**Smartphone (please complete the following information):**
 - Device:  Pixel4a emulator
 - Android version: Android api 30
 - Build number: na
 - Version na

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@aditya-07 
Can you please add the project name? (I don't have permission to add it.)

**Comment by omarismail94** [comment]
@santosh-pingle added the project name!
