### ISSUE TITLE
Launch date picker in the keyboard mode when click event happens on textfield.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1793]
**Describe the bug**
It's feature request to launch date picker in the keyboard/text mode when user clicks on textfield.

**Component**
SDC library

**Expected behavior**
Launch date picker in the keyboard/text mode when user clicks on textfield.

**Screenshots**
<img width="419" alt="Screenshot 2023-01-05 at 10 53 37 AM" src="https://user-images.githubusercontent.com/86107848/210707921-1239e589-2d1f-4bda-823d-cbb57f1a8d6b.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Hbkharsh** [comment]
can i get assigned?

**Comment by santosh-pingle** [comment]
As per UX testing, this behavior is no more required.
Now, user is allowed to provide input by typing a date.
