### ISSUE TITLE
Default to a numeric keyboard for numeric questions (SDC)

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1801]
Problem:
Alpha-numerical keyboard is sometimes used for numerical data entry, which is harder to use and the numbers are smaller compared to a numeric keyboard. 

Proposed Solution:
For any integer (numerical entry) default to a numeric keyboard. The numeric keyboard also needs to include special characters needed, such a `/` for dates and `+ ` for phone numbers. 

Research required:
Feasibility for including special characters. For example / seems to be part of Android 13 keyboard, but didn't appear on Android 12 keyboard.

Design mocks:
<img width="372" alt="Screenshot 2023-01-11 at 13 18 36" src="https://user-images.githubusercontent.com/86378921/211919898-e89b3486-a9b5-44d0-bc75-270ce15a7dd6.png">

**Comment by jingtang10** [comment]
verified on my device. this is already the case for numeric questions. for date questions, we will handle it in #1804

**Comment by fredhersch** [comment]
Has not been reported as an issue. Closing for now
