### ISSUE TITLE
Date picker: Automatically add slashes between month/day/year in keyboard entry (SDC)

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1802]
Problem:
People struggle to complete dates with the date picker keyboard entry as forward slash `/` was not available on keyboard.

Proposed solution:
1. Developer should define the date format for the questionnaire. 
2. Based on that date format, the slashes should be automatically added at the right intervals xx/xx/xxxx (likely most common in my opinion) 
3. Keyboard should also include a `/` as mentioned in issue #1801 

Alternative:
Use a different date entry method with dropdowns instead of text entry, see the next issue that I will post. (will update)

Design mocks:
<img width="513" alt="Screenshot 2023-01-11 at 13 48 03" src="https://user-images.githubusercontent.com/86378921/211924981-f2cf4ba2-de0b-45e8-9c76-5f82012c0361.png">

**Comment by PallaviGanorkar** [comment]
@shelaghm need clarification on below queries

- 1. What if user enters 1 for first month (January) instead 01 (example 112023 instead of 01012023). How to decide to append slash. do we have to append every time after 2digits?
- 2. Questionnaire date format includes -, ., /, etc special character yyyy-mm-dd, y. m. d. etc
- 3. In DateTime picker, how to handle if both format is specified or only date or only time is specified. as in current requirement time is not allowed to enter as text.
- 4. If format parsing is failed, do SDK need to support fall back to default locale format?

**Comment by shelaghm** [comment]
1. First step is to allow the developer to define the date format for the questionnaire.
2. If the developer does not define a date format, what format should we default to? SM proposal: default to one of the most common date formats such as dd/mm/yyyy (or yyyy/mm/dd)
3. Why not default to device format? Devices are not consistently set up across a deployment and might have a lot of variation in the format (this is not good for consistent data collection). For users, being presented with a confusing date format such as m/dd/y that doesn't match their mental model is worse than the developer opting for a default date format that is more recognizable. Open to other suggestions.
4. Slashes should be entered based on entry format that is shown. Show entry format in hint. If format is dd/mm/yyyy, show slash after 2 digits, then another 2 digits and expect that year should be 4 digits. If there are missing digits like `112023`, then show an error message to input date in desired date format. 
5. Day and Month should always be 2 digits to simplify when slashes should be added. From our initial research, using two digits for date and month is a common pattern.
6. What about year, how many digits should year be? We should not have date entry with only 2 digits for year. If the date format is dd/mm/yy, then we should modify it to be dd/mm/yyyy (not sure this is possible, so feel free to suggest another idea). For example: 01/01/23 will display an error due to year not being 4 digits.
7. Year entry should always be 4 digits (to improve data quality), if 23 is entered, does it mean 1923 or does it mean 2023? This is why we should opt for a 4 year digit. People are living longer and we should plan for digital records to also have a long life. 
8. If format is yyyy/mm/dd then we should add slashes after first 4 digits, then / after 2 digits and / after next 2 digits. 
9. In the Android date picker when the device format is mm/dd/y, the single `y` also accepts yy and yyyy when entered. The single `y` is confusing and doesn't match the mental model of users. Instead always show year as 4 digits. Open Q: Do others agree, or we do need to also support 2 digits for year? 
10.  Do we have to support all special characters, such as `-` or `.` depending on the date format? SM proposal: Suggest using `/` as default. Open question: what characters are included on the numeric keyboard? Do we want to support date formats with other special characters like `-` or `.`?
11. In Korean, the format is y. m. d., how do we support this? SM: for now, I don't think we can support. (Open question, please chime in if you have opinions)
12. If a person add their own slash and it is in the wrong place, should show an error (example: 1/22/2023, this is an error because it must be 01/22/2023)
13. If format parsing is failed, does the SDK need to support fall back to default locale format? SM proposal: Instead of device format, default to a more common mental model: dd/mm/yyyy (this would be the primary date format that is used in most countries that FHIR SDK is currently used in) Don't default to device format, the device format is confusing and many devices in these contexts are not setup. 
14. DateTime Picker: What time format should we default to? Could be device format or developer specified format. SM proposal: I suggest using 24h clock as it does not rely on specifying `am/pm` which is less precise. Is this consistent with FHIR and HL7? Was referencing [this resource](http://www.hl7.eu/refactored/dtDTM.html) 
15. One issue we might encounter, what if a person does not have the default google numerical keyboard? SM: Not sure what to do about this, except we should default to a numeric keyboard for date entry?

That was a lot, will be good to review and discuss with @jingtang10 to ensure alignment.

**Comment by PallaviGanorkar** [comment]
As discussed with @omarismail94 and @santosh-pingle , 

1. For initial step, we will proceed with Automatically adding slashes between month/day/year and hold on to add support for entryFormat extension to date.
2. in First PR we will handle slashes and then go for other special characters(like, -, .) and different formats like Korean(yy. M. d.)

**Comment by PallaviGanorkar** [comment]
AS defined in wiki page there are 4 separator used in date format  that is 
Separators of the components:

/ – oblique stroke (slash)
. – full stop, dot or point (period)
- – hyphen (dash)
– space

see: https://en.wikipedia.org/wiki/Date_format_by_country#:~:text=The%20international%20format%20yyyy%2Dmm,m%20yyyy%20are%20also%20acceptable.)

**Comment by jingtang10** [comment]
Thanks all for a great discussion. A heads up to @joiskash @f-odhiambo @rowo @parthfloyd about this change which will go in the next release.

And I'd also like to point out that FHIR https://build.fhir.org/datatypes.html#date does stipulate 2 digits for day and month, and 4 digits for year in its date format. I know this does not necessarily mean we need to use the same date format in the UI in all locales, but I do think it provides some justification for the assumption we're making here in order for the solution to work which is that day/month are 2 digits and year is 4 digits.

**Comment by shelaghm** [comment]
What is the fallback pattern if the EntryFormat entered by implementer is not valid?
- Today we look at device format and standardize it to have it use 2 digits for date/month and 4 digits for year.

@PallaviGanorkar to continue adding other questions here to resolve offline

**Comment by PallaviGanorkar** [comment]
@jingtang10 @shelaghm I have few queries to support date and time entry format in questionnaire as below,
1. What is the fallback/default pattern if the EntryFormat given in questionnaire by implementer is not valid?

-    approaches to handle it ,
    1. device local pattern will be the default/fallback pattern - I preferred this approach and implemented this way, as there is way to define format in questionnaire if device local format is not working 
    2. decide 1 standard pattern and make it default/fallback pattern
    3. throw exception as invalid pattern

2.  In date and time picker view, as per current implementation, we don't allow user to enter time, it simply opens material time picker dialog as per device locale. 
-    If date and time pattern is given in questionnaire, do we have to allow user to enter time as text?
- 

4.

**Comment by shelaghm** [comment]
1. **Fallback pattern:** During meeting with Jing we aligned on to use first option that you have implemented. `device local pattern will be the default/fallback pattern `

2. **If date and time pattern is given in questionnaire, do we have to allow user to enter time as text?** Yes, we should allow users to enter time as text and not just the `dial`. can we follow the material TimeDate pattern? Look at this material [guidelines](https://m3.material.io/components/time-pickers/guidelines) for more info. 

3 and 4. **Date and time entryFormat.** Yes, that's right. If time pattern is missing default to device system format. 12h vs 24h. Same for date format as described in (1) above.

**Comment by santosh-pingle** [comment]
@shelaghm @jingtang10 @PallaviGanorkar 
Maybe you can add your input on this?
I noticed a behavior where, when a user inputs a invalid date, the acceptance of the input stops when the character count reaches the length of "MM/dd/yyyy."
Is it acceptable to not restrict users from entering date input in the text field?

**Comment by santosh-pingle** [comment]
@shelaghm @jingtang10 @PallaviGanorkar 
I think a hint/label/instructions or somekind of help should be provided to the user in the widget itself that the separator character, such as `\`, will be added automatically while the user is entering a date input. This will ensure that the user does not add the separator character manually.

**Comment by shelaghm** [comment]
Discussion w/ Jing and Santosh: 

@PallaviGanorkar Please take a look
- Conclusion: Should not restrict the user to a maximum number of digits (remove character limit and show error message)

Slashes: Option 1: user needs to delete the too many slashes. Option 2: automatically delete a slash when it is user added.
- Conclusion: Option 1: user would need to delete the slash if they add their own slash. Can do option 2 in the next release

Instructions: 
- Conclusion: keep instructions as is, don't add any instructions about slashes automatically appearing.
