### ISSUE TITLE
Include symbols [ /  +] on the numeric keyboard (SDC)

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1804]
Problem:
In Android 12, there is no `/` that appears on the numeric keyboard. It appears on Android 13. It's unclear what appears on other Android versions. We need to further investigate the extent of the problem.

Related to #1801 

Solution:
- The numeric keyboard has `/` and `+` as symbols
- Research is needed to understand if this is feasible

Design mocks:
<img width="341" alt="Screenshot 2023-01-11 at 14 05 35" src="https://user-images.githubusercontent.com/86378921/211927930-e2f343cf-9840-4d4b-80d1-4549f5c2452f.png">

**Comment by fredhersch** [comment]
Not reported as an issue. Closing for now
