### ISSUE TITLE
[Feedback requested] Propose removing asterisk (*) symbol for required questions - what do you think?

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1806]
Problem:
In our usability testing research we found that many people were unfamiliar with, didn't notice or mis-interpreted the asterisk `*` symbol (thought it meant an error as the asterisk was red.) The symbol created more confusion than it provided clarity. 

Proposed solution:
Remove the asterisk * and show a written label that says `Required` in the instructions field.

Feedback wanted:
What has been your experience with people understanding what the asterisk `*` means? (tell us about the user's experience and if you have tested this with users where they were located)
What are your reactions to removing the asterisk *?

Current and proposed:
<img width="633" alt="Screenshot 2023-01-11 at 14 43 43" src="https://user-images.githubusercontent.com/86378921/211933846-e47a4461-5f36-4f28-836a-968a9d1df3e9.png">

**Comment by jingtang10** [comment]
Please see #544 for more background.

@joiskash @parthfloyd fyi
