### ISSUE TITLE
[Feedback requested] Update slider example in SDC Catalog app - What do you think?

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1807]
Problem:
The current slider is intended for numerical entry and this is not a good example of when to use the slider. For numerical entry it is more usable to use a text field.

Proposed solution:
- Update the example in SDC catalog app of when to use the slider with 
- Example 1: "How are you feeling today?" Great, fine, neutral, okay, bad. (slider with only 1-5 ticks)
- Example 2: In a scale from 1-5, how happy are you with X? (1 - very unhappy, 2-unhappy, 3-neutral, 4-happy, 5-very happy)
- Update corresponding documentation in the design guidelines

Feedback requested
Do you have an example of when you'd use a slider in your deployment? Please share it with us, would love to better understand when and why you'd want to use a slider.

Research required:
- Can we customize the slider so that text appears instead of number values?

Design mocks:
(work in progress)

**Comment by fredhersch** [comment]
No further research planned. Closing issue

**Comment by jingtang10** [comment]
i think we do any here it'll be guided by extensions in the sdc ig.
