### ISSUE TITLE
Review page: Iterate on visual design to make it more distinct from questionnaire

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1810]
Problem:
People land on the review page and are not sure what the purpose of the page is "Do I have to fill out the form again?"

Solution:
Iterate on the visual design to improve comprehension that this is a distinct step

Alternative:
- Add a header #1808 
- Add navigation and edit buttons so it looks more different #1809 

Design mocks (coming soon)

**Comment by fredhersch** [comment]
Closing this
