### ISSUE TITLE
Some Radio Buttons seems to deselect automatically after selection.  

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#1812]
**Describe the bug**
- Some radio buttons deselect automatically when selected. 
- Attached are the questions with such behaviors. 
[new_pregnancy_registration.json.zip](https://github.com/google/android-fhir/files/10427105/new_pregnancy_registration.json.zip)
- This happens with the latest SDK code on main

**Component**
SDC library

**To Reproduce**
Load the attached form to the SDK then test using the steps shown on the attached video
https://user-images.githubusercontent.com/4817531/212714001-5b944d84-d6ed-4a6a-9927-f892ac73a9f8.mov

**Expected behavior**
- [ ] The selections on a radio button should only change if the radio button is clicked on and not automatically. 

**Smartphone (please complete the following information):**
 - Device: Xiaomi 10T pro
 - Android version: Android 11

**Comment by santosh-pingle** [comment]
I also see below issue 

-  When single choice question get enabled and user try to provide input by clicking one of the answer option, it does not accept the input.
- nested question with type string of enabled question does not accept the input, keyboard get closed when user start typing the input

https://user-images.githubusercontent.com/86107848/212870289-ff4cbc38-68f6-4f21-9596-deeab8d61fe3.mov

https://user-images.githubusercontent.com/86107848/212871341-a7dd9b94-bbe9-4fb4-9fe7-8b0b1cc3b044.mov

**Comment by omarismail94** [comment]
@dubdabasoduba  are you by any chance using a QuestionnaireResponse as well? Just want to see if this Issue is similar to Issue #1784

**Comment by omarismail94** [comment]
I ran `git bisect`, and found this issue first started appearing with the introduction of repeated groups:

```
c888d5c75e7c996406d4af0f1d10893692388fc6 is the first bad commit
commit c888d5c75e7c996406d4af0f1d10893692388fc6
Author: Kevin Most <kevinmost@users.noreply.github.com>
Date:   Thu Nov 10 09:19:56 2022 -0500

    Repeated groups (#1559)
    
    Support repeated groups

 .../main/assets/repeated_group_questionnaire.json  |  92 +++++
 .../android/fhir/catalog/ComponentListViewModel.kt |   5 +
 catalog/src/main/res/menu/component_menu.xml       |   8 +-
 catalog/src/main/res/values/strings.xml            |   3 +-
 .../datacapture/MoreQuestionnaireItemComponents.kt |   2 +-
 .../fhir/datacapture/QuestionnaireViewModel.kt     | 131 +++++--
 .../QuestionnaireItemGroupViewHolderFactory.kt     |  15 +
 .../questionnaire_item_group_header_view.xml       |  36 +-
 datacapture/src/main/res/values/strings.xml        |   1 +
 .../fhir/datacapture/QuestionnaireViewModelTest.kt | 406 ++++++++++++---------
 .../QuestionnaireItemGroupViewHolderFactoryTest.kt |  30 ++
 11 files changed, 498 insertions(+), 231 deletions(-)
 create mode 100644 catalog/src/main/assets/repeated_group_questionnaire.json
````

looking further into the change that caused this

**Comment by omarismail94** [comment]
I found a simple solution, which is changing the statement:
```
    } else if (this@createQuestionnaireResponseItem.type ==
        Questionnaire.QuestionnaireItemType.GROUP
    ) {
```

to just an `else`:
```
    } else  {
      this@createQuestionnaireResponseItem.item.forEach {
        this.addItem(it.createQuestionnaireResponseItem())
      }
```

however, I am not sure if this diverts us from the FHIR standard (I am still a novice when it comes to the standard). If a Questionnaire Item type is "choice" or "text", can it have child items? The link below states that the type "group" should have at least one child item, but is unclear whether other types can:
https://www.hl7.org/fhir/valueset-item-type.html

**Comment by omarismail94** [comment]
Answer to my own question: 

Anything but display items can have child items. https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.item

**Comment by omarismail94** [comment]
@dubdabasoduba is there a reason for the questionnaire attached to have nested items? While we find a fix to support nested items, is it possible to flatten out the items?

**Comment by dubdabasoduba** [comment]
@omarismail94 yes, the nested items make it easier to write the enableWhen expressions. Instead of replicating the same enableWhen expression you just write it for the parent.

**Comment by dubdabasoduba** [comment]
The flattened forms work well FYI. I tested them on our imlementation

**Comment by omarismail94** [comment]
Thanks, good to know the flattened forms work! I know it isn't as nice as nested, but at least it unblocks you while we work on this issue. I had an initial solution working, but it created new problems when validating the questionnaire :(

**Comment by omarismail94** [comment]
Final finding for today, it seems like this is a known issue in our codebase. Looking at the test files, I see a  [unit test](https://github.com/google/android-fhir/blob/master/datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt#L1915-L1935) that has the same setup as this issue, but is ignored. Seems like Kashyap wrote this test, so will chat with him if he shows up to the developer call tomorrow

**Comment by santosh-pingle** [comment]
@joiskash

**Comment by jingtang10** [comment]
Updated the questionnaire to remove noise:

[new_pregnancy_registration_min.json.txt](https://github.com/google/android-fhir/files/10787812/new_pregnancy_registration_min.json.txt)

@dubdabasoduba please try to include minimum examples while creating issuse in the future (removing unnecessary information in your example and just the bare minimum required to reproduce the problem) - that makes it much easier to debug and to get to the bottom of the issue more quickly.

**Comment by dubdabasoduba** [comment]
> Updated the questionnaire to remove noise:
> 
> [new_pregnancy_registration_min.json.txt](https://github.com/google/android-fhir/files/10787812/new_pregnancy_registration_min.json.txt)
> 
> @dubdabasoduba please try to include minimum examples while creating issuse in the future (removing unnecessary information in your example and just the bare minimum required to reproduce the problem) - that makes it much easier to debug and to get to the bottom of the issue more quickly.

Makes sense.

**Comment by jingtang10** [comment]
@dubdabasoduba will you please test if PR #1881 fixes your issue?

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba will you please test if PR #1881 fixes your issue? 

I will test and raise a ticket for bugs if any

**Comment by dubdabasoduba** [comment]
This works well.
