### ISSUE TITLE
Checkbox with more that 10 options does not immediately show the option pop when clicked. 

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#1813]
**Describe the bug**
- A checkbox with 10+ options should pop a dialog to allow selection of the options when clicked. This does not work currently. 
- When it happens (very intermittently) the option selected is not added to the item answer options on the questionnaire. 
- Here is the form 
[pregnancy_visit.json.zip](https://github.com/google/android-fhir/files/10427690/pregnancy_visit.json.zip)

**Component**
SDC library

**To Reproduce**
- Load the attached form to the SDK and follow the steps shown on the video below
https://user-images.githubusercontent.com/4817531/212721678-5746d9ae-9802-49eb-93e3-80d02e964ce5.mov

**Expected behavior**
- [ ] When a checkbox with more than 10options is clicked, the options popup should be shown immdiately.  
- [ ] When a checkbox option is select the selected item should be added to the answerOptions immediately

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Xiaomi 10T pro
 - Android version: Android 11

**Additional context**
- This happens on the latest code on main

**Comment by santosh-pingle** [comment]
I am seeing this issue with nested question items of enabled question, where it does not accept the click event.

**Comment by santosh-pingle** [comment]
I think we can mark this issue as duplicate of #1812 where nested question items of enabled question does not accept the click event is also observed.

**Comment by jingtang10** [comment]
@santosh-pingle  Can you please verify that this is fixed, and if so, mark this as duplicate of 1812?

**Comment by santosh-pingle** [comment]
This is a duplicate of #1812.
This issue is fixed by pr #1881
