### ISSUE TITLE
Multiple Attachment views in a single form, uploading file in one item also shows in other item.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1821]
**Describe the bug**
Questionnaire json file contains multiple attachment widgets.
When user start uploading file to respective attachment item, it also uploads same file to other attachment view.
When user delete file from other attachment view, application exits.

Referred questionnaire
[component_attachment.txt](https://github.com/google/android-fhir/files/10485995/component_attachment.txt)

Captured video

https://user-images.githubusercontent.com/86107848/214203803-e0d13024-2271-46ac-8512-d1c75602449e.mov

**Component**
SDC library

**Expected behavior**
Uploaded file should be shown in the respective attachment widget.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 12

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@FikriMilano

**Comment by FikriMilano** [comment]
@santosh-pingle thanks for the bug report, I will have a look

cc @f-odhiambo

**Comment by santosh-pingle** [comment]
@FikriMilano any updates on it? thanks!

**Comment by FikriMilano** [comment]
@santosh-pingle not much update, I was logging the logic and doesn't found anything wrong.

Still investigating, but I have a conjecture that it's related to the recycling of recycler view

**Comment by santosh-pingle** [comment]
similar issue was found in https://github.com/google/android-fhir/issues/1818, may be you need to clear the old state before binding the data to the item.

**Comment by FikriMilano** [comment]
@santosh-pingle I have created PR https://github.com/google/android-fhir/pull/1828 to close this ticket.

Yeah, it turns out we need to clear the preview if there is no answer. And it has to be declared when binding the view holder.

**Comment by FikriMilano** [comment]
The reason why the other widget is also seems to be uploaded is because it recycles from the top widget, which already been uploaded. But if we click Delete at the other widget, it crashes because the answer is null. So it only recycles the view but not the answer.

**Comment by FikriMilano** [comment]
So, yeah, by clearing the preview if there is no answer will fix the bug
