### ISSUE TITLE
Add cancel button to the QuestionnaireFragment

### ISSUE THREAD

**Issue by Itskiprotich** [google/android-fhir#1829]
**Is your feature request related to a problem? Please describe.**
Provide an option where a user can cancel the data collection 

**Describe the solution you'd like**
Add a cancel button 

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="322" alt="Cancel Button" src="https://user-images.githubusercontent.com/26279422/214572136-1cd833c7-2c68-483b-83b8-01219d48a6da.png">
**Would you like to work on the issue?**
Yes

**Comment by omarismail94** [comment]
@Itskiprotich have you been facing issues with the up/back button that currently cancels the questionnaire collection? 

@shelaghm  FYI

**Comment by Itskiprotich** [comment]
@omarismail94  the up/back button works well. However, for uniformity design-wise, I find it ideal to have both submit and cancel buttons.

**Comment by jingtang10** [comment]
Thanks @Itskiprotich for raising this issue and creating the PR.

@shelaghm @rowo @joiskash @kunjan8794 please note the change that is being proposed in this ticket. I do feel this is a very reasonable feature, but also something that would require an option to turn it on/off.

One thing I'm not totally sure is just whether this is something that should be default to on or off? Any thoughts?

Also I don't know if it's a good idea to limit this to single page questionnaire... ? should paginated questionnaires also have an option to include a cancel button? if so should it be on the first page or every page? if every page how do we position this button together with the prev/next buttons?

**Comment by joiskash** [comment]
This looks good! I would vote for default on

**Comment by shelaghm** [comment]
Re: paginated 

I've mocked up some options so we can discuss what the best option is.
<img width="734" alt="Screenshot 2023-02-03 at 11 18 20" src="https://user-images.githubusercontent.com/86378921/216688881-36e431a7-2d77-4b16-abd2-c9df8abde2b6.png">

My preference is for `A`, not including a cancel button on paginated questionnaires. The existing arrow serves the same action of exiting the questionnaire.
`B`, I worry about adding a third button next to back/next navigation buttons and I think it might add confusion. Depending on phone size/text size the buttons are also too close to each other and worry about accidental taps.
`C`, I believe breaks some of the Android standard navigation patterns, so not sure if this a good idea either. 

What do you all think? Other options we should explore for this?

**Comment by shelaghm** [comment]
Discussion w/ Jing and team: 
- Default is `A`, and if showing the cancel button is on, then show `B`
- Also show a cancel dialog with "Do you want to exit the questionnaire?" Yes/No. 
@santosh-pingle

**Comment by Itskiprotich** [comment]
@shelaghm I have updated the feature to include the confirmation dialog within the SDC.
<img width="322" alt="Cancel Button" src="https://user-images.githubusercontent.com/26279422/218382434-28c87aa7-8906-454a-adc4-7b9ffbe1feec.png">

**Comment by shelaghm** [comment]
Thank you! Looks great @Itskiprotich
