### ISSUE TITLE
Add support for answerReference when using enableWhen

### ISSUE THREAD

**Issue by KhumboLihonga** [google/android-fhir#1834]
**Is your feature request related to a problem? Please describe.**
I can't use enableWhen to show/hide an item that depends on an item of type 'reference'

**Describe the solution you'd like**
I would like to be able to use answerReference attribute 

**Describe alternatives you've considered**
I've set the type of the item as a choice and instead used answerCoding but there are too many options to put in the questionnaire

**Additional context**
Here is the [questionnaire](https://github.com/google/android-fhir/files/10546572/answer-reference-sample.txt) that I used and this is the [log](https://github.com/google/android-fhir/files/10546567/answer-reference-log.txt) that I got

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
@santosh-pingle can you take a look at this

**Comment by santosh-pingle** [comment]
looking into it.
