### ISSUE TITLE
SDC | enableWhenExpression not working with displayCategory Extension

### ISSUE THREAD

**Issue by ppanchal-argus** [google/android-fhir#1835]
**Describe the bug**
In a questionnaire item with enableWhenExpression & displayCategory Extension it is not executing correctly.

**Component**
SDC Library

**To Reproduce**
1.Replace the new-paginated-registration-paginated.json with this questionnaire :
[displayCategoryEnableWhenQuestionnaire.txt](https://github.com/google/android-fhir/files/10551783/displayCategoryEnableWhenQuestionnaire.txt)

**Expected behavior**
in the questionnaire "with wheezing" instruction should be displayed.

**Screenshots**
Current output:
![Screenshot from 2023-01-31 14-58-19](https://user-images.githubusercontent.com/99809012/215904545-f4b5bfdc-884a-40a7-b79f-03ab386182ba.png)

Expected output:
![Screenshot from 2023-01-31 15-06-20](https://user-images.githubusercontent.com/99809012/215904578-435a8b4e-b0bb-479f-9492-74443199c6ef.png)

cc: @jingtang10 @delcroip

**Comment by MJ1998** [comment]
With the above PR this is what I get in the questionnaire.
Note: The given questionnaire had to be modified to this one: 
[new-patient-registration.txt](https://github.com/google/android-fhir/files/10887750/new-patient-registration.txt)

Screenshots:-
<img width="298" alt="Screenshot 2023-03-03 at 9 27 05 PM" src="https://user-images.githubusercontent.com/22965002/222882858-f89400c2-1b1d-4adf-8930-16769bbc5207.png">
<img width="298" alt="Screenshot 2023-03-03 at 9 27 00 PM" src="https://user-images.githubusercontent.com/22965002/222882865-c2b93a8b-09a9-43c3-872c-ca54fc6d2c77.png">

Please try this out.

**Comment by ppanchal-argus** [comment]
@MJ1998 Tested! Works well!
