### ISSUE TITLE
Add integration tests for the QuestionnaireFragment in the datacapture module

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#184]
https://github.com/google/android-fhir/issues/184#issue-794091744

**Comment by s-ayush2903** [comment]
Are we going to follow the robot pattern for testing the activities and fragments(mostly UI testing), also what we'll use, UI automator or espresso?

**Comment by s-ayush2903** [comment]
I'll take up this issue once it is clear/finalized what to use.

**Comment by jingtang10** [comment]
oops sorry i forgot to add this link: https://developer.android.com/guide/fragments/test

**Comment by epicadk** [comment]
@s-ayush2903 I noticed you are working on #186 . Are you working on this as well or can I take it up?

**Comment by s-ayush2903** [comment]
@jingtang10 The spelling of _Questionnaire_ in the issue title is wrong :laughing: , change it before someone opens a PR for it 😝

**Comment by epicadk** [comment]
> @jingtang10 The spelling of _Questionnaire_ in the issue title is wrong 😆 , change it before someone opens a PR for it 😝

😅

**Comment by s-ayush2903** [comment]
I didn't intend it specifically for someone, just had in my head that there were few PRs related to it :sweat_smile:. Apologies if it made you feel uneasy :disappointed:.

**Comment by epicadk** [comment]
> I didn't intend it specifically for someone, just had in my head that there were few PRs related to it 😅. Apologies if it made you feel uneasy 😞.

No relax 😂.

**Comment by jingtang10** [comment]
@s-ayush2903 I've updated the title of this issue - the `QuestionnaireFragment` in question is the one in the `datacapture` module rather than the `datacapturegallery` module. Sorry if this wasn't clear.

**Comment by s-ayush2903** [comment]
Thanks for info! Then what to do with the linked PR, Probably create an issue that targets the test it proposes, thoughts?

**Comment by jingtang10** [comment]
Thanks @s-ayush2903! I don't think testing the reference (gallery) application is a priority for us. In fact, I would go as far as saying it probably is a distraction. So I really would rather not work on this for now. Can you please close this PR and we can revisit if this becomes a priority? Thanks

**Comment by jingtang10** [comment]
@s-ayush2903 please comment on if you want to work on this? and unassign if appropriate.

**Comment by epicadk** [comment]
> As [mentioned previously](https://chat.fhir.org/#narrow/stream/276344-android/topic/stream.20events/near/234751232) in the channel I'm not able get the instrumentation tests running on my machine for libs, so I won't be able to work on any related issues.

++ I can't get them working on my device either.

**Comment by jingtang10** [comment]
> As [mentioned previously](https://chat.fhir.org/#narrow/stream/276344-android/topic/stream.20events/near/234751232) in the channel I'm not able get the instrumentation tests running on my machine for libs, so I won't be able to work on any related issues.

What I found on my machine is that I have to right click the folder containing the instrumentation tests and select run... Not sure if this helps you.

**Comment by epicadk** [comment]
> > As [mentioned previously](https://chat.fhir.org/#narrow/stream/276344-android/topic/stream.20events/near/234751232) in the channel I'm not able get the instrumentation tests running on my machine for libs, so I won't be able to work on any related issues.
> 
> What I found on my machine is that I have to right click the folder containing the instrumentation tests and select run... Not sure if this helps you.

Thanks this works. Any idea why this happens?

**Comment by jingtang10** [comment]
> > > As [mentioned previously](https://chat.fhir.org/#narrow/stream/276344-android/topic/stream.20events/near/234751232) in the channel I'm not able get the instrumentation tests running on my machine for libs, so I won't be able to work on any related issues.
> > 
> > 
> > What I found on my machine is that I have to right click the folder containing the instrumentation tests and select run... Not sure if this helps you.
> 
> Thanks this works. Any idea why this happens?

I'm not sure sorry. @deepankarb @yigit @florina-muntenescu @kevinmost not sure if anyone else knows why this is happening and if this is a bug worth filing to android studio.

**Comment by Ana2k** [comment]
> Thanks @s-ayush2903! I don't think testing the reference (gallery) application is a priority for us. In fact, I would go as far as saying it probably is a distraction. So I really would rather not work on this for now. Can you please close the linked PR and we can revisit if this becomes a priority? Thanks

hi @jingtang10 is this being revisited now?
i saw it in-progress here : https://github.com/google/android-fhir/projects/1#column-12632674
can I work on this?

**Comment by omarismail94** [comment]
Just cleaning things up. Closing this as QuesitonnaireFragmentTest exists
