### ISSUE TITLE
Support questionnaire-constraint Extension

### ISSUE THREAD

**Issue by delcroip** [google/android-fhir#1849]
**Is your feature request related to a problem? Please describe.**
I need to set validation a bit more complex than max/min on question there is an extension available 
http://hl7.org/fhir/StructureDefinition/questionnaire-constraint

**Describe the solution you'd like**
Support of the extension and run add it to the form validation  
Must support reference to the item value through:
- getValue() 
- %qitem

Neither are supported today (GetValue() return always null, %qitem throw a Fhirpath exception) might be related to https://github.com/google/android-fhir/issues/1246

**Describe alternatives you've considered**
[Min /Max  ](http://hl7.org/fhir/StructureDefinition/maxValue)

but the issue it can only do numeric validation

also the message cannot be customised

**Additional context**
here a simple example (like a max)

```
{
                        "extension": [
                            {
                                "extension": [
                                    {
                                        "url": "key",
                                        "valueId": "EmCare.A.DE13.a"
                                    },
                                    {
                                        "url": "expression",
                                        "valueExpression": {
                                            "language": "text/fhirpath",
                                            "expression": "getValue().empty() or getValue()>=0 and getValue()<4"
                                        }
                                    },
                                    {
                                        "url": "severity",
                                        "valueCode": "error"
                                    },
                                    {
                                        "url": "human",
                                        "valueString": "the number of year cannot be above 4"
                                    }
                                ],
                                "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-constraint"
                            },
                            {
                                "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-enableWhenExpression",
                                "valueExpression": {
                                    "language": "text/fhirpath",
                                    "expression": "%resource.repeat(item).where(linkId='EmCare.A.DE12').answer.first().value.code = 'EmCare.A.DE13'"
                                }
                            }
                        ],
                        "linkId": "EmCare.A.DE13.a",
                        "text": "Age in years",
                        "type": "quantity",
                        "required": false,
                        "repeats": false
                    },
```

**Would you like to work on the issue?**
no, I don't have the skills

**Comment by delcroip** [comment]
Update on other alternatives: Min / Max is not supportted for Quantity type

**Comment by delcroip** [comment]
I think qitem should be part of that list https://github.com/google/android-fhir/blob/e0c92b27f453a97b38f9f3fd80b704ae0bfdf56e/datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt#L46

**Comment by jingtang10** [comment]
Please see in #2003 for additional comments.

Assigned to @FikriMilano. Thanks for taking this Fikri.
