### ISSUE TITLE
Support max length and min length

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#185]
In our views for different question types, we need to validate the lengths of the answers by respecting the min and max length constraints.

The max length constraint is part of the `Questionnaire` resource in FHIR: https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.maxLength
The min length constarint is part of the structured data capture implementation guide (SDC IG): http://hl7.org/fhir/uv/sdc/2019May/behavior.html#value-constraints Notice the difference: it's an extension, not part of the core resource.

@kunjan8794 already created a validation framework: https://github.com/google/android-fhir/tree/master/datacapture/src/main/java/com/google/android/fhir/datacapture/validation

We will need to create possibly 2 more validators, which will be triggered if the max length field is set or the min length extension exists.

The result of the validation will then be displayed in the UI in the appropriate places in different types of input.

To begin with, we can probably focus on EditText types of controls.

**Comment by Manikant25** [comment]
Can I work on the issue?

**Comment by pankajkatoch** [comment]
> Can I work on the issue?

Hi Manikant,
If you have a context and background of this project, and have some knowledge of FHIR, then sure go ahead.
Otherwise I had planned to handle it next week.

Thanks.

**Comment by s-ayush2903** [comment]
@Manikant25 We already have a PR for this, see #224

**Comment by Manikant25** [comment]
> > Can I work on the issue?
> 
> Hi Manikant,
> If you have a context and background of this project, and have some knowledge of FHIR, then sure go ahead.
> Otherwise I had planned to handle it next week.
> 
> Thanks.

No, I don't know much about the project if you are doing keep doing. 
Thanks

**Comment by Manikant25** [comment]
> @Manikant25 We already have a PR for this, see #224

@s-ayush2903 Thanks for informing me.

**Comment by jingtang10** [comment]
#224 is about min and max *value* rather than min and max *length*.

@pankajkatoch do you have an estimated date for this one?

thanks all!

**Comment by sakets3010** [comment]
@jingtang10 i would like to work upon this issue, if its still available.

**Comment by kunjan8794** [comment]
@jingtang10 Should I take this up next?

**Comment by jingtang10** [comment]
@sakets3010 will you be able to work on this? @kunjan8794 might be able to help since he implemented the validator framework.

**Comment by sakets3010** [comment]
> @sakets3010 will you be able to work on this? @kunjan8794 might be able to help since he implemented the validator framework.

Hi @jingtang10 , I wont be able to work on this immediately. Pleases feel free to reassign. Apologies.

**Comment by kunjan8794** [comment]
@jingtang10 In that case, should I take this up next?
