### ISSUE TITLE
Questionnaire pagination

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#186]
Use the `page` value in here: http://build.fhir.org/codesystem-questionnaire-item-control.html#questionnaire-item-control-page

**Comment by fredhersch** [comment]
@jingtang10 This looks right for pagination, that is, authors need to 'group' the items and specify the page attribute. Is that correct?

**Comment by fredhersch** [comment]
@jingtang10 I can see in issue #161 (HIV IG case report) the items are nicely grouped already. Can we treat each group as a page by default? And work on rendering that way?

**Comment by jingtang10** [comment]
> @jingtang10 This looks right for pagination, that is, authors need to 'group' the items and specify the page attribute. Is that correct?

Yep that's right!

> @jingtang10 I can see in issue #161 (HIV IG case report) the items are nicely grouped already. Can we treat each group as a page by default? And work on rendering that way?

I think we should not treat groups as pages automatically. Reason being sometimes groups are used to logically group questions, or hide/show questions (using enableWhen). So we should only treat then as page if there's an extension that says this group should be treated as a page.

**Comment by s-ayush2903** [comment]
I would like to work on this issue.

**Comment by fredhersch** [comment]
Goal(s): Provide the ability to render a multi-page form based on the definition in the FHIR Questionnaire. Manage data when moving through the pages (of the rendered form) and if there are validation errors on submission

Key points:
1. Given a FHIR questionnaire that specifies the 'page' attribute, show the grouped items on a separate page
2. On the first page show only the 'next' page option
3. On subsequent pages, show 'prev' and 'next' options
4. On the final page, show 'prev' and 'submit' options
5. When moving between pages, completed fields should hold the values
6. If there are validation errors on submit, be able to update them and resubmit
7. The labels for next and prev is loaded from the strings.xml and should support translations

See issue[ #161 ](url) Sample form with extension and grouped items here - https://github.com/google/android-fhir/issues/161

Sample UI for placement of controls:

Step 1: 
![image](https://user-images.githubusercontent.com/34733/116204875-c39d3380-a76f-11eb-955c-358b66230967.png)

Step 2: 
![image](https://user-images.githubusercontent.com/34733/116204926-d0ba2280-a76f-11eb-9257-58e1faa7612f.png)

**Comment by vincent-karuri** [comment]
This is going to be an important and high priority feature for us. Is it possible to see how we can align on this?

**Comment by fredhersch** [comment]
@vincent-karuri Sounds good. Should we discuss this on the developers call tomorrow?

**Comment by vincent-karuri** [comment]
yep, thanks @fredhersch

**Comment by fredhersch** [comment]
Discussed three approaches:

1. Controls outside the Questionnaire Fragment
2. Controls within the Questionnaire Fragment
3. Implementing 1, but with defaults in place that can be overridden

Decision:

- Aim to start with 2. Questionnaire drives the pagination
- Implications of this: controls are within Questionnaire
- Will revisit extending this in the future to add additional customisation

**Comment by jingtang10** [comment]
@vincent-karuri @kevinmost will you two be able to collaborate on this (and bringing in @s-ayush2903 where poss)? Thanks!

**Comment by jingtang10** [comment]
Note that the positions of the prev/next buttons will be different from the mocks @fredhersch posted now that we're going with option 2 in https://github.com/google/android-fhir/issues/186#issuecomment-833329895.

Also see https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Paging.20behavior for some past discussions.

**Comment by vincent-karuri** [comment]
```
{
  "linkId": "death",
  "text": "Patient death",
  "type": "group",
  "extension": [
    {
      "url": "http://hl7.org/fhir/questionnaire-item-control",
      "valueCode": "page"
    }
  ],
  "item": [
    {
      "linkId": "dateOfDeath",
      "text": "Date of death",
      "type": "date"
    },
    {
      "linkId": "causeOfDeath",
      "text": "Cause of death",
      "type": "string"
    }
  ]
}
```

Is this how we want to mark a group as a page?

**Comment by vincent-karuri** [comment]
> Note that the positions of the prev/next buttons will be different from the mocks @fredhersch posted now that we're going with option 2 in [#186 (comment)](https://github.com/google/android-fhir/issues/186#issuecomment-833329895).
> 
> Also see https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Paging.20behavior for some past discussions.

also from the chat

1.  Do we only need to mark one group (most intuitively the first) as a page and from then on treat all other subsequent groups as pages? 
2. Do we validate that there's no mixing of groups and non-groups in a Questionnaire when the page extension is specified?
3. Related to 2, is the assumption that we have a well-authored Questionnaire that only contains groups when pagination is expected?

**Comment by kevinmost** [comment]
Per Lloyd in the chat, I believe all pages should be marked as pages.

> Lloyd McKenzie: You could have some groups marked as header or footer. Otherwise, I'd expect them to all be pages. What happens otherwise is undefined.

At least for an initial implementation, let's assume that we have a well-formed questionnaire, which means that either all groups or no groups are marked as pages.

**Comment by jingtang10** [comment]
Agreed. I think these two assumptions should suffice:
1. A page must be a top-level item of the questionnaire.
2. A sibling of a page must be a page.
