### ISSUE TITLE
[Roadmap] alpha-01 release of Knowledge Manager Library

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#1862]
The Knowledge Manager Library will provide a layer to load, store and manage Knowledge Resources.

These are typically the resources that are packaged up into a FHIR IG such as:
* ValueSets
* Questionnaires
* Plan/Activity Definitions
* Library Resources containing CQL/ELM

This library will initially support FHIR IG loading with additional support planned for alternative server side approaches to defining the Knowledge Resources required for a FHIR based application

The Knowledge Manager will expose a set of APIs that can be used by other libraries - such as the SDC, FHIR Engine or Workflow to load specific resources

**Comment by omarismail94** [comment]
closing as this has been released
