### ISSUE TITLE
Mobile number gets cleared on entering 11th digit

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1869]
**Describe the bug**
In catalog app, default / paginated layout, Mobile number gets cleared when user enters 11th digit in input box

**Component**
 SDC library  SDC gallery app

**To Reproduce**
1. Go to 'Default/paginated layout'
2. Click on 'Mobile number input box and enter 10 digit mobile number and the 11th digit'
3. See error "entered mobile number gets cleared on entering 11th digit"

**Expected behavior**
Instead of clearing all digits app must show error message.

**Screenshots**
[mobileNumberClearedOn11digit.webm](https://user-images.githubusercontent.com/13957417/218704570-85b3f04a-85c9-4e90-84dd-15cf6bb56980.webm)

**Smartphone (please complete the following information):**
 - Device:  Nexus 5X emulator
 - Android version: API 24

**Comment by santosh-pingle** [comment]
It can be marked as duplicate of #1718

**Comment by PallaviGanorkar** [comment]
Closing this issue as its handled in #1718
