### ISSUE TITLE
Tests for LocalChangeUtils

### ISSUE THREAD

**Issue by deepankarb** [google/android-fhir#187]
> did you add tests for this static class? if not, please create an issue as a follow up :)

i think one of the benefits of having this static class is that the tests can be written very independently.

_Originally posted by @jingtang10 in https://github.com/google/android-fhir/pull/146#r564426060_

**Comment by Ana2k** [comment]
@deepankarb @jingtang10 I have created similar issues(#380 and #381). 
Can I take on this issue and make a PR ASAP?

**Comment by omarismail94** [comment]
LocalChangeUtilsTest exists
