### ISSUE TITLE
Date Time Picker Component behavior is broken

### ISSUE THREAD

**Issue by PallaviGanorkar** [google/android-fhir#1870]
**Describe the bug**
In catalog app, select date time picker component - there are 2 issue as broken behavior
1. By default time input UI is enabled, which is expected to be enabled after entering Valid date
2. Date format error is displayed, though user has entered valid date 

**Component**
SDC library, SDC gallery app

**To Reproduce**
1. Go to 'Catalog App, Date time picker component'
3. See error 'By default time input UI is enabled'
4. Enter 'Valid date in date input widget by text (without date picker)'
5. See error "Date format needs to be MM/dd/yyyy (e.g. 01/31/2023)"

**Expected behavior**
1. By default time widget should be disabled untill Valid date is entered
2.  Date format error should disappear on entering Valid date.

**Screenshots**
Videos are attached below

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - Android version:API 24

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by PallaviGanorkar** [comment]
[1_ByDefaultTimeInputUIIsEnabled.webm](https://user-images.githubusercontent.com/13957417/218727885-6d698943-fae4-45aa-85f9-7f2f1fd86572.webm)

**Comment by PallaviGanorkar** [comment]
[2_InvalidDateFormatErrorIsDisplayed.webm](https://user-images.githubusercontent.com/13957417/218728106-67696e58-2f4a-474b-9be9-45b0e88a34ea.webm)

**Comment by santosh-pingle** [comment]
looking into it.
