### ISSUE TITLE
connectedCheck fails in Android SDK level (tentatively) above 30

### ISSUE THREAD

**Issue by MJ1998** [google/android-fhir#1905]
**Describe the bug**
**Android SDK level 33**
module: benchmark
test command: ./gradlew connectedCheck
failed task: benchmark:connectedReleaseAndroidTest
Error: Some FileNotFoundException very similar to [this](https://b.corp.google.com/issues/203598149). 
[The solution in the above link works for 30..31]
Log: [issue1.txt](https://github.com/google/android-fhir/files/10939380/issue1.txt)

So I installed SDK level 31 and the tasks benchmark:connectedReleaseAndroidTest and benchmark:benchmarkReport run 
successfully.  But following is the details of what still fails:-
**Android SDK level 31**
module: implementationguide
test command: ./gradlew connectedCheck
failed task: implementationguide:connectedDebugAndroidTest
error: failed tests in com.google.android.fhir.implementationguide.db.impl.ImplementationGuideDatabaseTest
log: [issue2.txt](https://github.com/google/android-fhir/files/10939470/issue2.txt)

I didn't check for other versions.

**Component**
benchmark, implementationguide

**To Reproduce**
1. Install Pixel 4 with SDK level 33/31
2. Run `./gradlew connectedCheck` for this device

**Expected behavior**
Check runs successfully

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel4a emulator
 - Android version: 12
 - Build number: SE1A.220203.002.A1
 - Version 33, 31

**Additional context**
Probably [this](https://github.com/captain-miao/AndroidException/issues/7) is relevant.

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by omarismail94** [comment]
closing as this is obsolete. Our testsing suite tests API Level 24 and 33
