### ISSUE TITLE
Cursor skipping back while start typing a value in numeric field

### ISSUE THREAD

**Issue by owais-vd** [google/android-fhir#1914]
**Describe the bug**
Cursor is skipping back while start typing on the numeric field if the initial value is set to 0

**Component**
SDC library

**To Reproduce**
1. Go to any questionnaire.
2. Click on any field that has a support number only.
3. Type a 0 first.
4. Then type any number like 100 after 0.
5. You'll notice that the cursor is back to the second last character instead of the end.

**Expected behavior**
Cursor should stick to the end position of the field.

**Screenshots**

https://user-images.githubusercontent.com/62104757/225643988-45aa0c54-56b1-403a-874d-2beec2593324.mp4

**Smartphone (please complete the following information):**
 - Device: emulator
 - Android version: 11
 - Build number: RSR1.201013.001

**Comment by omarismail94** [comment]
I can replicate this! Interesting bug for sure. Ill look into this some more

**Comment by f-odhiambo** [comment]
This issue seems to be reoccurring again cc @omarismail94

**Comment by jingtang10** [comment]
@f-odhiambo please assign this to someone thanks!

**Comment by AngelaKabari** [comment]
@MJ1998 please find here a screen recording of the cursor skipping bug on emulator, along with the emulator bug report.
- [Cursor skipping bug.webm](https://github.com/google/android-fhir/assets/8417097/4b0653f3-380c-4b4d-a371-59a393ed78e6)
- [bugreport-Pixel_2_API_30-2024-05-02-15-31-37-40356b20-1bad-437f-8110-81a8a5accccb.zip](https://github.com/google/android-fhir/files/15188754/bugreport-Pixel_2_API_30-2024-05-02-15-31-37-40356b20-1bad-437f-8110-81a8a5accccb.zip)

Let me know if you require any further information or clarification?

**Comment by karina4050** [comment]
@MJ1998 Screen recording of the bug on the SID BUnda app. 
Device: Emulator Pixel 2 API 29
Android Version: 10
Build Number: QSR1.190920.001

[Screen_recording_20240503_125603.webm](https://github.com/google/android-fhir/assets/73172427/3fb2a708-4f86-4c19-9594-95276e9e2fe2)

**Comment by MJ1998** [comment]
Thanks. Looking into this

**Comment by aditya-07** [comment]
The way I was able to consistently replicate the issue was by doing some intensive work on the main thread.

I simply created an infinite loop in the `MainActivity.onCreate` that would work for some time and then sleep for sometime.

```
lifecycleScope.launch {
    while(true) {
      for(i in 0..100_000){
       println("$i")
      }
       delay(100)
    }
}
```
