### ISSUE TITLE
Extend or update the Search DSL 'has' function to include resource type as parameter

### ISSUE THREAD

**Issue by ellykits** [google/android-fhir#1921]
**Is your feature request related to a problem? Please describe.**
In FHIRCore we would want to use the nested search DSL `has` function however we do not know the type of the resource at the time of the execution; the current `Search#has` function is generic and expects a resource type.

**Describe the solution you'd like**
Implement an overloaded extension function that accepts resource type as a parameter without affecting the existing implementation.

**Describe alternatives you've considered**
As an alternative we can update the existing `Search#has` function to accept `resourceType` as a parameter instead of using generic types.

**Additional context**
To offer more flexibility the recommendation is to update or implement a new function with the following signature
```kotlin
fun Search.has(
  resourceType: ResourceType,
  referenceParam: ReferenceClientParam,
  init: Search.() -> Unit
) 
```

Here is the current
```kotlin 
inline fun <reified R : Resource> Search.has(
  referenceParam: ReferenceClientParam,
  init: Search.() -> Unit
) 
```

**Would you like to work on the issue?**
Yes

**Comment by f-odhiambo** [comment]
@omarismail94 Do you mind taking a lot at this and approving if it is something we can work on resolving? Thanks!

**Comment by omarismail94** [comment]
Im adding @aditya-07   as he wrote the code for this. Aditya - is there a reason we went with a reified function as opposed to the signature that @ellykits is suggesting? I think what Elly is suggesting makes sense, but wanted to see what you thought as well!

**Comment by aditya-07** [comment]
@omarismail94 There wasn't any particular reason to make the function `reified`. @ellykits @f-odhiambo Please feel free to add generic `has` api.

**Comment by ellykits** [comment]
Thanks @aditya-07. This is noted.

**Comment by jingtang10** [comment]
@ellykits @f-odhiambo @pld can you please elaborate a bit more on how you're using this new API?

I'm guessing you have some kind of configuration that defines a search by specifying its resource type and search params and that's why the type resolution must be done at runtime?

**Comment by ellykits** [comment]
The implementation can be compared to the overloaded `FhirEngine#get` function

(with no resource type as parameter)
```kotlin
suspend inline fun <reified R : Resource> FhirEngine.get(id: String): R 
```

and this 

(with resource type as parameter)
```kotlin
suspend fun get(type: ResourceType, id: String): Resource
```

**Comment by jingtang10** [comment]
> @omarismail94 There wasn't any particular reason to make the function `reified`. @ellykits @f-odhiambo Please feel free to add generic `has` api.

reified is needed if at runtime you need to access the type information of the generic class.

But that's not really relevant in this issue.

Thanks @ellykits for providing the examples. Makes sense.
