### ISSUE TITLE
Support for _tag and _profile as search parameters in x-fhir-query expression

### ISSUE THREAD

**Issue by gosso22** [google/android-fhir#1935]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to use _tag or _profile with x-fhir-query for example you can not have Location?_tag=salima-catchments with within x-fhir-query expression. You will get an exception that the _tag not found in resource Location.

**Describe the solution you'd like**
Be able to tag resources and use the tags to filter them using x-fhir-query expressions

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
I have a potential fix for this issue

**Comment by santosh-pingle** [comment]
@aditya-07 Can you please add this issue to Android FHIR SDK project?
