### ISSUE TITLE
[IgManager] Support downloading IGs from the remote Package Manager

### ISSUE THREAD

**Issue by ktarasenko** [google/android-fhir#1937]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@ktarasenko Could you please add more details to the description?

**Comment by santosh-pingle** [comment]
@aditya-07 Can you please add this issue to Android FHIR Sdk project?
