### ISSUE TITLE
[demo] Sync progress bar visibility + percent > 100

### ISSUE THREAD

**Issue by MJ1998** [google/android-fhir#1949]
**Describe the bug**
Sync progress bar has following issues:-
1. The sync percent goes above 100.
2. Creating a patient we come back to PatientList page. The sync progress bar becomes visible with 0% full progress.

**Component**
demo app, fhir-engine

**To Reproduce**
Just run the demo app in master branch normally

**Expected behavior**
The sync percent to be correctly shown
sync progress bars to be not shown when there's no data being downloaded

**Screenshots**
[This screenshot is pertaining to the 2nd issue mentioned above]
<img width="324" alt="Screenshot 2023-04-03 at 5 35 26 PM" src="https://user-images.githubusercontent.com/22965002/229504053-b8f9037f-6d77-4531-8ff0-475bf0d1ed32.png">

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 31
 - Build number: 

**Additional context**
This is happening because `total` in `DownloaderImpl` is calculated based on the `urls` present at first. This fails to track total resources when `urls` is modified  by adding more urls to be processed in `processResponse` block. This results into completed > total and hence percent > 100.

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
Is this still reproducible?

**Comment by MJ1998** [comment]
Nope. Closing this.
