### ISSUE TITLE
Use custom SQL query in FHIR Engine

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#1950]
**Is your feature request related to a problem? Please describe.**

See comment in https://github.com/opensrp/fhircore/issues/2066#issuecomment-1473385899:
```
Write raw queries instead of using the FHIR Engine search API. I had to add a method inside FhirEngine to allow raw queries and return a raw Cursor
```

**Describe the solution you'd like**
Provide an API so that developers can write custom SQL queries to search the offline FHIR Engine database.

**Describe alternatives you've considered**
@ekigamba can you please provide some examples of the custom queries you need to write? And we can see if there're any alternative approach we can take.

**Additional context**
https://github.com/opensrp/fhircore/issues/2066

**Would you like to work on the issue?**
Potentially

**Comment by ekigamba** [comment]
We don't need this at this point. We can close this
