### ISSUE TITLE
Handle delete resource 

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#1951]
**Describe the bug**
Handle delete resource :
1. If Resource is already deleted on server side
2. If Resource is deleted before uploading it. eg: Phone is offline, creates an Observation , adds it to the Provenance resource, Deletes the Observation. Now if referential integrity check on upload is on in the server, the upload will fail. 

**Component**
Core library

**To Reproduce**
Described above

**Expected behavior**
1. Handle with the appropriate result message
2. Do not squash the change? Not sure how FHIR servers handle insert followed by delete in the same transaction. 

**Would you like to work on the issue?**
No

cc: @aditya-07 @jingtang10

**Comment by omarismail94** [comment]
@joiskash  can you cherry-pick PR#2133 and see if that fixes this issue
