### ISSUE TITLE
Show required text if the question must be answered. Otherwise, provide configuration to support optional text.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#1954]
**Is your feature request related to a problem? Please describe.**
As per the discussion with @shelaghm and @jingtang10, and considering the input from the external community, it has been decided that
1. If a question item is required, then the required text will be shown in the form just below the view. This will be the default behavior.
2. Also support the configuration to show optional text for optional questions instead of the default behavior.

#544 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Looking into it.

**Comment by santosh-pingle** [comment]
@shelaghm 
If there are instructions for a required question, is there a specific order or precedence to follow when displaying the required text?
Currently, if the required text is shown, it overrides existing instructions. To resolve this conflict, we need to decide how to show the required text along with instructions, if present.

**Comment by shelaghm** [comment]
I suggest showing 'required' text first, and then the rest of the instructions or entryFormat. Screenshot below. What do you think?

<img width="488" alt="Screenshot 2023-04-10 at 15 13 40" src="https://user-images.githubusercontent.com/86378921/231009088-244f26bf-97dc-483d-9fc8-f604f9669225.png">

**Comment by santosh-pingle** [comment]
> I suggest showing 'required' text first, and then the rest of the instructions or entryFormat. Screenshot below. What do you think?
> 
> <img alt="Screenshot 2023-04-10 at 15 13 40" width="488" src="https://user-images.githubusercontent.com/86378921/231009088-244f26bf-97dc-483d-9fc8-f604f9669225.png">

Thanks!
yes, I am also of the same opinion to show the required text and instructions in the same line, if both are present.

**Comment by santosh-pingle** [comment]
@shelaghm 

If optional text is configured, but question text is not provided in the questionnaire, then I am of the opinion that optional text should not be shown as the only question text.

Do you have any suggestions?

Note: Please refer to the attached screenshots from the link below for (optional) text configuration.
