### ISSUE TITLE
Modified Date is needed as sorting parameter for all FHIR resources

### ISSUE THREAD

**Issue by khyativyasargus** [google/android-fhir#1956]
**Describe the bug**
Currently while querying resources from SDC , sort() method is available which can be used to get sorted data specially while we want to query resources with pagination, but currently modified date is stored only in meta data , not available for sort method parameter.

**Component**
Engine library

**To Reproduce**
1. Go to PatientListViewModel file in demo app
2. check getSearchResults method to get Patient resource list
3. sort(Patient.GIVEN, Order.ASCENDING) method is used in that method which is available at query level sorting
4. But when you check other available sorting parameters for Patient as GIVEN, Modified date can not be found which is needed in some cases for example,  while we want to fetch last modified patients at top!
5. Same applies on all the resources

**Expected behavior**
For sort(Patient.GIVEN, Order.ASCENDING),  Modified date should be available as well,

@jingtang10

**Comment by aditya-07** [comment]
@khyativyasargus Is the expectation to sort by the server assigned `lastUpdated` date or the local `lastUpdated` ?

**Comment by khyativyasargus** [comment]
@aditya-07  local assigned lastUpdated is needed

**Comment by santosh-pingle** [comment]
@khyativyasargus is it okay to change component from sdc library to engine library?

**Comment by khyativyasargus** [comment]
@santosh-pingle can you provide more context on this?
cc @jingtang10 @aditya-07

**Comment by santosh-pingle** [comment]
> @santosh-pingle can you provide more context on this? cc @jingtang10 @aditya-07

@khyativyasargus 
I intended to remove the SDC library from the component in the description of the issue. You can ignore it now, as I have updated the corresponding change. thanks!

**Comment by khyativyasargus** [comment]
@santosh-pingle Okay got it. Thanks!

**Comment by jingtang10** [comment]
As we don't store the local last updated timestamp, we will need to start storing it when we update resources locally.

Options:
1. use the meta element's last updated timestamp locally
2. add a new db column in resources table
3. same as 2 but add a new meta table which includes last updated timestamp
4. add a new default custom index in the date index table for all resources by default

Comparison:
| |Update resource meta data | New column in resource table | New meta data table | New custom index |
|-|-|-|-|-|
| DB change | ✅ No db change | ⛔️ Need db change  | ⛔️ Need db change | ✅ No db change | 
| Preserve server last updated | ⛔️ No | ✅ Yes | ✅ Yes | ⛔️ No |

So it seems like first we need to make a decision about if we want to overwrite server-side last updated timestamp.

**Comment by aditya-07** [comment]
@jingtang10 Another option could be to same as 4 but add a custom search parameter exclusively for local_lastUpdated . That way, we won't have to do a DB change and we can preserve server lastUpdated as well.

**Comment by aditya-07** [comment]
@omarismail94 @khyativyasargus @joiskash @ellykits @ekigamba Do you have any inputs or thoughts about the options listed above?
