### ISSUE TITLE
Support fhirpath supplement context literal

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1958]
**Is your feature request related to a problem? Please describe.**
To make question fhirpath dynamic and have current questionnaire item we need to support fhirpath supplement context literal. This allow to get current questionnaire item as %context into fhirpath  expressions on questionnaire items. Details for spec defined here https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements . 

**Describe the solution you'd like**
An implementation exists in PR #1957 . This has a catalog implementation as an example as well. The enableWhen evaluate method passes the questionnaireResponseItem when calling evaluate for expression. 

**Additional context**
This is a bug fix and the changes MAY affect existing use of enableWhenExpression where anyone tried to write expression for questionnaireResponse as $this. $this refers to current item under consideration aka %context as well. Old implementation might have entertained $this as questionnaireResponse. Hence anyone using expression wrongfully can have erratic behavior for their current enableWhenExpressions 

**Would you like to work on the issue?**
Done in PR #1957

**Comment by jingtang10** [comment]
Updated the issue title since this should not be limited to enable when expression -> this should be available to all fhir path expressions in a questionnaire.
