### ISSUE TITLE
[SDC] Refactor text overflow in dropdown

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1966]
**Problem**
Overflow texts gets cut off in dropdown

**Describe the solution you'd like**
Text should overflow to the next line. EmCare team has solved this in this commit https://github.com/google/android-fhir/commit/17774dabd17dadfc5fbbef1a07e871c0dbbf46e3

cc @santosh-pingle @kunjan8794 @khyativyasargus @jingtang10

**Comment by santosh-pingle** [comment]
@kunjan8794 @khyativyasargus
I see corresponding commit opened for this feature on your repository.
Are you going to create PR corresponding to main repository android fhir sdk?
Or you want me to look into it?

cc @jingtang10

**Comment by khyativyasargus** [comment]
@santosh-pingle Sure. We will create PR for this in main repository.

**Comment by santosh-pingle** [comment]
@khyativyasargus thanks!, is there any approximate date by which we can expect the pull request?

**Comment by khyativyasargus** [comment]
@santosh-pingle Yes, You can expect all PRs done by 24th April, Monday. Let me know if it's needed before that. Thanks!
