### ISSUE TITLE
[SDC] Reduce space between question title & options in default layout

### ISSUE THREAD

**Issue by shelaghm** [google/android-fhir#1967]
**Problem**
The spacing between the question title and options is too big. It is also not configurable for developers so they can easily adjust.

**Solution**
1. Adjust the default spacing to be 4dp (so it is consistent with a 4dp grid)
2. Make spacing a configurable attribute

**EmCare commit**
https://github.com/google/android-fhir/commit/1b9023b3f585418bc5624d8050e886ee878e6706

cc @santosh-pingle @kunjan8794 @khyativyasargus @jingtang10

**Comment by santosh-pingle** [comment]
@kunjan8794 @khyativyasargus
I see corresponding commit opened for this feature on your repository.
Are you going to create PR corresponding to main repository android fhir sdk?
Or you want me to look into it?

cc @jingtang10

**Comment by khyativyasargus** [comment]
@santosh-pingle Sure. We will create PR for this in main repository.

**Comment by santosh-pingle** [comment]
@khyativyasargus thanks!, is there any approximate date by which we can expect the pull request?

**Comment by khyativyasargus** [comment]
@santosh-pingle Yes, You can expect all PRs done by 24th April, Monday. Let me know if it's needed before that. Thanks!
