### ISSUE TITLE
Ability to provide headers in the DownloadWorkManager

### ISSUE THREAD

**Issue by anchita-g** [google/android-fhir#1989]
**Is your feature request related to a problem? Please describe.**
Application should be able to use e-tags  based headers like `if-modified-since`, `if-none-match` for optimised download/upload of resources. 

**Describe the solution you'd like**
Along with the URL, it will be useful to provide the ability to mention the additional headers that should be sent in the request to the server.

**Additional context**
[FHIR specification](https://www.hl7.org/fhir/http.html#cread)

cc: @jingtang10

**Comment by santosh-pingle** [comment]
@anchita-g
Are you going to work on this issue?
(If yes, please add priority and effort to fix this issue.)
