### ISSUE TITLE
Usage of fhirPathEngine in Utils should be centralized and made consistent

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#1993]
**Describe the bug**
As per discussion here https://github.com/google/android-fhir/pull/1957#discussion_r1179019296 the fhirPathEngine usage should be centralized and made consistent throughout app. There are usages in ExpressionEvaluator, QuestionnaireViewModel and ResourceMapper which should be modified so that all expressions evaluated are passed with corresponding context data consistently.

**Component**
SDC library

**Comment by santosh-pingle** [comment]
@maimoonak 
Is it okay to add code health label?

**Comment by omarismail94** [comment]
I think this is resolved now. We only have one fhirPathEngine in FhirPathUtil that gets passed around in the different classes in datacapture. If this is not true, feel free to re-open the issue
