### ISSUE TITLE
SDC | Nested items of group are not rendering when loading Questionnaire using QuestionnaireResponse

### ISSUE THREAD

**Issue by ppanchal-argus** [google/android-fhir#1998]
**Describe the bug**
Nested items under group  type are not rendering when loading Questionnaire using QuestionnaireResponse, however they are loading when nested items are under Boolean type.

**Component**
SDC Library

**To Reproduce**
1. On Master branch apply the patch [group_nested_items_not_visible.txt](https://github.com/google/android-fhir/files/11395022/group_nested_items_not_visible.txt)
2. Run the app, Go to new questionnaire (+ icon n patient list)
3. The questionnaire is not rendering the nested group items.
4. Undo the patch changes and apply this patch: [boolean_nested_items_are_visible.txt](https://github.com/google/android-fhir/files/11395125/boolean_nested_items_are_visible.txt)
5. Now Re-run the app and again open the questionnaire, on selecting option for boolean type, it shows the nested items. Only change done is that the group type is replaced with boolean type.

**Expected behavior**
Ideally the nested items should be visible even for group type.

**Screenshot**
Group Type:
![image](https://user-images.githubusercontent.com/99809012/236145783-f998a30d-0264-4fc3-aa4a-257a87247221.png)

Boolean Type:
![image](https://user-images.githubusercontent.com/99809012/236145648-6cf758a2-538e-4a72-b19b-255871ce6cf0.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a emulator

**Additional context**
After applying patch: Questionnaire is at file: assets/new-patient-registration-paginated.json & QuestionnaireResponse is on line: 82 (AddPatientFragment.kt)

cc: @jingtang10  @omarismail94

**Comment by khyativyasargus** [comment]
@jingtang10 @santosh-pingle 
I have re-tested with latest SDC code, and this is to confirm that the issue we mentioned still persists.

**Comment by santosh-pingle** [comment]
@ppanchal-argus  
Please provide the questionnaire file specifically associated with the reproducible issue? The previously uploaded file unfortunately contains extraneous characters that require removal before I can utilize it.

**Comment by ppanchal-argus** [comment]
@santosh-pingle 
Thanks for looking into this! 
From the first patch :
Questionnaire: [group_nested_item_not_visible_questionnaire.txt](https://github.com/google/android-fhir/files/11459937/group_nested_item_not_visible_questionnaire.txt)
QuestionnaireResponse: [group_nested_item_not_visible_questionnaire_response.txt](https://github.com/google/android-fhir/files/11459944/group_nested_item_not_visible_questionnaire_response.txt)

From the second patch:
Questionnarie: [boolean_nested_items_are_visible_questionnaire.txt](https://github.com/google/android-fhir/files/11460018/boolean_nested_items_are_visible_questionnaire.txt)
QuestionnaireResponse: [boolean_nested_items_are_visible_questionnaire_response.txt](https://github.com/google/android-fhir/files/11460020/boolean_nested_items_are_visible_questionnaire_response.txt)

**Comment by jingtang10** [comment]
hey @parthfloyd and @nsabale7, why are questionnaire responses provided without nested items? where did they come from?

can you fix this by using questionnarie responses with nested items?

**Comment by ppanchal-argus** [comment]
@jingtang10 This is occuring when the nested items are not enabled due to their enableWhenExpression logic. The questionnaireResponse generated in the SDC doesn't include these disabled (by enableWhenExpression logic) nested items. 

The issue occurs when the questionnaire is re-rendered with this QR and user changes question which satisfied the enableWhenExpression condition for those nested items.

**Comment by santosh-pingle** [comment]
Interesting, as per specification, if questionnaire item is not answered, then corresponding response item should be removed.

If the corresponding missing response items are added to the questionnaire response, and the `questionnaireFragment.getQuestionnaireResponse()` API is called to retrieve the response, it has been observed that the newly added items persist in the fetched response.
Interestingly, this response is equivalent to the one fetched when only the questionnaire is passed to the SDC module, and none of the enabled question items are answered.

Expectation as per QuestionnaireResponse specification which says `However, once a QuestionnaireResponse is marked as 'completed' (including if it is subsequently changed to 'amended'), all requirements of the associated Questionnaire must be met, all non-answered question items must be removed, all non-enabled items must be removed, etc.`
https://build.fhir.org/questionnaireresponse.html#validation
