### ISSUE TITLE
Questionnaire Constraint support

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2003]
**Is your feature request related to a problem? Please describe.**
Do custom validation for a given `questionnaire.item` with a FHIRPath custom predicate and custom error message.

Use case:
There is a vaccination date field, and we want to make sure that when the user inputs a date. The date must not be before the Patient's DOB.

What should happen:
If the user inputs a date that's before the Patient's DOB. Then show a custom error message below the field: “Date must not be before the DoB”.

**Describe the solution you'd like**
Add support for Questionnaire Constraint extension to do this.

**Describe alternatives you've considered**
N/A

**Additional context**
- Confirmed by Lloyd via [Zulip chat](https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/.E2.9C.94.20Custom.20Validation.20for.20Questionnaire.2Eitem) that the Questionnaire Constraint is the right extension 
- Questionnaire Constraint docs 
  - [FHIR R4](http://hl7.org/fhir/R4/extension-questionnaire-constraint.html) 
  - [FHIR IG](https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-questionnaire-constraint.html)
- Questionnaire Constraint is part of the [SDC Behavior](https://build.fhir.org/ig/HL7/sdc/behavior.html#other-control)
- Questionnaire Constraint will be used by ticket https://github.com/opensrp/fhir-resources/issues/1248

**Would you like to work on the issue?**
N/A

**Comment by FikriMilano** [comment]
@jingtang10 @f-odhiambo @pld @samkanga

**Comment by FikriMilano** [comment]
another use case is:
enter phone number field
confirm phone number field

if the 2 values are different, then show validation error

cc @mmweru

**Comment by FikriMilano** [comment]
@jingtang10 it has been finalized that I'm working on this

**Comment by FikriMilano** [comment]
@shelaghm Should we use the pop-up dialog that displays a list of errors to show a global level error message from this constraint-extension to the user?
What do you suggest?

<img width="319" alt="Screen Shot 2023-10-20 at 13 31 38" src="https://github.com/google/android-fhir/assets/62053304/4ec69eba-7b72-4719-bb91-e61195ddafc9">

**Comment by pld** [comment]
if we go w/that, is there a setting to disable the "submit anyway" button? there are projects that would not want to have that option available

**Comment by FikriMilano** [comment]
@pld the visibility of "submit anyway" button is not configurable.
We can discuss to make it configurable, @jingtang10 @santosh-pingle 

A question:
Do we have a use case to not use the error dialog itself? or are we ok for that dialog to start showing up in OpenSRP 2? My concern is, our SDK snapshot release should have the latest code on master. So, this dialog should now popping up on our OpenSRP 2 if there are validation errors. This is regardless of what causes the validation errors i.e. it could be from required field or others, so it's not only from this constraint extension.

**Comment by jingtang10** [comment]
Closing this in favour of #1849 which was opened first.

**Comment by jingtang10** [comment]
> if we go w/that, is there a setting to disable the "submit anyway" button? there are projects that would not want to have that option available

@pld we don't have this as a customized option at the moment. but as @FikriMilano said we might be able to add this. i'll create an issue for this.
