### ISSUE TITLE
Add slider control

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#201]
See http://hl7.org/fhir/R4/valueset-questionnaire-item-control.html for slider

**Comment by AliAkberAakash** [comment]
Hi, I'd like to contribute to this issue. Where do I have to add the slider?

**Comment by jingtang10** [comment]
Hi - thanks for your interest. Please refer to PR #191.

There are a few important things you'll need to do

- create a new layout file for the slider widget
- create a new factory class that will use the layout file to create the view holder
- change the `QuestionnaireItemAdapter.kt` file so that it uses the new factory for numbers
- add tests

please take a look at that PR and let me know if you have questions.

**Comment by jingtang10** [comment]
Ali - may I ask you to download the repo and try to build the datacapturegallery module first. Once you've done that and you're clear what to do I can grant write access.

**Comment by jingtang10** [comment]
An example can be found here: http://build.fhir.org/ig/HL7/sdc/examples.html#using-sliderstepvalue

**Comment by s-ayush2903** [comment]
This has been solved in #287, Issue can be closed.

**Comment by jingtang10** [comment]
Thanks @s-ayush2903!
