### ISSUE TITLE
SDC : Answer being vanished for Quantity type item after packRepeatedGroups

### ISSUE THREAD

**Issue by khyativyasargus** [google/android-fhir#2013]
**Describe the bug**
For nested item of group type with enable expression, in some case, answer is getting vanished for the item after packRepeatedGroups method while processing QR

**Component**
SDC library

**To Reproduce**
1. On Master branch apply the patch [signs_complete_patch.txt](https://github.com/google/android-fhir/files/11542871/signs_complete_patch.txt)
2. Run the app, Go to new questionnaire (+ icon n patient list)
3. Answer is not being rendered for the Respiratory rate
4. Undo the patch changes and apply this patch: [signs_questionnaire_patch_mvp.txt](https://github.com/google/android-fhir/files/11543243/signs_questionnaire_patch_mvp.txt)
 list)
5. Now Re-run the app and again open the questionnaire, Interestingly it's working fine with MVP signs_questionnaire_patch_mvp.txt for the same item

**Expected behavior**
Respiratory rate item answer should be rendered if it's given in QR, while debugging through SDC methods , we found that answer object for Respiratory Rate item is being vanished after packRepeatedGroups method with the Patch [signs_complete_patch.txt](https://github.com/google/android-fhir/files/11542871/signs_complete_patch.txt) 

**Screenshots**
Answer no being rendered for Respiratory rate
![image](https://github.com/google/android-fhir/assets/121015652/b0587403-7105-4786-ab7f-0f4593f33401)

Answer being rendered for Respiratory rate as standalone item
![image](https://github.com/google/android-fhir/assets/121015652/8e37682a-4ecd-49e6-9eee-123972ece3b4)

**Smartphone (please complete the following information):**
 - Device: Pixel4 emulator

**Additional context**
After applying patch: Questionnaire is at file: assets/new-patient-registration-paginated.json & QuestionnaireResponse is on line: 83(AddPatientFragment.kt)

@jingtang10 @santosh-pingle

**Comment by santosh-pingle** [comment]
@khyativyasargus 

Could you please remove any unnecessary characters from both the patch and attach separate questionnaire and questionnaire response files for the observed and not observed issues.

**Comment by santosh-pingle** [comment]
> @khyativyasargus
> 
> Could you please remove any unnecessary characters from both the patch and attach separate questionnaire and questionnaire response files for the observed and not observed issues.

@khyativyasargus 
any updates on it? thanks!

**Comment by ppanchal-argus** [comment]
> > @khyativyasargus
> > Could you please remove any unnecessary characters from both the patch and attach separate questionnaire and questionnaire response files for the observed and not observed issues.
> 
> @khyativyasargus any updates on it? thanks!

Thanks @santosh-pingle . Apologies for the delay. Here are the Questionnaires & QR (QR is same for both questionnaires)
The only difference in both questionnaires is of enableWhenExpression
[signs_not_showing_respiratory_rate_questionnaire.txt](https://github.com/google/android-fhir/files/11598060/signs_not_showing_respiratory_rate_questionnaire.txt)
[signs_not_showing_respiratory_rate_questionnaire_response.txt](https://github.com/google/android-fhir/files/11598061/signs_not_showing_respiratory_rate_questionnaire_response.txt)
[signs_showing_respiratory_rate_questionnaire.txt](https://github.com/google/android-fhir/files/11598063/signs_showing_respiratory_rate_questionnaire.txt)

Patches:
[not_working_signs.txt](https://github.com/google/android-fhir/files/11598099/not_working_signs.txt)
[working_signs.txt](https://github.com/google/android-fhir/files/11598100/working_signs.txt)

**Comment by santosh-pingle** [comment]
@khyativyasargus  

The description mentioned that it should work for one questionnaire.json file, but I am not seeing the quantity value in either case. Can you please confirm?

**Comment by santosh-pingle** [comment]
@khyativyasargus 
I see both questionnaire json has mentioned of unit extension which was not supported by sdc earlier.

**Comment by ppanchal-argus** [comment]
@santosh-pingle Can you try applying the `working_signs` patch directly? Ideally it should show this screen. Let me know if it's still not showing up.

![image](https://github.com/google/android-fhir/assets/99809012/16768381-0d11-418b-bcee-f108b8715a89)

**Comment by santosh-pingle** [comment]
@khyativyasargus  @ppanchal-argus 
https://hl7.org/fhir/extensions/StructureDefinition-questionnaire-unit.html
This is for use on items of type integer and decimal

**Comment by santosh-pingle** [comment]
@khyativyasargus 
Is the calculatedExpression extension truly necessary in `signs_not_showing_respiratory_rate_questionnaire.json`?

```
{
              "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-calculatedExpression",
              "valueExpression": {
                "language": "text/fhirpath",
                "expression": "iif(%resource.repeat(item).where(linkId='Respiratory Rate profile').answer.first().exists(), %resource.repeat(item).where(linkId='Respiratory Rate profile').answer.first().value,{})"
              }
            }
          ],
          "linkId": "EmCare.B22.DE01",
...
```

**Comment by santosh-pingle** [comment]
@khyativyasargus @ppanchal-argus 

The questionnaire item in questionnaire.json has a calculated expression that returns an empty answer. This empty answer is then updated to the existing answer, which is why the text field shows nothing.

**Comment by delcroip** [comment]
I don't Think so

I will remove it.

Br
