### ISSUE TITLE
Deprecate `getSummaryRequestUrls` in `DownloadWorkManager` in favour of a simpler interface for sync progress

### ISSUE THREAD

**Issue by anchita-g** [google/android-fhir#2015]
**Describe the bug**

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@anchita-g 
Please add more details to the description section.

**Comment by jingtang10** [comment]
This is a same as #1884 ?

**Comment by jingtang10** [comment]
closing in favour of #1884
