### ISSUE TITLE
Display prefixes in questions

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#202]
See the pain management questionnaire https://github.com/google/android-fhir/pull/196

Spec: https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.prefix

At the moment the prefixes are not displayed at all, this causes confusion in some questions where the prefix includes critical information.

**Comment by joiskash** [comment]
For True/False answers rendered as a check box, where will the prefix come? Seems odd if it looks like "Q2 |   | Are you feeling happy?"  
PS: |   | is a checkbox

**Comment by MuhammadSalman-7214** [comment]
@jingtang10 where do we want to show prefixes in questions ? please specify. Thanks

**Comment by jingtang10** [comment]
@MuhammadSalman-7214 yes that's the main focus of this issue. At the moment the prefixes are not handled/shown.

**Comment by jingtang10** [comment]
updated the description.

**Comment by MuhammadSalman-7214** [comment]
so, we want to show prefix for every question @jingtang10  or with only specific question @jingtang10 ?

**Comment by jingtang10** [comment]
I believe by default we should just show it for all questions. no reason to hide it for some questions. What do you think?

If you have doubts please feel free to use https://chat.fhir.org/#narrow/stream/179255-questionnaire to ask quesitons about the expecation of the standard itself.

What I'm not sure about is if we should use two different text views or concatenate the strings in one text view. Can you think aboout the pros and cons and write down your thoughts here @MuhammadSalman-7214? Thanks!

**Comment by MuhammadSalman-7214** [comment]
One thing is if we want to show prefix for each questionnaire, then we have to add the code in all the factory classes to show prefix with question, right @jingtang10 ?

I think rather than two different textviews, we should concatenate the prefix before question text, it's advantage is that we do not have to change xml at all, only the code files will change

**Comment by jingtang10** [comment]
Yes this will touch all view types.

I'm not sure I necessarily agree we should simply do the easiest thing.

One important consideration is that if the prefix needs to be rendered different (e.g. different color, size, font) then having it in the same text view would not be able to achieve that. Do you know if there's ever an expectation that it might need to be rendered differently? Can you do some research to figure this out?

**Comment by MuhammadSalman-7214** [comment]
I understand your point, but from where should I research or from where should I ask 
https://chat.fhir.org/login/#narrow/stream/179255-questionnaire
should I ask on this link?

**Comment by s-ayush2903** [comment]
>   I think rather than two different textviews, we should concatenate the prefix before question text, it's advantage is that we do not have to change xml at all, only the code files will change

I have a question, why we don't want to change XML? I believe it can be done with a little more effort using the data binding and conditionally adding the prefixes to the text needed

**Comment by MuhammadSalman-7214** [comment]
it's not that we don't want to change the xml, currently we are discussing the solutions

**Comment by MuhammadSalman-7214** [comment]
so how are we going about it @jingtang10 ?

**Comment by jingtang10** [comment]
did you get a chance to ask the question in the zulip chat stream?

as i said i'm concerned about the customization of styling for prefix and the main question text. so having 2 different views gives more flexibility.

**Comment by MuhammadSalman-7214** [comment]
posted it just now in the zulip chat stream

so should I start to add text views in every factory class then @jingtang10 ?

**Comment by jingtang10** [comment]
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Question.20Prefix
