### ISSUE TITLE
SDC : Some properties of Questionnaire are not accessible for custom components

### ISSUE THREAD

**Issue by khyativyasargus** [google/android-fhir#2023]
**Describe the bug**
Some properties are not accessible of Questionnaire object for custom components (Eg, orientation, answerOption). While creating custom components like BooleanType, orientation, answerOption properties have private access to the library and due to that we can't achieve functionalities like flexible orientation or custom text for radio buttons. 

**Component**
SDC library

**Expected behavior**
Each property of the Questionnaire which is required for component behavior should have public access.

cc @jingtang10

**Comment by FikriMilano** [comment]
Kind of makes sense, because it will be very useful if we can use those features in our custom widgets.

Seconding this :D

**Comment by jingtang10** [comment]
@khyativyasargus @FikriMilano please feel free to send a pr. thanks for raising this issue!
