### ISSUE TITLE
Search method takes more time when load 7k household list

### ISSUE THREAD

**Issue by mahmud6390** [google/android-fhir#2040]
Uploaded 7k household to FHIR server with basic info like name and id. After initial syncing done it's take more time to load at pagination or search by name. It take 2 minute to load all household at SDK.
Like a query below
`SELECT a.serializedResource FROM ResourceEntity a
LEFT JOIN DateIndexEntity b
ON a.resourceType = b.resourceType AND a.resourceUuid = b.resourceUuid AND b.index_name = '_lastUpdated'
LEFT JOIN DateTimeIndexEntity c
ON a.resourceType = c.resourceType AND a.resourceUuid = c.resourceUuid AND c.index_name = '_lastUpdated'
WHERE a.resourceType = 'Group'
AND a.resourceUuid IN (
SELECT resourceUuid FROM TokenIndexEntity
WHERE resourceType = 'Group' AND index_name = 'active' AND index_value = 'true'
)
AND a.resourceUuid IN (
SELECT resourceUuid FROM TokenIndexEntity
WHERE resourceType = 'Group' AND index_name = 'type' AND (index_value = 'person' AND IFNULL(index_system,'') = 'http://hl7.org/fhir/group-type')
)
AND a.resourceUuid IN (
SELECT resourceUuid FROM TokenIndexEntity
WHERE resourceType = 'Group' AND index_name = 'code' AND (index_value = '35359004' AND IFNULL(index_system,'') = 'https://www.snomed.org')
)
ORDER BY b.index_from DESC, c.index_from DESC
LIMIT 10 OFFSET 30`
when using ORDER BY  it's take 50 sec per page or getting search result after search by name.

Device configuration: samsung galaxy tab A 8 enc(SM-T295), ram 2 GB, rom 16 GB.

**Would you like to work on the issue?**
Yes, we want to work in this issue .We'll need to add order by with household added datetimewise, household serial number,lastvisited timewise. so how can we implement this any tips for this

**Comment by jingtang10** [comment]
can you please add your search api call here as well?

**Comment by ellykits** [comment]
@mahmud6390 Is this based on the FHIRCore code? Refer to [RegisterRepository#L91](https://github.com/opensrp/fhircore/blob/8a4a8c43f76bd92d7ef80360cd81d86d837b1fb4/android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/register/RegisterRepository.kt#L91) to access the Search API code responsible for generating the query.

**Comment by mahmud6390** [comment]
@jingtang10 time consuming whenever we have added `sort(DateClientParam("_lastUpdated"), Order.DESCENDING)` at `fhirEngine
      .search` method
testing code as below to filter household
 ```
fhirEngine
      .search<Group> {
        if (nameQuery.isNotEmpty()) {
          filter(
            StringClientParam(SP_NAME),
            {
              modifier = StringFilterModifier.CONTAINS
              value = nameQuery
            }
          )
        }
        filterFamily(this)
        sort(DateClientParam("_lastUpdated"), Order.DESCENDING)
        //count = 100
        from = 0
      }
      .mapIndexed { index, fhirGroup -> fhirGroup.toFamilyItem(index + 1) }
      .let { families.addAll(it) }
```

**Comment by mahmud6390** [comment]
private fun filterFamily(search: Search) {
    search.filter(
      TokenClientParam("type"),
      init = arrayOf(
        {
          val coding = Coding("http://hl7.org/fhir/group-type", "person", "")
          value = of(coding)
        },
      ),
    )

    search.filter(
      TokenClientParam("code"),
      init = arrayOf(
        {
          val coding = Coding("https://www.snomed.org", "35359004", "")
          value = of(coding)
        },
      ),
    )
  }

**Comment by ellykits** [comment]
@jingtang10  We also shared some feedback on some of the query performance issues on FHIRCore. Refer to the latest comments on this issue for more info https://github.com/opensrp/fhircore/issues/2066

**Comment by mahmud6390** [comment]
tested db size is 21 MB. fhircore db is not encrypted. but fhir sdk db is encrypted. @jingtang10

**Comment by mahmud6390** [comment]
tested db size is 21 MB. fhircore db is not encrypted. but fhir sdk db is encrypted. @jingtang10 
you may add below configuration for testing 
`FhirEngineProvider.init(
      FhirEngineConfiguration(
        enableEncryptionIfSupported = true,
        RECREATE_AT_OPEN,
        ServerConfiguration(
          "http://fhirqa.mpower-social.com:7070/fhir/",
          authenticator = object: Authenticator {
            override fun getAccessToken(): String {
              return "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIUTktRnk2NXM4WTRPb2pvOWFsRk9iSW02dHdISFJTNUpKdGVrZEFUeHFFIn0.eyJleHAiOjE2ODczMjkxMTMsImlhdCI6MTY4NzMyNTUxMywianRpIjoiYTI4OGIwYjktNzk0ZS00Yjg0LThlZWQtZWYwNDI2ZGFkNzMwIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay1uZXcubXBvd2VyLXNvY2lhbC5jb20vYXV0aC9yZWFsbXMvZmhpciIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJmOGVhODZlMy02YjMyLTQ5MzQtODY2OS1hMzRjN2Y2OTRjNTkiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmaGlyLWFwcCIsInNlc3Npb25fc3RhdGUiOiJhNDQ4ZDBhYy0xYmY1LTQ4MWMtOGIzYi1iZDU4Mzc1ZDgwYzIiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHA6Ly9maGlycWEubXBvd2VyLXNvY2lhbC5jb206NzA3MCIsImh0dHA6Ly8xOTIuMTY4LjE5LjYzOjgwODAiLCJodHRwOi8vMTkyLjE2OC4xOS42Mzo3MDcwIiwiaHR0cDovL2ZoaXItd2ViLm1wb3dlci1zb2NpYWwuY29tOjMwMDAiLCJodHRwOi8vMTkyLjE2OC4yMy4xNDo4MDgwIiwiaHR0cDovL2ZoaXIubXBvd2VyLXNvY2lhbC5jb206NzA3MCIsImh0dHA6Ly8xOTIuMTY4LjQzLjIxNDo4MDgwIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaHR0cDovLzE5Mi4xNjguMTkuNjM6MzAwMCIsImh0dHA6Ly9maGlyLXdlYnFhLm1wb3dlci1zb2NpYWwuY29tOjMwMDAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkxPQ0FUSU9OUyIsIkVESVRfS0VZQ0xPQUtfVVNFUlMiLCJST0xFX1ZJRVdfS0VZQ0xPQUtfVVNFUlMiLCJIRUFMVEhDQVJFX1NFUlZJQ0UiLCJDT01NT0RJVFkiLCJFREkiLCJHUk9VUCIsIlJPTEVfRURJVF9LRVlDTE9BS19VU0VSUyIsImRlZmF1bHQtcm9sZXMtZmhpciIsIlRFQU1TIiwiVklFV19LRVlDTE9BS19VU0VSUyIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJVU0VSUyIsIkNBUkVfVEVBTSIsIlFVRVNUIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtdXNlcnMiLCJ2aWV3LXVzZXJzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJhNDQ4ZDBhYy0xYmY1LTQ4MWMtOGIzYi1iZDU4Mzc1ZDgwYzIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJyYWkgaGFuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicmFpIiwiZ2l2ZW5fbmFtZSI6InJhaSIsImZhbWlseV9uYW1lIjoiaGFuIn0.Jul4y5nTwGafma-XQvnwXYesHiMO2LAFfgLUTzUdHYDFQIAvjmCr0LLyQR-VcjNxrMuB5xc-9QHBVXqKKnI_4UTXedi1i5cueiSWaJ-0qWWJ0rGSEfCBg2VeU0fJCeIRHAFsDHw0McqZbN5CBs1YRuauZK4Cbpo4aC1iT_iJifUIsgRkIMnQ-Y3mg3e94m9DuuBG_b-xidC04cQnSROMUtFIVaWA_mXjvtO92qdR1KOOalAcLgmkE9ehVzrrToHDIx96bjEpMQPgZxTxlPv_Xwa2EZ2rN4AgMMMh2jRP8Z_wWqKibnYqazrudTCBwPr_t5ZhEnDy3rRUUN6Cn9ecxA"
            }
          },
          httpLogger =
            HttpLogger(
              HttpLogger.Configuration(
                if (BuildConfig.DEBUG) HttpLogger.Level.BODY else HttpLogger.Level.BASIC
              )
            ) { Timber.tag("App-HttpLog").d(it) },
          networkConfiguration = NetworkConfiguration(uploadWithGzip = false)
        )
      )
    )`
for details you may check the below source tree
[https://github.com/asad-zaman/android-fhir/tree/develop](url)

**Comment by omarismail94** [comment]
@mahmud6390 I deleted your comment as it contained sensitive info. Just so we don't loose what was said, the DB size was 21MB

**Comment by mahmud6390** [comment]
> @mahmud6390 The auth token provided here has expired. Could you please provide a new token? Also, looks like the token expires in 1 hour, is there a way for you to provide a token that is valid for a couple of hours for us to be able to debug using it?

@aditya-07 would you please use below token
`"eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJIUTktRnk2NXM4WTRPb2pvOWFsRk9iSW02dHdISFJTNUpKdGVrZEFUeHFFIn0.eyJleHAiOjE2ODc4MzU4OTQsImlhdCI6MTY4NzUzNTg5NCwianRpIjoiYmI4NzU0NmUtZWQ5Mi00NDAyLWFiY2EtMTczMTBmNGEzMmRlIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay1uZXcubXBvd2VyLXNvY2lhbC5jb20vYXV0aC9yZWFsbXMvZmhpciIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJmOGVhODZlMy02YjMyLTQ5MzQtODY2OS1hMzRjN2Y2OTRjNTkiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmaGlyLWFwcCIsInNlc3Npb25fc3RhdGUiOiJmNjE4NTViYS0zODYyLTQ2ODMtYTRhMS03Yjc2ZDhlODdkZGUiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MCIsImh0dHA6Ly9maGlycWEubXBvd2VyLXNvY2lhbC5jb206NzA3MCIsImh0dHA6Ly8xOTIuMTY4LjE5LjYzOjgwODAiLCJodHRwOi8vMTkyLjE2OC4xOS42Mzo3MDcwIiwiaHR0cDovL2ZoaXItd2ViLm1wb3dlci1zb2NpYWwuY29tOjMwMDAiLCJodHRwOi8vMTkyLjE2OC4yMy4xNDo4MDgwIiwiaHR0cDovL2ZoaXIubXBvd2VyLXNvY2lhbC5jb206NzA3MCIsImh0dHA6Ly8xOTIuMTY4LjQzLjIxNDo4MDgwIiwiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaHR0cDovLzE5Mi4xNjguMTkuNjM6MzAwMCIsImh0dHA6Ly9maGlyLXdlYnFhLm1wb3dlci1zb2NpYWwuY29tOjMwMDAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkxPQ0FUSU9OUyIsIkVESVRfS0VZQ0xPQUtfVVNFUlMiLCJST0xFX1ZJRVdfS0VZQ0xPQUtfVVNFUlMiLCJIRUFMVEhDQVJFX1NFUlZJQ0UiLCJDT01NT0RJVFkiLCJFREkiLCJHUk9VUCIsIlJPTEVfRURJVF9LRVlDTE9BS19VU0VSUyIsImRlZmF1bHQtcm9sZXMtZmhpciIsIlRFQU1TIiwiVklFV19LRVlDTE9BS19VU0VSUyIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJVU0VSUyIsIkNBUkVfVEVBTSIsIlFVRVNUIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJtYW5hZ2UtdXNlcnMiLCJ2aWV3LXVzZXJzIiwicXVlcnktZ3JvdXBzIiwicXVlcnktdXNlcnMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJmNjE4NTViYS0zODYyLTQ2ODMtYTRhMS03Yjc2ZDhlODdkZGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJyYWkgaGFuIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicmFpIiwiZ2l2ZW5fbmFtZSI6InJhaSIsImZhbWlseV9uYW1lIjoiaGFuIn0.IPVe5Bba2db-sqPjGf44FbIM8HaBrejghMPTEpKRgirqk-V-yY_Z8NYlb_768iDmtcVXgMpJz0AJuZLoPp-4ZXaf9R-R5s8PCygPvG7xalLPjNZweF0RuxHKsBTva87A_jQa2Gr8YIexP6b-RUlGWBtGf1zaG1f7tEObO_dVMklOObRw8NGpcU562F0xHmdmM3bK3lDBfgbzNiqgier2akYsz4b9EcM7QKoYIQsw-Wz785L5swyqX1aDjrtc0hkHV7dxSODFeJ51xiMxBjRxuhlnvizifWaVUoJb3HUQUxQl8T8Qx6CZRlmkq_UYUuFYAquvRezLDjEoia1u84hkug"` i think if possible please  import below postman collection
https://github.com/google/android-fhir/files/11829710/FireCoreTest.postman_collection.zip

**Comment by omarismail94** [comment]
I can replicate the issue on my machine and can confirm the query is slow. The issue seems to be from the double left join we do when create the search query [here](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt#L63-L73) when the sort is done in a DateClientParam. If we are able to remove one of the left joins, the query runs much faster, e.g.:

```
SELECT a.serializedResource 
FROM ResourceEntity a 
LEFT JOIN DateIndexEntity b
ON a.resourceType = b.resourceType 
AND a.resourceUuid = b.resourceUuid 
AND b.index_name = '_lastUpdated' 
WHERE a.resourceType = 'Group' 
AND a.resourceUuid IN (
   SELECT resourceUuid 
   FROM TokenIndexEntity 
   WHERE resourceType = 'Group' 
   AND index_name = 'type' 
   AND (index_value = 'person' 
   AND IFNULL(index_system,'') = 'http://hl7.org/fhir/group-type') 
) 
AND a.resourceUuid IN (
   SELECT resourceUuid 
   FROM TokenIndexEntity 
   WHERE resourceType = 'Group' 
   AND index_name = 'code' 
   AND (index_value = '35359004' AND IFNULL(index_system,'') = 'https://www.snomed.org') ) 
ORDER BY b.index_from DESC
LIMIT 10 
OFFSET 30
```

**Comment by omarismail94** [comment]
I pushed a new commit to the PR to further optimise the query plan:

```
SEARCH a USING INDEX index_ResourceEntity_resourceType_resourceId (resourceType=?)
LIST SUBQUERY 1
SEARCH TokenIndexEntity USING INDEX index_TokenIndexEntity_resourceType_index_name_index_system_index_value (resourceType=? AND index_name=?)
LIST SUBQUERY 2
SEARCH TokenIndexEntity USING INDEX index_TokenIndexEntity_resourceType_index_name_index_system_index_value (resourceType=? AND index_name=?)
SEARCH b USING COVERING INDEX index_DateIndexEntity_resourceType_index_name_resourceUuid_index_from (resourceType=? AND index_name=? AND resourceUuid=?) LEFT-JOIN
SEARCH c USING COVERING INDEX index_DateTimeIndexEntity_resourceType_index_name_resourceUuid_index_from (resourceType=? AND index_name=? AND resourceUuid=?) LEFT-JOIN
USE TEMP B-TREE FOR ORDER BY
```

with these new commit, we are `USING COVERING INDEX`, which means  avoiding having to reference the original table, and instead the DB just uses the indexes table

**Comment by mahmud6390** [comment]
after merge PR https://github.com/google/android-fhir/pull/2047 now it's working smoothly like 50sec to 2 sec per page or search
