### ISSUE TITLE
KnowledgeManager | Version not being updated in ResourceMetadataEntity table after installing newer version of a FHIR library using KnowledgeManager.install()

### ISSUE THREAD

**Issue by ppanchal-argus** [google/android-fhir#2042]
**Describe the bug**
When a library is updated (version number is usually updated with that) and installed in knowledge manager through `knowledgeManager.install(writeToFile(libraryBNew))` then also it still points to the old version & can be cross verified using Android Studio's app inspection & checking `knowledge.db` database's `ResourceMetadataEntity` table.

I have attached a patch file to demonstrate this issue & attaching the upload bundle as well as the response bundle.

**Component**
Core library.

**To Reproduce**
1. On Master branch apply the patch [library_version_issue.txt](https://github.com/google/android-fhir/files/11768701/library_version_issue.txt)
2. Run the app, Go to new questionnaire (+ icon n patient list)
3. Submit the questionnaire as it is (Submit anyway)
4. Now check in App inspection and check `knowledge.db` database's `ResourceMetadataEntity` table.
5. You'll see that it has two entries only with version `A.1.0.0 & B.1.0.0` for `libraryA` and `libraryB` respectively but if you check on `AddPatientViewModel.kt 113->117` you'll see we have updated version to `A.1.0.1` and `B.1.0.3` respectively.
6. Additionally if you check `Device File Manager` (on Android Studio) and on path `/data/data/com.google.android.fhir.demo/files` you can see that the two library files do have the latest version number but it is not reflected in the database.

**Expected behavior**
Ideally the version number should be updated when a library with same id is installed with an updated version number.

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

cc: @jingtang10

**Comment by ktarasenko** [comment]
Thank you for the elaborate description, much appreciated. 

The fix is on its way [2043]

**Comment by ppanchal-argus** [comment]
Thanks @ktarasenko this resolved the issue!

**Comment by ppanchal-argus** [comment]
Thanks @ktarasenko This fixed the issue!

cc: @jingtang10
