### ISSUE TITLE
Dynamic answerExpression not working

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2052]
**Describe the bug**
answerExpression doesn’t support accessing context from variable expression, it only can for launch context. This makes it not possible to have dynamic answer options.

So basically, the answer options within the dropdown widget is static once the app render the questionnaire.

**Component**
SDC library

**To Reproduce**
1. Paste the downloaded sample Questionnaire into demo app `assets` folder
2. Replace the file name in the following line of code to 'dynamic-answer-expression.json'
https://github.com/google/android-fhir/blob/master/demo/src/main/java/com/google/android/fhir/demo/EditPatientViewModel.kt#L48
3. Run demo app, and wait for sync
4. Click a patient
5. Click edit icon (top-right corner)
6. In the first dropdown, select the "NAIROBI" city
7. Open the second dropdown
8. It still shows nothing

**Expected behavior**
answerExpression should be able to access other context including variable expression, therefore making the answer options dynamic, every time the variable updates.

**Screenshots**

[device-2023-06-30-181824.webm](https://github.com/google/android-fhir/assets/62053304/55b1fce7-44e4-4985-a80d-b55a1bb61369)

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**
- Sample Questionnaire, download below:
https://drive.google.com/file/d/1aweK2JZ-3dzG9N7M2KoPwy_80sqZF9my/view?usp=sharing
- The cqf-expression extension within the sample, serve as a prove that the variable expression DOES updates and you can see it in the second dropdown question title. But the answerExpression DOES NOT update.
- FHIR doc of answerExpression: https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-answerExpression.html
- More FHIR doc of answerExpression: https://build.fhir.org/ig/HL7/sdc/expressions.html#answerExpression
- In this case, answerExpression is retrieving a list of Patient from local db, then display it in the dropdown as answer options
- The code you probably need to look at: https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt#L585-L589

**Would you like to work on the issue?**
N/A

**Comment by MJ1998** [comment]
Hey @FikriMilano Could you give an example ?

**Comment by FikriMilano** [comment]
@MJ1998 thanks you so much for the interest!
I added the sample questionnaire, demo video, and more details in the ticket description.

**Comment by FikriMilano** [comment]
Hi @MJ1998
Kindly let me know if you have any follow up questions

**Comment by FikriMilano** [comment]
@f-odhiambo @pld

**Comment by MJ1998** [comment]
Hi @FikriMilano 
Sure. Thanks for adding a detailed description.

**Comment by FikriMilano** [comment]
@MJ1998 just to make sure, I would like to inquire whether you are currently working on this task. If not, I would be happy to pick this up, as it holds high priority for our team.

**Comment by MJ1998** [comment]
Yes @FikriMilano, I am working on this. I hope a solution by tomorrow should be good ? If its urgent then please feel free to take this up.

**Comment by FikriMilano** [comment]
That's great news! thank you @MJ1998 :D

Tomorrow is fine, please continue. It would be a shame if your 1 week of efforts is not getting merged. Looking forward for you code, thanks :D

**Comment by MJ1998** [comment]
Alright I have a crude working solution. There are 2 errors:
1. answerExpressionMap stores initial expression and does not re-evaluate
2. variables in x-fhir-query are not supported, only launchContext

Crude solution is to bypass 1 and replace variables with values evaluated in the fhir-query expression. 

But from the other PR's [comment](https://github.com/google/android-fhir/pull/2034#discussion_r1244169873) you tagged me, it seems its better to modify the QuestionnaireViewItem API with `enabledAnswerOptionList` .

**Comment by MJ1998** [comment]
@FikriMilano There you go!

**Comment by FikriMilano** [comment]
Thanks @MJ1998 :D
I'll review it.
