### ISSUE TITLE
SDC : Open-Choice or Modal type questions preserving its answers

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#2055]
**Describe the bug**

**Component**
SDC library

https://github.com/google/android-fhir/assets/82660329/39f97222-2d04-4669-999c-45fbce7c0616

**To Reproduce**
1. Go to Open Choice
2. Select any answer
3. Close the fragment
4. Go to Open Choice again

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@nsabale7 
thanks for raising this issue, I will take a look, if you have not started working on it yet.

**Comment by nsabale7** [comment]
> @nsabale7 thanks for raising this issue, I will take a look, if you have not started working on it yet.

Okay @santosh-pingle you can give a look.
