### ISSUE TITLE
CQF expression extension not working with html tags

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2056]
**Describe the bug**
When we put html tags in cqf-expression extension, the html tags is not working.

This is used in Questionnaire.item.text, to make that text bold, while also allowing that text dynamic by using cqf-expression extension.

**Component**
SDC library

**To Reproduce**
"Congrats!" should be bold, w the following sample.
```
{
  "_text": {
    "extension": [
      {
        "url": "http://hl7.org/fhir/StructureDefinition/cqf-expression",
        "valueExpression": {
          "language": "text/fhirpath",
          "expression": "<b>Congrats!</b> you have %variable-1 symptoms"
        }
      }
    ]
  }
}
```

**Expected behavior**
CQF expression should work with html tags, therefore making the text bold.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**
N/A

**Would you like to work on the issue?**
N/A

**Comment by jingtang10** [comment]
we probably should use Spanned for this

**Comment by santosh-pingle** [comment]
I will take a look, thanks!

**Comment by FikriMilano** [comment]
Thanks @santosh-pingle :D
