### ISSUE TITLE
Image shows different size bug

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2057]
**Describe the bug**
Every time you go back and forth to that page that has an image, it will show you different image size.

**Component**
SDC library

**To Reproduce**
1. Create paginated questionnaire
2. Have this itemMedia extension to a questionnaire.item
```
{
  "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemMedia",
  "valueAttachment": {
    "contentType": "image/png",
    "data": "base64 image",
    "title": "Discussion"
  }
}
```
3. Every time you go back and forth to that page that has an image, it will show different image size

**Expected behavior**
Image size should stay consistent

**Screenshots**
<img src="https://github.com/google/android-fhir/assets/62053304/5d1421b2-e080-418c-9403-3c578780fb1e" width="200" /> <img src="https://github.com/google/android-fhir/assets/62053304/15cdadd3-6bea-4515-9976-9a76ad82ac3b" width="200" />

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**
- Sample Questionnaire https://drive.google.com/file/d/18jGWg5AxCHra488OC2kMo2Q-_1FWa-xR/view?usp=sharing

**Would you like to work on the issue?**
N/A

**Comment by santosh-pingle** [comment]
@FikriMilano 
I will take look, if you have not started working on it yet. thanks!

**Comment by santosh-pingle** [comment]
Could you please attach the questionnaire json

**Comment by FikriMilano** [comment]
I've not started yet, thanks for picking this up @santosh-pingle 
I've added the sample Questionnaire in the ticket description
