### ISSUE TITLE
Need to Support Minimum API level 25

### ISSUE THREAD

**Issue by mahmud6390** [google/android-fhir#2077]
**Describe the Issue**
Many of Health Worker of BRAC are using API level 25 devices.
**Would you like to work on the issue?**
Yes, can we change the minimum API level 25 from 26?

**Comment by omarismail94** [comment]
The reason the Workflow library must be minSDK 26 is due to a run time dependency that requires it:
https://github.com/google/android-fhir/blob/master/workflow/build.gradle.kts#L123-L126

**Comment by jingtang10** [comment]
Looking at James's comment https://github.com/hapifhir/hapi-fhir/pull/3977#issuecomment-1309466453 we might have a chance to actually drop the API level with new HAPI versions.

We should at least give it a go.

**Comment by fredhersch** [comment]
@mahmud6390 For the initial application you are working on you should be able to use just the FHIREngine and Data Capture Libraries. These only require API 24.

Can you confirm this is a viable approach whilst we investigate whether the Workflow Library can be dropped to API 25 - based on the the comment from @jingtang10 

Thanks.

**Comment by mahmud6390** [comment]
@fredhersch  Okey, We are downgread  the API version and let you share the status with other dependency logic.

**Comment by fredhersch** [comment]
> @fredhersch we have tested to run fhircore app without workflow library. but it's showing many dependency error after build. If it's mandatory to use minimum sdk version 26 for FHIR app, we have to go to client with this message to update their devices.

Thanks @mahmud6390 If you are using FHIRCore, can you explore with the Ona team to discuss whether it's possible to build a version without Workflow Libraries? 

As per the thread above, @jingtang10 and @omarismail94 are looking into whether the depedency issues - which is what is driving API 26 requirement - can be resolved

**Comment by pld** [comment]
@mahmud6390 the main reason [opensrp](https://github.com/opensrp/fhircore/) depends on the workflow lib is for $evaluate-measure, which is required for in-app reporting. We'd be open to a PR that wraps all of in-app reporting, including the inclusion of the workflow lib, in a feature-flag that we could control at the flavor level.

But, a future reason for including the workflow lib will be using $apply. We are planning to shift from our $lite (from before $apply existed in the Android FHIR SDK) to $apply, but do not have a confirmed timeline for that. When that happens we would have a much harder, probably non-removable, dependency on the workflow lib.
