### ISSUE TITLE
Fix bug with date and date time widgets where you cannot reenter without moving away

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#208]
User experience : 
1. Open the date widget 
2. Select date
3. Press ok
4. Try to open the date widget again. It Does not open
If some one makes a mistake entering the date/time, the have to enter the time/date and then only then are they able to reopen the date widget. Not sure why this is happening. 

Also Looks like TextInputLayout remains highlighted if you click on a radio button / check box.

_Originally posted by @joiskash in https://github.com/google/android-fhir/pull/206#discussion_r568387420_

**Comment by varunvjha** [comment]
Can I work on this issue?

**Comment by jingtang10** [comment]
Hi Varun - same here - please try the app first and once we're clear on what to do I'll grant you write access! Thanks!

**Comment by joiskash** [comment]
This issue has resurfaced
