### ISSUE TITLE
Load custom questionnaires in the catalog app

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#2081]
**Is your feature request related to a problem? Please describe.**
We used to include sample questionnaires in the catalog app but we found that it was difficult to curate a good set of questionnaires that showcase all the features we have built.

As a result we moved to a new way to organize the app where we list widgets/features/behaviors - this gives a really good indication of the feature coverage we have for the SDC IG.

However, sometimes, developers/authors want to test their own questionnaires and this functionality still needs to be addressed in the catalog app.

**Describe the solution you'd like**
A new screen that is triggered from the top bar, and allows you to load either from a local file, or from a url.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
@santosh-pingle @williamito

**Comment by santosh-pingle** [comment]
I will start looking into it, thanks!

**Comment by santosh-pingle** [comment]
Attaching video to upload questionnaire json from local device storage.

https://github.com/google/android-fhir/assets/86107848/3b00b7d5-185b-4f65-b1ef-558e29db2793
