### ISSUE TITLE
Help icon cropped (a bit on the right side)

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2093]
**Describe the bug**
Right side of the help icon is cropped a little bit.

<img width="430" alt="Screen Shot 2023-07-22 at 18 42 28" src="https://github.com/google/android-fhir/assets/62053304/5d5813ea-b34c-47e2-b13b-308d74861911">

**Component**
SDC library

**To Reproduce**

**Expected behavior**
It should not cropped.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
N/A

**Comment by FikriMilano** [comment]
@shelaghm @f-odhiambo 
good first issue

**Comment by santosh-pingle** [comment]
@khyativyasargus 
Are you working on a UX issue where the alignment of the help icon changes?

**Comment by khyativyasargus** [comment]
> @khyativyasargus Are you working on a UX issue where the alignment of the help icon changes?

No @santosh-pingle I think that PR is on hold for now as @jingtang10  was supposed to think about Image style configuration while using as Image Span. but yes I already had suggestions on that PR to fix this icon crop issue.
https://github.com/google/android-fhir/pull/1984#issuecomment-1525802880 
https://github.com/google/android-fhir/pull/1984#issuecomment-1641718831
