### ISSUE TITLE
Refactor ExpressionEvaluator to evaluate expressions more generically

### ISSUE THREAD

**Issue by MJ1998** [google/android-fhir#2094]
**Describe the Issue**
Same logic in fn:`evaluateExpression` is being used in fn:`evaluateQuestionnaireItemVariableExpression` and fn:`createXFhirQueryFromExpression` as well (post PR [2066](https://github.com/google/android-fhir/pull/2066) merges).  
Additionally the cqfExpression should also support xFhirQuery language [[source](http://build.fhir.org/ig/HL7/sdc/expressions.html#expression-extensions)]. So resolving expressions could become more generic and there need not be different functions like `resolveCqfExpression` and `resolveAnswerExpression`.

**Would you like to work on the issue?**
Yes

**Comment by FikriMilano** [comment]
thanks @MJ1998

**Comment by FikriMilano** [comment]
@f-odhiambo by accident, I'm actually working on this in PR https://github.com/google/android-fhir/pull/2132
