### ISSUE TITLE
Support launchContext for other resource

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2102]
**Is your feature request related to a problem? Please describe.**
We cannot use launchContext other than these following resource: Patient, Encounter, Location, User, ResearchStudy.
It would be useful to allow other resources to use launchContext.

**Describe the solution you'd like**
Allow other resources to use launchContext.
> Launch context information is passed to the QuestionnaireResponse evaluation process by the launching application. It will pass whatever contexts it is aware of. SDC systems SHOULD support all four of the contexts defined in this specification (e.g. Patient, Encounter, Location, User), **_but are free to support others._**

**Describe alternatives you've considered**
N/A

**Additional context**
- Documentation of launchContext is free to use other resources https://build.fhir.org/ig/HL7/sdc/expressions.html#launchContext

**Would you like to work on the issue?**
N/A

**Comment by FikriMilano** [comment]
@f-odhiambo @ellykits

**Comment by FikriMilano** [comment]
good first issue

**Comment by jingtang10** [comment]
@FikriMilano is this a theoretical scenario or are you blocked on launch context being able to support a resource type not listed in the value set?

**Comment by ellykits** [comment]
We would want to use `Group` resource in the launchedContext. Some of our Questionnaires use the `Group` as the subject.
