### ISSUE TITLE
Support PUT in UrlUploadRequest

### ISSUE THREAD

**Issue by omarismail94** [google/android-fhir#2112]
The url passed to  UploadRequest would be different based on the type of request, e.g for put, it would be `resource.resourceType.name/resource.logicalId`

_Originally posted by @aditya-07 in https://github.com/google/android-fhir/pull/2109#discussion_r1281999344_

**Comment by fredhersch** [comment]
@jingtang10 to review progress. Thanks

**Comment by aditya-07** [comment]
In a non Bundle upload setting, the URL to make the api call is different based on the HttpVerb
To create a Patient using POST, the url would be /Patient whereas to create or update with PUT it would be /Patient/<logical-id>. 
The original code didn't take these things into account.

But, with the code refactoring, the issue has been resolved with `UrlRequestGenerator` . 
Functions `postForCreateResource`, `putForCreateResource` and `patchForUpdateResource` create appropriate endpoints for the requests.
