### ISSUE TITLE
Add an option to enable caching in the OkHttp Client used in com.google.android.fhir.sync.remote.RetrofitHttpService

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#2118]
**Is your feature request related to a problem? Please describe.**
OkHttp Client Supports caching but it is off by default . https://square.github.io/okhttp/features/caching/

**Describe the solution you'd like**
Improve the FHIR engine configuration to allow users to configure the OkHttpClient Cache.

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Yes

**Comment by joiskash** [comment]
@jingtang10 and @omarismail94 let me know if this makes sense, I was thinking of adding 

```
Cache(
          directory = File(application.cacheDir, "http_cache"),
          // $0.05 worth of phone storage in 2020
          maxSize = 50L * 1024L * 1024L // 50 MiB
      )
```

as part of the `NetworkConfiguration` data class

**Comment by omarismail94** [comment]
hmm interesting! I can see this being very useful! A few questions:
* What would be cached when we communicate with a FHIR server?
* If a change for a resource that is cached is made on the server, is it always picked up?

**Comment by joiskash** [comment]
https://hapifhir.io/hapi-fhir/docs/server_jpa/configuration.html

As per the documentation above in the "Search Result Caching" Section

> Clients can selectively disable caching for an individual request using the Cache-Control header: 
    Cache-Control: no-cache

And in the Headers sent by OkHttpClient it seems like Cache-Control is off by default by setting the header as shown below.

Cache-Control: no-cache, no-store, max-age=0, must-revalidate

So it seems like we are currently not taking advantage of HAPI search cache.

**Comment by joiskash** [comment]
> hi @joiskash can you send a pr?
Done, https://github.com/google/android-fhir/pull/2144
