### ISSUE TITLE
Store sync progress in a local storage in the engine.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#2119]
**Is your feature request related to a problem? Please describe.**
FhirEngine module should store FhirSyncWorker's progress states in a local storage instead of the WorkManager to provide progress. This is required since work manager isn't designed to be a source of truth for the apps and also the end states differ depending on the worker types.

**Describe the solution you'd like**
Use [DataStore](https://developer.android.com/topic/libraries/architecture/datastore) to store the progress of each worker.

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
I will take look, thanks!

**Comment by santosh-pingle** [comment]
@aditya-07 
I have created a document of the initial implementation design, please review it.

**Comment by omarismail94** [comment]
@santosh-pingle any update on this?

**Comment by santosh-pingle** [comment]
@omarismail94 
Today, I have started implementation as per design.

**Comment by tanany365** [comment]
> I have created a document of the initial implementation design, please review it.

@santosh-pingle , please, can you share the "docuemnt of initial implementation design"?
