### ISSUE TITLE
Workflow: PlanDefinition apply is failing if the library have the same id as the PD

### ISSUE THREAD

**Issue by delcroip** [google/android-fhir#2155]
**Describe the bug**
PlanDefinition apply is failing if the library have the same id as the PD

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**
execute the test "testGoogle" before that commit:

https://github.com/delcroip/android-fhir/commit/5906036afe4fcb160135d3d79a50a51fb64d0a3a

**Expected behavior**
the resource type are different, id should not collide

**Screenshots**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
We will make sure to not have same id between Library and other resource (PD, Activity) so this is not a blocking issue for us

**Would you like to work on the issue?**
No

**Comment by santosh-pingle** [comment]
@divyaramnath-13 @MJ1998 can you please review this issuee?

**Comment by MJ1998** [comment]
This is same as #2490. Closing this.
