### ISSUE TITLE
Handle Questionnaire with item repeats to handle questions which can have more than one answer

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#216]
[Questionnaire.item.repeats](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.repeats) is used to indicate that a particular question / group of questions can have multiple answers. 

> When rendering the questionnaire, it is up to the rendering software whether to render the question text for each answer repetition (i.e. "repeat the question") or to simply allow entry/selection of multiple answers for the question (repeat the answers).
This issue is linked to the following:
- [ ] https://github.com/google/android-fhir/issues/606

**Comment by epicadk** [comment]
can I work on this?

**Comment by jingtang10** [comment]
I believe @joiskash was gonna take this.

**Comment by joiskash** [comment]
Yup that's right :)

**Comment by joiskash** [comment]
There are two main requirements as defined in the [FHIR spec](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.repeats)

1. Multiple answers for questions 
2. Multiple sets of answers for groups.

> If repeats is missing : Items are generally assumed not to repeat unless explicitly specified. Systems SHOULD always populate this value

> If a question is marked as repeats=true, then multiple answers can be provided for the question in the corresponding QuestionnaireResponse. When rendering the questionnaire, it is up to the rendering software whether to render the question text for each answer repetition (i.e. "repeat the question") or to simply allow entry/selection of multiple answers for the question (repeat the answers). Which is most appropriate visually may depend on the type of answer as well as whether there are nested items.

@jingtang10 @fredhersch just wanted your views on the comment above. 

que-6 | Rule | Required and repeat aren't permitted for display items | type!='display' or (required.empty() and repeats.empty())

**Comment by jingtang10** [comment]
I didn't know that a group can be repeated too. Interesting. It makes sense. I guess that could be handled in a separate PR or even in a separate issue if you prefer.

About the text you quoted, I think it depends on type of answer and whether nested items exist. For example, multiple choices questions with checkboxes probably don't need to repeat the question. But questions with nested items might need to have the question repeated to make it clear. We can probably depriorise this case (repeating the question) for now and focus on repeated questions without nested items.

Would this be enough as a starting point? 

@fredhersch we might benefit from some mocks / UX support for this one.

**Comment by joiskash** [comment]
ok got it. Yea that makes sense and is a good starting point for this PR. Thanks @jingtang10

**Comment by joiskash** [comment]
Points to keep in mind  for questionnaire items that can have more than one answer,:

1. The ViewHolder has to initialize correctly i.e. if answers already exist , they should be displayed.

**Comment by joiskash** [comment]
Points to keep in mind  for questionnaire items that can have more than one answer,:

1. The ViewHolder has to initialize correctly i.e. if answers already exist , they should be displayed. 
2. The ViewHolder must be able to add new answers . Each ViewHolder must have its own mechanism to add new answers from UI. In the case of checkbox it is simple but in the case of an integer question with a slider widget it seems more complex. What will this look like? a "plus" icon? 
3. The ViewHolder must be able to remove answers. What will this look like for complex cases? a "dustbin" icon ?

**Comment by jingtang10** [comment]
@fredhersch on 2) and 3).

A plus icon sounds reasonable to me. Rather than a dustbin icon, can we do a minus icon? Simpler. Also can we try to use material icons?

**Comment by joiskash** [comment]
Sure I will use material design.

As discussed with Jing, I will be going ahead with the following design:
I will extract an interface on top of QuestionnaireItemViewHolder. This interface will have functions such as addAnswer, removeAnswer, updateAnswer(?) which will be implemented by each ViewHolderFactory. eg: In the case of check boxes, addAnswer removeAnswer simply means allowing multiple answers to be checked and unchecked. For more complex examples like edit text we will have to follow some UI pattern as described above.
The implications of this will be each type of view holder factory will have to handle its own case of rendering UI to allow multiple answers. The questionnaireItem.repeats will be used to check if multiple answers are allowed.

**Comment by jingtang10** [comment]
@fredhersch how is "nested items" and "multiple items selected" different from the other items?

**Comment by jingtang10** [comment]
- [ ] Set of checkboxes
- [ ] Multi-select dropdown with checkboxes
- [ ] Edit text
- [ ] Groups (of questions)

**Comment by jingtang10** [comment]
I think the most important of these is the set of checkboxes. The rest will be good to have but probably not critical (yet). But this issue should be kept open for record keeping.

**Comment by fredhersch** [comment]
I think adding multi-select dropdown with checkboxes is a priority given the mobile surface we are supporting. The rest can be nice to haves for now.
cc: @joiskash @jingtang10

**Comment by jingtang10** [comment]
Closing this issue since any work is tracked in sub-items: #606
