### ISSUE TITLE
ResourceMapper set initial property of questionnaire on initial expression evaluation

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#2161]
**Describe the bug**
ResourceMapper class at com.google.android.fhir.datacapture.mapping.ResourceMapper#populateInitialValue L260, set the questionnaire-item property `initial` to evaluated values of expression which is not the right behavior and causes [Rule](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.initial) fail.

**Component**
SDC library

**Comment by jingtang10** [comment]
@santosh-pingle

**Comment by f-odhiambo** [comment]
@jingtang10 I think we cal close this

**Comment by MJ1998** [comment]
Thanks @f-odhiambo
