### ISSUE TITLE
Support fhirpath supplement %questionnaire and %qItem literals in expression evaluator

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#2163]
**Is your feature request related to a problem? Please describe.**
To make question fhirpath dynamic and have current questionnaire and item available expression, we need to support fhirpath supplement `%questionnaire`, and `%qItem` literal. This allow to get current questionnaire and item into fhirpath expressions on questionnaire items when doing evaluation. Details for spec defined here https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements . 

**Describe the solution you'd like**
Add both literals `%questionnaire` and `%qItem` in com.google.android.fhir.datacapture.fhirpath.ExpressionEvaluator#evaluateExpression and ensure that expression evaluation is centralized. Make sure to double check evaluation in enableExpression, and answerExpression if those are implementing their own evaluation instead of using this centralized method.

Linked issue #1849

**Comment by jingtang10** [comment]
not sure this is a high priority right now, haven't had any real usecase from any implementers.

should not be difficult to implement either given our existing code structure.

**Comment by f-odhiambo** [comment]
@jingtang10 should we close this ticket given we have a fix on PR #2346
