### ISSUE TITLE
Need updates of the CQF libs

### ISSUE THREAD

**Issue by delcroip** [google/android-fhir#2172]
**Describe the bug**
ActivityDefinition/$Apply is not working well (via planDefinition/$apply)
- resources cannot be managed by DynamicValue
- CQL not supported in DynamicValue

**Component**
Evaluator

**To Reproduce**

**Expected behavior**
should be able to add contained and inputs on Task/Medication Request

**Additional context**
Major updates were made on the CQF library, those upgrade were tested successfully on the CQF-Ruler Docker snapshot `alphora/cqf-ruler:0.14.2-SNAPSHOT` (it creates a medication request )

**Comment by omarismail94** [comment]
This change will not be as simple as changing the versions of the cqf libraries in the Dependencies file. The `engine` and `evaluator` belong to the `org.opencds.cqf.cql` group Id. However, the group id has been deprecated and now all the Cql libraries reside under the `info.cqframework` group. Coupled with the API changes, going from 2.x to 3.x will take time

**Comment by delcroip** [comment]
thanks for the update

**Comment by fredhersch** [comment]
@jingtang10 @brynrhodes Can we define the work for @vitorpamplona to complete to resolve this issue here.

**Comment by jingtang10** [comment]
the proxy repository should actually be able to query either the content repostiory for knowledge artifacts or the data repository for patient data. so this actually maps to fhir engine and knowledge manager quite well. but it might also fall-through, which is what we want.

**Comment by jingtang10** [comment]
from bryn: https://github.com/cqframework/pd-apply

**Comment by lukeaduncan** [comment]
Here is a bundle of files that I was able to get working.  From https://github.com/WorldHealthOrganization/smart-immunizations/tree/cleanup
[measlesApplyTest.json.txt](https://github.com/google/android-fhir/files/12796216/measlesApplyTest.json.txt)

**Comment by jingtang10** [comment]
I think this has been addressed in #2637
