### ISSUE TITLE
Write tests for "click" in view holder factories

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#218]
"click" event has to be tested for widgets like the date picker, drop down etc.

**Comment by joiskash** [comment]
Initially reported by @jingtang10 [here](https://github.com/google/android-fhir/pull/209#discussion_r568944706)

**Comment by s-ayush2903** [comment]
How exactly is the "click" supposed to be unit-tested? If it were an instrumentation test then we could verify the nature of click via seeing if the corresponding dropdown occurs or not, but how is it going to be unit tested? Can you please throw some light on it, it would be very kind of you, thanks

**Comment by jingtang10** [comment]
Thanks @s-ayush2903. I've updated the title of the issue. Will you be interested in taking this issue?

**Comment by s-ayush2903** [comment]
Yes, definitely. But I have a question, our automated testing architecture would be a/c to what, I mean we would be using espresso or UI automator along with robot pattern?

**Comment by jingtang10** [comment]
Yes I think we would be using espresso and/or UI automator. Will you be able to do some research and create a draft PR please?

**Comment by s-ayush2903** [comment]
Yes

**Comment by jingtang10** [comment]
Please don't wait as that PR hasn't been approved yet. Also it's only a reformatting PR so although it will cause conflicts it should be easy to resolve. If you're rebasing please just make sure that you're using the version on your own branch and ignore the master's HEAD. that way the only thing you have to do after rebasing is to rerun `./gradlew spotlessApply`. I hope this makes sense.

**Comment by jingtang10** [comment]
is there more progress on this? thanks!

**Comment by s-ayush2903** [comment]
Moving it up in my list :+1:

**Comment by jingtang10** [comment]
> "click" event has to be tested for widgets like the date picker, drop down etc.

more work to address these issues in the first comment.

**Comment by jingtang10** [comment]
we need to test the click event for the date picker and date time picker still.

**Comment by Anshul-9923** [comment]
@jingtang10 I would like to work on 2 remaining tasks of https://github.com/google/android-fhir/issues/107. Can you please assign it to me?

**Comment by jingtang10** [comment]
Sorry. That issue is obsolete.

**Comment by Anshul-9923** [comment]
Ok @jingtang10 , Sir can you assign me this issue?

**Comment by vj-codes** [comment]
@Tarun-Bhardwaj hey is this issue still valid?

**Comment by omarismail94** [comment]
Just cleaning things up. Closing this as our androidTests inclide clicking
