### ISSUE TITLE
Set up codeql

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#2185]
**Describe the Issue**
Set up codeql: https://codeql.github.com/

**Would you like to work on the issue?**
no thanks.

**Comment by vorburger** [comment]
@jingtang10 @omarismail94 would you welcome it if I had a go at a PR for this? Or is someone else (un-assigned) already working on it?

**Comment by jingtang10** [comment]
> @jingtang10 @omarismail94 would you welcome it if I had a go at a PR for this? Or is someone else (un-assigned) already working on it?

Feel free to take a look please. Perhaps before committing time to making the script work, a bit of analysis on the benefits here first might be most useful.

I doubt there will be much downside to setting this up. But would like to understand how much are the benefits to justify us spending time.

Thanks 🙏

**Comment by vorburger** [comment]
@jingtang10 the advantage is some vulnerability scanning. I have this on a several other repos. For Kotlin it's apparently still more limited than Java, but still already available. For me to set it up you, you would have to grant me full Collaborator privilege, so that I can get access to and make changes in the _Settings_ of the repo.

**Comment by jingtang10** [comment]
Sounds good. @vorburger sent you an invite. by the way please check out @williamito 's PR which is linked here.

@williamito fyi michael is going to help on this one.

**Comment by vorburger** [comment]
Thanks, invite accepted, and _You now have view access to the google/android-fhir repository._ but I still cannot access the _Settings_ tab of this repo. @jingtang10 can you? Or is that Org Admins only?

**Comment by vorburger** [comment]
@jingtang10 thanks for helping to get the right access level, I have it now. FYI this is what it looks like when set up (from another project):

![screencapture-github-MariaDB4j-MariaDB4j-security-code-scanning-2023-09-25-12_24_41](https://github.com/google/android-fhir/assets/298598/8f2d4425-2bf6-4fba-97e4-2c13b87b9d75)

**Comment by vorburger** [comment]
I have clicked _Enable_ on _CodeQL analysis_ [here](https://github.com/google/android-fhir/settings/security_analysis) and it says _Setting Up,_ with a [log here](https://github.com/google/android-fhir/actions/runs/6306337701) ... I'll check back if that worked, or why not, some other time.

**Comment by vorburger** [comment]
> I'll check back if that worked, or why not, some other time.

The "`Default`" configuration where (supposedly...) _CodeQL will automatically find the best configuration for your repository._ doesn't quite work. I have analyzed the error log, and it appear something Java 11 vs 17 version confusion related. Maybe it would be possible to fix the Gradle configuration of this project? But the easier solution is likely to use an "`Advanced`" set-up to _Customize your CodeQL configuration via a YAML file checked into the repository_ instead - I'll raise a PR for that, and we'll see if that works.

**Comment by vorburger** [comment]
Initial attempt #2204 didn't work, it fails with: _Error: Encountered a fatal error while running "/opt/hostedtoolcache/CodeQL/2.14.5/x64/codeql/codeql database finalize --finalize-dataset --threads=64 --ram=244226 /home/runner/work/_temp/codeql_databases/java". Exit code was 32 and error was: CodeQL detected code written in Java/Kotlin but could not process any of it. Review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build_

Second attempt #2205 fails with `TaskSelectionException: Task 'testClasses' not found in root project 'android-fhir' and its subprojects.`; I'll see if I can figure out how to fix that.

**Comment by vorburger** [comment]
@jingtang10 @omarismail94 looks like this is now working! Check out https://github.com/google/android-fhir/security/code-scanning.
