### ISSUE TITLE
[Bug] Failing execution of $evaluate_measure API  for MeasureReporting

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#2187]
Based on the latest release artifacts listed below we are facing the following listed issues 
1. [Workflow Library 0.1.0-alpha03](https://github.com/google/android-fhir/releases/tag/workflow-0.1.0-alpha03) - Latest version in test 
2. [FHIR Engine 0.1.0-beta04](https://github.com/google/android-fhir/releases/tag/engine-0.1.0-beta04) - Not used in the latest release 
3. [FHIR engine 0.1.0 beta03](https://github.com/google/android-fhir/releases/tag/engine-0.1.0-beta03) - Used in the latest release but outdated

**Detected issues** 
1. Engine module class search returns List<SearchResult<R>> -> https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt#L59
4. Workflow module and CQL libs using old release version search expects List<Resource> -> https://github.com/google/android-fhir/blob/master/workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineDal.kt#L79
5. Workflow gradle using engine https://github.com/google/android-fhir/blob/master/workflow/build.gradle.kts#L136 has old dependency https://github.com/google/android-fhir/blob/master/buildSrc/src/main/kotlin/Dependencies.kt#L260

**Comment by jingtang10** [comment]
looking at this today

**Comment by jingtang10** [comment]
We have just pushed knowledge manager 0.1.0 alpha03 and workflow library 0.1.0 alpha04. @f-odhiambo @dubdabasoduba @roywanyaga @ellykits fyi

**Comment by jingtang10** [comment]
the published versions of the libraries should have consistent dependencies now
