### ISSUE TITLE
Demo app reskinning. 

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#2188]
**Describe the bug**
Update visual appearance of demo app.
Refer below link for reference
https://github.com/google/fhir-app-examples/tree/main/configurablecare

**Component**
reference app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Registered Patients Screen

1. Change the app bar background to match the rest of the screen (white).
2. Remove the margin at the start and end of the divider.
3. Align the patient contents to the left and reduce the margin at the start.
4. Reduce the margin at the start for the number of patients and align this text with the patient list.



 

<img width="437" alt="Screenshot 2023-09-25 at 10 03 46 AM" src="https://github.com/google/android-fhir/assets/86107848/1b4cd877-51df-4ced-83e9-e09c3c2b4c59">

**Comment by santosh-pingle** [comment]
Patient Card Screen : 

1. Round the corners of the complete survey button.
2. Remove the left margin of the card.
3. Update the background of the patient card.
4. Remove the right margin of the card.
5. Adjust the app bar background to match the screen's background (white).

<img width="403" alt="Screenshot 2023-09-25 at 10 25 02 AM" src="https://github.com/google/android-fhir/assets/86107848/1f24a4bb-7d7c-402b-b69f-9b10b4b9b9e1">

**Comment by santosh-pingle** [comment]
Edit Patient  : 

1. Adjust the app bar background to match the screen's background (white).
<img width="396" alt="Screenshot 2023-09-25 at 12 00 42 PM" src="https://github.com/google/android-fhir/assets/86107848/8956e776-2220-4c6c-b170-ef1eb065d156">

**Comment by santosh-pingle** [comment]
Add Patient : 

1. Adjust the app bar background to match the screen's background (white).
<img width="405" alt="Screenshot 2023-09-25 at 12 06 55 PM" src="https://github.com/google/android-fhir/assets/86107848/3c062be6-0f2f-4550-8464-9a540eba0304">

**Comment by santosh-pingle** [comment]
Action item : 
Migrate from material 2 to material 3. 

I will start with this.

**Comment by MJ1998** [comment]
Do you think we should also add a menu / home page like this ?
<img width="292" alt="Screenshot 2023-09-29 at 2 14 11 PM" src="https://github.com/google/android-fhir/assets/22965002/cdd49ae3-5435-48f6-a472-79ba3b7f4482">

**Comment by MJ1998** [comment]
Regarding the 3rd issue on Registered Patients Screen, the left blank portion we see is for the patient status based on the risk probability. Currently no RiskAssessment resources are synced hence no statusView is assigned and the view is blank. Do we wanna remove the risk-to-status binding and relevant codes as well ?
[Code Link](https://github.com/google/android-fhir/blob/b860a2993f5afc14882bccd8d7147d30dd028529/demo/src/main/java/com/google/android/fhir/demo/PatientItemViewHolder.kt#L45)

**Comment by santosh-pingle** [comment]
> Do you think we should also add a menu / home page something like this (but without the Implementation Guide box)? <img alt="Screenshot 2023-09-29 at 2 14 11 PM" width="292" src="https://user-images.githubusercontent.com/22965002/271519022-cdd49ae3-5435-48f6-a472-79ba3b7f4482.png">

thanks @MJ1998 

I think it might be a good idea to add a dashboard. What are your thoughts?@shelaghm @jingtang10

**Comment by santosh-pingle** [comment]
> Regarding the 3rd issue on Registered Patients Screen, the left blank portion we see is for the patient status based on the risk probability. Currently no RiskAssessment resources are synced hence no statusView is assigned and the view is blank. Do we wanna remove the risk-to-status binding and relevant codes as well ? [Code Link](https://github.com/google/android-fhir/blob/b860a2993f5afc14882bccd8d7147d30dd028529/demo/src/main/java/com/google/android/fhir/demo/PatientItemViewHolder.kt#L45)

yes.
It might be a good idea to align the risk assessment status in such a way that it doesn't appear as a blank space. What are your thoughts on this? @shelaghm @jingtang10

**Comment by jingtang10** [comment]
can you take a look at this @santosh-pingle https://github.com/google/fhir-app-examples/tree/main/configurablecare and try to match the style there in the demo app?
