### ISSUE TITLE
Clear all action on Questionnaire

### ISSUE THREAD

**Issue by ellykits** [google/android-fhir#2221]
**Is your feature request related to a problem? Please describe.**
We'd like to reset all the answered fields in the questionnaires via a `Clear all` action.

**Describe the solution you'd like**

The "Clear all" function will remove all the answer items for the "current" QuestionnaireResponse when the questionnaire is being used actively.

**Describe alternatives you've considered**
None

**Additional context**
In order to filter the content of our registers (list of resources) we opted to re-use the UI rendered via Questionnaires instead of implementing custom UI to capture the content for the filter. As part of the requirement, a "Clear all" action is required to reset all the data filter fields".  

See the screenshot below, the Questionnaire is the second screen in the pic.

![image (1)](https://github.com/google/android-fhir/assets/26865532/0287a73d-6efd-4383-a199-e868f6aa0eac)

**Would you like to work on the issue?**
Yes

**Comment by santosh-pingle** [comment]
@ellykits 
Can you please create separate issue to configure Submit Button text?

**Comment by ellykits** [comment]
@santosh-pingle Done here https://github.com/google/android-fhir/issues/2239

**Comment by santosh-pingle** [comment]
I will work on this issue.

**Comment by fredhersch** [comment]
Thanks @santosh-pingle I have assiged you.

**Comment by santosh-pingle** [comment]
@ellykits @jingtang10 
Could you please confirm if the 'Clear All' button is associated with the application's user interface and not linked specifically to the questionnaire? We're mainly interested in ensuring we support the functionality or API required to clear the questionnaire responses.

**Comment by ellykits** [comment]
The request is to support the API to allow clearing of Questionnaire answers. The UI shared was an illustration of how we plan to use it.

**Comment by jingtang10** [comment]
@ellykits the screenshot in your issue description is about filtering and not clearing answers. can you attach the right screenshot please?

**Comment by jingtang10** [comment]
i don't think it's clear to us right now if the clear all button should be in the questionnaire or outside the questionnaire. if we consider the submit button we have, we actually have one version inside the questionnaire controlled by a setting but also have the api so that if there's a button outside the questionnaire the application can still call the api... should we do the same for clear all?

**Comment by jingtang10** [comment]
the only question about it being inside is that i don't know where it should be in the questionnaire... the bottom navigation is already busy with previous, next and submit buttons. so maybe we can start from building the clearAll api...

**Comment by jingtang10** [comment]
@ellykits please can you comment on my above points? thx

@rowo fyi

**Comment by ellykits** [comment]
@jingtang10 We need the **Clear All** API which exposes the functionality to the implementers. No UI changes is necessary.

**Comment by ellykits** [comment]
In the issue description, the screenshot with the 'Clear All' button is in the middle. I provided the images for context . And as you can see, we implemented the button UI in our code.

**Comment by ellykits** [comment]
I'm currently on leave. Kindly follow up with @dubdabasoduba or Allan from Ona for any clarifications. Thanks.

**Comment by FikriMilano** [comment]
@dubdabasoduba @allan-on 
Can you clarify how are we going to trigger the clearAll() functionality with the exposed API? I'm assuming it's from outside the questionnaire.

**Comment by allan-on** [comment]
Hi @FikriMilano @jingtang10 
We have the "**Clear All**" button already defined on our end (as part of our `QuestionnaireActivity`) The button's visibility is configurable. 

![filter_questionnaire](https://github.com/google/android-fhir/assets/16164649/cc3068cf-41db-4a55-9b00-b5d792574fb2)

We'll make the call to the API to clear all `QuestionnaireResponse` items from our listener implementation (in the Activity).  

Hence EllyKits' comment 👇🏾 

> @jingtang10 We need the **Clear All** API which exposes the functionality to the implementers. No UI changes is necessary.
