### ISSUE TITLE
Allow modification of Questionnaire submit action button text via configuration

### ISSUE THREAD

**Issue by ellykits** [google/android-fhir#2239]
**Is your feature request related to a problem? Please describe.**
As part of the enhancement, we'd like to set the text for the submit action button via configuration.

**Describe the solution you'd like**
Expose a function/property etc. to allow modification of the submit action button text.

**Describe alternatives you've considered**
For the set save button text, we can `findTheViewById` and apply the text as desired but this will be subject to code changes.

**Additional context**
In order to filter the content of our registers (list of resources) we opted to re-use the UI rendered via Questionnaires instead of implementing custom UI to capture the content for the filter. As part of the requirement a configuration to change the text for the submit action to "APPLY FILTERS" is needed.  

See the screenshot below, the Questionnaire is the second screen in the pic.

![image (1)](https://github.com/google/android-fhir/assets/26865532/0287a73d-6efd-4383-a199-e868f6aa0eac)

**Would you like to work on the issue?**
Yes

**Comment by MJ1998** [comment]
The app bar is not controlled by the QuestionnaireFragment. You can probably achieve this by customizing app bar in your application for this particular fragment where you are hosting the QuestionnaireFragment as its child fragment. Example is [this older version of ScreenerFragment](https://github.com/google/android-fhir/blob/225ff1dadc853fd9868086509e6657855691d7b6/reference/src/main/java/com/google/android/fhir/reference/ScreenerFragment.kt#L43-L68)

Or am I missing something ?

**Comment by DebbieArita** [comment]
@MJ1998 For this issue, we're trying to make the submit action button text on the QuestionnaireFragment configurable. Reference the second screen whose action button reads 'APPLY FILTERS'. There are cases where I want to be able to override the default 'SUBMIT' text and have any other text on the action button. The app bar issue will be addressed [here](https://github.com/google/android-fhir/issues/2221). I hope that clarifies.

**Comment by f-odhiambo** [comment]
@DebbieArita has an open PR on this
