### ISSUE TITLE
Performance Issue: Slow FHIR Package Loading with SimpleWorkerContext

### ISSUE THREAD

**Issue by nsabale7** [google/android-fhir#2240]
**Describe the bug**
I have encountered a performance problem with the loading of a FHIR package using `SimpleWorkerContext`. It approximately takes couple of minutes to load a zipped package of size 4MB. 

`
val contextR4 = SimpleWorkerContext.fromPackage(
      NpmPackage.fromPackage(
        assets.open("package.r4.tgz")
      ),true).apply {
      setExpansionProfile(Parameters())
      isCanRunWithoutTerminology = true
    }
`

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 13
 - RAM : 8GB
 
 @jingtang10 @fredhersch

**Comment by jingtang10** [comment]
@nsabale7 @joiskash @divyaramnath-13 @delcroip @dubdabasoduba @roywanyaga and I briefly discussed this.

On one hand, we should try to contribute to upstream libs and use the NpmPackageManager in HAPI, and make sure that it can be performant enough on Android. On the other hand, we have built the Knowledge Manager library on Android which has significant functionality overlap and is intended to make using NPM packages (and individual knowledge resources) easier on Android.

I think going forward we have two approahces:

1. we could try to implement the IWorkerContext using knowledge manager, and essentially for knowledge manager to provide a worker context to the SDC library to use. This way, as an Android developer, your interation with npm packages should all go through knowledge manager.
2. another approach is actually rewrite knowledge manager using the worker context as its in-memory model. but we really need to figure out why the context is running slowly on android before we can commit to this.

i feel like kashyap's pr https://github.com/google/android-fhir/pull/2280 is a good step towards 1.

for 2, we will need to do some profiling in android studio. @omarismail94 has some experience with this and may be able to help. but i'm not sure of his bandwidth. so @nsabale7 and others please feel free to take this on.

@brynrhodes fyi

**Comment by jingtang10** [comment]
i should also add 1 and 2 in my above comment are not mutually exclusive - we can do both.

1 is about providing a simpler api to developers. 2 is about knowledge manager's internal implementation detail.

**Comment by MJ1998** [comment]
With merging of #2448 I guess we can close this ?
@nsabale7  ?

**Comment by MJ1998** [comment]
@dubdabasoduba Tagged you as well

**Comment by dubdabasoduba** [comment]
@MJ1998 I think this can be closed for now. @nsabale7 already worked fixed the loading of context worker using KM.
