### ISSUE TITLE
Questions which have multiline text cannot be read completely in the dropdown and edittext widget

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#226]
Long questions cannot be read completely.

eg: "How much pain is the patient in,please select any of the options below?"

Appears as "How much pain is the patient in,please select any..."

Originally reported by @kumaakh

**Comment by jingtang10** [comment]
@joiskash can you add a screenshot for this?

I think the solution is that we need to use a separate view (text view) for the question text. the hint field in the text input layout itself is too small. @fredhersch for input.

**Comment by joiskash** [comment]
![Screenshot_20210209-164420.jpg](https://user-images.githubusercontent.com/48797364/107507298-5ee92880-6bc5-11eb-9752-d9acd3c910f4.jpg)

**Comment by jingtang10** [comment]
I don't think this is blocking the alpha01. @jtournier23 for comment. @joiskash does this block you from testing this lib?

**Comment by joiskash** [comment]
It does not block us from testing the library but it surely is a high priority task .

**Comment by jingtang10** [comment]
@MuhammadSalman-7214 can you take a look at this please?

**Comment by MuhammadSalman-7214** [comment]
We can also set hint to autoCompleteTextView rather than textInputLayout, because setting hint to autoCompleteTextView shows text completely no matter how long it is

**Comment by MuhammadSalman-7214** [comment]
Me and @jingtang10 decided to go with TextView as a Question and then the autoCompleteTextView below the question TextView for selecting the answer option. This way question will always be there with any length. @joiskash

**Comment by joiskash** [comment]
> 
> 
> Me and @jingtang10 decided to go with TextView as a Question and then the autoCompleteTextView below the question TextView for selecting the answer option. This way question will always be there with any length. @joiskash

Cool makes sense to me :)

**Comment by MuhammadSalman-7214** [comment]
great then

**Comment by jingtang10** [comment]
Thanks both. @MuhammadSalman-7214 will you please make sure to post a screenshot here of your prototype before sending out PR? Cheers.

**Comment by MuhammadSalman-7214** [comment]
your welcome, sure
![Screenshot_1614003197](https://user-images.githubusercontent.com/64642723/108720221-5dfbb380-7542-11eb-9403-a0e5fddc001d.png)

**Comment by jingtang10** [comment]
thanks @MuhammadSalman-7214 for your work!

can you do the same for the edit text widget and then we can close this issue.

**Comment by MuhammadSalman-7214** [comment]
your welcome @jingtang10, can you please tell me what exactly is required for edit text widget?

**Comment by jingtang10** [comment]
See the below example for date (and same for date+time) and edit text widgets

![C7n5X2UcEckhqBB](https://user-images.githubusercontent.com/28757340/108997710-d58f2700-7697-11eb-9725-79b3b13500a2.png)

**Comment by MuhammadSalman-7214** [comment]
For date and edit text widgets, its done, but for date + time widgets, we are setting them in a horizontal linear layout which first takes date and then time, so do we want to change here as well as I am not seeing any example of date+time in the application @jingtang10 ?

**Comment by joiskash** [comment]
@MuhammadSalman-7214 There is an example, check the second questionnaire, the Neonate record . After you select an option for the Vitamin K given question, a new question will show up of type date+time

**Comment by MuhammadSalman-7214** [comment]
Thanks @joikash

**Comment by MuhammadSalman-7214** [comment]
Thanks @joikash
