### ISSUE TITLE
Intermittent patches are being updated.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#2271]
**Describe the bug**

On the Device:

1. Disable the device's internet connection.
   
2. Update the patient's phone number on the device.
   
3. Save the changes on the device.

On the Test Server:

4. Access the same patient record for which the phone number was updated on the device.

5. Update the patient's phone number with a different value on the server.

6. Save the patient record on the server.

Back on the Device:

7. Re-enable the internet connection on the device.

8. Trigger a manual synchronization between the device and the server.

Outcome:

9. Check whether the changes made on the device and the server are matching or not. 

Expectation:

10. The expectation is that the updated phone number for the patient on the device and server should be in sync, and both should show the same, updated version of the patient record.

**Component**
Core library, 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4, Emulator
 - Android version: android 12
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
instance 1 : (https://github.com/google/android-fhir/files/12925199/fhir17_12-8.txt)

instance 2 : [fhir17_11_46.txt](https://github.com/google/android-fhir/files/12925203/fhir17_11_46.txt)

**Comment by jingtang10** [comment]
@santosh-pingle the result phone number depends on the conflict resolution strategy right? i think by default the device would download the change, and then try to patch the local change on top before uploading again, so the phone number should be the one you input on the device?

**Comment by santosh-pingle** [comment]
new instance : [fhir_17_3_43.txt](https://github.com/google/android-fhir/files/12927434/fhir_17_3_43.txt)
