### ISSUE TITLE
Questionnaire submit crash

### ISSUE THREAD

**Issue by ageryck** [google/android-fhir#2291]
**Describe the bug**
The questionnaire submit validation action provides two options to either fix incorrect fields or submit anyway, should one hit submit anyway the app enters into the wait of death(hangs indefinitely)

**Component**
SDC library

**To Reproduce**
See the attached screen record

**Expected behavior**
What was the initial concept behind the `submit anyway`? If there' need to keep it then we need to handle its persistence in the application. Alternatively, can this be configurable for those who want to implement draft questionnaires?

**Screenshots**

https://github.com/google/android-fhir/assets/23252704/2c3fe403-00ce-42f7-b892-a54b41fb4fff

**Smartphone (please complete the following information):**
 - Device: Xiomi - Redmi Note 9 Pro
 - Android version: 10 QKQ1.191215

**Would you like to work on the issue?**
No

**Comment by jingtang10** [comment]
@ageryck, `submit anyway` should trigger the code here https://github.com/google/android-fhir/blob/aa6b233221e6a38aaed765c42bacd1a847049be4/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt#L256 which will set the fragment result.

So the fact that the subsequent dialog is hanging seems to be a fhircore issue instead.

Closing this issue for now. Please feel free to reopen Ager if this is indeed an SDK issue and not a fhircore issue.
