### ISSUE TITLE
Enable cqf expressions to evaluate variables on questionnaire extensions

### ISSUE THREAD

**Issue by ageryck** [google/android-fhir#2292]
**Is your feature request related to a problem? Please describe.**
The current problem is the inability to pass a saved `date value` to be used as a questionnaire `date picker validation` value i.e. using the dob as a minimum value to capture any patient-related services like immunization. This requires passing the already saved `dob` to used a `min date` on the questionnaire date picker. The cqf currently fails to evaluate the variable passed. 

**Describe the solution you'd like**
Allow the cqf expression to access and evaluate expressions for parameters stored/passed in the launch context

**Describe alternatives you've considered**
prepopulating the questionnaire with the dob value and passing that as an express dob value

**Additional context**
The extension below currently works for max value validation, this feature should allow the use of the same extension or min value validation
```
{
              "url": "http://hl7.org/fhir/StructureDefinition/maxValue",
              "valueDate": {
                "extension": [
                  {
                    "url": "http://hl7.org/fhir/StructureDefinition/cqf-calculatedValue",
                    "valueExpression": {
                      "language": "text/fhirpath",
                      "expression": "today()"
                    }
                  }
                ]
              }
            }
```

**Would you like to work on the issue?**
Yes

**Comment by FikriMilano** [comment]
just to clarify.
we'll be passing declared variables, launchContexts, %resource, and other FHIRPath context variable when we evaluate the cqf-calculated-value for both min and max validator
