### ISSUE TITLE
Kokoro: Build and Device Tests Expected — Waiting for status to be reported

### ISSUE THREAD

**Issue by vorburger** [google/android-fhir#2300]
PRs regularly (e.g. #2283 & #2285) appear to get stuck in _"Some checks haven’t completed yet"_ due to:

_Kokoro: Build and Device Tests Expected — Waiting for status to be reported_

@jingtang10 @omarismail94 do you happen to know what's going on here?

PS: Is our "workaround" for this to add that `kokoro:force-run` label?

**Comment by jingtang10** [comment]
yeah i normally add the force run labe... :(

**Comment by vorburger** [comment]
N/A with #2304.
