### ISSUE TITLE
Too many Email Notifications since Committers (Maintainers) seem to automagically get added as reviewers now?

### ISSUE THREAD

**Issue by vorburger** [google/android-fhir#2320]
It "feels" to me like I may be getting too many 💌  Email Notifications from this repository... 

Some are normal and expected, as I contribute (more), GitHub notifies me about Comment - great!

But there are also notifications which I do not expect to receive, and typically don't get on other open source projects... as far as I can tell so far, they may break down into 1-2 different cases:

1. There seems to be something (new?) which automagically decides that I could be a suitable reviewer on certain PRs? An example is #2319 which says _"DebbieArita requested a review from vorburger (assigned from google/android-fhir)"_ - was that an intentional recent repo Settings configuration change? Or something new that's https://github.com/google wide? I'm not sure I'm a huge fan of that... 😃 

2. I am not 100% sure if there is something else, slightly different from above, where thinks that GitHub may think it should send me email for PRs where the `android-fhir` _Group_ (not me individually) is added as Reviewer; but I don't have an example of that yet. 

@jingtang10 my I assign this to you to look into? If you want I can also help to figure this out. Reading https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team, it looks like that's something that we should be able to tweak on the _Settings_ tab on https://github.com/orgs/google/teams/android-fhir, but I don't seem to have access to that - do you?

If this is less of a "technical tool configuration" and more of a general "process" kind of discussion, I'm also happy to chat about how the project can best go about this, based on what I have seen in other open source communities. One feedback I would have is to perhaps establish a clearer sub-group of active general reviewers (of which e.g. I myself am not sure I could be a part of, both time and current skill and codebase familiarity wise), and then a clear process of roles and responsibilities and "cadence".

PS: If this can't be fixed by project configuration I would have to address it with personal email filtering; but if possible, it seems better to me to fix this in the project, and benefit other Committers (Maintainers) as well.

**Comment by vorburger** [comment]
> GitHub sends me email for PRs where the android-fhir Group (not me individually) is added as Reviewer

an example of that is e.g. #2319

**Comment by vorburger** [comment]
I'm also getting pop-up notifications from some (work internal, I think) tool e.g. for 2319, because, even though I (manually, which I shouldn't have to) clicked _Unsubscribe_ on it, and it says _You’re not receiving notifications from this thread._ on its Notifications, on top it still says _"Xyz requested your review on this pull request."_ so that notification tool probably still think it should tell me e.g. when the PR is updated with new changes.

**Comment by vorburger** [comment]
This is now annoying (interrupting) me enough that I want to fix it! I have figured out that it's because of https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners, ergo specifically the mention of `@google/android-fhir` added in #2001 to https://github.com/google/android-fhir/blob/63151b5f1fdb6c1ad843d1421ea354b84fb51378/CODEOWNERS#L2

This means that the current 11 members of https://github.com/orgs/google/teams/android-fhir are all pinged to review PRs. But the reality is that those 11 do not. There appears to be a separate https://github.com/orgs/google/teams/android-fhir-reviewers - let's use that one!

#2536 raised to proposed to change it.

**Comment by jingtang10** [comment]
thanks @vorburger for raising this and @elegantmush for helping.

so just a little bit of background - the auto sync'ed team (android-fhir-1) is synced from google internal teams - so i think it still makes sense to keep using that but also makes sense to use the android-fhir team for wider community engagement. i'm ok with whatever that's the easiest without creating too much process - so if the current setup works, we don't have to make huge changes (and nothing is perfect). but i like the idea of creating a review group so it can be managed easily without having to change the reviewer file all the time.

**Comment by jingtang10** [comment]
@ktarasenko is revisiting this.

fyi @vorburger i'm goign to remove you from the team android-fhir-reviewers
