### ISSUE TITLE
Exception with the Flow while using Obfuscation and Shrink Resource in release build

### ISSUE THREAD

**Issue by Naveens1605** [google/android-fhir#2327]
**Describe the Issue**
While running app with Obfuscation and Shrinking Resource. I'm getting following error.

```
Work [ id=*unique_work_id*, tags={ *classname* } ] failed because it threw an exception/error
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Flow exception transparency is violated:
Previous 'emit' call has thrown exception ca.uhn.fhir.context.ConfigurationException: HAPI-1753: Unable to initialize StAX - XML processing is disabled, but then emission attempt of value 'Failure(syncError=ResourceSyncException(resourceType=Patient, exception=ca.uhn.fhir.context.ConfigurationException: HAPI-1753: Unable to initialize StAX - XML processing is disabled))' has been detected.
Emissions from 'catch' blocks are prohibited in order to avoid unspecified behaviour, 'Flow.catch' operator can be used instead.
For a more detailed explanation, please refer to Flow documentation.
```

Everyhting working fine in Debug Mode.

Please provide any missing pro-guard rule
[Reference for Pro-guard used](https://github.com/google/android-fhir/issues/1901)

@aditya-07 @jingtang10 @FikriMilano 

Thanks in Advance.

**Would you like to work on the issue?**
No.

**Comment by FikriMilano** [comment]
@khyativyasargus can you check this issue? I think you were having similar issue in the past, was that resolved?

**Comment by santosh-pingle** [comment]
@khyativyasargus can you please provide your input on it?

**Comment by santosh-pingle** [comment]
@aditya-07

**Comment by khyativyasargus** [comment]
Hi @FikriMilano @santosh-pingle , at that time we tried the pro-guard rules suggested/added for demo app, but some other library in emcare was conflicting so we dropped to shrink apk at that time and decided to do it later as we had higher-priority tasks.

**Comment by aditya-07** [comment]
@Naveens1605 PR https://github.com/google/android-fhir/pull/1916 should fix this issue.
