### ISSUE TITLE
Error with Json Patch

### ISSUE THREAD

**Issue by evance-mose** [google/android-fhir#2342]
**Describe the bug**
Right now, we have a problem adding multiple activities to the CarePlan. The issue lies in the Json Patch. It's giving us the same path for each activity in the patch file. When the changes are merged, the system compares them based on the path [in this file](https://github.com/google/android-fhir/blob/704d753daeec67f05dbeea9e138cd9ada686043b/engine/src/main/java/com/google/android/fhir/sync/upload/patch/PerResourcePatchGenerator.kt#L116) `.associateBy { it.optString("op") to it.optString("path") }`. This causes it to pick only one activity that's being updated, resulting in the server returning a CarePlan with just one added activity.

After investigating the Json Patch further, it seems there are problems with it, causing it to return the wrong patch. [json-patch](https://github.com/java-json-tools/json-patch/issues)

**Component**
Fhir Engine

**To Reproduce**
1. Open an existing CarePlan in app (already in sync with server)
2. Update it to add 2 or more Task activities to the CarePlan, to generate LocalChange for the CarePlan
3. Sync to server, only the last task activity in the Careplan gets synced

**Additional context**
Patch File - LocalChange payload
```
[
  {
    "op": "replace",
    "path": "/activity/6/detail/status",
    "value": "in-progress"
  },
  {
    "op": "add",
    "path": "/activity/-",
    "value": {
      "outcomeReference": [
        {
          "reference": "Task/4f26da79-4571-4442-911a-c3a707e3e662",
          "display": "Viral Load Collection"
        }
      ],
      "detail": {
        "kind": "Task",
        "code": {
          "coding": [
            {
              "system": "https://d-tree.org/",
              "code": "art-client-viral-load-collection"
            }
          ]
        },
        "status": "in-progress",
        "scheduledPeriod": {
          "start": "2023-11-15T11:45:40+02:00",
          "end": "2023-12-14T11:10:34.227+03:00"
        },
        "performer": [
          {
            "reference": "Practitioner/311015",
            "display": "John Doe"
          }
        ],
        "description": "Viral Load Collection"
      }
    }
  },
  {
    "op": "add",
    "path": "/activity/-",
    "value": {
      "outcomeReference": [
        {
          "reference": "Task/6f6e6672-ef2d-4e57-9854-0a04cd0fb001",
          "display": "Index Case Testing"
        }
      ],
      "detail": {
        "kind": "Task",
        "code": {
          "coding": [
            {
              "system": "https://d-tree.org/",
              "code": "art-client-index-case-testing"
            }
          ]
        },
        "status": "in-progress",
        "scheduledPeriod": {
          "start": "2023-11-15T11:45:40+02:00",
          "end": "2023-12-14T11:10:34.227+03:00"
        },
        "performer": [
          {
            "reference": "Practitioner/311015",
            "display": "John Doe"
          }
        ],
        "description": "Index Case Testing"
      }
    }
  }
]
```

Local CarePlan.
[local-careplan.json](https://github.com/google/android-fhir/files/13484582/local-careplan.json)

Remote CarePlan
[remote-careplan.json](https://github.com/google/android-fhir/files/13484589/remote-careplan.json)
 
**Would you like to work on the issue?**
yes, @LZRS and @evance-mose 

cc @KhumboLihonga

**Comment by kelvin-ngure** [comment]
This issue is also causing household members to disappear when syncing.

The same line of code @evance-mose causes `add` patch operations performed on the same `Group.member` resource to disappear. This is because having the key of the hashmap be a non unique value (i.e the op) causes the overwrite

**Comment by aditya-07** [comment]
@evance-mose @omarismail94 Is anyone working on this?

**Comment by omarismail94** [comment]
I've created PR#2370 as a fix. @kelvin-ngure @evance-mose  can you cherry-pick the commit and see if that resolves the issue?
