### ISSUE TITLE
Migrate to Kotlin Multiplatform

### ISSUE THREAD

**Issue by jeffnyauke** [google/android-fhir#2343]
Migrate the library from android-only to Kotlin multiplatform in order to target Android, JVM, iOS and Web

**Comment by fredhersch** [comment]
Thanks @jeffnyauke can you provide some additional information to this issue

**Comment by jeffnyauke** [comment]
> Thanks @jeffnyauke can you provide some additional information to this issue

Updated 🙂

**Comment by jingtang10** [comment]
Closing in favour of #1497. Please continue discussions there.
