### ISSUE TITLE
Questionnaire content style customization

### ISSUE THREAD

**Issue by Rkareko** [google/android-fhir#2353]
**Is your feature request related to a problem? Please describe.**
It's not possible to customize the padding for the RecyclerView that contains the questionnaire content.

**Describe the solution you'd like**
FHIRCore has a UX design update that requires modifying the padding around the questionnaire content. To achieve this, the proposal is to add a style to the RecyclerView that will allow for customization.

**Describe alternatives you've considered**

**Additional context**
This is related to the UX Questionnaire adjustments on FHIRCore [Styling update to forms](https://github.com/opensrp/fhircore/issues/2910)

Updated design
![questionnaire_content_padding](https://github.com/google/android-fhir/assets/47570855/a55347f4-96b4-4f95-b4a0-d125f27d49f3)

![questionnaire_button_padding](https://github.com/opensrp/fhircore/assets/47570855/30fe2d95-2398-4536-b35b-fdbec3661b36)

![questionnaire_button_text_padding](https://github.com/opensrp/fhircore/assets/47570855/20426693-1568-439d-bd41-fdcde1571fd2)

**Would you like to work on the issue?**
Yes.

**Comment by Rkareko** [comment]
@shelaghm Kindly share your thoughts on this UI change cc @f-odhiambo @HenryRae

**Comment by shelaghm** [comment]
@Rkareko @f-odhiambo @henryrae this proposed change looks good to me from the design side. Padding is consistent with our design guidelines.

**Comment by f-odhiambo** [comment]
[sharon2719](https://github.com/sharon2719) is working on this
