### ISSUE TITLE
Getting null in exceptions when worker failed

### ISSUE THREAD

**Issue by Zibran1999** [google/android-fhir#2371]
**Describe the bug**
When a worker fails, wants to get an exception message but gets null.

**Component**
Fhir SyncWorker 

**To Reproduce**
1. Pass wrong token while execute worker
2.  run the worker
3. check Failed SyncJobStatus

**Expected behavior**
Once a worker failed should get exceptions

**Additional context**
getting this from FhirSyncWorker:
`Received result from worker Failed(exceptions=[ResourceSyncException(resourceType=List, exception=retrofit2.HttpException: HTTP 500 Server Error), ResourceSyncException(resourceType=Patient, exception=retrofit2.HttpException: HTTP 500 Server Error), ResourceSyncException(resourceType=Questionnaire, exception=retrofit2.HttpException: HTTP 500 Server Error)]) and sending output Data {StateType : com.google.android.fhir.sync.SyncJobStatus$Failed, State : {"timestamp":"2023-12-15T11:40:32.5007+05:30"}, }`

while observing getting this: 
`Exceptions: Failed(exceptions=null)`

**Comment by Zibran1999** [comment]
@jingtang10 
@fredhersch 
@aditya-07 
@santosh-pingle

**Comment by jingtang10** [comment]
closing in favour of #1654
