### ISSUE TITLE
Storing answers of incomplete questionnaires after a fragment is exited / closed

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#238]
If a questionnaire is partially filled, and the fragment is destroyed, we lose all data. In the current system, after #189 is completed it will be up to the client application to maintain the partially filed form data. Should this be handled by the datacapture module ?

**Comment by joiskash** [comment]
This would also directly relate to maintaining the [state](https://www.hl7.org/fhir/questionnaireresponse-definitions.html#QuestionnaireResponse.status) of the QuestionnaireResponse which is required field.

**Comment by epicadk** [comment]
Can I work on this?

**Comment by Ana2k** [comment]
@jingtang10 @joiskash seems like we will need shared preferences here. Is this issue a priority and still open?

**Comment by jingtang10** [comment]
@yigit

**Comment by jingtang10** [comment]
related: #672

We will explore persisting partical response in this ticket

**Comment by omarismail94** [comment]
Just cleaning things up. Closing this as the introduction of draftAnswers takes care of this. Feel free to re-open if that is incorrect
