### ISSUE TITLE
minValue and maxValue support for quantity datatype

### ISSUE THREAD

**Issue by BuchiNy** [google/android-fhir#2381]
**Is your feature request related to a problem? Please describe.**
trying to limit the range entered in a field which has the quantity datatype using minValue and maxValue but the two extensions do not work with the quantity datatype

**Describe the solution you'd like**
the user should not be allowed to enter a number outside the minValue and maxValue set.

**Comment by BuchiNy** [comment]
<img width="505" alt="Screenshot 2023-12-19 155704" src="https://github.com/google/android-fhir/assets/79569415/6e5a8b71-8cc0-4222-bb93-020c2709734c">

**Comment by MJ1998** [comment]
Hey @BuchiNy 

Try this instead :-

```
{
  "url": "http://hl7.org/fhir/StructureDefinition/minValue",
  "valueQuantity": {
    "value": 7,
    "unit": "mo",
    "code": "mo",
    "system": "http://unitsofmeasure.org"
  }
},
{
  "url": "http://hl7.org/fhir/StructureDefinition/maxValue",
  "valueQuantity": {
    "value": 27,
    "unit": "mo",
    "code": "mo",
    "system": "http://unitsofmeasure.org"
  }
},
```

**Comment by BuchiNy** [comment]
@MJ1998

> Hey @BuchiNy
> 
> Try this instead :-
> 
> ```
> {
>   "url": "http://hl7.org/fhir/StructureDefinition/minValue",
>   "valueQuantity": {
>     "value": 7,
>     "unit": "mo",
>     "code": "mo",
>     "system": "http://unitsofmeasure.org"
>   }
> },
> {
>   "url": "http://hl7.org/fhir/StructureDefinition/maxValue",
>   "valueQuantity": {
>     "value": 27,
>     "unit": "mo",
>     "code": "mo",
>     "system": "http://unitsofmeasure.org"
>   }
> },
> ```

thank you for your suggestion but it is still not working and causes the applications to close after entering a number

**Comment by MJ1998** [comment]
So this works with the latest code in the datacapture library. Let me check with the released version.

**Comment by MJ1998** [comment]
Hey @BuchiNy 

Which library version are you using ?
Tested with latest version `implementation("com.google.android.fhir:data-capture:1.0.0")`. This is what it shows:-

<img width="298" alt="Screenshot 2023-12-21 at 14 51 01" src="https://github.com/google/android-fhir/assets/22965002/0022f860-02ec-4720-9b42-880bc9bd371d">

It's able to successfully test min and max extensions according to the extension I provided earlier.

Note: There is a slight error in the validation message where the value is shown as null. This has been fixed in the current master repo which we will have in the next release.

**Comment by BuchiNy** [comment]
@MJ1998 

so i am using the same version, so i realized your method works like how you have shown when i just ran that code on its own but when i integrate it to the rest of the whole questionnaire it causes problems. but thank you for directing me in the right direction

**Comment by MJ1998** [comment]
Ok so due to some other logic in the questionnaire the app is crashing ?
If yes, glad to know we are good here. Can we close this issue ?

**Comment by BuchiNy** [comment]
@MJ1998 yea it's a logic problem. we can close the issue
