### ISSUE TITLE
Hide previous and next button

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2394]
**Is your feature request related to a problem? Please describe.**
Would like for the next and previous button to be hidden i.e. when the user is in the first and last page (see image below)

**Describe the solution you'd like**
Simply hide them (as we agreed)

**Describe alternatives you've considered**
Configure the buttons visibility, might be overkill

**Additional context**
<img width="188" alt="wait-what" src="https://github.com/google/android-fhir/assets/62053304/59037837-b7bc-45be-8737-1a7c2ec97846">

**Would you like to work on the issue?**
Yes

**Comment by FikriMilano** [comment]
@f-odhiambo @rowo

**Comment by jingtang10** [comment]
@FikriMilano can you fix the screenshot? i can't see it.

**Comment by jingtang10** [comment]
@shelaghm fyi

**Comment by jingtang10** [comment]
as commented in the PR, i wonder if we should simply always hide these buttons.

@shelaghm @rowo any thoughts on this one?

**Comment by FikriMilano** [comment]
@jingtang10 image fixed

**Comment by rowo** [comment]
@jingtang10 agree we should always hide since disabled states imply there is a situation where the user would be allowed to interact with a button/component whereas in the start/end of forms, the "previous/next functionalities do not exist — so the buttons should be hidden.
