### ISSUE TITLE
The visual of the bottom-rightmost button is getting cut off.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#2404]
**Describe the bug**
When the Cancel button is configured, the rightmost button at the bottom gets partially cut off in the paginated layout.

**Component**
SDC library

**To Reproduce**

1. Configure the Cancel button.
2. Open the paginated layout questionnaire.
3. Click the Next button until the page reaches the last page.
4. Observe the appearance of buttons at the bottom.

**Expected behavior**
The buttons should not be cut off; the user should be able to scroll the bottom view horizontally to see the buttons.

**Screenshots**
<img width="431" alt="Screenshot 2024-01-09 at 12 48 32" src="https://github.com/google/android-fhir/assets/86107848/a6893f4a-0d29-458c-b972-48be8fd326a8">

**Smartphone (please complete the following information):**
 - Device: Pixel2a
 - Android version:  12

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
looking into it.

**Comment by santosh-pingle** [comment]
1. One approach is to add a HorizontalScrollView, allowing users to scroll and view partially hidden buttons. In this case, there's no need to hide disabled buttons.

2. Alternatively, you can choose to hide the disabled buttons, ensuring enough space for other buttons to be rendered on the screen. #2397

**Comment by jingtang10** [comment]
i think scrollable bottom view is not ideal.

suggestions:

1) can we always hide the next button when there's submit button? or always hide it on the last page?
2) the margins between these buttons are huge. can we reduce them. please make sure this is aligned with the material guidelines.
3) can we make the cancel button border-less. it seems very large for what it is
