### ISSUE TITLE
Add ability to sort items on a Spinner widget 

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#2405]
**Use case**: 

The spinner widget picks the data from the database and then filters it into the dropdown items (in our case locations) using fhir-path expression - Dynamic answerExpression. The implementation for this was done here #2052. POst QA we have a requirement to view the listed items in an alphabetical order (a-z)/asc/desc or by ID

**Requirement** 
Add the ability to sort items on a Spinner widget based on defined criteria

**Sample Screenshots** 
<img src="https://github.com/google/android-fhir/assets/4540684/e6d9d219-523c-4699-a44a-2336ad066e18" width="200" height="400" />
<img src="https://github.com/google/android-fhir/assets/4540684/ab53842c-3d5f-4f0b-abdf-1101792b1b85" width="200" height="400" />
<img src="https://github.com/google/android-fhir/assets/4540684/064ba3fa-c17e-4461-87e2-93a16af4db09" width="200" height="400" />
<img src="https://github.com/google/android-fhir/assets/4540684/9ba25e68-4052-4f7e-8583-099c6a7eebd4" width="200" height="400" />
<img src="https://github.com/google/android-fhir/assets/4540684/f64c0ce6-e75b-4007-9593-9beea30e9c49" width="200" height="400" />

**Comment by pld** [comment]
How are these being sorted for display now? If it's by an internal ID, is there a way we can control that for now (e.g. based on creation order) that can serve as a temporary work around?

**Comment by jingtang10** [comment]
> How are these being sorted for display now? If it's by an internal ID, is there a way we can control that for now (e.g. based on creation order) that can serve as a temporary work around?

sorry missed this - we don't change the order at all, so if the locations are in a value set this would just be the order of the values in the valueset.
