### ISSUE TITLE
Partial Success during upload results in lost updates to the db.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#2408]
**Describe the bug**
In the current uploader, if more than one requests is sent to the server and the last request fails, the success of the previous requests is ignored. This results in the DB not getting the updated values from the server and local changes still persist even though they have been successfully uploaded.

**Component**
Core library

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
is this fixed by #2392?

@MJ1998 @aditya-07

**Comment by aditya-07** [comment]
@jingtang10 Yes, it is fixed by https://github.com/google/android-fhir/pull/2392. So closing it.
