### ISSUE TITLE
Allow Resource Creation using POST http verb.

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#2440]
**Is your feature request related to a problem? Please describe.**

User should be able to create a resource on the Fhir Server using Http-POST. This ticket should handle only the `UrlUploadRequest` and the `BundleUploadRequest` can be handled in a subsequent ticket.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
@aditya-07 
I looked at the current upload strategy code. As I will start working on designing and implementing it, could you add more details for reference?
