### ISSUE TITLE
CodeQL GitHub Action Workflow is broken

### ISSUE THREAD

**Issue by vorburger** [google/android-fhir#2465]
While [verifiying #2461](https://github.com/google/android-fhir/pull/2461#issuecomment-1981378129), I've noticed that [the CodeQL GitHub Action Workflow](https://github.com/google/android-fhir/actions/workflows/codeql.yaml) is completely broken; reason:

> [Invalid workflow file: .github/workflows/codeql.yaml#L32](https://github.com/google/android-fhir/actions/runs/8175411373/workflow)
The workflow is not valid. .github/workflows/codeql.yaml (Line: 32, Col: 10): Unexpected symbol: '||'. Located at position 34 within expression: github.head_ref || github.ref || || github.run_id

**Comment by MJ1998** [comment]
Is this still valid ? @vorburger

**Comment by vorburger** [comment]
> Is this still valid ? @vorburger

@MJ1998 yeah, the aforementioned link still shows the problem.

#2616 should do the trick.
