### ISSUE TITLE
demo application doesn't start on windows

### ISSUE THREAD

**Issue by icrc-fdeniger** [google/android-fhir#2470]
**Describe the bug**
can't start the demo application on Windows 10 with java 17

Relevant log:

```
java.io.FileNotFoundException: C:\WINDOWS\sqlite-3.36.0-d1d580cc-94e1-44dd-976b-9d0203cd82d9-sqlitejdbc.dll.lck (Access is denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at org.sqlite.SQLiteJDBCLoader.extractAndLoadLibraryFile(SQLiteJDBCLoader.java:210)
```

I managed to let it work by migrating to kspid("com.google.devtools.ksp").version("1.9.21-1.0.16"):
https://github.com/google/android-fhir/compare/master...icrc-fdeniger:android-fhir:icrc-ok-pull-data?expand=1#diff-84cb3f8fc96e6909e77e32e7f45a90496814fd34fb2e9822056aea55aaa0e9e7

I believe the root is that I can open a file located the folder  C:\WINDOWS ( not an admin)

**Comment by MJ1998** [comment]
Thanks for raising this @icrc-fdeniger 

I think I know why ksp works and kapt does not.  The overhead of kapt's stub generation process likely ran into permission problems in your non-admin setup. The exact folders it tried to write to are unknown, but they were probably system-protected.

See more in [Why KSP](https://kotlinlang.org/docs/ksp-why-ksp.html#comparison-to-kapt)?
Also Android documentation recommends to [migrate to ksp](https://developer.android.com/build/migrate-to-ksp)!

This seems to be a valid change and I think ksp is safe for room compiler. 
Would you like to submit a PR for this ?

**Comment by icrc-fdeniger** [comment]
Sure I tried with a first draft here :) 
https://github.com/google/android-fhir/pull/2471

Not an expert with KSP, KAPT so I'm sure it should be polished. it's ok for me with this configuration but I will need to have feedback on my modification. For instance for the ksp version (1.9.21-1.0.16). It seems it was the only config working for me..
I can do more tests

**Comment by MJ1998** [comment]
Thanks and no worries @icrc-fdeniger.  Have left some comments on your PR.
