### ISSUE TITLE
Be able to configure the FHIR Server and a user/password for Demo App

### ISSUE THREAD

**Issue by icrc-fdeniger** [google/android-fhir#2473]
**Is your feature request related to a problem? Please describe.**
By default the fhir server https://hapi.fhir.org/baseR4/" is used without login.
It should be great if developper can change the server and specify a another FHIR Server and use a login/pwd

**Describe the solution you'd like**
Be able to configure these configuration in the file local.properties

**Describe alternatives you've considered**
Fork and modify manually FhirApplication

**Additional context**

**Would you like to work on the issue?**
Why not

**Comment by MJ1998** [comment]
Thank you for your interest in our demo app! It sounds like you're looking for guidance on implementing authentication.

While the FHIR SDK library offers powerful tools, it's not directly designed to handle user authentication. We recommend checking out our dedicated repository, [fhir-app-examples](https://github.com/google/fhir-app-examples). This repository provides various examples of end-to-end applications including authentication. More information in the READMEs of the specific application. For your need I would recommend going through this [demo](https://github.com/google/fhir-app-examples/tree/main/demo) in the same repo.

Let us know if you have any other questions.

**Comment by icrc-fdeniger** [comment]
Hello @MJ1998, thanks for the link to the examples.
My point was to be able to test directly the engine on a different FHIR Server without having to install the access gateway  ( still wondering if the gateway is mandatory :) )

**Comment by MJ1998** [comment]
Hey @icrc-fdeniger , sorry I missed this.

Got it !
Yes, we support authentication! You can integrate your own authentication system by providing your URL and an authenticator via the `serverConfiguration.authenticator` setting in `FhirEngineConfiguration`.
For example in this [demo](https://github.com/google/fhir-app-examples/tree/main/demo) I shared earlier, [this is how we provide a custom authenticator](https://github.com/google/fhir-app-examples/blob/4b79549db6fd0fc3f87cb9d79c46da2038b67a9f/demo/app/src/main/java/com/google/fhir/examples/demo/FhirApplication.kt#L47) - notice that LoginRespository is an extension of Authenticator interface.

Also you're right gateway is not mandatory.
