### ISSUE TITLE
Add questionnaire and qItem as reserved variables

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2477]
**Describe the Issue**
Add `questionnaire` and `qItem` as reserved variables.

Note:
Based on this doc, I would argue that `qItem` is not supposed to be accessed via root level of any expression based extension. BUT still, I don't see the downsides of adding `qItem` as part of the reserved variables. It's simpler too.

> The %qitem variable is defined as a shortcut to get to the Questionnaire.item that corresponds to the context QuestionnaireResponse.item. **It is only valid for FHIRPath expressions defined within a Questionnaire item.**
https://build.fhir.org/ig/HL7/sdc/expressions.html#fhirpath-supplements

**Would you like to work on the issue?**
Yes

**Comment by MJ1998** [comment]
@FikriMilano 

You mean that, based on doc, qItem can still be used in expression defined at questionnaire root level, right ?

**Comment by MJ1998** [comment]
I mean the same. qItem should be a reserved item in Questionnaire items. But from definition, one should be able to use it as a variable name (not recognized as a reserved word) when declared in the questionnaire root extension(s), correct ?

**Comment by MJ1998** [comment]
Supporting this will also not be a big change but it's not needed currently.
I am fine with it. @jingtang10
