### ISSUE TITLE
Sync upload local changes reordering patch issue

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#2500]
**Describe the bug**
After the latest updates to Sync, an exception is thrown on the [code block/line here](https://github.com/google/android-fhir/blob/a5db185c60035c4b9a1f1c287a3d4f0c2dbba766/engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt#L131) :

```kotlin
private fun createTopologicalOrderedList(adjacencyList: Map<Node, List<Node>>): List<Node> {
    val stack = ArrayDeque<String>()
    val visited = mutableSetOf<String>()
    val currentPath = mutableSetOf<String>()

    fun dfs(key: String) {
      check(currentPath.add(key)) { "Detected a cycle." }
      if (visited.add(key)) {

```
The check throws an exception if it detects a cycle, however there could be valid cycles . 

See screenshot (Shows breakpoint debugging of [code block/line above](https://github.com/google/android-fhir/blob/a5db185c60035c4b9a1f1c287a3d4f0c2dbba766/engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt#L131) )

**Component**
Core library - Engine

**To Reproduce**
1. Trigger sync upload after a workflow that creates resources with a dependency tree as shown on the screenshot.

**Expected behavior**
Sync upload should be successful

**Screenshots**
![Screenshot 2024-03-26 at 15 14 50](https://github.com/google/android-fhir/assets/10017086/711ae5eb-5413-4077-8024-ccf30fc0634c)

[Screenshot shows breakpoint debugging of line here](https://github.com/google/android-fhir/blob/a5db185c60035c4b9a1f1c287a3d4f0c2dbba766/engine/src/main/java/com/google/android/fhir/sync/upload/patch/PatchOrdering.kt#L131) 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Would you like to work on the issue?**
@aditya-07 worked on the original issue

**Comment by aditya-07** [comment]
@ndegwamartin Can you add some data for the valid cycle.

**Comment by santosh-pingle** [comment]
@ndegwamartin Did you share the data with @aditya-07 for the valid cycle?

**Comment by ndegwamartin** [comment]
@aditya @santosh-pingle for context the above screenshot was captured after migrating to the latest codebase. 

Attached is the SQL to recreate the state of the `LocalChangeEntity` and `LocalChangeResourceReferenceEntity`
[resources_db-LocalChanges.sql.zip](https://github.com/google/android-fhir/files/14849345/resources_db-LocalChanges.sql.zip) . Let me know if you need data from any of the other tables.

I'm also happy to jump on a call to clarify further

**Comment by aditya-07** [comment]
> @aditya @santosh-pingle for context the above screenshot was captured after migrating to the latest codebase.
> 
> Attached is the SQL to recreate the state of the `LocalChangeEntity` and `LocalChangeResourceReferenceEntity` [resources_db-LocalChanges.sql.zip](https://github.com/google/android-fhir/files/14849345/resources_db-LocalChanges.sql.zip) . Let me know if you need data from any of the other tables.
> 
> I'm also happy to jump on a call to clarify further

@ndegwamartin The .zip doesn't have sql to recreate `LocalChangeResourceReferenceEntity` .

**Comment by ndegwamartin** [comment]
@aditya-07 you are correct, appears the  `LocalChangeResourceReferenceEntity` was not part of the archive. I've recreated the scripts with a new data set attached here - [LocalChangesSQL.zip](https://github.com/google/android-fhir/files/14884729/LocalChangesSQL.zip)

<img width="270" alt="Screenshot 2024-04-05 at 15 18 51" src="https://github.com/google/android-fhir/assets/10017086/d875677f-6dcc-463d-80cf-7af8a7f5602e">

**Comment by pld** [comment]
hi @aditya-07 any update on progress here? Thank you!
