### ISSUE TITLE
Improve initial load for calculated-expression

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2519]
**Is your feature request related to a problem? Please describe.**
The initial load calculated-expression algorithm is very inefficient:
- In a nutshell what it does right now is, for each questionnaireItem, find other questionnaireItems that's using calculated-expressions, then process the calculation. 
- Problem is, it's finding ALL calculated-expression for each questionnaireItem, so in one of our forms, we have around 420 normal questionnaireItem, and 80 questionnaireItem with calculated-expression within a form, it will be 33.600(420*80) processes in total. Each calculated-expression is processed 420 times and it's a waste of resource, 1 time is enough. This is a rough estimation, but you see my point.

**Describe the solution you'd like**
During initial load, directly find all calculated-expression within a form, and process that. It will be 80 process in total.

**Describe alternatives you've considered**
N/A

**Additional context**
- The following is total calculation and the time it takes to process it
- Before improvement (~70 seconds)
<img width="380" alt="Screen Shot 2024-04-23 at 08 12 36" src="https://github.com/google/android-fhir/assets/62053304/de0ff49c-a58c-494c-94f1-a42d9238a252">

- After improvement (<1 second)
<img width="380" alt="Screen Shot 2024-04-23 at 08 12 48" src="https://github.com/google/android-fhir/assets/62053304/e97e62cf-ab0c-45d6-9036-ce88fa346774">

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
thanks for raising this issue @FikriMilano and amazing to see the improvements! i'll leave technical comments in the pr itself.
