### ISSUE TITLE
Do you think it would be important to handle [WorkInfo.State#BLOCKED](https://developer.android.com/reference/androidx/work/WorkInfo.State#BLOCKED) status or defaulting to error would just be enough?

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#2538]
Do you think it would be important to handle [WorkInfo.State#BLOCKED](https://developer.android.com/reference/androidx/work/WorkInfo.State#BLOCKED) status or defaulting to error would just be enough?

_Originally posted by @ellykits in https://github.com/google/android-fhir/pull/2511#discussion_r1588948160_

**Comment by jingtang10** [comment]
closing this

fyi @santosh-pingle
