### ISSUE TITLE
Snapshot Packages are not published or visiblie

### ISSUE THREAD

**Issue by vorburger** [google/android-fhir#2579]
Since #2525 got merged as bf83f8511df6af6d82e333e4cfb3ff162f4ca4be,

based on https://google.github.io/android-fhir/use/Snapshots/, I was expect there would be a tab, at:

https://github.com/google?tab=packages&repo_name=android-fhir

but there is none...

nor is there a https://maven.pkg.github.com/google/android-fhir (it 404s), although that may be more normal.

@icrc-fdeniger did you notice? Do you understand why it doesn't seem to publish?

Or does it actually work for you? Is it Just the tab that's missing, is it only a UI issue? Or does it really not publish, for some reason?

@jingtang10 @fredhersch FYI

**Comment by icrc-fdeniger** [comment]
@vorburger  yes we noticed that. It's working for us and it seems it's a UI issue only.
I've just updated the doc here and created a PR: https://github.com/google/android-fhir/pull/2578

**Comment by jingtang10** [comment]
thanks michael for raising this. i've raised an internal request to see if there's anything that the organization can configure for the repo - but as far as i can see as the repo admin there's no setting to enable this in the repo.

**Comment by vorburger** [comment]
https://github.com/orgs/google/packages?repo_name=android-fhir, as per #2578, has them! Noice.

**Comment by vorburger** [comment]
@icrc-fdeniger @jingtang10 FYI I just remembered that by clicking on the "wheel" in the upper right hand corner of https://github.com/google/android-fhir/ to _"Edit repository details"_ we can select **Packages** to be _"Include in the home page"_ ... it now shows up on the right hand side, mid-way, under _"Releases",_ above _"Contributors"._

**Comment by jingtang10** [comment]
oh wow @vorburger i had been looking for it for a long time in repo settings and never realised it's that button next to "About"... great find - thanks!
