### ISSUE TITLE
UI/UX Design: Warning text (i.e. text that are nudging clinical decision guideline to users) looks visually similar with other fields

### ISSUE THREAD

**Issue by arulferiandevops** [google/android-fhir#2596]
**Is your feature request related to a problem? Please describe.**
Warning text (i.e. text that are nudging clinical decision guideline to users) looks visually similar with other fields. 

**Describe the solution you'd like**
Warning text should be visually eye-catching (i.e. colored “red” or “green”) so user can notice this warning more attentively

**Additional context**
![image](https://github.com/google/android-fhir/assets/149508752/036a6ad9-bdf7-4b25-8ae3-989c251f0d4d)

**Would you like to work on the issue?**
@jingtang10 @f-odhiambo @SebaMutuku @MargaretNjenga

**Comment by jingtang10** [comment]
this is possible with style customization built into the sdc library: please see https://google.github.io/android-fhir/use/SDCL/Customize-how-a-Questionnaire-is-displayed/#localize-questionnaires

@santosh-pingle can you please try to create an example and perhaps we can even add it to the catalog app?

thanks

**Comment by jingtang10** [comment]
this new section @santosh-pingle added provides detailed example of how to do this: https://google.github.io/android-fhir/use/SDCL/Customize-how-a-Questionnaire-is-displayed/#custom-style-per-question-item
