### ISSUE TITLE
Flyover text as secondary dialog title

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2647]
**Is your feature request related to a problem? Please describe.**
Currently, when the item.text is null, the title of the dialog is also null. We'd still like to have something displayed as the dialog title, and the closest thing is to display the flyover text. Unless there's a specific extension to display a dialog title (couldn't find one).

Currently:
```
              OptionSelectDialogFragment(
                title = questionnaireItem.localizedTextSpanned ?: "",
                config = questionnaireItem.buildConfig(),
                selectedOptions = selectedOptions,
              )
```

**Describe the solution you'd like**
If item.text is null, apply flyover text as the dialog title.
```
              OptionSelectDialogFragment(
                title = questionnaireItem.localizedTextSpanned ?: questionnaireItem.localizedFlyoverSpanned ?: "",
                config = questionnaireItem.buildConfig(),
                selectedOptions = selectedOptions,
              )
```

**Describe alternatives you've considered**
Specific extension to display a dialog title (couldn't find one).

**Additional context**
<img width="362" alt="Screen Shot 2024-07-29 at 06 00 55" src="https://github.com/user-attachments/assets/dbedf578-c863-43e7-aa81-c9372c3879ba">

**Would you like to work on the issue?**
Yes

**Comment by MJ1998** [comment]
Using flyover here might cause developer miss adding localized text.
But I guess I am okay with this solution as there are no recommendation in FHIR about this.
Should we suggest this in FHIR community ?

**Comment by MJ1998** [comment]
@FikriMilano, btw, why not change the text in the questionnaire itself ?

**Comment by jingtang10** [comment]
if we're using fly over as the title for the dialog, shouldn't we just not use the question text as the dialog title?

how would you customise the dialog title if you already have question text?

**Comment by MJ1998** [comment]
What if you use [questionnaire-rendering](http://hl7.org/fhir/StructureDefinition/questionnaire-rendering) extension and set code to "no-header" ?

**Comment by jingtang10** [comment]
> 1. Exactly, that's what I did
> 2. We will have 2 item, first item is a display type that contains the question text (item.text). Second item is the dropdown field w flyover that will open the dialog, but have a null question text.

Yeah but what I mean is I'd like for you to be able to do that using only 1 questionnaire item... I feel it's easier just to use the flyover text for the dialog title (without first checking the question text)

**Comment by MJ1998** [comment]
@FikriMilano Sorry I thought there is some "questionnaire-rendering" extension.
What my idea was to use an extension which disables header text. This way you could have added the text in the second item without displaying it above the field, and it would have also shown as dialog title. 
Instead of the flyover text as a custom approach, I incline more towards having a custom extension which disables header text.

**Comment by jingtang10** [comment]
> @FikriMilano Sorry I thought there is some "questionnaire-rendering" extension. What my idea was to use an extension which disables header text. This way you could have added the text in the second item without displaying it above the field, and it would have also shown as dialog title. Instead of the flyover text as a custom approach, I incline more towards having a custom extension which disables header text.

why would we want to disable header test?

**Comment by jingtang10** [comment]
> 1. > What if you use [questionnaire-rendering](http://hl7.org/fhir/StructureDefinition/questionnaire-rendering) extension and set code to "no-header" ?
>    
>    
>    @MJ1998 could provide a more detailed documentation, I couldn't find what you're referring to.
> 2. > Yeah but what I mean is I'd like for you to be able to do that using only 1 questionnaire item... I feel it's easier just to use the flyover text for the dialog title (without first checking the question text)
>    
>    
>    @jingtang10 I mean, sure, thank you, but what if someone is just simply using `item.text`? How should we handle that?

they that should be used as question title. if we're forcing questionnaire authors to write split their questions into two because of the dialog title it's bad for consistency. imagine if questionnaire authors need to know the quirks of android fhir sdk sdc library to be able to write a questionnaire that's correctly rendered - we don't want that.

i'd rather if we reuse an extension, or come up with a new extension for the dialog title.

**Comment by jingtang10** [comment]
why do you need an anternative title again? is it because of space? would this work https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-shortText.html?

**Comment by jingtang10** [comment]
> @jingtang10 we want a dialog title that can be defined with a custom extension, or simply reuse the flyover extension.
> 
> The extension you mentioned has a different purpose
> https://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-shortText.html

Yes but why do you want an alternative title? Is it because of space? Would the short text be more suitable than fly over?

**Comment by jingtang10** [comment]
but why is the question text null in this case? i'm trying to look for the most sensible way for both questionnaire authors and implementation to do this using the right extensions. i know for your question you might not have text field but the question is why? This dictates if we will try to reuse an extension or create a new extension.

In the original screenshot I am seeing question text in the background actually.

**Comment by jingtang10** [comment]
does it not have question text because you're using another display item for the question text before this drop down? that is strange and i would argue it's a usage pattern that should be discouraged.

**Comment by jingtang10** [comment]
Fikri's reply:
```
can you pls add some background as to the root reason?
A: It's simply a UI preference, where instead displaying the question above the field, we display it as flyover text (see image) 

why is the dialog title different from question text?
A: It's still the same, but the dialog title is retrieved from flyover, the flyover is the question in this case.

is it because it needs to be shorter? 
A: No

and if you say the original question has null text that's even odder - why doesn't a question have text but require the dialog to have text...?
A: the question still have text but that is retrieved from flyover, knowing that, the dialog title now needs to also display the text from flyover (see image).
```

**Comment by jingtang10** [comment]
Thanks @FikriMilano for the replies to my questions - now I understand the issue I'm happy with the PR.
