### ISSUE TITLE
Optimize the Database Search API

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#2668]
**Is your feature request related to a problem? Please describe.**
Did some profiling on [this DatabaseImpl method here](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L204-L212) that has the below code:

```kotlin
  override suspend fun <R : Resource> search(
    query: SearchQuery,
  ): List<ResourceWithUUID<R>> {
    return db.withTransaction {
      resourceDao.getResources(SimpleSQLiteQuery(query.query, query.args.toTypedArray())).map {
        ResourceWithUUID(it.uuid, iParser.parseResource(it.serializedResource) as R)
      }
    }
  }
```
The mapping block takes a lot of time since each serialized resource has to be deserialized sequentially for every element in the list returned from the database. The time taken is linear and the more the db results returned the longer the API takes to return a result.

**Describe the solution you'd like**
 It should be possible to optimize this block by introducing a parallelized implementation e.g. Using _coroutines_ and _async_ within each iteration and then collecting the results and get a significant improvement. 

**Describe alternatives you've considered**
Instead of letting the _async_ launch with the current dispatcher(probably IO at that point) we could instead switch to the Default dispatcher since it is a computationally expensive task. This will however require us to create a new JSONParser object per iteration since it is not thread safe.

**Additional context**

**Would you like to work on the issue?**
Yeah

**Comment by ndegwamartin** [comment]
The [DatabaseImpl.searchForwardReferencedResources](https://github.com/google/android-fhir/blob/d9653b61d03eb3b1d4a570c451269ab7f3fd03c7/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L214C24-L214C56) and [DatabaseImpl.searchReverseReferencedResources](https://github.com/google/android-fhir/blob/d9653b61d03eb3b1d4a570c451269ab7f3fd03c7/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L230) functions can also benefit from the  same optimization and should be included.

**Comment by joiskash** [comment]
This seems like an interesting approach. What are the memory implications of creating a new Parser per iteration?

I have a few questions related to this issue that are related to the use case:

1. How many resources are we talking about here? 100s, 1000s or more?
2. Do these resources only contain text or does this also contain binary data like base64 encoded images?
3. Is there any scope for chunking instead of fetching all resources?

**Comment by ndegwamartin** [comment]
I suppose though if the idea is to use chunking to change the overall approach in terms of improving the UX then yeah, that works okay. We have implemented batching on our record fetches (10 records) by using pagination for registers and infinite scrolling e.g. for searches.

**Comment by ndegwamartin** [comment]
Looks like creating a new JsonParser for each iteration should not be a concern after all (provided the parent class FHIR Context is already created) [as mentioned on the comment here](https://github.com/hapifhir/hapi-fhir/blob/02d38bce1467aefad359385d2052221808a376db/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L862).

>Performance Note: This method is cheap to call, and may be called once for every message being processed without incurring any performance penalty

**Comment by ndegwamartin** [comment]
Looks like creating a new JsonParser for each iteration should not be a concern after all (provided the parent class FHIR Context is already created) [as mentioned on the comment here](https://github.com/hapifhir/hapi-fhir/blob/02d38bce1467aefad359385d2052221808a376db/hapi-fhir-base/src/main/java/ca/uhn/fhir/context/FhirContext.java#L862).

>Performance Note: This method is cheap to call, and may be called once for every message being processed without incurring any performance penalty

I will go ahead and update the PR with this variant of the optimization.
