### ISSUE TITLE
Task 'wrapper' not found in project ':engine' and its subprojects.

### ISSUE THREAD

**Issue by DavidSaruni** [google/android-fhir#2724]
When I try to import any subproject like cataog or demo or any other, I get this error:
`Task 'wrapper' not found in project ':engine' and its subprojects.`

This is a screenshot of it
![Image](https://github.com/user-attachments/assets/76183b9b-a93d-46c7-9f44-20ef70dd8cc8)

**Comment by jingtang10** [comment]
Hi @DavidSaruni - thanks for raising this.

You will need to open the root project for the gradle wrapper to be recognised by android studio. See screenshot:

![Image](https://github.com/user-attachments/assets/8eaef267-e157-4fc8-98a6-4a44c08b16e6)

And then you can run specific modules: for example the demo app or the catalog app module

![Image](https://github.com/user-attachments/assets/deb836b6-db43-4e23-974e-b39965d2e234)

and if you're making contributions to the codebase you will need to run the tests.

I'll close this issue for now - but please reopen if the issue persists.

**Comment by DavidSaruni** [comment]
Thank you this worked for me
