### ISSUE TITLE
Questionnaire population with another resource

### ISSUE THREAD

**Issue by mberg** [google/android-fhir#273]
This is related to the draft stage suggestion in #227. 

One of the things about SDC in FHIR is that a submission will not just create a questionnaire reponse but also potentially create corresponding resources.   We will need to figure out the logic to revert / cancel resources if a questionnaire is edited or potentially deleted.

**Comment by jingtang10** [comment]
Thanks @mberg for creating this. I want to break this down a little bit more. The workflow currently is as follows

1. You have a `Questionnaire` from somewhere (loaded from db, downloaded from a server, hardcoded in app, wherever you get it from)
2. You call the sdc lib to draw the form from the `Questionnaire`
3. The user fills out the form
4. You call the sdc lib or the user clicks some button to generate a `QuestionnaireResponse`
5. You call the sdc lib to create a (as an example) `Patient`

So what does reverting mean here technically for the sdc lib? 

If it's about deleting either the `QuestionnaireResponse`, or the `Patient`, then it's totally outside the remit of the sdc lib. The app is free to do whatever they want.

So what does editing mean here technically for the sdc lib? 

That means we'll need to populate the `Questionnaire` with either the `QuestionnaireResponse` or the `Patient`.

**Comment by pld** [comment]
It sounds like the SDK appropriate task here is populating a Questionnaire resources with another resource. Related to that is defining how the other resource maps to the Questionnaire resource.

@jingtang10 what do you think? does it makes sense to update/replace this issue with one more focused on that task?

**Comment by jingtang10** [comment]
#377

**Comment by Rkareko** [comment]
@jingtang10 the proposed strategy is to use [Expression-based Population](http://build.fhir.org/ig/HL7/sdc/populate.html#expression-based-population) as defined in the SDC spec. We shall be using FHIR path to set the initial value of a Questionnaire item an example of which is given on [this article](https://developer.commure.com/docs/apis/sdc/examples/#using-a-fhir-path-to-set-the-initial-value-of-a-questionnaire-item)

Steps

1. Add a function `populate` in the ResourceMapper which takes a `Questionnaire` and `Resource` and returns a `QuestionnaireResponse`
2. For each item in the questionnaire use `FHIRPathEngine` to evaluate the `questionnaire-initialExpression` `valueExpression.expression` and retrieve the value from the resource
3. Create an item in the `QuestionnaireResponse` for the `Questionnaire` item in step 2 and populate the `item.answer` with the retrieved value.

**Comment by MuhammadSalman-7214** [comment]
@jingtang10 how can we set an answer after retrieving the value using Fhir Path. To give you an idea, I have a hashMap containing all the answers. Following is the code

answer =
              mutableListOf(
                QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
                  value = retrievedAnswer as Type?
                }
              )
              
              where retrievedAnswer can be a String or boolean depending upon the question. I have to cast the answer as Type as value can be set with Type only. So how can I cast the answer to Type then? thanks.

**Comment by jingtang10** [comment]
You need to try to figure out what the type is and set the right value. Do not use `value = `, use something like `booleanValue = ` etc.

Can you try to do something like this: https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt#L203
or this: https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemTypes.kt?

**Comment by MuhammadSalman-7214** [comment]
okay, thanks @jingtang10

**Comment by MuhammadSalman-7214** [comment]
The approach to achieve population of Related Person would be as follow:
1. We will pass populate function two parameters, first is questionnaire and the second parameter would be a list of Resources
2. For each Resource present in the Resource List, we will populate Initial Values for each Resource using FhirPathEngine.evaluate
3. Then We will create a Questionnaire Response, that will contain responses for all Resources, in our case it would be for Patient and Related Person 
@jingtang10 please review the solution and advise, thanks.

**Comment by MuhammadSalman-7214** [comment]
also @jingtang10, we have gender values as Radio buttons in Fhir Core, if we pass Patient.gender.value, it returns gender value as StringType, and if we pass Patient.gender, it returns gender value as Enumeration, whereas to set value for Radio buttons, it requires value in terms of Coding. Can you please suggest how can we get gender value as Coding from fhirPathEngine.Evaluate because Patient.gender.value and Patient.gender both doesn't serve our purpose, thanks

**Comment by MuhammadSalman-7214** [comment]
@jingtang10 if we add the following code in the sdk, gender value would be in coding then in QuestionnaireResponse:

if (answerExtracted is Enumeration<*>) {
          answerExtracted = if (answerExtracted.valueAsString == "male") {
            Coding("", "male", "Male")
          } else {
            Coding("", "female", "Female")
          }
        }

**Comment by jingtang10** [comment]
> @jingtang10 if we add the following code in the sdk, gender value would be in coding then in QuestionnaireResponse:
> 
> if (answerExtracted is Enumeration<*>) {
> answerExtracted = if (answerExtracted.valueAsString == "male") {
> Coding("", "male", "Male")
> } else {
> Coding("", "female", "Female")
> }
> }

You code won't work with enums with other values -- this is not generic enough. You need to find comon logic to deal with this.

**Comment by jingtang10** [comment]
@santosh-pingle

**Comment by aditya-07** [comment]
This case is being handled in the PR https://github.com/google/android-fhir/pull/646 given sdc-questionnaire-initialExpression -> "expression" is "Patient.gender"

**Comment by MuhammadSalman-7214** [comment]
okay, thanks @aditya-07
