### ISSUE TITLE
Ability to open a link defined using html <a> tag

### ISSUE THREAD

**Issue by FikriMilano** [google/android-fhir#2731]
**Is your feature request related to a problem? Please describe.**
Open a link when it's clicked, the link will be defined using html <a> tag.
For example `<a href="https://www.youtube.com/">link text</a>`

**Describe the solution you'd like**
Apply this code to the TextView which adds ability to open a link in the TextView.
```
question.movementMethod = LinkMovementMethod.getInstance()
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
is this needed for fhircore?

**Comment by FikriMilano** [comment]
@jingtang10 yeah, we have a project where the user needs to open a youtube link declared inside item.text

FYI @f-odhiambo
