### ISSUE TITLE
Nested items are tied to the answer of the parent item

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#274]
Based on the discussion [here](https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Questionnaire.20Response.20example/near/227278538)

> When you have questions that are nested beneath questions, they are always tied to the answer. That's because if the parent item allows multiple answers, you answer the child questions for each answer for the parent question.

This is needed especially in the case of items which are repeatable and have nested items.

**Comment by jingtang10** [comment]
also worth mentioning if questions are nested under group, their responses will be nested under group as you'd expect.

**Comment by jingtang10** [comment]
See this discussion on fhir chat: https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/Questionnaire.20Response.20example
