### ISSUE TITLE
Improve ResourceIndexerTest.kt

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#282]
https://github.com/google/android-fhir/blob/master/core/src/test/java/com/google/android/fhir/index/impl/ResourceIndexerTest.kt

- It's really difficult to read the tests because the actual test resources are hidden away in json files in a different folder
- It would be good to really lock down the behavior by having exhaustive unit tests
- It might be useful to have some 'integration tests' where we use some real world resources, and check that everything that should be indexed is indexed

At the moment the test cases seem to be somewhere in between unit and integration tests. in the unit tests i would love for the test resources to be really simple -- as long as we hit the code path we're sorted. in the integration tests it makes sense to have more complex resources.

**Comment by pld** [comment]
Related to the broader theme of code coverage mentioned here is this issue about tracking coverage and enforcing in CI, https://github.com/google/android-fhir/issues/233

**Comment by epicadk** [comment]
Can I work on this? I have added some unit tests in #332 I'll setup the integration tests in a different folder.

**Comment by epicadk** [comment]
I was making a few of my own FHIR resources for testing and I had a question. Should I only add resources marked as normative to the tests or will an [maturity level](https://www.hl7.org/fhir/versions.html#maturity) do?

**Comment by jingtang10** [comment]
@epicadk please feel free to send a pr
