### ISSUE TITLE
Handle date search parameters when the data type isn't date

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#285]
the data type could be 

- date
- dateTime
- instant
- Period
- Timing

See https://www.hl7.org/fhir/search.html#date. At the moment we only index the date values. We need to handle the other 4 types of values.

**Comment by epicadk** [comment]
Can I work on this?

**Comment by epicadk** [comment]
Btw are we not indexing the instant values as well?
 https://github.com/google/android-fhir/blob/85a4e853e597b0ec75c6f27bf467e3ec7789330a/core/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt#L125-L134
