### ISSUE TITLE
Validate data type and item nesting within answers for repeated answers while prefilling UI with a Questionnaire response

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#286]
We need to validate the Questionnaire Response structure with that of the Questionnaire before prefilling the UI. This is to make sure that this particular questionnaire response has been generated by answering the current questionnaire.
Currently we only validate nesting of item within group and the linkId.

We will also have to add checks to make sure:

1. The data type of the questionnaire-item and questionnaireResponse-item match
2. Item nesting within answers #274 

This is an improvement related to #244

**Comment by kartikeysaran** [comment]
Can i work on this if available

**Comment by jingtang10** [comment]
@kartikeysaran can you briefly describe what's needed to be done and your plan here? thanks!
