### ISSUE TITLE
Memory leak warning by Android studio in ViewHolderFactories

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#289]
**Describe the bug**
IDE warning : 

> Do not place Android context classes in static fields; this is a memory leak

**Component**
SDC library

**To Reproduce**
1. Open QuestionnaireItemCheckBoxViewHolderFactory and hover above the line `private lateinit var checkBox: CheckBox`

You will see the above warning,

**Expected behavior**

**Screenshots**

- Android gradle-plugin 4.1.2

![image](https://user-images.githubusercontent.com/48797364/110113690-763cbf80-7dd9-11eb-8720-5694117d2139.png)

**Comment by jingtang10** [comment]
Thanks for raising this @joiskash.

I must say I don't fully understand the warning. We create a new object for each view holder so I don't believe this is a static field. @yigit is this a misleading warning? Or are we actually risking leaks?

**Comment by jingtang10** [comment]
I have clicked "Provide feedback on this warning" and reported this as a false positive.
