### ISSUE TITLE
Use ktfmt

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#290]
Start using https://github.com/facebookincubator/ktfmt

Under this issue please do the following

- Research the pros and cons of using ktfmt (background: https://github.com/google/android-fhir/discussions/246#discussioncomment-431418) and document them in this issue
- Update the `build.gradle` file to use ktfmt (if we're going ahead with this) and potentially converting some existing code
- Update the developer's guide: https://github.com/google/android-fhir/wiki/Developer's-Guide
- Create a discussion topic to communciate this to the contributors

Thank you!

**Comment by jingtang10** [comment]
FYI: @deepankarb @pankajkatoch @yigit @pld @MuhammadSalman-7214 @joiskash @kunjan8794

**Comment by s-ayush2903** [comment]
@deepankarb Should I give this issue a shot if you haven't started working on it yet, because I want to acquaint myself with the project codebase and therefore finding some ways to contribute and learn

**Comment by jingtang10** [comment]
Apologies @deepankarb and @s-ayush2903... I was just finishing #294 which I just linked here.

I've compared ktfmt, ktlint, and diktat. One really cool thing about spotless which we use is that you can use multiple linters (it's a linter aggregator). So we can totally use ktlint and ktfmt as well as diktat all together to benefit from their different strengths.

As an example, I've discovered that ktlint enforces the no-wildcard rule where ktfmt doesn't do anything about wildcards. So it's a good reason to keep ktlint.

But why ktfmt, and why the google-java-format? After experimenting with it, the [rectangle rule](https://github.com/google/google-java-format/wiki/The-Rectangle-Rule) among other things really stood out for me as a good exmaple of how this style guide produces really neat and readable code. The philosophy of ktfmt is also that the developer shouldn't worry about formatting, which is great.

I will update the developer's guide to add a section to configure the ktfmt plugin for AndroidStudio.
