### ISSUE TITLE
Migrate Groovy gradle files to Kotlin scripts

### ISSUE THREAD

**Issue by s-ayush2903** [google/android-fhir#307]
**Is your feature request related to a problem? Please describe.**
Currently the gradle files contain a lot of stuff which they do not need to handle indeed, such as storing the version numbers/ids, raw dependencies' names in strings. They can be cleaned up and via separating the functionalities, they'll be more readable and understandable.

**Describe the solution you'd like**
Conversion from groovy to kotlin scripts, so that we can use dsls to make 'em look clean.

**Describe alternatives you've considered**
No alternatives yet

**Additional context**
--No additional context--

PS: I can work on this issue if it turns out to be a valid one to project maintainers, thanks.

**Comment by jingtang10** [comment]
Thanks for filing this - yes I believe this is a valid item. @yigit @kevinmost for any additional input.

**Comment by ayush1729cpp** [comment]
i would like towork upon this issue . reply if i can start?

**Comment by epicadk** [comment]
> i would like towork upon this issue . reply if i can start?

I think @s-ayush2903 is working on this.

**Comment by s-ayush2903** [comment]
@ayush1729cpp, I'd be creating a pull request soon for this issue, you can take up some other ones.
