### ISSUE TITLE
Spelling mistake in QuestionnaireActivity.kt 

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#309]
https://github.com/google/android-fhir/blob/b338ed4fdad4bf61fec751fc4a6a4001fb7d8c7f/datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt#L82

https://github.com/google/android-fhir/blob/b338ed4fdad4bf61fec751fc4a6a4001fb7d8c7f/datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireActivity.kt#L70

Spelling of Questionnaire is wrong

If this is valid I can work on it.

**Comment by epicadk** [comment]
Just for future reference I wanted to ask if contributors should wait till a maintainer validates the issue or can we just send it prs?

**Comment by jingtang10** [comment]
For spelling issues like this, you can just send a PR without creating an issue. But if it's a proper bug or a feature request please always create an issue and get the owners/maintainers to comment first.

Thanks!
