### ISSUE TITLE
Reference app crashes when asked for evaluation

### ISSUE THREAD

**Issue by s-ayush2903** [google/android-fhir#319]
**Describe the bug**
Reference App in cql loading screen crashes when asked for evaluation 

**Component**
Reference Application

**To Reproduce**
1. Click on `Load CQL Resources & Patients` from the menu at top right
2. Click evaluate button and witness the crash

The crash occurs irrespective of the arguments supplied, i.e., no matter whether those params are empty or filled

**Expected behavior**
No crash

**Screenshots**
NA

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M31
 - Android version: 10
 - Build number: RP1A.200720.012.M315FXXU2BUAC

**Additional context**
NA

**Comment by jingtang10** [comment]
Thanks for creating this issue. The current plan is to remove this the `Load CQL Resources & Patients` from the reference application and place it in a separate reference application.

**Comment by jingtang10** [comment]
Actually @s-ayush2903, would it be possible to migrate your work to a different module. Maybe called `cqlreference`. Basically move that activity to a different app.

@fredhersch fyi

**Comment by s-ayush2903** [comment]
Yep, I'll do that!
