### ISSUE TITLE
consider moving to instrumentation tests for android dependant stuff

### ISSUE THREAD

**Issue by yigit** [google/android-fhir#32]
robolectric runs tests on main thread which becomes a problem w/ room.

The official recommendation for Room is to actually test on a device since different SQLite versions on devices have different issues and we probably need to support really old devices.

Until then, we'll need to allow main thread queries in room. If we decide to keep it, we should at least make it a test only option.

**Comment by jingtang10** [comment]
I believe this has been done by @deepankarb moving tests to `/androidTest`. @yigit @deepankarb can you please confirm and close if appropriate.
