### ISSUE TITLE
Data Capture Gallery app crashes 

### ISSUE THREAD

**Issue by Manikant25** [google/android-fhir#320]
**Describe the bug**
When Covid-19 Case Report is clicked in Data Capture Gallery App, it crashes.

**Component**
 SDC gallery app

**To Reproduce**
1. Click on `COVID-19 Case Report`

**Expected behavior**
No crash

**Screenshots**
[Error shown in logcat](https://github.com/Manikant25/Monster-Killer-Game/blob/master/Screenshot%20(531).png)

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a3
 - Android version: 11
 - Build number: qssi-user 11 RKQ1.200903.002 V12.0.6.0.RFQMIXM
 

**Additional context**
NA

**Comment by s-ayush2903** [comment]
Already reported, see #271 & #308

**Comment by Manikant25** [comment]
> Already reported, see #271 & #308

Thanks for informing me.
