### ISSUE TITLE
Add chat link in Contributions

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#322]
Chat links were not found on the **main page** and doing so could help in smoother communication with new users.

Also enabling new stream in zulip chatbox for android-fhir

ie. https://chat.fhir.org/#android-fhir

**Comment by epicadk** [comment]
> Chat links were not found on the **main page** and doing so could help in smoother communication with new users.
> 
> Also enabling new stream in zulip chatbox for android-fhir
> 
> ie. https://chat.fhir.org/#android-fhir

I think the zulip link you shared is for communications pertaining to the standard itself and not this project.

**Comment by jingtang10** [comment]
thanks both.

there is an existing stream on zulip (albeit quiet): https://chat.fhir.org/#narrow/stream/276344-android. so we should stick to that.

the zulip chat stream is for android in general and is not limited to this project. so i suggest it be listed as an addtional resource but it's not a chat for this repo.

**Comment by maanuanubhav999** [comment]
okay, closing issue.

**Comment by jingtang10** [comment]
i think it doesn't harm adding the chat link to the wiki pages by the way.

**Comment by maanuanubhav999** [comment]
@jingtang10  sure, should I add it under developer's guide or user's guide.

**Comment by jingtang10** [comment]
Thanks. I've done it.
