### ISSUE TITLE
Gradle Sync Failure 

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#336]
**Describe the bug**
Gradle Sync failure due to beta version

**To Reproduce**
Steps to reproduce the behaviour:
1. Fork the repo
2. Build the app in stable version of Android studio

**Expected behavior**
Succesful Gradle Snc and stable build of app.

**Screenshots**
![Screenshot from 2021-03-18 21-31-32](https://user-images.githubusercontent.com/54909114/111657576-9173ea00-8831-11eb-830a-b0e2e1de0ee4.png)

**Android Studio :**
 - Studio Version [4.1.2]
 
**Additional context**
Upon doing gradle version changes app runs well.

**Comment by Ana2k** [comment]
@jingtang10 I would like to work on this issue. Can you assign it to me please?

**Comment by epicadk** [comment]
You can take a look at [this discussion](https://github.com/google/android-fhir/discussions/312)

**Comment by Ana2k** [comment]
> You can take a look at [this discussion](https://github.com/google/android-fhir/discussions/312)

 @epicadk I had resolved the issue and made a pr already. 
 Thanks for the discussion thread link anyways!

**Comment by jingtang10** [comment]
Please see developer's guide here: https://github.com/google/android-fhir/wiki/Developer's-Guide which recommends using AS 4.2. I'm closing this issue and if your issue isn't resolved after upgrading to 4.2 please feel free to re-open with more details. Thanks!

**Comment by atm1504** [comment]
@jingtang10 I was scrolling through the issue section and found this issue. Even, while building the app I faced the same issue. I went through the guidelines  https://github.com/google/android-fhir/wiki/Developer's-Guide and found that it asks to use 4.2+ version of the android studio which is the beta version currently.

I did as stated. I downloaded the latest beta release which is Android 4.Beta 6. but the issue raised again. To make the app run, I have to update the Gradle version from 4.2.0-beta02 to 4.2.0-beta06

I hope the best thing would be to make the app compatible to run in the latest stable version of android studio and the latest stable Gradle version. As most of us would really be using the latest stable versions.

Please look into this issue and update us. 

Below is the attached ss
![Screenshot from 2021-03-23 16-55-48](https://user-images.githubusercontent.com/43731599/112139353-ac12de00-8bf8-11eb-857e-1541ab9eff62.png)

**Comment by deepankarb** [comment]
So downgrading is not possible and we are tied to `4.2-beta-02` currently. Till we hit a stable AS 4.2 here are some workarounds:

* Switch to your AGP version e.g. `4.2-beta-06` or whatever studio beta you are on by modifying `deps.gradle`. Cons: You have to be careful about not checking in your gradle version changes to `deps.gradle` (i.e. revert before commit or don't add `deps.gradle` to the index)
* Use command line gradle wrapper `gradlew` instead of studio for `spotlessApply`, `connectedCheck` etc. Cons: Additional RAM consumption.

**Comment by Ana2k** [comment]
> So downgrading is not possible and we are tied to `4.2-beta-02` currently. Till we hit a stable AS 4.2 here are some workarounds:
> 
> * Switch to your AGP version e.g. `4.2-beta-06` or whatever studio beta you are on by modifying `deps.gradle`. Cons: You have to be careful about not checking in your gradle version changes to `deps.gradle` (i.e. revert before commit or don't add `deps.gradle` to the index)
> * Use command line gradle wrapper `gradlew` instead of studio for `spotlessApply`, `connectedCheck` etc. Cons: Additional RAM consumption.

 @deepankarb ,agreed with you and @joiskash 's  instructions on fix #337 helped immensely, but there is a bug I found here.

You need to explicitly install Android Sdk:29 to get the gradle to work. 
Else, the gradle build fails.
