### ISSUE TITLE
Replace capitialize() with capitalize(Locale.ROOT)

### ISSUE THREAD

**Issue by Manikant25** [google/android-fhir#340]
**Describe the bug**
This is a suggestion given by android studio to use capitalize(Locale.ROOT)
`Implicitly using the default locale is a common source of bugs: Use capitalize(Locale) instead. For strings meant to be internal use Locale.ROOT, otherwise Locale.getDefault().`

**Component**
SDC gallery app

**To Reproduce**
1. Double click shift
2. Search for  `ResourceMapper.kt`
3. Scroll down to `line 104`

**Expected behavior**
Not as such behavior change.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a3
 - Android version: 11
 - Build number: qssi-user 11 RKQ1.200903.002 V12.0.6.0.RFQMIXM

**Additional context**
If this is a valid issue, I can send PR.

**Comment by jingtang10** [comment]
We shouldn't make this change. The capitalization is used for reflection. The method name doesn't change depending on the user's locale. The current code is correct.

Instead, please add `@SuppressLint("DefaultLocale")`.
