### ISSUE TITLE
Redundant Namespace in XML

### ISSUE THREAD

**Issue by Manikant25** [google/android-fhir#342]
**Describe the bug**
There is an extra namespace declaration in the child view.

**Component**
 SDC gallery app

**To Reproduce**
1. Go to datacapure module
2. Click on res
3. Scroll down to 'layout'
4. click on questionnaire_item_radio_group_view.xml

**Expected behavior**
The parent view already has a namespace, so there is no need to declare again in child view.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: xiaomi mi a3
 - Android version: 11
 - Build number:  qssi-user 11 RKQ1.200903.002 V12.0.6.0.RFQMIXM

**Additional context**
N/A

**Comment by epicadk** [comment]
since #344 was merged this can be closed.
