### ISSUE TITLE
Add chore issue template

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#350]
**Is your feature request related to a problem? Please describe.**
Addition of Chore template for changes in documentation-workflow-dependency related code changes.
This will increase the clarity of issue type.

**Describe the solution you'd like**
Adding a separate issue template.

**Describe alternatives you've considered**
Making further issue template changes as required by code reviewers.

**Comment by Ana2k** [comment]
@jingtang10 @deepankarb I would like to implement this feature.

**Comment by jingtang10** [comment]
I'm not sure "chore" is the language I would use here. I think there're the following issue types that might be worth adding:

- research: there're lots of research tasks we need to create and manage. things to write include background, goal, methodology
- code health: refactoring, improving testing infrastructure, documentation can probably fall into this category
- process: builds and releases, communications, templates (e.g. this issue itself)

**Comment by Ana2k** [comment]
@jingtang10 I have updated the issue templates as instructed.
 Please have a look and let me know if further changes are required.
