### ISSUE TITLE
Rename code-of-conduct.md to gsoc-guidelines.md

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#355]
Currently, the [code-of-conduct.md](https://github.com/google/android-fhir/blob/master/docs/code-of-conduct.md) file contains Google Open Source Community Guidelines. 

So, it should be renamed to differentiate from another  file [CODE_OF_CONDUCT.md](https://github.com/google/android-fhir/blob/master/CODE_OF_CONDUCT.md) .

**Comment by Ana2k** [comment]
@jingtang10 @deepankarb  I would like to work on this issue.

**Comment by jingtang10** [comment]
i see we have 2 code of conduct docs. we should merge them. but i don't understand why one of them needs to be renamed to gsoc-guidelines.

**Comment by Ana2k** [comment]
> i see we have 2 code of conduct docs. we should merge them. but i don't understand why one of them needs to be renamed to gsoc-guidelines.

Ok sure I am creating a pr and merging them. 
Thank you for the specifics.

**Comment by jingtang10** [comment]
did you see any instructions on creating gsoc-guidelines.md from gsoc?
