### ISSUE TITLE
Low border visibility for outline styled edit text fields when dark mode is enabled

### ISSUE THREAD

**Issue by sakets3010** [google/android-fhir#368]
**Describe the bug**
As discussed with @jingtang10 in the comment ,https://github.com/google/android-fhir/issues/163#issuecomment-804018707, the borders of the material edit text fields are not visible for my device with dark mode enabled (screenshots 1 and 2 for reference, notice how the field borders are visible when clicked upon but not otherwise)

When tested after disabling dark mode, the borders are visible (screenshot 3)

**Component**
 SDC gallery app

**To Reproduce**
1. Go to the sdc gallery app and enable your device's dark mode
2. Click on "Real-world lifelines questionnaire"
3. Go to the "General questions" and click on any one of the available text fields

**Expected behavior**
one should be able to view the field borders for the edit text fields 

**Screenshots**
<img src="https://user-images.githubusercontent.com/63781668/111962110-e9536f00-8b17-11eb-9ecc-5e462697c916.jpg" width="200">  <img src="https://user-images.githubusercontent.com/63781668/111962166-fcfed580-8b17-11eb-8d58-5ee679cda2e6.jpg" width="200"> <img src="https://user-images.githubusercontent.com/63781668/111991336-32b4b600-8b3a-11eb-89a6-28abe502b1f1.jpg" width="200" >

**Smartphone :**
 - Device: Redmi note 7 pro
 - Android version: 10 QKQ1.190915.002

**Comment by sakets3010** [comment]
willing to add dark mode support for the app if required. Thanks!

**Comment by jingtang10** [comment]
I'm on a Pixel 4a
Android version: RQ2A.210405.005

[
![Screenshot_20210323-091831](https://user-images.githubusercontent.com/28757340/112123988-c5e10080-8bb9-11eb-8f4a-d1d9f1026243.png)
](url)

**Comment by Ana2k** [comment]
@sakets3010 its working on my phone<Samsung Galaxy M21>. 
Have you tried updating you Android version to the latest ?

**Comment by hk022** [comment]
i can contribute in this Bugs.

**Comment by sakets3010** [comment]
@Ana2k yes i did, probably has something to do with MIUI because its working fine on other phones

**Comment by santosh-pingle** [comment]
<img width="435" alt="Screenshot 2023-03-03 at 4 55 10 PM" src="https://user-images.githubusercontent.com/86107848/222708436-2db7794a-06c2-4a6b-9f98-0b441f2c4403.png">

**Comment by santosh-pingle** [comment]
Issue was fixed.
