### ISSUE TITLE
Support date and date time in search

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#375]

**Comment by jingtang10** [comment]
https://github.com/OpenSRP/fhircore/issues/20

**Comment by epicadk** [comment]
I'd like to work on this

**Comment by fredhersch** [comment]
@jingtang10 is this pending PR review?

**Comment by epicadk** [comment]
Solving conflicts.

**Comment by fredhersch** [comment]
@epicadk how are you doing on this? any updates?

**Comment by epicadk** [comment]
@fredhersch PR is pending review
