### ISSUE TITLE
Support contains for string search

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#376]
related to https://github.com/OpenSRP/fhircore/issues/20 but this shoud not block it as the first version would target at simplest use case with exact match.

See spec https://www.hl7.org/fhir/search.html#modifiers

**Comment by epicadk** [comment]
Related to #414. We can still support contains without full text search however according to the accepted answer on this [question](https://stackoverflow.com/questions/14290857/sql-select-where-field-contains-words) the full text search is faster
