### ISSUE TITLE
SDC Population

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#377]
See http://build.fhir.org/ig/HL7/sdc/populate.html

we need to design an API and implement this spec. probably the reverse of [`ResourceMapper.extract`](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt#L58) so it would take a `Questionnaire` and `Base` and returns a `QuestionnaireResponse`.

**Comment by s-ayush2903** [comment]
Seeking approval to add it to my list and push a fix.

**Comment by maanuanubhav999** [comment]
@s-ayush2903 can I work on this?  I am trying to contribute and get some insights of the project and I think this would be good start.  @jingtang10

**Comment by jingtang10** [comment]
Hi both - contribution is welcome but please write down your proposed solution and have a discussion before working on anything to avoid going down the wrong route. thanks.

**Comment by jingtang10** [comment]
marking this as duplication as #273
