### ISSUE TITLE
Migrate hardcoded strings to strings.xml value file

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#379]
**Is your feature request related to a problem? Please describe.**
Strings in value file, make for easy changes in UI, reusability etc.

**Describe the solution you'd like**
Migrate the hardcoded strings to strings.xml file.

**Describe alternatives you've considered**
N/A

**Additional context**
One example file includes:https://github.com/google/android-fhir/blob/master/core/src/main/java/com/google/android/fhir/resource/Resources.kt
---> Line 30-37

**Would you like to work on the issue?**
Yes.

**Comment by epicadk** [comment]
Which context would you use to fetch the strings ?

**Comment by jingtang10** [comment]
I don't think we typically do l10n or i18n on error messages. Is there any other example?

**Comment by Ana2k** [comment]
> I don't think we typically do l10n or i18n on error messages. Is there any other example?

I found quite a few hardcoded strings throughout the code base eg. Xml files, in snackbar etc.
I was thinking of making a PR migrating all I can find to string values file, and then you can suggest required changes?

Secondly, for illegalErrorExceptions in try-catch blocks, same message is written across different files.
Re-using that same string as value, will reduce redundancy for further added files.

**Comment by jingtang10** [comment]
I think we should use the XML files for user-facing strings. So snackbar -> yes, but exceptions -> no. What do you think?

**Comment by Ana2k** [comment]
> I think we should use the XML files for user-facing strings. So snackbar -> yes, but exceptions -> no. What do you think?

I have migrated almost all the user-visible strings I could find(mostly XML and snackbar)
Most exceptions message where relevant and function specific.

Except at one place I saw a bit of redundancy.  
You can review it, and suggest further changes (like whether to keep it or drop it)?
