### ISSUE TITLE
Add unit test for the Util.kt file in the core module

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#380]
**Describe the solution you'd like**
Add unit test for the Util.kt

**Additional context**
#233 issue number adds a similar point.

**Would you like to work on the issue?**
Yes.

**Comment by jingtang10** [comment]
why instrumentation rather than unit?

**Comment by Ana2k** [comment]
> why instrumentation rather than unit?

Yupp unit test. Sorry my mistake.

**Comment by omarismail94** [comment]
Cleaning things up. Closing as UtilTest now exists
