### ISSUE TITLE
Add android test for FhirEngineImpl.kt

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#381]
**Describe the solution you'd like**
Add android test for FhirEngineImpl.kt

**Additional context**
#233 describes a similar issue.

**Would you like to work on the issue?**
Yes.

**Comment by deepankarb** [comment]
IMHO `FhirEngine` is too big to take a first shot at. I suggest you at the existing tests for any `Dao` or sync and send an improvement PR first.

**Comment by Ana2k** [comment]
> IMHO `FhirEngine` is too big to take a first shot at. I suggest you at the existing tests for any `Dao` or sync and send an improvement PR first.

I was working on the small-medium test files in core module, and I guess you are right.
If I am not wrong this falls under the large-tests?
For now, I will work on getting better at writing larger test files?
 
PS: Thanks for the link on #367

**Comment by omarismail94** [comment]
Cleaning things up. Closing this FhirEngineImplTest exists
