### ISSUE TITLE
Support encryption of sqllite DB with SQLCipher

### ISSUE THREAD

**Issue by vincent-karuri** [google/android-fhir#392]
**Is your feature request related to a problem? Please describe.**
Due to the sensitive nature of medical data, we need to re-assure users of their data privacy. This issue seeks to address that by supporting encryption of data generated when using the SDK.

**Describe the solution you'd like**
We have a related discussion [here](https://github.com/OpenSRP/fhircore/issues/35#issuecomment-801774240) around possibly integrating with SQLCipher.

**Describe alternatives you've considered**
None at the moment. Open to discussion.

**Additional context**
https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-android-with-room SQLCipher + Room integration

**Would you like to work on the issue?**
Open to it

**Comment by vincent-karuri** [comment]
Maybe a separate discussion is key management depending on the encryption strategy. And whether the option to encrypt can be exposed as an opt-in (configurable) feature to SDK users.

**Comment by jingtang10** [comment]
Related: https://github.com/sqlcipher/android-database-sqlcipher#using-sqlcipher-for-android-with-room

**Comment by fredhersch** [comment]
@vincent-karuri Assiged us to work on this together. I'll take a first pass at sketching out the requirements. Will be good to get your technical input. Thanks

**Comment by vincent-karuri** [comment]
np

**Comment by fredhersch** [comment]
Thanks @yigit for surfacing this. Looks very relevant: https://sonique6784.medium.com/protect-your-room-database-with-sqlcipher-on-android-78e0681be687
@jingtang10

**Comment by Tarun-Bhardwaj** [comment]
@stevenckngaa , @dustinking-google , could you please provide the ETA to close this issue?
