### ISSUE TITLE
Make string search case-insensitive by default

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#400]
**Is your feature request related to a problem? Please describe.**
String search is case-sensitive in the API by default.

**Describe the solution you'd like**
Make search case-insensitive by default. Probably should use `COLLATE NOCASE` in the SQL query.

This is releated to #376  

**Describe alternatives you've considered**
NA

**Additional context**
https://www.hl7.org/fhir/search.html#string indicates search should be case-insensitive by default.

**Would you like to work on the issue?**
This would be a good starter issue.

**Comment by maanuanubhav999** [comment]
@jingtang10  i would like to work on this.

**Comment by jingtang10** [comment]
yeah this is probably a small PR to send. please feel free to raise one. but please write down your plan here. also you should probably wait until #395 is merged.

**Comment by maanuanubhav999** [comment]
okay. Currently figuring out the API working and will be using the statement-level collation as asked above.

**Comment by maanuanubhav999** [comment]
@jingtang10 I need help here. We need to make every String search case-insensitive. Before that, we will need to complete #376 am I correct?

**Comment by Syed-Affan-Hameed** [comment]
Hi! @jingtang10 is this issue still open can I work on this 2/8 tasks are still incomplete.

**Comment by maanuanubhav999** [comment]
hello, @Syed-Affan-Hameed issue is completed, all it needed was some check. thanks.

**Comment by Syed-Affan-Hameed** [comment]
@maanuanubhav999 Can you suggest me some open issues?

**Comment by epicadk** [comment]
@jingtang10 the current solution will only work for ASCII text. Do we not plan on support other encodings?
