### ISSUE TITLE
Make the string search match the beginning of the string by default

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#401]
**Is your feature request related to a problem? Please describe.**
We do an exact match right now.

**Describe the solution you'd like**
Probably use `LIKE` operator in the SQL query.

**Describe alternatives you've considered**
NA

**Additional context**
https://www.hl7.org/fhir/search.html#string

See ongoing work in #395 

**Would you like to work on the issue?**
Good starter issue.

**Comment by rkodev** [comment]
@jingtang10 If this issue is still open, I'd like to work on it.

**Comment by rkodev** [comment]
This issue is closed by pr https://github.com/google/android-fhir/issues/376
