### ISSUE TITLE
Hardcoded Log tags

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#406]
**Describe the Issue**
Log tags have been hardcoded, individually in all log-tag statements. Instead, we should use, log-Tag with class names in every files, for all the log tags present in that file. 
This can be done, by defining a log-tag , inside the class, So that it can be reused , in every log-statements of that file. 

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
Hi @Ana2k - thanks for creating this issue this is great! Please feel free to send a PR!

**Comment by Tarun-Bhardwaj** [comment]
@Ana2k , any ETA to create  a pull request for the changes?

**Comment by Ana2k** [comment]
> @Ana2k , any ETA to create a pull request for the changes?

I am currently working on a couple of fhir engine test files.
As soon as they are done, will make a pr for this.

**Comment by omarismail94** [comment]
Cleaning things up. Closing as we use Timber now which takes care of this
