### ISSUE TITLE
Use Constant Files to store constants

### ISSUE THREAD

**Issue by Ana2k** [google/android-fhir#408]
**Describe the Issue**
While exploring the code I found that there were some constants defined for every page. 
Some of these constants like the URLs were defined repeatedly, across different files. 

So we should have a constant.kt file which will store all the constant values used in the app. 
This will enhance app integrity overall.

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
Thanks for raising this issue.

I quite strongly disagree with the general approach of putting all constants in a single file per module. I don't understand the benefits of it. From a code readability perspective, you don't want to have to open up a different file every time you want to look up a constant value. It's too much cognitive burden and makes debugging more difficult. Keep things that are related close together.

Yes there are instances where you might want to create a file for globally useful constants. But not in the cases in the PR linked here.

There's this post that explains it quite eloquently: https://stackoverflow.com/questions/6220726/where-do-you-keep-constants-used-throughout-your-application

I will close this issue.
