### ISSUE TITLE
Research Full-text search (FTS)

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#414]
**Describe the issue to be researched**
The usability and methodology of adding FTS support.

**Describe the goal of the research**
Produce:
- Use cases
- Potential technology sulution
- API changes
- Estimate of eng effort
- Performance implications

**Describe the methodology**
For implementers to provide details 

**Would you like to work on the issue?**
No :)

**Comment by epicadk** [comment]
Sql cannot use an index if the argument to like starts with a wildcard.  The full text search would help here. 
However the obvious drawback of FTS is the increased size of the index. 
The use case is the string contains modifier used in string searches (don't really see any other use case). FTS can be enabled like [this](https://developer.android.com/reference/androidx/room/Fts4). We could just change the exisitng string index table to an FTS table. It wouldn't break anything it would only be an internal change in the `StringIndexEntity.kt` file and changing the SQL queries for string search in the MoreSearch.kt file. The Performance for the contains function would be enhanced (it would be similar to using indexs for queries that start with a wildcard)

**Comment by epicadk** [comment]
We would also need to update the roboelectric dependency because the current one has some issue in creating the FTS table

**Comment by fredhersch** [comment]
- [ ] Determine if FTS is required
- [ ] If so, what is the priority
- [ ] What are the approaches and pros and cons

**Comment by fredhersch** [comment]
We are trying to get to some level of resolution for this. As it stands today, we can't see a need for implementing FTS. The search use cases and implementation of the FHIR search specification is documented here #484 

Current thinking is to keep FTS on the backlog for now and we can revisit if there is a clear use case / need from the community.

Please let me know if there are strong objections to this and share the use case / rationale.

Thanks.

cc: @rkodev @joiskash @pld

**Comment by f-odhiambo** [comment]
I think we can deprioritize this for now unless there is a strong use case for it which doesn't seems to be the case at the moment

**Comment by fredhersch** [comment]
Outcome of the research task:

- The main requirement here is for fuzzy search on Patient name to avoid re-registering (and duplicates) due to a mis-spelt name.
- However, creating a FTS index has a storage cost

**Proposed solution** is to enable this as an option that implementers could enable. By default it will be disabled

cc: @pld @f-odhiambo @joiskash
