### ISSUE TITLE
Support minValue maxValue in the sdc library for Decimal, Date and DateTime values

### ISSUE THREAD

**Issue by kunjan8794** [google/android-fhir#415]
This issue is a followup issue for #164

**Comment by jingtang10** [comment]
There's also `Date` and `DateTime` to handle. Happy for you to either update the title of this issue or create a new one.

**Comment by kunjan8794** [comment]
@jingtang10 updated the title

**Comment by vincent-karuri** [comment]
@jingtang10 I can help here

**Comment by jingtang10** [comment]
@kunjan8794 is there a way to divide this issue to parallelise?
