### ISSUE TITLE
Datacapturegallery - date value gets minus by one month upon selecting time value in dateTime input type

### ISSUE THREAD

**Issue by kunjan8794** [google/android-fhir#425]
**Description**
If the questionnaireItem type is dateTime, there will be two editTexts, one for selecting a date and other one for selecting time. If we select 2021-04-05 as date, and the go on selecting the time, after time is selected, the month value in the date editText gets substracted by one. i.e if I have selected date as 2021-04-05 , it becomes 2021-03-05 as soon as we select time. The application also crashes if we choose January month and then try to select the time.

**Component**
SDC datacapturegallery

**To Reproduce**
1. Go to a questionnaire having dateTime component
2. Click on date field and select a date
3. Then continue selecting the time
4. Observe the value you selected for date editText. You will see a month lesser than whatever you selected before.

**Expected behavior**
The date value should remain intact after selecting the time.

**Comment by jingtang10** [comment]
Thanks for filing this @kunjan8794.

In the fix  to the month value here needs to be incremented by 1: https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt#L103

**Comment by jingtang10** [comment]
and this is why we need better integration tests.

**Comment by jingtang10** [comment]
#305
