### ISSUE TITLE
Robust signals for upload operation outcome result

### ISSUE THREAD

**Issue by deepankarb** [google/android-fhir#440]
We need a robust and consistent signal to determine the result of an upload operation. Current impl depends on `OperationOutcome` response from server which does not have a strong specified indicator of results esp. in case of success.

Cursory search on chat.fhir.org is indicative that the practice in community is to look at HTTP response codes to infer operation result and use `OperationOutcome` (which can be coerced with `Prefer:` header) for details about errors.

_see https://github.com/google/android-fhir/pull/437#discussion_r612365815 for context_

**Comment by Tarun-Bhardwaj** [comment]
Closing the issue as this is now obsolete.
