### ISSUE TITLE
Allow custom implementation of views in the sdc lib

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#447]
**Is your feature request related to a problem? Please describe.**
At the moment the sdc library will render any questionnaire item based on the questionnaire item type (also taking into consideration the item control extension if present). But there're cases where developers might need custom rendering of specific widgets. We should allow this. 

**Describe the solution you'd like**
The adapter https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt is where the type of widget is selected for each questionnaire item. We should expose an interface for the developer to intercept and provide their own implementation.

**Describe alternatives you've considered**
N/A

**Additional context**
#138 is a draft PR (subsequently closed) but should give a good idea of what's needed here.

**Would you like to work on the issue?**
No.

**Comment by vincent-karuri** [comment]
@jingtang10 I could pick this up. I see it's marked as low priority.

**Comment by fredhersch** [comment]
**User story:** As a developer I can define my own UI elements for Questionnaire items in the Questionnaire that can then be rendered by the SDC Library

Please review the draft PR #127 as a reference for earlier prototype implementation

**Comment by vincent-karuri** [comment]
@jingtang10  don't think I have permissions to open a pr
