### ISSUE TITLE
Fetch resource by Id

### ISSUE THREAD

**Issue by rkodev** [google/android-fhir#452]
**Is your feature request related to a problem? Please describe.**
Add ability to find or fetch a resource by Id

**Describe the solution you'd like**
Load a resource from the local data source by the resource Id. This can either return the resource from the local database or either `null` or an Optional<*> object

**Describe alternatives you've considered**
N/A

**Additional context**
This is useful when fetching a resource with a known ID i.e navigating from a ListView to a Patient's Detail View.

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
The current API is here: https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/FhirEngine.kt#L49

```
suspend fun <R : Resource> load(clazz: Class<R>, id: String): R
```

Is there anything else you need here?

**Comment by rkodev** [comment]
@jingtang10 This works
