### ISSUE TITLE
Answer selected by user changes automatically in Radio Button

### ISSUE THREAD

**Issue by MuhammadSalman-7214** [google/android-fhir#455]
**Describe the bug**
Radio Button answer selected by user changes to some other radio button options. For example you have one radio button with different options and you select any of the option as answer, and similarly you have another radio button with multiple options as well. You select second option as an answer to first radio button and select fourth option to second radio button. Now change the answer selected of the first radio button from second option to first option. Now go to second radio button and you'll see that the answer of the second radio button has automatically changed to the option you selected for the first radio button, in our case the answer of the second radio would have been changed from fourth option to first option as we selected first option as an answer to first radio button. 

**Component**
SDC library

**To Reproduce**
Same as description of the bug

**Expected behavior**
Expected behavior was the answer of the second radio button shouldn't changed automatically, with changing of the first radio button answer   

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nexus 6P
 - Android version: 10
 - Build number: 200715.0026695061
 - Version 29

**Additional context**

**Would you like to work on the issue?**
This issue can be solved by person who write the code of Radio buttons in sdc library

**Comment by jingtang10** [comment]
Thanks for creating this issue!

Can you do an `adb shell screenrecord` and upload the video here? Thanks!

@joiskash

**Comment by MuhammadSalman-7214** [comment]
https://user-images.githubusercontent.com/64642723/116402614-10533e00-a846-11eb-9114-91e5eef168e4.mp4

**Comment by joiskash** [comment]
Hi @MuhammadSalman-7214 please have a look at #459 . Pull the branch and check if the issue is fixed for you. I have tested it on my side. Thanks!
