### ISSUE TITLE
Add support for count operation in  Search 

### ISSUE THREAD

**Issue by rkodev** [google/android-fhir#458]
**Is your feature request related to a problem? Please describe.**
Adding ability to return results such as count based on a query without returning all the records from the query

**Describe the solution you'd like**
Return the number of Resources based on a search/filter parameter

**Describe alternatives you've considered**
Possible but with a massive performance penalty, return all objects from the query and get the size of collection

**Would you like to work on the issue?**
Yes

**Comment by jingtang10** [comment]
@rkodev is it preferable to modify the existing api to include a result count or something like that? a bit like bundle in FHIR.

**Comment by rkodev** [comment]
@jingtang10 Yes implementing a bundle can be helpful in paging requests and showing the number of pages.
