### ISSUE TITLE
Add autoComplete UI control item for inlined answerOptions [draft]

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#469]
**Is your feature request related to a problem? Please describe.**
As a user when looking up a value in a selection list I should be able to find matches based on text entered

**Describe the solution you'd like**
- [ ] For a valid FHIR questionnaire with answerOption options, when a user starts to type the list of options is filtered
- [ ] Selecting the option populates the relevant field with the value
- [ ] On change of state the field holds the value selected

**Additional context**

- The scope of this is for *inlined answerOptions*. 
- Support for contained valueSets in out of scope for now

**Example item**

!!Is missing extension for autoComplete
```
           {
              "linkId" : "past-medical-history",
              "prefix" : "1.1",
              "text" : "Past Medical History",
              "type" : "choice",
              "repeats" : false,
              "answerOption" : [
                {
                  "valueString" : "Diabetes"
                },
                {
                  "valueString" : "Hypertension"
                },
                {
                  "valueString" : "High Cholesterol"
                }
              ]
            }
```
**UI designs for how this should look**

**Comment by omarismail94** [comment]
I think we have achieved this with AutoCompleteViewAnswerOption, and will close this issue. Feel free to re-open if that's incorrect
