### ISSUE TITLE
Support prefixes in search: eq, ne, gt, lt, ge, le

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#474]
**Is your feature request related to a problem? Please describe.**
https://www.hl7.org/fhir/search.html#prefix

**Describe the solution you'd like**
Design and implement the change to the search API

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
No

**Comment by epicadk** [comment]
#436 & #419 add these prefixes for number and date. Is this what you had in mind or it is something else?

**Comment by epicadk** [comment]
Most of these are supported for Date and Number ( see #436 and #419 ) I'll add them for quantity types.

**Comment by epicadk** [comment]
Update, working on this. Will open a pr soon.

**Comment by Tarun-Bhardwaj** [comment]
@epicadk, thanks for the update. Is there an ETA you have for completing the code changes for this?

**Comment by epicadk** [comment]
I'm still searching for a library/any other solution that would help convert units to UCUM base units. I can get the rest of it done in around a week i.e. search on quantity types without canonical matches.

**Comment by Tarun-Bhardwaj** [comment]
@epicadk , were you able to move ahead with this issue? Any ETA that you can provide for completion?

**Comment by epicadk** [comment]
Sorry, slipped my mind, I'll open a pr that adds basic functionality by tomorrow.

**Comment by Tarun-Bhardwaj** [comment]
Thanks @epicadk. By adding basic functionality, are there any changes that are being excluded from the PR for now or would it cover the entire scope mentioned as part of this issue? I assigning it to a reviewer in the meantime.

**Comment by epicadk** [comment]
Yup, all functionality has been added except for date approximate as discussed here. https://github.com/google/android-fhir/pull/419#discussion_r644688966. Will discuss with @jingtang10 and get that done as well. After that , it should not take more than a day to complete.

**Comment by epicadk** [comment]
FYI https://github.com/google/android-fhir/issues/568

**Comment by epicadk** [comment]
Re-opened because still need to address #568.

**Comment by Tarun-Bhardwaj** [comment]
> Re-opened because still need to address #568. We could also close this and just have #568. @Tarun-Bhardwaj

@epicadk , thanks Aditya. Have assigned #568 to you. Let's keep #474 open until #568 is addressed as they both are closely linked. CC @jingtang10
