### ISSUE TITLE
Support search parameter common for all resources

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#481]
**Is your feature request related to a problem? Please describe.**

Currently we do not support  Search parameter for all resources

**Describe the solution you'd like**

Support  Search parameter for all resources
**Additional context**
 
https://www.hl7.org/fhir/search.html#all

**Would you like to work on the issue?**

Yes

**Comment by Tarun-Bhardwaj** [comment]
@epicadk , could you please provide the target date for closing this issue and the estimated effort pending on this?

**Comment by epicadk** [comment]
> @epicadk , could you please provide the target date for closing this issue and the estimated effort pending on this?

I've linked a pr. It's pending review.
