### ISSUE TITLE
Use proper transactions in the db code (instead of @Transaction)

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#485]
I was seeking the code to find what i was referring to but just found another issue, these Transaction annotations are no op:
https://github.com/google/android-fhir/blob/1992c7a03e13f71a88bff72177901bc048237729/engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt#L64

Because that is not a class Room parses. Transaction annotation only works on Room DAO's so this code needs to use a real transaction (`db.withTransaction {}` )

The main reason i asked for an update was because I thought we had some TypeConverteer's that needs other values injected but seems like we don't have that case. Regardless, it is still good to update.

_Originally posted by @yigit in https://github.com/google/android-fhir/issues/473#issuecomment-841326246_

**Comment by FikriMilano** [comment]
@jingtang10 just to clarify.
We have to change the use of @Transaction annotation to `db.withTransaction {}`

Is that right?
If yes, then can I give it a try?

**Comment by jingtang10** [comment]
Yes!

**Comment by FikriMilano** [comment]
Thank you for your trust!
