### ISSUE TITLE
Handle repeated answers in questionnaire validation

### ISSUE THREAD

**Issue by stevenckngaa** [google/android-fhir#487]
The [validation framework](https://github.com/google/android-fhir/tree/master/datacapture/src/main/java/com/google/android/fhir/datacapture/validation): only validates the first answer from QuestionnaireResponseItemComponent. Suggest to validate all answers.

**Comment by jingtang10** [comment]
https://github.com/google/android-fhir/blob/a9d95db49da6e99c3dbe06f3c81846b4db019059/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/PrimitiveTypeAnswerMaxLengthValidator.kt#L37
https://github.com/google/android-fhir/blob/a9d95db49da6e99c3dbe06f3c81846b4db019059/datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValueConstraintExtensionValidator.kt#L38
