### ISSUE TITLE
Use dependency management improvements in Gradle 7.0

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#492]
**Describe the Issue**

for future reference, gradle 7.0 adds a much nicer way to define dependencies:

https://docs.gradle.org/7.0/release-notes.html#dependency-management-improvements

_Originally posted by @yigit in https://github.com/google/android-fhir/pull/482#discussion_r636529647_

**Would you like to work on the issue?**
Maybe...

**Comment by FikriMilano** [comment]
@jingtang10 can I work on this?

**Comment by FikriMilano** [comment]
https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#changes_7.0
https://docs.gradle.org/7.0/userguide/variant_attributes.html#sub:jvm_default_attributes

**Comment by jingtang10** [comment]
@FikriMilano so sorry - please feel free to go ahead with this

**Comment by FikriMilano** [comment]
No worries - thanks!

**Comment by FikriMilano** [comment]
cc @f-odhiambo

**Comment by omarismail94** [comment]
Closing this as we are at Gradle 8 now
