### ISSUE TITLE
Adopt "Squash and Merge" strategy

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#498]
**Describe the Issue**
There are [3 merge strategies](https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits) we can use on GitHub.

- Create a merge commit
- Squash and merge
- Rebase and merge

We have been using the first one for all PRs as far as I know.

@kevinmost raised a really good point:

> I've noticed recently that the git commit history is quite messy 🙂

> I think that this is mostly due to PRs being merged with the default Github strategy, which merges a submitted PR into master.

> You can currently submit a PR using "Merge (Squash)", as I did here https://github.com/google/android-fhir/pull/496. You can see near the top of my attached git log screenshot that that commit is flat + linear on top of master, which IMO makes the master branch history look a lot cleaner.

> Merge (Squash) is currently optional. Are there any objections to making this the default + only strategy for submitting Github PRs?

![image (2)](https://user-images.githubusercontent.com/28757340/119635517-ae1d3700-be0b-11eb-8e96-c704905665ac.png)

> Switching to this strategy shouldn't change anyone's workflow. The main difference is that the master branch will become strictly linear, with one commit per submitted PR

I think we can probably all agree that rebase and merge is not a great strategy. For the first two strategies, there are people who prefer one or the other on the internet:

- https://blog.developer.atlassian.com/pull-request-merge-strategies-the-great-debate/
- https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/

To me, the second article puts forward a much stronger argument with clearly articulated benefits (especially around how the merge history can be more useful for blame, cherry-pick, rollback etc) rather than a "very simple" reason of "traceability and context" in the first article without further discussion or evidence.

So I would second @kevinmost's proposal. But creating this issue here to allow for further discussion from all contributors.

**Would you like to work on the issue?**
Yes I can adjust which ones of the three strategies are allowed for the codebase if we reach concensus here.

**Comment by jingtang10** [comment]
@pld @joiskash @ekigamba @Ana2k @epicadk @yigit @s-ayush2903 @shoaibmushtaq25 @rkodev @vincent-karuri

**Comment by jingtang10** [comment]
@kunjan8794

**Comment by epicadk** [comment]
Yup. I agree. We should squash and merge.

**Comment by deepankarb** [comment]
Thanks Kevin and Jing. I went through the second article and thought about it and why we should not do this. I couldn't think of any downside :) Let's switch to squash and merge. You have my axe!

**Comment by FikriMilano** [comment]
Definitely agree, the commit will become kind of a summary of the change

**Comment by jingtang10** [comment]
Thanks all -- seems we have pretty unanimous support.
