### ISSUE TITLE
Show related controls using the local language

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#499]
**Is your feature request related to a problem? Please describe.**
Show related controls using the local language e.g. prev / next buttons for pagination

**Describe the solution you'd like**
We might need to provide these translations

**Describe alternatives you've considered**
NA

**Additional context**
#465 

**Would you like to work on the issue?**
NA

**Comment by Ana2k** [comment]
hi @jingtang10 i wanted to work on this issue if this is still open.

**Comment by jingtang10** [comment]
obsolete
