### ISSUE TITLE
Create examples of custom style in the sdc gallery application

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#501]
**Is your feature request related to a problem? Please describe.**
We should create examples in the sdc gallery app to show how implementers can change the color/style/text appearance of the questionnaire to match their application.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
This could be hard-coded for certain questionnaires, or maybe we can even have a control panel where the user can choose from a list of colors, text appearances to customize the questionnaire.

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by FikriMilano** [comment]
@jingtang10 so we are going to add a theming feature that can change:
- Colour
- View Style
- Text Appearance

...for each questionnaire?
(1 control panel for each questionnaire)

Or the whole app?
(1 control panel in questionnaire list that applies to all questionnaire)

For the control panel, how about we use Bottom Sheet or do you have something to suggest?

**Comment by FikriMilano** [comment]
We have lots of header that can be customized in each questionnaire. For it's style, should we create only 1 header style then use it in all of the headers (except group header) or make specific one for each questionnaire?

For example from the screenshot below, we have edit text and date picker questionnaire. Both have their own header.
<img src="https://user-images.githubusercontent.com/62053304/127876346-f23d6754-3268-4b27-80f8-ee6c526a7d34.png" width="256">
