### ISSUE TITLE
Definition-based extraction: extracting multiple resources from a single questionnaire

### ISSUE THREAD

**Issue by ekigamba** [google/android-fhir#504]
As of https://github.com/google/android-fhir/tree/4892adbddf78f4fdef40d3f95bd5e2bb19424fdf, the ResourceMapper supports definition-based extraction only for a single Resource. The [FHIR SDC extraction](http://build.fhir.org/ig/HL7/sdc/extraction.html) defines three mechanisms for extraction. Based on the specification, definition-based is insufficient for the real-world use-cases as sampled from the current Ona OpenSRP apps.

Below are some of the use-cases:

| Use case  | Extracted Resources | Extraction method  | Reasons for extraction-method |
|----------|---------------------|--------------------|-------------------------------|
| 1. Register an OPD patient and their emergency/immediate contact | - Patient <br> | Definition-based | Extraction to a single resource
| 2. Register vaccinations given | - Encounter<br>- +1 Immunization <br>- Each Immunization referencing the Encounter | - StructureMap-based <br>- Definition-based (Encounter generated before) | Extraction to multiple resources requiring ID references between them
| 3. Register a pregnancy outcome where we can have multiple births and collect birth observations(eg. weight) | - Encounter <br> - +1 Patient <br> - +1 Observation ?? | ?? |
| 4. Child U5 registration <br> - Register child with birth weight, birth height, mother details, doses of TdV & mother's HIV status | - Patient (child) <br> - Observation (birth height) <br> - Observation (birth weight) <br> - RelatedPerson (Mother details with Patient reference to child) <br> - Patient (mother) <br> - Mother observations | - StructureMap-based | - Extraction to multiple resource <br> - Multiple resources of similar type <br> - References between patient and observation resources <br> - https://www.hl7.org/fhir/patient.html#maternity
| 5. ANC registration | - Patient | Definition-based | Extraction to a single resource
| 6. Maternity registration | - Patient <br> - OccupationData | - Definition-based | - Extraction of a single resource with extension on occupation <br> - Extraction of 2 resources with a one resource having a reference to the other resource

### Limitations of definition-based extraction

1. Generated resources cannot be linked/referenced to each other
2. Specification on handling multiple resources of the same type is shallow/non-existent eg. registering a child with two observations of the child's height and weight. This is an issue when resource switching is allowed since it becomes ambiguous which resource within the list of ResourceType 1 is being mapped. Misalignment and resource context switching is supported by defining the `questionnaire-itemExtractionContext`

![Screenshot from 2021-05-17 15-39-57](https://user-images.githubusercontent.com/31766075/119843574-59afaf80-bf10-11eb-8d17-270ab8aa4653.png)

### Open questions?

1. Can we autogenerate the resource id using an expression on the Questionnaire? Does this happen during population or during extraction?
2. Can we easily map it back the Resource? The Hapi FHIR core module breaks the standard by using a `Resource.id` of type `IdType` instead of the defined [id](https://www.hl7.org/fhir/datatypes.html#id) which should be a JSON String
3. Is there a way to copy/mirror the answer to another question? This would help us to add the references on the Questionnaire directly

### Original issue: https://github.com/opensrp/fhircore/issues/111#issue-877216091

**Comment by ekigamba** [comment]
@jingtang10 I think we can have the discussion here to get a solution

**Comment by jingtang10** [comment]
Thanks for the excellent write-up @ekigamba!

> ### Limitations of definition-based extraction
> 1. Generated resources cannot be linked/referenced to each other

This is definitely a limitation. To get around this, the application would either pre-determine the IDs and prepopulate the questionnaire (or use hidden questions and hidden answers in the questionnaire) or post-process the result of extraction. Not pretty, but workable.

> 2. Specification on handling multiple resources of the same type is shallow/non-existent eg. registering a child with two observations of the child's height and weight. This is an issue when resource switching is allowed since it becomes ambiguous which resource within the list of ResourceType 1 is being mapped. Misalignment and resource context switching is supported by defining the `questionnaire-itemExtractionContext`

According to the spec: `If creating, then for each occurrence of each item asserting a questionnaire-itemExtractionContext, a resource of the context type will be defined. It will be populated with answers to questions (hidden or not) that have a definition that matches the resource type of the context.` So I think it's definitely possible to define a questionnaire that extract two observations one for weight one for height. 

> ### Open questions?
> 1. Can we autogenerate the resource id using an expression on the Questionnaire? Does this happen during population or during extraction?

I'm not sure this is a problem with definition based extraction, or extraction in general. I think the commonly used approach is to have a hidden question for ID which is pre-filled by the application. Not sure how this can be done differently using structure map based extraction.

> 2. Can we easily map it back the Resource? The Hapi FHIR core module breaks the standard by using a `Resource.id` of type `IdType` instead of the defined [id](https://www.hl7.org/fhir/datatypes.html#id) which should be a JSON String

We might need to handle id as a special case.

> 3. Is there a way to copy/mirror the answer to another question? This would help us to add the references on the Questionnaire directly

Yes this is probably something that can be done more easily by structure map.

**Comment by syedowaisali90** [comment]
Hi @jingtang10 here is a sample patient registration questionnaire [json](https://github.com/opensrp/fhircore/blob/issue-184/android/app/src/main/assets/patient-registration.json) with two sections one is [Patient](https://www.hl7.org/fhir/patient.html) and the other is [RelatedPerson](https://www.hl7.org/fhir/relatedperson.html). Actually, need to find a proper way to get the multiple resources from the questionnaire response.

**Comment by ekigamba** [comment]
@jingtang10 Could you add your suggestions on achieving multiple resource extraction with referencing for the sample form in the comment above :arrow_up:? The questionnaire json has been linked

Initially, I assumed that the  `questionnaire-initialExpression`, `questionnaire-calculatedExpression` in combination with the FHIR queries and FHIRPath expressions would help auto-generate the UUID and possibly copy the value of another answer. It's not completely clear how this would look like

**Comment by jingtang10** [comment]
In the sdc spec for definition based extraction http://build.fhir.org/ig/HL7/sdc/extraction.html#definition-based-extraction:

> In some cases, the context of an element will switch. For example, an item might have a definition of "http://hl7.org/fhir/MedicationStatement#MedicationStatement.medicationReference" and a questionnaire-itemExtractionContext extension that shifts the context to "Medication". Subsequent children would then have definitions based on the "http://hl7.org/fhir/Medication" resource.

So I think what needs to happen in that json is to add `questionnaire-itemExtractionContext` to the group containing questions for a different type of resource. How's that?

**Comment by Kigamba** [comment]
@jingtang10 Yea, that's right. What about the referencing? I remember you had an elaborate idea around that

**Comment by ekigamba** [comment]
@jingtang10 Yea, that's right. What about the referencing? I remember you had an elaborate idea around that

**Comment by ekigamba** [comment]
Quick one, we are also aiming to add configurability as much as we can and prevent hardcoding logic as much as we can. Can we break("extend") the SDC standard and add constants/functions that can be replaced/executed  at the end of extraction eg.
1. `$UUID.generate()`  - To generate a UUID
2. `$this.linkId`  - To copy the value from another answer
For definition-based extraction only? The idea is to give it as make it just powerful enough that it covers the small weaknesses preventing it from being the default option.

This is going to be the last option

**Comment by Kigamba** [comment]
Links to FHIR chat questions on the use of `initialExpression` and `calculatedExpression` extensions

https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/calculatedExpression.20.26.20type/near/241787902
https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/Creating.20a.20Coding.20in.20FHIRPath/near/241785622

**Comment by Kigamba** [comment]
An example showing how to use `calculatedExpression` to calculate the BMI when the weight and height of a person are entered http://build.fhir.org/ig/HL7/sdc/examples.html#using-calculatedexpression-and-variable

**Comment by ekigamba** [comment]
Links to FHIR chat questions on the use of `initialExpression` and `calculatedExpression` extensions

https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/calculatedExpression.20.26.20type/near/241787902
https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/Creating.20a.20Coding.20in.20FHIRPath/near/241785622

**Comment by ekigamba** [comment]
An example showing how to use `calculatedExpression` to calculate the BMI when the weight and height of a person are entered http://build.fhir.org/ig/HL7/sdc/examples.html#using-calculatedexpression-and-variable

**Comment by ekigamba** [comment]
@jingtang10 
1. FHIRPath and FHIR expression cannot be used to generate a `UUID`
2. `calculatedExpression` can be used to copy the a value on another item through the FHIR Expression. The FHIR expressions can be used to access anything in the Questionnaire/QuestionnaireResponse via `%questionnaire` and `%resource`. However, if you are dealing with an Expression in a repeating group, you can't find the correct repetition that way, and need to rely on %context, which limits you to the item and its children. In that case you would want a variable on the repeating group. https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/calculatedExpression.20.26.20type/near/241937354

We can achieve UUID generation by adding a constant which can be implemented during population `$UUID.generate()`

**Comment by jingtang10** [comment]
@maimoonak FYI

**Comment by fredhersch** [comment]
@Tarun-Bhardwaj @ekigamba Is this issue still open?

**Comment by jingtang10** [comment]
we can extract multiple resources after #670 - that's correct.

@ekigamba 's comments on expressions will be addressed by multiple other tickets regarding expressions.

so i think this issue can be closed.
