### ISSUE TITLE
Review database failure model design+implementation (exceptions, failure mode, transaction)

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#510]
**Is your feature request related to a problem? Please describe.**
Current implementation needs to be reviewed. Related to this discussion https://github.com/google/android-fhir/pull/482#discussion_r636532906

**Describe the solution you'd like**
- Review current design and implementation
- Review existing thread
- Make any necessary outstanding changes
- Identify any additional requirements and prioritise on roadmap

**Comment by deepankarb** [comment]
Inputs from some senior devs @ Google:

>DatabaseImpl.kt LGTM. That being said I'm not a Room expert, but DatabaseImpl doesn't seem to be doing anything esoteric. The one question I have is how are the indexes handled.
>
>FhirSynchronizer.kt LGTM too. The only thing that pops up is that It downloads resource types sequentially (line47) , which could potentially be done concurrently, but if not in any critical path it's perfectly fine that way.

Opened #574 for second item.
