### ISSUE TITLE
Regarding android-fhir client

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#514]
**Describe the Issue**
[https://github.com/google/android-fhir/wiki/GSoC-Project-Ideas#android-fhir-client](url)

**There are few doubts regarding the project.**
1. I think the project will act as a combination of reference app and dc gallery app? am I correct here. How should we get started with it?
2. Should we make a sample design for the app.

**Comment by Manikant25** [comment]
@maanuanubhav999  I have the same doubts. My mentor told me he is waiting for someone from the organization before we start with the project. I guess we must wait for some time and do other stuff.

**Comment by maanuanubhav999** [comment]
okay, thanks @Manikant25

**Comment by ekigamba** [comment]
@Manikant25 @maanuanubhav999 We can try and define the scope for this during our next call. I think the design should come after we decide on the scope of the reference app(s)

**Comment by maanuanubhav999** [comment]
Sure @ekigamba I agree with you.
