### ISSUE TITLE
Enable view binding in reference 

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#515]
**Is your feature request related to a problem? Please describe.**
https://developer.android.com/topic/libraries/view-binding 

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
As we have already added view binding to sdc Gallery app it may be required here too.
#318 

**Would you like to work on the issue?**
yes

**Comment by epicadk** [comment]
Since compose will be stable by July (as mentioned at Google-IO) do you think it would make sense to use compose instead?

**Comment by maanuanubhav999** [comment]
Yes, sure. But when should we start shifting towards Compose?

**Comment by epicadk** [comment]
I think if @jingtang10 agrees we can start working on it immediately

**Comment by FikriMilano** [comment]
Honestly I don't think shifting to compose is necessary for us right now

**Comment by epicadk** [comment]
Why not? I think compose will be very popular and would be the way to build UI components going forward. Wouldn't hurt to use it in sample apps to show the SDK's usage.

**Comment by FikriMilano** [comment]
Yes it didn't hurt to use it and compose is the way to build UI components in the future. And we definitely need to add sample apps for our SDK using it.

But for now, I think we should focus in the issues that we have right now.

**Comment by FikriMilano** [comment]
@jingtang10 @Manikant25 @kunjan8794

**Comment by maanuanubhav999** [comment]
@FikriMilano you have a point but as @epicadk, I also think shifting to compose will be needed, Soon we will be working on the **android-fhir client** and if compose is used for it, future adoptable will be much simpler and also redoing the UI part could be reduced.

**Comment by FikriMilano** [comment]
True, @epicadk has a point too.
Sooner or later we will use compose, might as well use it now.

We just have to wait for @jingtang10 's approval.

**Comment by jingtang10** [comment]
@epicadk can you please open an issue to track the work to use jetpack compose.

@maanuanubhav999 please feel free to open a PR for view binding.

**Comment by maanuanubhav999** [comment]
Sure.
