### ISSUE TITLE
Nested items are still revealed after deselecting / removing the answer for the parent item

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#530]
**Describe the bug**
The SDC has a feature which hides nested items until the parent item has been answered. On removing the answer/ deselecting the option , the nested items are still visible and do not go back to the hidden state.

**Component**
 SDC library

**To Reproduce**
1. Go to datacapturegallery app. 
2. Click on Neonate record from New South Wales, Australia
3. Scroll down to Hep B give y/n
4. Press the checkbox - Date given will appear
5. Uncheck the check box - Date given remains

**Expected behavior**
Date given is supposed to go back to hidden state

**Screenshots**
![Initial](https://user-images.githubusercontent.com/48797364/120614619-0f30b480-c475-11eb-803d-df941e8660a6.jpg)
![answerSelected](https://user-images.githubusercontent.com/48797364/120614624-1061e180-c475-11eb-9440-cdad922e8b77.jpg)
![answerUnselected](https://user-images.githubusercontent.com/48797364/120614628-10fa7800-c475-11eb-93fa-dcdb90956210.jpg)

**Smartphone (please complete the following information):**
 - Device: One plus 7T pro
 - Android version: 10
 - Build number: QKQ1.200909.002

Originally reported by @f-odhiambo

**Comment by maanuanubhav999** [comment]
@joiskash, can I work on this?

**Comment by joiskash** [comment]
Sure , it fine by me :) cc: @Tarun-Bhardwaj @jingtang10

**Comment by jingtang10** [comment]
thanks for creating this issue!

**Comment by jingtang10** [comment]
repeating here what i posted in the PR: see this discussion: 
https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/EnableWhen.20behavior.20with.20operator.20.60exists.60

Basically i think this is expected behavior - we probably need to render boolean questions as 3 radio buttons yes / no / [empty] rather than just a checkbox. this is becase an answer 'false' is still an answer and will make nested items appear.

**Comment by jingtang10** [comment]
same applies to multiple choice questions -- if you can choose a list of codes you must be able to clear the answer also

**Comment by Tarun-Bhardwaj** [comment]
@maanuanubhav999 are you working on this issue?

**Comment by maanuanubhav999** [comment]
@Tarun-Bhardwaj  yes.

**Comment by Tarun-Bhardwaj** [comment]
@maanuanubhav999 , could you please provide an ETA for completing the code changes?

**Comment by maanuanubhav999** [comment]
@Tarun-Bhardwaj  I was having some trouble with the instrumental test otherwise the PR was ready.  If the tests start working, 4-5 days.

**Comment by Tarun-Bhardwaj** [comment]
> @Tarun-Bhardwaj I was having some trouble with the instrumental test otherwise the PR was ready. If the tests start working, 4-5 days.

@maanuanubhav999 , any progress on this issue?

**Comment by maanuanubhav999** [comment]
Hi, @Tarun-Bhardwaj I will update in 1-2 days. thanks
