### ISSUE TITLE
Clients have to use packagingOptions to filter duplicate META-INF/ files

### ISSUE THREAD

**Issue by kevinmost** [google/android-fhir#534]
Our dependency on `com.github.java-json-tools:json-patch` brings in multiple `META-INF/ASL-2.0.txt` and `META-INF/LGPL-3.0.txt` files to client projects. This will result in an error in apps that use the FHIR SDK like this:

```

* What went wrong:
Execution failed for task ':reference:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 4 files found with path 'META-INF/ASL-2.0.txt' from inputs:
      - /home/kmost/.gradle/caches/modules-2/files-2.1/com.github.java-json-tools/json-patch/1.13/c8b72249e50fe778e7df223e5b1fed1931a4a688/json-patch-1.13.jar
      - /home/kmost/.gradle/caches/modules-2/files-2.1/com.github.java-json-tools/jackson-coreutils/2.0/6374371261b91b829d10f21256b2feefdf8f0a78/jackson-coreutils-2.0.jar
      - /home/kmost/.gradle/caches/modules-2/files-2.1/com.github.java-json-tools/msg-simple/1.2/a06afa2d5d75c98e54ab370107930978fc3f9937/msg-simple-1.2.jar
      - /home/kmost/.gradle/caches/modules-2/files-2.1/com.github.java-json-tools/btf/1.3/6cf5405e214cbc83337a107cdef8401fb6aa6383/btf-1.3.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
```

Adding a `packagingOptions { ... }` block in the library is not enough, as these files are not actually present in the library, but end up getting merged into the client app from the transitive dependencies on json-tools, Jackson, and other libs.

We should try to fix this before beta, so that clients don't have to add the following block to their own `build.gradle`s:

```kt
  packagingOptions {
    exclude("META-INF/ASL-2.0.txt")
    exclude("META-INF/LGPL-3.0.txt")
  }
```

Some research:

https://stackoverflow.com/a/29829883/3204764

**Comment by kevinmost** [comment]
I've looked into this pretty extensively, and it doesn't seem like there is any action we can take here.

Unfortunately, the AGP (Android Gradle Plugin) does not consider the `android.packagingOptions` of libraries/dependencies when assembling an application jar. So our `excludes`/`pickFirst` options don't get transitively picked up by the consuming app.

Since we aren't actually including these duplicate files in our jar (they're part of our transitive dependencies), there's not much that can be done beyond making apps specify these `packagingOptions`.

Some reading:

[kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines/issues/2023#issuecomment-858644393) has this same issue; someone from JetBrains has confirmed that this is a limitation that they have to work around as well. Their [documentation](https://github.com/Kotlin/kotlinx.coroutines/tree/master/kotlinx-coroutines-debug#debug-agent-and-android) includes this workaround, just like ours.

[google/prefab](https://github.com/google/prefab/issues/118) also suggests this workaround. Includes a [buganizer bug](http://b/168777344) where there is consensus that this is the only way to fix this issue for now.

**Comment by sultanularefin** [comment]
I was facing this problem while producing a development built in a new RN application:

`* What went wrong:
Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 2 files found with path 'META-INF/DEPENDENCIES' from inputs:
      - /home/arefin/.gradle/caches/transforms-3/a3ac8ef0f2100cc8b5d126502fa8817e/transformed/jetified-httpclient-4.5.11.jar
      - /home/arefin/.gradle/caches/transforms-3/b7066b7bc7a676def30aa231d94c26c1/transformed/jetified-httpcore-4.4.13.jar
     Adding a packagingOptions block may help, please refer to
     https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.PackagingOptions.html
     for more information
`
I added this packaging options line **pickFirst 'META-INF/DEPENDENCIES'** in my app level build.gradle file's android Block like this:

`android {

    packagingOptions {
        pickFirst 'META-INF/DEPENDENCIES'
    }
 
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
       ...
    }

}`
