### ISSUE TITLE
Horizontal layout support for radio buttons in the datacapture library

### ISSUE THREAD

**Issue by shoaibmushtaq25** [google/android-fhir#542]
**Radio group/buttons horizontal layout is not supported in the datacapture library**
I added a patient gender as horizontal radio group with the `choiceOrientation` as `horizontal` in Patient questionnaire on implementer app but I found out the horizontal layout is not supported yet in datacapture library

```json
{
  "linkId": "1.0",
  "extension": [
    {
      "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-itemControl",
      "valueCodeableConcept": {
        "coding": [
          {
            "system": "http://hl7.org/fhir/questionnaire-item-control",
            "code": "radio-button",
            "display": "Radio Button"
          }
        ]
      }
    },
    {
      "url": "http://hl7.org/fhir/StructureDefinition/questionnaire-choiceOrientation",
      "valueCode": "horizontal"
    }
  ],
  "definition": "http://hl7.org/fhir/StructureDefinition/Patient#Patient.gender",
  "type": "choice",
  "text": "Gender:",
  "answerOption": [
    {
      "valueCoding": {
        "code": "F",
        "display": "Female"
      }
    },
    {
      "valueCoding": {
        "code": "M",
        "display": "Male"
      }
    }
  ]
}
```

**Solution**
We need to implement http://hl7.org/fhir/R4/extension-questionnaire-choiceorientation.html for radio-buttons

**Alternatives**
For now, I have made radio group as default vertical layout on implementer app

**Screenshot**
Expected result:
![Screenshot from 2021-06-08 13-44-21](https://user-images.githubusercontent.com/12672919/121153694-b6d82900-c85f-11eb-9890-e4b8539eead7.png)

Actual result:
![Screenshot from 2021-06-07 18-17-24](https://user-images.githubusercontent.com/31766075/121198969-358e8f80-c87b-11eb-8e3b-149b9cdf0cbc.png)

**Would you like to work on the issue?**
I am open to work on it or anyone else can pick it up

cc: @jingtang10 @ekigamba

**Comment by FikriMilano** [comment]
@shoaibmushtaq25 may I?

**Comment by shoaibmushtaq25** [comment]
> @shoaibmushtaq25 may I?

@FikriMilano Yeah sure, you can pick it up. Thanks for it. :+1:

**Comment by jingtang10** [comment]
Use the choice orientation extension:

http://hl7.org/fhir/uv/sdc/2019May/rendering.html#control-appearance

**Comment by ekigamba** [comment]
@jingtang10 Correct, I have updated the issue with the correct details. Are you OK with this? Should this be implemented to all choice type questions

**Comment by FikriMilano** [comment]
> Use the choice orientation extension:
> 
> http://hl7.org/fhir/uv/sdc/2019May/rendering.html#control-appearance

Ok, I will use this

**Comment by FikriMilano** [comment]
> @jingtang10 Correct, I have updated the issue with the correct details. Are you OK with this? Should this be implemented to all choice type questions

I think we might as well implement this for all choice type questions. I'm open for further suggestions though. @ekigamba @jingtang10 @shoaibmushtaq25

**Comment by FikriMilano** [comment]
As mentioned here,

> URL = http://hl7.org/fhir/StructureDefinition/questionnaire-choiceOrientation
choiceOrientation: Identifies the desired orientation when rendering a list of choices (typically radio-box or check-box lists).

Therefore, I plan to add horizontal layout support for radio-button and check-box.

**Comment by jingtang10** [comment]
> As mentioned here,
> 
> > URL = http://hl7.org/fhir/StructureDefinition/questionnaire-choiceOrientation
> > choiceOrientation: Identifies the desired orientation when rendering a list of choices (typically radio-box or check-box lists).
> 
> Therefore, I plan to add horizontal layout support for radio-button and check-box.

yeah that's fine. thanks for taking this up.

**Comment by FikriMilano** [comment]
cc @f-odhiambo
