### ISSUE TITLE
StructureMap-based extraction

### ISSUE THREAD

**Issue by ekigamba** [google/android-fhir#543]
**Is your feature request related to a problem? Please describe.**
Partly yes. 

1. Problem - Extracting complex multiple resources and performing transformations is currently not possible
2. FHIR Spec support - We need to support SDC StructureMap-based extraction mechanisms

**Describe the solution you'd like**
Defining a Questionnaire with the StructureMap reference and automatically getting the extracted resources when `ResourceMapper#extraction` is called with the `Questionnaire` and `QuestionnaireResponse`

### Scoping

- Change the `ResourceMapper#extraction` return type to `Bundle`
- Move definition based extraction functionality to a different function
- Add structuremap-based extraction functionality on a different function
- Both extraction functions should return a `Bundle`
- StructureMap-based extraction should only be used if there is a `questionnaire-targetStructureMap` extension on the Questionnaire root
- Fetch the StructureMap from the DB so that it can be invoked against the QuestionnaireResponse - The url of the StructureMap is retrieved from the extension's `valueCanonical`. Functionality for invoking a StructureMap on a resource is already implemented in the hapi-fhir `rg.hl7.fhir.r4.utils.StructureMapUtilities`.

### Handling of errors
- If the StructureMap execution fails, no data will be extracted from the Questionnaire
- If the StructureMap is not found, the extraction fails - We need to figure out a way to retry extraction

**Describe alternatives you've considered**
None

**Additional context**
http://build.fhir.org/ig/HL7/sdc/extraction.html#structuremap-based-extraction

**Would you like to work on the issue?**
Yes

**Comment by ekigamba** [comment]
@jingtang10 Could you take a look at this and see if this implementation is OK with you?

**Comment by jingtang10** [comment]
We still need a follow-up PR to convert the functions to suspend functions.

**Comment by ekigamba** [comment]
@jingtang10 I have created the issue [here](https://github.com/google/android-fhir/issues/666) as discussed
