### ISSUE TITLE
Add "required" text for required fields in Questionaire

### ISSUE THREAD

**Issue by Manikant25** [google/android-fhir#544]
**Is your feature request related to a problem? Please describe.**
No this is just an enhancement.

**Describe the solution you'd like**
Asterisks symbol can be added for the fields which have an attribute ``"required": "true"``.
``*`` indicates required fields as seen in the sample below.

<img width="311" alt="Screenshot 2021-06-11 002613" src="https://user-images.githubusercontent.com/55659857/121582499-b81a7900-ca4c-11eb-9a99-fc052e561330.png">

**Describe alternatives you've considered**
NA

**Additional context**
NA.

**Would you like to work on the issue?**
Yes

**Comment by Manikant25** [comment]
@jingtang10  If you like the feature, then may I start with it.

**Comment by epicadk** [comment]
#470 ?

**Comment by Manikant25** [comment]
> #470 ?

okay, thanks.

**Comment by Manikant25** [comment]
> #470 ?

#470 does show an asterisk for required fields.

**Comment by jingtang10** [comment]
@Manikant25 thanks for raising this - this is now an urgent need from two implementers.

@Manikant25 please feel free to send a pr asap - if you don't have time @santosh-pingle will work on this.

**Comment by Manikant25** [comment]
sure, I will try to send the PR by the end of this weekend.

**Comment by jingtang10** [comment]
@shelaghm can you please comment on the UX design of this issue?

**Comment by shelaghm** [comment]
This makes sense to me. I assume it will also be important to pair the astericks `*` with instructions that say `required question`. We are planning to test this in an upcoming usability study to learn if people are familiar with what `*` means.

From a UX perspective I recommend making the `*` the same color as the question text. In an error state it can be red to indicate that a response is missing to a required question.

**Comment by santosh-pingle** [comment]
@Manikant25 Any updates would you like to share on it?

**Comment by santosh-pingle** [comment]
Looking into it.

**Comment by santosh-pingle** [comment]
> This makes sense to me. I assume it will also be important to pair the astericks `*` with instructions that say `required question`. We are planning to test this in an upcoming usability study to learn if people are familiar with what `*` means.
> 
> From a UX perspective I recommend making the `*` the same color as the question text. In an error state it can be red to indicate that a response is missing to a required question.

@shelaghm 
Does it require to show * in instructions if required field is true, as it is already being shown in question text?
if yes, also is it (* in instructions) required to show in red color if it's in error state?

**Comment by shelaghm** [comment]
I suggest we use words to explain what * means by adding`required question` in the instructions text field.

<img width="213" alt="Screen Shot 2022-10-04 at 10 37 57" src="https://user-images.githubusercontent.com/86378921/193888321-6cc80301-3a35-4e06-a678-15f6c7d5dbc2.png">

Error state should look something like this screenshot. I don't think the asterisk needs to be red in error state, only the instructions text. What do you think?
<img width="408" alt="Screen Shot 2022-10-04 at 10 40 29" src="https://user-images.githubusercontent.com/86378921/193888779-532c6abe-c7ed-4d12-9245-8808528c6a86.png">

**Comment by santosh-pingle** [comment]
> I suggest we use words to explain what * means by adding`required question` in the instructions text field.
> 
> <img alt="Screen Shot 2022-10-04 at 10 37 57" width="213" src="https://user-images.githubusercontent.com/86378921/193888321-6cc80301-3a35-4e06-a678-15f6c7d5dbc2.png">
> 
> Error state should look something like this screenshot. I don't think the asterisk needs to be red in error state, only the instructions text. What do you think? <img alt="Screen Shot 2022-10-04 at 10 40 29" width="408" src="https://user-images.githubusercontent.com/86378921/193888779-532c6abe-c7ed-4d12-9245-8808528c6a86.png">

@shelaghm 
what about instructions which get defined in questionnaire form? currently existing implementation only shows instructions if it is defined in questionnaire form.

**Comment by jingtang10** [comment]
yeah agreeing with santosh we need to resolve this question: if there's already an instruction do we override it? or do we show both?

late to the party, but my experience as a user (i think mostly with html web forms) has been that the asterisk is always red. i think this is consistent with google forms too:

<img width="766" alt="Screenshot 2022-10-07 at 11 59 04" src="https://user-images.githubusercontent.com/28757340/194538482-6524cc3c-3a60-4a15-b009-8b18284c567d.png">

**Comment by shelaghm** [comment]
1. I'm convinced, let's make the asterisk red
2. If there's already an instruction, I think we should show original instructions and display the error message below. 

Rationale for #2 is an assumption that it will make it easier for users to know how to complete the question by showing the instructions and that we cannot rely on that the questionnaire builder to write an error message that will include comprehensive enough info. Do you agree with this assumption or have a different perspective? @santosh-pingle @jingtang10 

Examples 
<img width="406" alt="Screen Shot 2022-10-07 at 11 58 43" src="https://user-images.githubusercontent.com/86378921/194635245-a9455434-3871-4bd2-9150-df67f23dcebe.png">

Example that instruction text can be used for more than just basic instructions
<img width="413" alt="Screen Shot 2022-10-07 at 11 59 55" src="https://user-images.githubusercontent.com/86378921/194635261-f996b32f-848c-4afd-ac04-57f263c9c72a.png">

**Comment by dubdabasoduba** [comment]
@jingtang10 @shelaghm @santosh-pingle I would advocate for the asterisk to also be in red. Most web forms and mobile forms use the red asterisk to denote required fields.  

This would be easy to use for users since they are already used to it in the different apps and web forms they interact with.

**Comment by shelaghm** [comment]
@dubdabasoduba Thanks for your feedback, helpful to hear your experience! Red asterisk it is!

**Comment by jingtang10** [comment]
@aditya-07 commented that when there's no question text, having an asterisk is very strange. i think @shelaghm and @santosh-pingle agree. 

@shelaghm please advise how to proceed - we could either use flyover when there's no question text. or we can just add another line (maybe similar to the instructions) to explicitly say "Required".

**Comment by shelaghm** [comment]
I recommend using the `flyover/ label text` field to display the asterisk. Ideally also include *required in the `help field/entry format` field below the text box. This follows the [Material design recommendations.](https://m3.material.io/components/text-fields/guidelines#6c36a812-273d-4f5d-9102-2f00386c9145)

<img width="639" alt="Screen Shot 2022-11-11 at 15 21 17" src="https://user-images.githubusercontent.com/86378921/201443536-b4c52782-e7bd-4337-8ef1-05f9916ab282.png">

**Comment by santosh-pingle** [comment]
looking into it.

**Comment by santosh-pingle** [comment]
@shelaghm 
Some views does not have flyover attribute to show * in the view e.g boolean choice, single choice, multiple choice... 
Any thought how can we show asterisk in those views? may be instructions text or separate text line?

**Comment by shelaghm** [comment]
@santosh-pingle For all of these (boolean choice, single choice, multiple choice) I think there's a much higher likelihood that they will have a question title as it will be hard for people to know what they are answering without a question title. 
My recommendation would be to use instructions text field to show `required question`

Mocking it up it looks a bit strange with no title, but with instructions showing `required question` My perspective is that this is an edge case I think developers should avoid and we should encourage the use of question titles :) 
<img width="433" alt="Screen Shot 2022-12-12 at 07 21 21" src="https://user-images.githubusercontent.com/86378921/207083572-5a6dba44-1503-4800-9b25-04161474be4c.png">

**Comment by shelaghm** [comment]
@santosh-pingle Yes, show `*required` below. 

In our usability testing we found that most participants either didn't notice or didn't know what the `*` means.  
This is also consistent with [material.io guidance ](https://m3.material.io/components/text-fields/guidelines#6c36a812-273d-4f5d-9102-2f00386c9145)

**Comment by jingtang10** [comment]
can we just say `required` then without using `*`?

i feel asterisk is a shorthand for required when explained at the beginning of the questionnaire, if people don't understand it and we have to explain it every time, we might as well just simply say required every time without using asterisk.

**Comment by shelaghm** [comment]
@jingtang10 This is a good point. Hadn't considered removing the `*` until now. My only hesitancy is that many people are familiar with what `*` means and would expect to see it? But maybe it doesn't matter as it will reduce visual clutter and using the word `required` is much more meaningful. I'm open to removing the `*` and only using `required` instead. @jingtang10 What do you think? Any risk in removing the asterisk?

Why only use `required` text?
- Reduce the # of elements in the form. Having both `*` and `required` is redundant and makes the form look more cluttered.
- The explanation `required` is more helpful and meaningful to people than just an `*`
- `*` is meaningless to many people without the explanation, so why include to begin with

Why both `*` and `required` text? 
- Even though we tested this with new or some experience internet users in Nigeria, other people might be more familiar with the `*` as a pattern to indicate required than those we tested it with
- The `*` is a common pattern across web forms and many expect it
- Having the `*` symbol is a quick way to notice if it is required

**Comment by jingtang10** [comment]
Thanks @shelaghm for the writeup!

First of all let me say, if (and I'm not saying that I necessarily think this is the right approach) we do add `*` and `required`, I don't think `*` needs to appear twice. At the moment it's added after the question text e.g `Name *` and then before required i.e. `*required` just below the question. This doesn't make sense to me. Having `* required` is an explanation of what `*` means at the beginning of the form like a graph legend. I think if we add the text `required` each time the `*` is present we should just do `required` and that's enough. 

So now, the question becomes, do we add `*` after the question text. I think you made good points both ways. But for simplicity I personally prefer just not having it.

**Comment by shelaghm** [comment]
Ahh, got it. @jingtang10 I think this is a good approach. 

In conclusion:
Keep `*` after the question text . But in hint text remove `*required` and just say `Required`
<img width="493" alt="Screen Shot 2022-12-27 at 12 22 50" src="https://user-images.githubusercontent.com/86378921/209718674-f90ad7f2-1dab-4413-832f-bcc43333e21a.png">

@santosh-pingle we've made a decision on this issue so you can continue the implementation.

**Comment by jingtang10** [comment]
also just confirming that we don't want to show the asterisk in red anywhere right? just following the question text color.

**Comment by shelaghm** [comment]
@jingtang10 Yes, that's right. A few participants in the usability study were confused and thought since it was red that it meant there was an error. So I recommend changing it to same color as the text string to reduce confusion and not associate it with the error color.

**Comment by jingtang10** [comment]
cool thanks for confirming @shelaghm
@santosh-pingle fyi

**Comment by jingtang10** [comment]
talked with @shelaghm on wednesday, i think we're thinking of jsut not showing the asterisk at all, and just use the required string.

**Comment by dubdabasoduba** [comment]
@rowo What are your thoughts on this?

**Comment by HenryRae** [comment]
@dubdabasoduba required questions should have no special treatment i.e  * 
Only optional questions should have special treatment i.e have the tag "optional"
<img width="282" alt="Screenshot 2023-01-13 at 18 34 43" src="https://user-images.githubusercontent.com/31955469/212358375-96a3cc5d-74cb-4b1e-9f4d-9d3ba8272f04.png">

@shelaghm any thoughts on this?

**Comment by HenryRae** [comment]
Adding this here as well.

> No, we shouldn't do "*" on very required question. We should only show "(optional)" for questions that are optional.
In summary: only questions that are optional will be treated different thus will have optional tag. Required questions shouldn't have anything to show they are required. They should return an error if user tries to submit a form with none optional fields not filled
See attached example for all required fields. Only return errors that they need to be filled when user submits a form with one of the fields empty ![image](https://user-images.githubusercontent.com/31955469/212376419-6c4ac52b-6959-4fb1-b542-44ad616db18e.png)

> Only optional questions should have a tag. And that tag is "(optional)" as shown in the screenshot. When these are not filled(fields with optional), we should allow user to submit the form if there are no other errors ![image](https://user-images.githubusercontent.com/31955469/212376492-e9d0403d-c567-43a8-85a9-88b1dc970138.png)

**Comment by shelaghm** [comment]
Thanks @HenryRae for adding your thoughts and raising that Optional might be a better pattern to follow. 
I agree that showing `(Optional)` is more helpful than `required` in the scenario where almost all the questions are required and only a few questions are optional. We have this guidance in (our soon to be shared) design guidelines, where we mention using optional instead of required when that is the case. 

`Required` label makes sense in the inverse scenario where most questions are optional and only a few are required. I'm not sure how common this is in these types of questionnaires and if we should support both options (required and optional)?

My question for the group is if there's still value in having the opportunity to mark questions as required?

**Comment by rowo** [comment]
As a principle for form content, I think (and try to convince health teams) that anything optional should just be removed for CHWs. And it's the case most of the time I've seen. However, it's safer to have an option for marking required questions to cover of all the bases and I guess I could think of times where people would want to use it. Maybe in forms that aren't done often?

The balance might be how much complexity it adds to people trying to configure the app. Are we able to default with the guideline approach? Is this a per form configuration (rather than entire app)?

**Comment by shelaghm** [comment]
@rowo 
+1 to 
> As a principle for form content, I think (and try to convince health teams) that anything optional should just be removed for CHWs. And it's the case that there are only a few optional questions most of the time I've seen.

Thanks for chiming in with your experience and reflections.

From a questionnaire authoring perspective, questions are indicated as `required` in the code, so that we can show the appropriate error messages if they are incomplete. So for me, the key takeaway is that showing an error message is more helpful than displaying `*`, `required`, or `optional` if someone hasn't completed a required question. Error messages are helpful because it helps people know how to fix the error. 

I'm weary of that the FHIR SDK needs to work across different country contexts, use cases and users, so I don't want to hastily remove functionality that's critical for some developers. 

Seeing `required` everywhere gets very repetitive for a form that people are completing several times a day. Which is a bit different from a consumer form where they are completing it only once and then knowing what's required or not is likely more helpful.

I'm leaning towards that the default should be to not show anything additional for required questions (eg no `*`or `required`) and instead rely on error messages if something is incomplete. 

Will discuss with @jingtang10 when he's back to make a decision on next steps.

**Comment by shelaghm** [comment]
Aligned with @jingtang10 
Our proposal is that this needs to be configurable, so that developers can select if they'd prefer to display required or optional. Default display should be required. Configurable setting for optional.

**Comment by jingtang10** [comment]
Let me just add that FHIR by default assumes questions are not required unless stated otherwise. So that is at odds with the pattern Roger described which is that questions should be required by default and there should be as few optional questions as possible.

So I think we probably would have to be a bit neutral here - as in not assuming most questions are required by default, or optional by default. And if we want to do anything, as Shelagh said, we'd probably make it configurable.

**Comment by santosh-pingle** [comment]
Looking into it.

**Comment by santosh-pingle** [comment]
@shelaghm 

- Can you please confirm whether * will not be shown for mandatory(required = true) question and instead of this required text will be shown just below the view
- If the configuration is not present, the default behavior is to display the required question.

**Comment by santosh-pingle** [comment]
@jingtang10 
Considering the approach below, the application will update the bundle with the following value to the questionnaire fragment : 

Pass a boolean value of 'true' as an argument in the bundle to differentiate the optional questions. 
Also, include the optional text as a string value in the bundle (e.g., 'Not required'), if the value is not present, use 'optional' as the default text. 

e.g 
Q.1 National Id (optional)

**Comment by santosh-pingle** [comment]
Closing this issue as I have opened issue #1954. thanks!
