### ISSUE TITLE
Use parametrized tests for Number Search

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#545]
or use proper parameterized tests? may be an overkill though.

_Originally posted by @jingtang10 in https://github.com/google/android-fhir/pull/436#discussion_r650080850_

**Comment by epicadk** [comment]
I think we could test each prefix for the following cases

1. Decimal (100.00)
2. Integer (100)
3. Integer in scientific notation (1e2)

**Comment by Anshul-9923** [comment]
@epicadk I would like to work on this issue, can you assign it to me?

**Comment by Anshul-9923** [comment]
@jingtang10 Can you please briefly explain the issue? I am not able to get it.
