### ISSUE TITLE
Add support for translations on CodeSystem and ValueSet

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#552]
**Is your feature request related to a problem?**
Add support for translations on CodeSystem and ValueSet : https://www.hl7.org/fhir/languages.html#%23term. 

This is related to the internationalisation(i18n) spec. Currently we only support [Translation Extensions](https://www.hl7.org/fhir/languages.html##ext)

**Describe the solution you'd like**
For applications using the **Code System**, we'd like to support rendering the designation of the language corresponding to the selected application context/locale. This should work the same for **ValueSets** that contain concepts with designations.

See [7.15.4 Translations on CodeSystem and ValueSet ](https://www.hl7.org/fhir/languages.html#%23term)

The config would look like this
```
{
  "code": "de",
  "display": "German",
  "designation": [{
      "language": "nl",
      "value": "Duits"
    },{
      "language": "ru",
      "value": "Немецкий"
    },
    {
      "language": "zh",
      "use": {
        "system": "http://terminology.hl7.org/CodeSystem/designation-usage",
        "code": "display"
      },
      "value": "德语"
    }
  ]
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
- [PR#166](https://github.com/google/android-fhir/pull/166)
- Issue #465

**Would you like to work on the issue?**
Yeah

**Comment by jingtang10** [comment]
Closing as per previously referenced issues - please feel free to reopen. Remaining discussion to continue in #928
