### ISSUE TITLE
Feat : Add functionality to convert Hapi resources to Fhir protos (JSON)

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#556]
**Describe the solution you'd like**

Add functionality to convert Hapi resources to Fhir protos by converting first to JSON and then to then parsing it to the other format. 

**Describe alternatives you've considered**

Use reflection to covert between the resources directly. (will be done later)

FYI @Rkareko

**Comment by fredhersch** [comment]
@jingtang10 is there an update on this PR?

**Comment by jingtang10** [comment]
@epicadk ?

**Comment by epicadk** [comment]
PR is awaiting review from @Rkareko. It's related to my GSoC project.

**Comment by epicadk** [comment]
Sorry I meant to assign @Rkareko  to the PR and not this issue.
