### ISSUE TITLE
Patient duplication in reference app

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#563]
**Describe the bug**
Duplicate patients in the reference app

**Component**
Reference app

**To Reproduce**
1. Open the reference app

**Expected behavior**
No patient duplication

**Screenshots**
(![Screenshot (21 Jun 2021 09_18_46)](https://user-images.githubusercontent.com/28757340/122730397-124be300-d272-11eb-9b52-5f4308fff1f6.png))

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android version: 11
 - Build number: RQ3A.210605.005

**Additional context**
HAPI test server: http://hapi.fhir.org/search?serverId=home_r4&pretty=true&_summary=&resource=Patient&param.0.qualifier=&param.0.0=NAIROBI&param.0.name=address-city&param.0.type=string&sort_by=&sort_direction=&resource-search-limit=

**Would you like to work on the issue?**
No

**Comment by santosh-pingle** [comment]
Hi Jing,

Though records are same, but it has different resource id.
Same is verified with remote FHIR server data.

Please let me know if you do have any query.

**Comment by jingtang10** [comment]
can you update the server-side data so that we don't get this type of duplicates in the app?

**Comment by santosh-pingle** [comment]
There were 3-4 records which were having the same data except resource id. Those are updated by replacing family and given attributes of name.
Other data is not duplicated in remote FHIR and local databases.

But some records are still shown as duplicate in the reference app.
Records which have 2 elements in the name array, those are seen as duplicate records with “family” and “given” attribute values with “use:official”.

Debugging further.

**Comment by santosh-pingle** [comment]
Looks like search operation which internally uses getQuery() api which generates extra records,
and if a patient has an array of names then “given” is present in StringIndexEntity that number of times, and it causes an extra record.
Debugging further.

**Comment by jingtang10** [comment]
Discussed with @santosh-pingle and the problem is that the index records in the index table are duplicated. Fixes:

1. in the code deduplicate index records before inserting to index tables
2. in the code deduplicate search results after execution of db query
3. add unique constraint on index tables

after discussion we think 1 and 2 are useful to do and 3 is probably not worth it given that it'll increase the index size.

**Comment by FikriMilano** [comment]
@jingtang10 @santosh-pingle we might want to open this issue again.
After investigating #596, there are still hidden duplication on patient 21 and 22. I think it will show up when #596 got fixed

<img src="https://user-images.githubusercontent.com/62053304/124091011-975ba700-da7f-11eb-9564-7efce0a586ca.png"  width="256">

**Comment by santosh-pingle** [comment]
@FikriMilano 

Above mentioned Patient duplication does not belong to same patient resource id.
It happened to be two patient resources are having same records with different resource id.

Please see below attached screenshots

<img width="1359" alt="Screen Shot 2021-07-01 at 3 39 09 PM" src="https://user-images.githubusercontent.com/86107848/124109892-40f16700-da85-11eb-8bfb-5451295c3fd7.png">

<img width="1323" alt="Screen Shot 2021-07-01 at 3 40 09 PM" src="https://user-images.githubusercontent.com/86107848/124109936-4e0e5600-da85-11eb-839f-037e085a2638.png">

**Comment by FikriMilano** [comment]
@santosh-pingle 
I see, you're right. Thanks for the explanation
