### ISSUE TITLE
Support the Approximate prefix while searching for dates

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#568]
**Describe the solution you'd like**

Support Approximate prefix while searching for dates.

 ref https://www.hl7.org/fhir/search.html#prefix.

> the value for the parameter in the resource is approximately the same to the provided value.
Note that the recommended value for the approximation is 10% of the stated value (or for a date, 10% of the gap between now and the date), but systems may choose other values where appropriate

**Additional context**

We need to discuss how to implement this, and what approximate would imply. We could stick to what the spec recommends (stated above) or we could come up with our own definition. 

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

Maybe adter we decide what the strategy.

**Comment by Tarun-Bhardwaj** [comment]
@epicadk , could you please provide an ETA for closing this issues as closure of #474 is dependent on it?

**Comment by epicadk** [comment]
> @epicadk , could you please provide an ETA for closing this issues as closure of #474 is dependent on it?

awaiting review.

 Currently I have implemented in the way the spec recommends. However, @jingtang10 had mentioned that it may not be the best way to implement this and we could also decide to not implement this at all  (which I agree with). If we do decide that we don't want to support approximate for dates it would take a day at max to make the required changes. cc @jingtang10
