### ISSUE TITLE
Add code snippets to the user guide for fhir engine

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#580]
potentially take some from: https://docs.google.com/presentation/d/1oc6EBJAcXsBwyBgtnra61xoM7naBF0aj8WbfrUT7Y2A/edit

should include

- how to create a fhir engine
- how to save/load/update fhir resources
- how to search for fhir resources
- how to sync with a remote server

**Comment by fredhersch** [comment]
Done
