### ISSUE TITLE
Add documentation code snippets for data capture library

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#581]
potentially taking some content from: https://docs.google.com/presentation/d/1oc6EBJAcXsBwyBgtnra61xoM7naBF0aj8WbfrUT7Y2A/edit#slide=id.gbb0f485cce_0_0

should include

- how to render a questionnaire from a questionnaire resource
- how to get the questionnaire response
- how to extract the fhir resource from the questionnaire response
- how to pre-populate the questionnaire with a fhir resource
- how to validate the questionnaire response against the questionnaire
- how to customize the UI

**Comment by fredhersch** [comment]
Updated https://github.com/google/android-fhir/wiki/Using-the-Structured-Data-Capture-API

Need to review some of the content together with @jingtang10 this week

**Comment by jingtang10** [comment]
this is done in https://github.com/google/android-fhir/wiki/Structured-Data-Capture-Library
