### ISSUE TITLE
Create "Add patient" screen

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#590]
**Is your feature request related to a problem? Please describe.**
We need to add an 'add patient' screen to the reference application

**Describe the solution you'd like**

**User story:** As a user I can register a new patient using the client application

Requirements:

- [ ] add a dependency from the reference application to the data capture library (`datacapture` mdoule)
- [ ] create a FHIR questionnaire resource which can be stored in the assets folder in the reference app that defines the questions to be asked while registering a patient (ask @fredhersch)
- [ ] use the `QuestionnaireFragment` to render the above questionnaire
- [ ] a new 'add patient' button (e.g. FAB https://material.io/components/buttons-floating-action-button) on the patient list screen
- [ ] modify the navigation graph so that clicking the add patient button would take the user to the new fragment
- [ ] use the `ResourceMapper` API to create a patient from the questionnaire response
- [ ] save the resulting patient into the db using the FHIR engine API
- [ ] show the new patient in the patient list view

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
Yes

**Comment by fredhersch** [comment]
@jingtang10 For the ResourceMapper, do we have any examples for how to represent the FHIRPath logic in the Questionnaire?

**Comment by jingtang10** [comment]
> @jingtang10 For the ResourceMapper, do we have any examples for how to represent the FHIRPath logic in the Questionnaire?

@f-odhiambo can you please help link to the example Rodgers created? Thanks!

**Comment by santosh-pingle** [comment]
In progress.
1. A new 'add patient' button (e.g. FAB https://material.io/components/buttons-floating-action-button) on the patient list screen.

**Comment by santosh-pingle** [comment]
@fredhersch Can you please help me to get the questionnaire to register the patient which we need for action item "create a FHIR questionnaire resource which can be stored in the assets folder in the reference app that defines the questions to be asked while registering a patient (ask @fredhersch)"

**Comment by santosh-pingle** [comment]
[#614 ](url)
Temporarily unblocked add patient screen tasks by renaming UcumException class name locally.

**Comment by santosh-pingle** [comment]
We are using below new patient registration json. But added couple of changes in json file  to avoid empty list exception and id not null exception.
1. Existing extension url is replaced with "url": "http://hl7.org/fhir/uv/sdc/StructureDefinition/sdc-questionnaire-itemExtractionContext",
2. Id item is added.

**Comment by santosh-pingle** [comment]
@jingtang10 
Currently, below patient-registration json questionnaire is used/referred to add patient screen as you suggested. But it does not have **resource id item**. Therefore current implementation does not have an id item in add patient questionnaire.
Can you please confirm the above mentioned behaviour?

https://github.com/opensrp/fhircore/blob/main/android/app/src/main/assets/patient-registration.json

**Comment by jingtang10** [comment]
can you merge this one with the current https://github.com/opensrp/fhircore/blob/main/android/app/src/main/assets/patient-registration.json to make it a single form? I think ID and basic info in the first page and contact details in second page is fine.

**Comment by jingtang10** [comment]
discussed offline with @santosh-pingle. just to document here. the patient id doesn't make sense to be an input for the CHW. so we're left with 2 options

1. annotate the question so that the sdc library knows to generate an ID either during extraction or during initial rendering of the questionnaire
2. let the developer decide what to do after getting the resource, and set an id to the resource (presumably using the java uuid library) prior to saving to fhir engine.

I think 2) is realistic and reasonble to do in this PR. @santosh-pingle can you also please create an issue for 1) as we schedule the work for the sdc lib?

**Comment by santosh-pingle** [comment]
As per discussion with @jingtang10, option 2 (set an id to the resource (presumably using the java uuid library) prior to saving to fhir engine.) is implemented.

Done.
