### ISSUE TITLE
Set-up reference app to connect to different FHIR servers

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#593]
**Is your feature request related to a problem? Please describe.**
Currently the reference app is configured to use a HAPI FHIR server. If a developer wants to use a cloud service like GCP FHIR Store they cannot easily do this

**Describe the solution you'd like**
As a developer, I can:
- [ ] Connect the client application to any FHIR compliant server by specifying the URL and credentials in client app config
- [ ] Connect a client application with a GCP FHIR store

**Comment by Tarun-Bhardwaj** [comment]
Discussed with @jingtang10 offline that this issue does not reflect the latest status of reference app. Hence closing this issue.
CC: @fredhersch
