### ISSUE TITLE
Implement Peer to Peer transfer 

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#600]
**Is your feature request related to a problem? Please describe.**
Research and implement Peer to Peer transfer without an internet connection.

**Describe the solution you'd like**
API we are likely going to use.
[wifip2p](https://developer.android.com/guide/topics/connectivity/wifip2p#api-overview)
Alternative (currently researching between the two)
[nearby connection](https://developers.google.com/nearby/connections/overview)

**why not use a library**
All the libraries I have encountered were not documented properly or were not updated 
Also, there have been major changes in the API related and older libraries could cause some error or misconfiguration. 
Related libraries are mentioned in the Document below.

**Describe alternatives you've considered**
N/A

**Additional context**
Document regarding the same is attached below,  **feel free to comment if there is an issue.**
[Document](https://docs.google.com/document/d/1o9m1vUh2tkAuzKS-JIFEohUHeVWeas36ob0ztOlBF0A/edit?usp=sharing)

As discussed with @ekigamba

**Comment by pld** [comment]
Note R&D issue here, https://github.com/google/android-fhir/issues/258

**Comment by Tarun-Bhardwaj** [comment]
@maanuanubhav999 , can we close this issue since we already have #258 and thus this one is a duplicate?

**Comment by maanuanubhav999** [comment]
@Tarun-Bhardwaj sure.
