### ISSUE TITLE
Buttons in pagination float over form elements

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#602]
**Describe the bug**
There is no padding between the Questionnaire items and the next/previous controls in pagination

**Component**
SDC Library

**To Reproduce**
1. Checkout fh/patient-registration-questionnaire and run the SDC Gallery App
2. Click on 'New patient registration' option (last one)
3. Scroll down to the bottom of the first page

**Expected behavior**
Should be padding between the form elements and the next/prev buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/34733/123749791-6432df80-d8e8-11eb-933f-0da83eccd726.png)

**Smartphone (please complete the following information):**
 - Device: virtual device (pixel)
 - Android version: 29

**Comment by sparrow007** [comment]
Hello, @fredhersch I wanted to contribute to this project, so may I start working on this issue?

**Comment by prsndp** [comment]
Hi @fredhersch Could You Assign me this issue, please? I want to fix this issue.

**Comment by prsndp** [comment]
> Hi @fredhersch Could You Assign me this issue, please? I want to fix this issue.

Thanks:)

**Comment by joiskash** [comment]
This issue has not been fixed
