### ISSUE TITLE
Search by multiple resource types

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#611]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Search with joins of different types of resources within a single search:
- result[] = Get all Patients Where Observation.Code = "<SNOMED Code for XYZ>"
- See https://www.hl7.org/fhir/observation.html

Other examples:

As a CHW, show me all of the Patients currently enrolled in the ANC program
* ANC-Code =  Lookup ValueSet (see #609)
* Search for Patients Where EpisodeOfCare.type = ANC-Code.value AND Status.equals("Active") SORT BY DESC

**Describe alternatives you've considered**
Implement two-step search of:
1. Get a collection of Patients 
2. For each Patient, search by Resource Type for the specific item

**Comment by jingtang10** [comment]
Examples:
- patients with latest risk assessmenet e.g. `high`
- patients with condition diabetes
