### ISSUE TITLE
Choice item answer lookups via "contained" ValueSet answerOptions within Questionnaire

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#612]
**Is your feature request related to a problem? Please describe.**
Currently, the choice item controls only works for inlined answerOptions.

**Describe the solution you'd like**

[1] For a Questionnaire that has an expanded "contained" ValueSet
- choice itemControl should be able to lookup the answerOptions when a user starts typing

**Describe alternatives you've considered**
Inlined answerOptions already supported

**Additional context**
* The HIV Case Reporting Questionnaire has examples of contained expanded valueSets (for gender)

**Comment by fredhersch** [comment]
@aditya-07 This looks like relevant context http://hl7.org/fhir/R4/questionnaire.html#choices

**Comment by jingtang10** [comment]
for this - @fredhersch and @litlfred do we have an example of expanded valueset in contained? @aditya-07 couldn't find any. at the moment we only have non-expanded valuesets in the contained resources list of a questionnaire.

**Comment by aditya-07** [comment]
@fredhersch @litlfred  [openhie-covid-case-report.json](https://github.com/google/android-fhir/blob/master/datacapturegallery/src/main/assets/openhie-covid-case-report.json) has contained sets but all of them have **compose** instead of the **expanded** CodeSystem.

**Comment by fredhersch** [comment]
I see the problem @aditya-07 .. We will need to generate our own example. Maybe we can add something simple to an existing one for Yes/No? Happy to have a look at this tomorrow.
