### ISSUE TITLE
Duplicate Files Exception

### ISSUE THREAD

**Issue by MuhammadSalman-7214** [google/android-fhir#614]
**Describe the bug**
Duplicate class org.fhir.ucum.UcumException found in modules data-capture-0.3.0-alpha02-runtime (com.google.android.fhir:data-capture:0.3.0-alpha02) and engine-0.0.2-runtime (com.google.android.fhir:engine:0.0.2)

**Component**
SDC library

**To Reproduce**
The issue can be reporduced by using sdc library and engine library simultaneously 

**Expected behavior**
Duplicate files should be handled properly so they don't block us

**Screenshots**

**Smartphone (please complete the following information):**
 Not related to a specific device 
**Additional context**

**Would you like to work on the issue?**
  yeah I would like to work on the issue
![Screenshot from 2021-07-01 13-22-36](https://user-images.githubusercontent.com/64642723/124091564-6a06fd00-da6f-11eb-8244-3327ddf21ae1.png)

**Comment by jingtang10** [comment]
can you do something like this: https://github.com/google/android-fhir/blob/916cf74b87b4654d846884abb6b2bdde12bebc74/reference/build.gradle.kts#L37 in your project to deduplicate this file?

you might want to use option `pickFirsts` rather than `exclude`: https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/PackagingOptions

**Comment by MuhammadSalman-7214** [comment]
> can you do something like this:
> 
> https://github.com/google/android-fhir/blob/916cf74b87b4654d846884abb6b2bdde12bebc74/reference/build.gradle.kts#L37
> 
> in your project to deduplicate this file?
> you might want to use option `pickFirsts` rather than `exclude`: https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/PackagingOptions

@jingtang10 this is already added in the project, but the problem still persists

**Comment by MuhammadSalman-7214** [comment]
> > can you do something like this:
> > https://github.com/google/android-fhir/blob/916cf74b87b4654d846884abb6b2bdde12bebc74/reference/build.gradle.kts#L37
> > 
> > in your project to deduplicate this file?
> > you might want to use option `pickFirsts` rather than `exclude`: https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/PackagingOptions
> 
> @jingtang10 this (packagingOptions) is already added in the project, but the problem still persists

@jingtang10 this solution is not working, can you please suggest something else? thanks

**Comment by Tarun-Bhardwaj** [comment]
@MuhammadSalman-7214 is there an ETA by when this issue can be closed? It is blocking #590 which is a high priority for Q3 v0 release.

**Comment by MuhammadSalman-7214** [comment]
@Tarun-Bhardwaj this issue needs discussion with @jingtang10 because the solution for this issue hasn't been finalized yet.

**Comment by jingtang10** [comment]
https://stackoverflow.com/questions/21319020/duplicate-class-contained-in-the-libs-of-android-project
