### ISSUE TITLE
Run tests with API 30

### ISSUE THREAD

**Issue by yigit** [google/android-fhir#617]
what title says :) we should update the workflow to also run tests on API 30.

We could also consider a bit of a cleanup to have 1 task build all apks and other tasks to just run tests with the output of the previous task.

**Comment by jingtang10** [comment]
we run tests on api 30 now.

**Comment by jingtang10** [comment]
i think we also do this now: `have 1 task build all apks and other tasks to just run tests with the output of the previous task`

we have the `./gradlew build` step

and then test step for `./gradlew check` and then emulator test separated for each module e.g. `./gradlew :engine:connectedCheck`

so i think this can be closed.

@yigit @omarismail94 FYI

i'm gonna be aggressive and close this. but please feel free to reopen if i'm wrong :)
