### ISSUE TITLE
View patient card

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#622]
User story: As a logged in user I am able to select a patient and view details about them such as registration information and any relevant health history

Steps:
- Logged in user views a list of patients that they have access to
- Taps one of the patients in the list
- This opens a view patient screen
- Is able to see registration information and any relevant health history
- Can navigate back to the worklist/home view

**Additional context**
For the first iteration of this, **just show the patient registration information** that was captured in the Add patient issue. These can be displayed as name/value pairs in rows

**Comment by santosh-pingle** [comment]
Started working on it.

**Comment by santosh-pingle** [comment]
@fredhersch  (Is able to see registration information and any relevant health history)
Can you please give me more details about what registration information will be shown?

**Comment by fredhersch** [comment]
@santosh-pingle Updated the description
