### ISSUE TITLE
Allow implementers to specify custom search fields

### ISSUE THREAD

**Issue by rkodev** [google/android-fhir#637]
**Is your feature request related to a problem? Please describe.**
Individual implementers of the SDK do require to sometimes search data that is not index / optimized for search in the database.

A use case of this feature is the ability to create indexes on an extension. e.g Having a location resource defined as an extension to a Patient resource and requiring to retrieve all the patients within that location 

**Describe the solution you'd like**
Allowing implementers to define custom search fields so that they can be indexed and optimize search queries for retrieval

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Would you like to work on the issue?**
Open to it

**Comment by jingtang10** [comment]
The first question is that should this customization be done in 1) FHIR resources or 2) as part of the app. If we do it in FHIR resources what extensions/other mechanism should be defined as part of the standard. If we do it in the application what config do we use? @pld for input.

**Comment by pld** [comment]
This feels like an app config setting, but I could see an argument for doing it in FHIR resources to make it easier for the SDK client to dynamically create indices, ie if I had a List resource with an Indentifier (or some other field) the SDK could know this List resource is responsible for configuring indices and look at it's entries to decide on the additional indices to create

**Comment by jingtang10** [comment]
This was addressed under #1382

@pld and @rkodev please check it out! And feel free to open any follow-up issues.
