### ISSUE TITLE
Pop up numeric keyboard for a question that requires phone number as the input

### ISSUE THREAD

**Issue by joiskash** [google/android-fhir#650]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to specify a text input widget to show the number keyboard instead of the entire alphanumeric keyboard

**Describe the solution you'd like**
One way to do this is to check if there is a regex condition on item which only has numbers and then default to a number input only.

**Describe alternatives you've considered**
Use a phone-number extension item control. This is not there, though there is something called [entry-format](http://hl7.org/fhir/R4/extension-entryformat.html) but it has a maturity level of 1 only.

**Comment by joiskash** [comment]
ETA 19th August 2021

**Comment by jingtang10** [comment]
I think we should prioritise this one

**Comment by joiskash** [comment]
Going to make this a separate widget in a new package (for eg: with the Barcode scanner) so that app developers can override and use this widget without having to depend on the standard. Once the standard has converged, we can shift towards that.

cc: @fredhersch @jingtang10

**Comment by joiskash** [comment]
> 
> 
> There are two ways of doing this:
> 
>     1. Using http://hl7.org/fhir/R4/extension-regex.html
> 
>     2. Using http://hl7.org/fhir/R4/extension-entryformat.html
> 
> 
> https://chat.fhir.org/#narrow/stream/179255-questionnaire/topic/SDC.20.3A.20Phone.20number.20widget
> 
> cc: @jingtang10

Message from Loyd:

If we were going to define a keyboard type/input type, we'd need:

    an expectation that it would work across a range of browsers and device types
    an expectation that it would work consistently

If we can come up with a value set that meets those two requirements, I'd be happy to see a change request for us to define such an extension.

**Comment by joiskash** [comment]
https://jira.hl7.org/browse/FHIR-33675
