### ISSUE TITLE
Mock splash and login screen

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#655]
Implement the splash screen (on app loading) and a mocked up login screen

**Additional information**
Color palette information (waiting on design output):
- Main background (e.g. for splash screen): background: #1967D2
- Header text: Font-family: Google sans 18px
- Placeholder text (inside the mobile number form field): Roboto 400 16px
- Instructions text under the entry field: Google-sans 14px

**Notes:**
* Do not add the first drop down for the region
* Do show the language switcher option
* For the create account button, this does not do anything
* On selecting next, go to the home page (no validation for now)

**Screenshots**

<img width="412" alt="Splash (1)" src="https://user-images.githubusercontent.com/34733/126090623-9ca3e903-b573-407c-a469-be89389a6028.png">

<img width="412" alt="Login 1" src="https://user-images.githubusercontent.com/34733/126090656-7f23c6f9-1a4f-46e6-bfb7-25df1dd7ea1e.png">

**Comment by jingtang10** [comment]
I don't think we need this any more. Obsolete. Closing issue.
