### ISSUE TITLE
Implementation of $apply API

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#656]
**User story:** 
As an implementer I can use the $apply operation to generate a CarePlan for a patient given a PlanDefinition

**Background**
CQL (Clinical Quality Language) is the HL7 standard for providing logic execution for decision support and clinical quality measures. 

Our initial goal with the CQL Library will be to demonstrate over time the ability to:

- Generate a MeasureReport via $measure-evaluate operation 
- Load and execute a custom CQL library (Library resource) for decision logic
- Transform a PlanDefinition to a CarePlan using $apply operation

**Comment by jingtang10** [comment]
dependency:
- https://github.com/cqframework/clinical_quality_language/issues/640
- https://github.com/cqframework/clinical_quality_language/issues/523

**Comment by maimoonak** [comment]
Few Observations during code exploration
- CRUD in CQL, whether fhir spec allows it or not
- CRUD in Measure, whether fhir spec allows it or not
- Library Processor L213 -> if (!url.contains("/Library/"))
- Library name RuleFilter
- ELM+JSON LIbrary works with CQL. XML throws Serializer exception
- Translating Library matcher translatorOptionsMatch needs replacement with matcher method
- The CQL Builder with default constructor does not initialize properly with library loader hence missing libraries on runtime
- libraryCache needs to be carefully implemented, currently alot of initialization happens with in classes privately
- The FHIRDal i.e. CQL would be loading data on demand. This restricts us running CQL before saving entities (For example we just want to test questionnaire, extraction, and CQL without persisting entities)
- ExpressionEvaluator runs expression as library but in resources no content / library has been provided     
  libraryProcessor.evaluate(new VersionedIdentifier().withId("expression").withVersion("1.0.0"), subject,

@f-odhiambo @pld

**Comment by f-odhiambo** [comment]
Seem like we have the following 

**Input**
```
val cp = fhirOperator.generateCarePlan(
      planDefinitionId = “plandefinition-RuleFilters-1.0.0”,
      patientId = “Reportable”,
      encounterId = “reportable-encounter”
    )
```

and gettging the following output based on @maimoonak updates 

**Output**
` {"resourceType":"CarePlan","contained":[{"resourceType":"RequestGroup","id":"3ddb8524-345a-4477-9589-4144b71ff88c","status":"draft","intent":"proposal"}],"instantiatesCanonical":["plandefinition-RuleFilters-1.0.0"],"status":"draft","subject":{"reference":"Reportable"},"encounter":{"reference":"reportable-encounter"},"activity":[{"reference":{"reference":"#3ddb8524-345a-4477-9589-4144b71ff88c"}}]}`

Are you getting the same @jingtang10?

CC @pld @mberg

**Comment by jingtang10** [comment]
Thanks @pld for raising this. In the call earlier today we discussed this and @maimoonak will share the changes she has made and raise a draft pr against this issue.

also would love to get input from jp and vitor (sent them invite to the repo).

**Comment by Tarun-Bhardwaj** [comment]
@f-odhiambo , though the associated PR #1195 is merged, what would it need to close this issue?

**Comment by f-odhiambo** [comment]
I think we can track the $apply issues based on @vitorpamplona updates. I am ok closing this issue. WIll update and coordinate with @maimoonak on where we can push the subsequent updates

**Comment by jingtang10** [comment]
> 



> Few Observations during code exploration
> 
> * CRUD in CQL, does fhir spec allow it or not?
> * CRUD in Measure, does fhir spec allowsit or not?
> * Library Processor L213 -> if (!url.contains("/Library/"))
> * Library name RuleFilter
> * ELM+JSON LIbrary works with CQL. XML throws Serializer exception
> * Translating Library matcher translatorOptionsMatch needs replacement with matcher method
> * The CQL Builder with default constructor does not initialize properly with library loader hence missing libraries on runtime
> * libraryCache needs to be carefully implemented, currently alot of initialization happens with in classes privately
> * The FHIRDal i.e. CQL would be loading data on demand. This restricts us running CQL before saving entities (For example we just want to test questionnaire, extraction, and CQL without persisting entities)
> * ExpressionEvaluator runs expression as library but in resources no content / library has been provided      (removing expressions make testcase pass)
>   libraryProcessor.evaluate(new VersionedIdentifier().withId("expression").withVersion("1.0.0"), subject,
> 
> Plz check commit [here](https://github.com/google/android-fhir/commit/0dfafe95c1fb06c91eeacab42ae7d20cfefadffa). These changes were required to run the library loaders. The test does not pass though due to expression not added as library (Not sure if I am missing anything here)
> 
> @f-odhiambo @pld @jingtang10 @dubdabasoduba

Let's close this issue once we address everything in @maimoonak 's commit in her comment above. @maimoonak please close this issue or raise a PR if necessary.

**Comment by jingtang10** [comment]
@vitorpamplona @brynrhodes can you help here please?

**Comment by vitorpamplona** [comment]
Fixed on https://github.com/google/android-fhir/pull/1603
