### ISSUE TITLE
Implementation of $measure-evaluate API

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#657]
**User story**
As an implementer I can use the $measure-evaluate to generate a MeasureReport

- Given a set of pre-loaded patients, run the $measure-evaluate operation to generate a MeasureReport
-- On a single patient, the $measure-evaluate will return a MeasureReport with a value of 1 or 0
-- For a group of patients, the $measure-evaluate will return a MeasureReport

- Example indicator (measure): [ANC.IND1:](https://apps.who.int/iris/bitstream/handle/10665/339742/WHO-SRH-21.3-eng.xlsx) Percentage of antenatal women with 1st ANC contact in 1st trimester (before 12 weeks)

**Background**
CQL (Clinical Quality Language) is the HL7 standard for providing logic execution for decision support and clinical quality measures. 

Our initial goal with the CQL Library will be to demonstrate over time the ability to:

- Generate a MeasureReport via $measure-evaluate operation 
- Load and execute a custom CQL library (Library resource) for decision logic
- Transform a PlanDefinition to a CarePlan using $apply operation

**Comment by epicadk** [comment]
How hapi fhir  handles [this](https://github.com/hapifhir/hapi-fhir/blob/097a2f70b3a1531a76031f3d051191f9315f7507/hapi-fhir-jpaserver-cql/src/main/java/ca/uhn/fhir/cql/r4/provider/MeasureOperationsProvider.java#L75) .

Dependencies 

- https://github.com/DBCG/cql_engine
