### ISSUE TITLE
Update path splitting logic in FhirIndexerImpl

### ISSUE THREAD

**Issue by deepankarb** [google/android-fhir#67]
We index search parameters in `FhirIndexerImpl.kt` by type. We extract the object instances by splitting the `path` in the `SearchParamDefinition` and walking the `Resource` members depth-first. With splitting the path by dot notation, e.g. `Observation.code.value` we are missing out on Search params which do not conform to this pattern. E.g. `SP_PHONE` in `Patient` is `Patient.telecom.where(system='phone')`.

We should try out the [HAPI FHIR splitting logic](https://github.com/jamesagnew/hapi-fhir/blob/622659cbb3e310d8d6037334da77edbff70c588f/hapi-fhir-jpaserver-searchparam/src/main/java/ca/uhn/fhir/jpa/searchparam/extractor/BaseSearchParamExtractor.java#L1139):

```java
@Override
	public String[] split(String thePaths) {
		if (getContext().getVersion().getVersion().isEqualOrNewerThan(FhirVersionEnum.R4)) {
			if (!thePaths.contains("|")) {
				return new String[]{thePaths};
			}
			return SPLIT_R4.split(thePaths);
		} else {
			if (!thePaths.contains("|") && !thePaths.contains(" or ")) {
				return new String[]{thePaths};
			}
			return SPLIT.split(thePaths);
		}
	}

```

**Comment by jingtang10** [comment]
i think this can be addresssed by #280. Closing this.
