### ISSUE TITLE
How to use sdk in my project?

### ISSUE THREAD

**Issue by tunm1228** [google/android-fhir#679]
**Describe the bug**
dependencies {
    implementation 'com.google.android.fhir:data-capture:0.1.0-alpha01'
}
I added the following to the build.gradle . script.
But there are no instructions for connecting to sdk?

**Component**
Core library, SDC library, reference app, or SDC gallery app

**Comment by maanuanubhav999** [comment]
Hi @tunm1228. Did you tried the [Documentation](https://github.com/google/android-fhir/wiki/Structured-Data-Capture-Library-User's-Guide)

**Comment by fredhersch** [comment]
@tunm1228 Are you trying to use just the SDC Library or the FHIREngine as well?

Please review the [documentation here](https://github.com/google/android-fhir/wiki)

Let us know if you have specific questions
