### ISSUE TITLE
Add patient Ui is not working properly in dark mode

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#684]
**Describe the bug**
UI for add patient in reference is shown unusually when the device is in dark mode.

**Component**
Reference app

**To Reproduce**
1. Go to reference app
2. Switch device to dark mode
3. Click on the + icon for adding patients.

**Expected behavior**
Should show UI elements uniformaly 

**Screenshots**

UI when device is in dark mode.

![Screenshot_2021-08-04-18-06-03-88_edecc48dc70661d9bcefd800b60814c3](https://user-images.githubusercontent.com/26630009/128183166-0ae0aa37-331a-48b5-b103-8b19cb686fe0.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme narzo 20
 - Android version: Android 11
 - Build number: RMX2191_11_C.10
 

**Would you like to work on the issue?**
Not sure yet.

**Comment by f-odhiambo** [comment]
Check this fix https://github.com/opensrp/fhircore/pull/128

**Comment by maanuanubhav999** [comment]
thanks @f-odhiambo

**Comment by f-odhiambo** [comment]
@maanuanubhav999 I also think this is not a bug and just how dark mode is supposed to work. You are supposed to define the theme/style for both Dark and Light modes. Thoughts are welcome
