### ISSUE TITLE
Research into Bulk Data API

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#686]
**Describe the issue to be researched**

Whether we should support a bulk data API within the SDK

**Describe the goal of the research**

* Develop a better understanding of the use cases where Bulk Data API is appropriate
* Identify use cases and amount of data
* Determine whether to provide support and if so what is the priority

**Describe the methodology**
* Review of available materials
* Discussion with community

**Would you like to work on the issue?**
Yes

**Comment by fredhersch** [comment]
Reviewed a number of resources related to the Bulk Data API:

- [FHIR Bulk Data API IG](https://hl7.org/fhir/uv/bulkdata/)
- [FHIR Bulk Data API Presentation, July 2020](https://docs.google.com/presentation/d/14ZHmam9hwz6-SsCG1YqUIQnJ56bvSqEatebltgEVR6c/edit#slide=id.g8c17644f87_23_919)
- [FHIR Chat #bulk-data stream](https://chat.fhir.org/#narrow/stream/179250-bulk-data)

From my understanding:
* The Bulk Data API is mainly designed to enable export of large data sets for population health or for transfer between eMRs to a (Cloud) FHIR store etc
* The design of the API is to package up all resources of a single type into an .ndjson format (i.e. not patient level) e.g. set of patient resources, set of observation resources. These are then able to be imported into a server that supports the $import operation
* Looks like the Google Cloud $import operation provides some under the hood ways to do this with more flexibility (using bundles?)

Amount of data:

* Trying to estimate this is a little bit hard. Back of the envelope estimates are something like:
* Assumptions for an initial import of data:
 * 1,000 unique patients
 * 25-50 resources per patient (based on 1 or 2 encounters, set of observations, conditions etc)
 * Size per resource (raw) 5kb (avg)
 * Would be approx 125-250 mb for the initial download

Thoughts:
* On reviewing the various sources, this doesn't look to be the right approach for this use case
* Use of the transaction bundles is probably the correct way to implement this for now
 * Could look at the Google Cloud import operation e.g. per [Paul Church on FHIR chat](https://chat.fhir.org/#narrow/stream/179250-bulk-data/topic/NDJSON.20Resource.20Expectations)
 `The Google import operation has a mode that accepts bundles and unwraps them into individual resources (without regard for the bundle type or semantics, it's just a bag of resources - but this could be improved in the future) and users have found that useful. It comes up a lot in cases like synthea where the input is per-patient bundles, but could also apply to scenarios like this.
`
* Alternative would be to add support for $import operation 
* Main question is how much can we build into the sync to address the 'small pipes' constraints - as per https://chat.fhir.org/#narrow/stream/179250-bulk-data/search/mobile

**Comment by jingtang10** [comment]
Closing in favour of #791
