### ISSUE TITLE
Element extension: maxDecimalPlaces

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#710]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by epicadk** [comment]
We can create a `DecimalTypeMaxDecimalValidator` object that implements `ConstraintValidator`
