### ISSUE TITLE
Research: Authentication support (e.g Smart-on-FHIR via the SDK) 

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#713]
**Describe the issue to be researched**
Include any background information and available resources.

**Describe the goal of the research**
What's the desired outcome of this task? What artifacts should be produced?

**Describe the methodology**
Where can more information be found? Who should the assignee approach to ask questions? How can a decision be made?

**Would you like to work on the issue?**

**Comment by omarismail94** [comment]
Closing as we can do this now with the Authentication interface in FHIR Engine
