### ISSUE TITLE
Sync Status - Show sync status & last sync time

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#715]
From #605 

User story: As a logged in user I can choose to sync the mobile client with a FHIR server and visually see the status changes

Steps:

User is logged in
Clicks on the settings which opens a drawer menu
From the drawer menu, user can see sync option and last sync'd time/date
User clicks the sync option which starts the sync process. The status changes visually by showing a spinner (or other) and continues in the background
End state:

On completion, shows a status change (complete) and summary of # records syncd
On error, will attempt to retry until it either completes or fails. Status should reflect this

**Comment by santosh-pingle** [comment]
@aditya-07 
Can you please update the issue with description and expectation, Thanks!

**Comment by santosh-pingle** [comment]
I will be working on it, until #625 get unblocked.

**Comment by santosh-pingle** [comment]
Its in progress.

**Comment by santosh-pingle** [comment]
Currently, we are having issue where navigation drawer icon get shown at all fragment action bar,and it get opened at all fragments.

trying for solution where navigation drawer icon can be shown and drawer will be opened at first fragment only.

Will try to push PR by eod today.
