### ISSUE TITLE
Requirements and design of workflow library to support CarePlan generation and Implementation Guides

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#716]
**Describe the issue to be researched**
Include any background information and available resources.

**Describe the goal of the research**
What's the desired outcome of this task? What artifacts should be produced?

**Describe the methodology**
Where can more information be found? Who should the assignee approach to ask questions? How can a decision be made?

**Would you like to work on the issue?**

**Comment by jingtang10** [comment]
i think this is done as part of #1195
