### ISSUE TITLE
Could not find com.google.android.fhir:data-capture:0.1.0-alpha04

### ISSUE THREAD

**Issue by tunm1228** [google/android-fhir#722]
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.fhir:data-capture:0.1.0-alpha04.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/fhir/data-capture/0.1.0-alpha04/data-capture-0.1.0-alpha04.pom
       - https://jcenter.bintray.com/com/google/android/fhir/data-capture/0.1.0-alpha04/data-capture-0.1.0-alpha04.pom
       - file:.../libs/data-capture-0.1.0-alpha04.jar
       - file:.../libs/data-capture.jar
     Required by:
         project :app

**Comment by tunm1228** [comment]
it works well with: com.google.android.fhir:data-capture:0.1.0-alpha03

**Comment by fredhersch** [comment]
Can you try alpah03

**Comment by tunm1228** [comment]
I don't change it anymore but keep the same version: alpha01
