### ISSUE TITLE
Allow disjunction of mulitple search parameters (i.e. name is joe or address is france)

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#723]
Discussed with @ekigamba @f-odhiambo @aditya-07 and @fredhersch yesterday. We identified 2 different use cases

1. while searching using a search parameter (i.e. given name), provide multiple possible matches that are joined together as a disjunction/OR. This is the example @ekigamba provided `("name" = ("joe" or "john")) AND ("age" = (11 or 12))` and this is what the FHIR RESTful APIs already support (not that we must follow the RESTful spec in our offline search API)
2. having multiple search parameters in a disjunction (OR) rather than conjunction (AND). At the moment when you list multiple search parameters in the search API, we add them on top of each other. In other words we apply them as filters and each filter further narrows down the resources. @ekigamba gave the example - we might want to search for patients whose name is XXX OR whose patient id is XXX. This is useful when in the UI we use 1 search box that searches for patients using multiple fields. In our discussion, we identified a way to get around this which is simply issue multiple search queries. However, I think in more complex cases the need for the search API to handle this properly is going to be more important (so the onus of deduplicating is not on the developer).

OK, so in this issue - let's focus on number 1. I will create another issue for number 2.

_Originally posted by @jingtang10 in https://github.com/google/android-fhir/issues/292#issuecomment-900113580_

**Comment by jingtang10** [comment]
In this issue we will focus on number 2.

**Comment by Tarun-Bhardwaj** [comment]
Code changes merged with PR #827
