### ISSUE TITLE
Create a DSL for the sync API

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#732]
**Is your feature request related to a problem? Please describe.**
Sync API can be improved by defining a DSL similar to https://github.com/google/android-fhir/pull/395

**Describe the solution you'd like**
https://github.com/google/android-fhir/pull/395

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Would you like to work on the issue?**
NA

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 , is this still required?

**Comment by jingtang10** [comment]
> @jingtang10 , is this still required?

This can probably be closed. The current sunc API probably won't benefit much from DSL.
