### ISSUE TITLE
Index common search parameters `_profile` and `_tag`

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#735]
See https://github.com/opensrp/fhircore/issues/276#issuecomment-899362217

https://www.hl7.org/fhir/search.html#all

we already handle last updated.

We want to handle profile and tag as well -- not entirely sure it makes sense to handle the other parameters

@maimoonak

**Comment by epicadk** [comment]
can be done in #488. I'll remove the other parameters.
