### ISSUE TITLE
Enable https://github.com/cashapp/licensee

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#750]
**Describe the Issue**
Enable the plugin and configure it so it allows only compatible licences in our dependencies.

**Would you like to work on the issue?**
@kevinmost made a headstart :)

**Comment by Tarun-Bhardwaj** [comment]
@kevinmost , could you please provide an ETA for fixing this issue?

**Comment by kevinmost** [comment]
This change is ready to go, but we are not submitting it until we verify that we can remove a problematic dependency from HAPI FHIR, rather than exempting that dependency in our licensee config.
