### ISSUE TITLE
Though enable when is false QuestionResponseItem with initial value present in questionnaire response at the time of data extraction.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#755]
**Describe the bug**
Found a new edge case which is not supported yet by sdk.
If the question item has enablewhen clause, and it also has initial coding value, in that case though enablewhen clause is false question response item with initial coding value present in questionnaire response at the time of data extraction.

Just consider the symptoms question as an example.
Symptoms main question has 4 answer options as checkboxes.
None of the answer options are selected initially.
There are hidden question items with initial coding value and enablewhen clause is false.
Bug = > though enable when is false, question response item with initial coding value present in question response at the time of data extraction.

**Component**
SDC library

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Its in progress.

**Comment by santosh-pingle** [comment]
#625

**Comment by jingtang10** [comment]
According to the standard: https://www.hl7.org/fhir/questionnaireresponse.html

`When a QuestionnaireResponse references a Questionnaire, all the items in the questionnaire SHOULD be included in the QuestionnaireResponse if they are relevant to the interpretation of the answers, including items of type = display. This might also include items that were >not enabled when the Questionnaire was answered, though of course these will not have answers`

It appears that in the case where a questionnaire item is disabled, we have the liberty to choose whether to include the response item (which will have no answers) or simply exclude it from the questionnaire response. given the issues we have run into (questionnaire size) i would advocate for not including them at all for simplicity.

**Comment by joiskash** [comment]
Yes this makes complete sense to me. If there is no answer, then its best to optimize for memory and not include a questionnaireResponse.item with an empty answer.
