### ISSUE TITLE
Questionnaire sync with HAPI throws OutOfMemory around page 700

### ISSUE THREAD

**Issue by maimoonak** [google/android-fhir#761]
**Describe the bug**
Questionnaire sync with HAPI throws OutOfMemory issue around page 700

**Component**
SDK FHIR Engine FhirSynchronizer

**To Reproduce**
1. Run Sync for Questionnaire
2. Wait until sync page offset comes around page 700 ( somewhere around http://hapi.fhir.org/baseR4?_getpages=e3f46ec4-94ea-4437-aa9c-7a65ef2d5c21&_getpagesoffset=720&_count=20&_pretty=true&_bundletype=searchset)

**Expected behavior**
Out of Memory Exception - https://github.com/google/android-fhir/files/7055990/questionnaire_outofmemory_exception.txt 

**Screenshots**

**Would you like to work on the issue?**
No.

**Comment by aditya-07** [comment]
Fixed with this PR #880.
