### ISSUE TITLE
Please import `Truth.assertThat` directly:

### ISSUE THREAD

**Issue by deepankarb** [google/android-fhir#766]
Please import `Truth.assertThat` directly:

```kt
import com.google.common.truth.Truth.assertThat
```

```kt
assertThat(engineOne).isSameInstanceAs(engineTwo)
```

_Originally posted by @kevinmost in https://github.com/google/android-fhir/pull/749#discussion_r699401052_

**Comment by arlhs** [comment]
Hey, I would like to contribute to this issue. I have fairly good experience in Android development.
As new to open source can you guide me how to contribute to this project.

**Comment by deepankarb** [comment]
Hi,

Check out https://github.com/google/android-fhir/wiki/Developer's-Guide, fix the issue and send a pull request.

Thanks,

**Comment by arlhs** [comment]
I have followed the setup instruction and deployed it on my system but it is showing error in gradle module.

Cannot access 'kotlin.collections.Collection' which is a supertype of 'org.gradle.api.artifacts.dsl.RepositoryHandler'. Check your module classpath for missing or conflicting dependencies
Cannot access 'kotlin.collections.Iterable' which is a supertype of 'org.gradle.api.artifacts.dsl.RepositoryHandler'. Check your module classpath for missing or conflicting dependencies
<img width="1440" alt="Screenshot 2021-09-05 at 3 08 45 PM" src="https://user-images.githubusercontent.com/19245260/132122296-ee2adb28-6241-4a4f-872a-b4437e444b84.png">

**Comment by maanuanubhav999** [comment]
> s 'kotlin.collections.Collection' which is a supertype of 'org.gradle.api.artifacts.dsl.RepositoryHandler'.

have you tried following [stackoverflow](https://stackoverflow.com/questions/68134482/cannot-access-kotlin-collections-collection-which-is-a-supertype-of-org-gradl)

**Comment by arlhs** [comment]
No, I cannot find any /Library/Caches/Google/AndroidStudio4.2 path in my mac.

**Comment by epicadk** [comment]
Which version of android studio are you using ? @arlhs

**Comment by arlhs** [comment]
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 27, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.facebook.ktfmt_idea_plugin, google-java-format, com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown

This my whole canfiguration.

**Comment by epicadk** [comment]
Doesn't seem to be an issue with the version or the config. If even invalidating and restarting doesn't work maybe you'll have to manually clear the cache.

**Comment by epicadk** [comment]
> No, I cannot find any /Library/Caches/Google/AndroidStudio4.2 path in my mac.

I think it should be `AndroidStudio2020.3` now.

**Comment by arlhs** [comment]
> AndroidStudio2020.3

In Caches directory only there is no directory named as Google

**Comment by harkirat2309** [comment]
Hello, I have downloaded the source code and have imported the Truth.assertThat directly in the respective file. I would like to contribute, so can you tell me the way to contribute?

Thanks
Harkirat Singh

**Comment by Mehul-Bisht** [comment]
@deepankarb is this issue still open?

**Comment by Harsh9149** [comment]
@deepankarb I would like to work on this issue. Please assign this issue to me.

**Comment by samiali12** [comment]
if this issue is not resolved, can you assign me?

**Comment by Harsh9149** [comment]
@samiali12 I am working on this issue.
