### ISSUE TITLE
SDK Compat with Android 12

### ISSUE THREAD

**Issue by jtournier23** [google/android-fhir#783]
There is a [behavior change](https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability) in Android 12 which requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent if the app is targeting Android 12. Current stable versions of WorkManager don’t have these flags, and so it affects all apps directly, or indirectly using WorkManager.

Android FHIR SDK has a dependency on an older version of WorkManager and so is affected.

Android FHIR SDK is using WorkManager 2.5.0.
https://github.com/google/android-fhir/blob/d65bc7e5164a182291adaaa311a247494746d57f/buildSrc/src/main/kotlin/Dependencies.kt#L113

Apps will throw the following exception in runtime

```
Fatal Exception: java.lang.IllegalArgumentException: com.sample.packagename: Targeting S+ (version 10000 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles. at android.app.PendingIntent.checkFlags(PendingIntent.java:386) at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:657) at android.app.PendingIntent.getBroadcast(PendingIntent.java:644) at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174) at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108) at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86) at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:920)
```

Developer could manually adding the a compatible version of WorkManager (i.e. 2.7.0-beta01) in their build.gradle file
```
// For apps targeting Android 12, add the following
constraints {
    implementation('androidx.work:work-runtime:2.7.0-beta01') 
}
```
AI

- [ ] Update the documentation to let developer knowing there is a work around before a new version is available.
- [ ]  Release a new version of the SDK, built on a compatible version of WorkManager

**Comment by omarismail94** [comment]
Closing as this is obsolete. We are using WorkManage 2.8 with compatabiltiy with Andorid API level 24-33
