### ISSUE TITLE
Design and implementation for generation of UUID by FHIR Engine

### ISSUE THREAD

**Issue by Tarun-Bhardwaj** [google/android-fhir#784]
**Is your feature request related to a problem? Please describe.**
How do we handle resource IDs by the FHIR SDK. This has implications for how we can do the Sync from the Android client to the FHIR Server and also resolve potential ID conflict issues

See [this deck](https://docs.google.com/presentation/d/1xx1mt8wjktVanrjQk3YQe0jmfyigTcQLM24kxv6v79A/edit#slide=id.gf01cad751a_0_5) for exploration of the different approaches

**Describe the solution you'd like**
Use PUT to create new resources on the server side. The SDK does not enforce (but strongly recommends) UUID creation (option 3)

* The SDK should be able to specify UUIDs for resources created by the client application 
* Resources created on the SDK side should be able to be sync'd to the FHIR server using PUT (not POST)
* The FHIR SDK will not enforce, but strongly recommend UUID creation - **default behaviour will be to create the UUIDs providing implementers the ability to override**

**Describe alternatives you've considered**
See this deck for detailed alternatives. In summary these include:
1. Server sets the resource IDs on POSTing the new resources
2. FHIR SDK enforces the creation of UUIDs

**Additional context**
1. UUIDs will only be generated for newly created resources.
2. This conforms to the standard according to the [FHIR spec](https://www.hl7.org/fhir/http.html#upsert). The FHIR SDK is effectively an extension of the FHIR server 
3. There will be server side requirements that will need to be enabled to support this. This will be documented as part of an ImplementationGuide

**Comment by fredhersch** [comment]
@aditya-07 I updated the issue here to reflect option 3 as the desired approach. I thought that we could address this by:

1. SDK will generate and assign resource IDs by default
2. SDK will allow implementers to override this in the methods for creating new resources
3. UUIDs provided by implementers should conform to the UUID standard (and will be validated by the SDK)
