### ISSUE TITLE
Add location mapping widget

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#800]
**Is your feature request related to a problem? Please describe.**
Add a location widget that allows you to submit the location with GPS coordinates and location details as FHIR [Location](https://www.hl7.org/fhir/location.html) resources
**Describe the solution you'd like**
1. **ANC Usecase**
 In the ANC use case, add a location of a facility or a family residence or village during a family registration/enrollment [Encounter](https://www.hl7.org/fhir/encounter.html#Encounter) that will in turn reference a Patient plus a Practioner. Tagged via [Encounter.location](https://www.hl7.org/fhir/encounter-definitions.html#Encounter.location.location) This should submit a location payload tagged to a patient while enrolling ANC Clients or registering a family and its householder members
2. **Covax Usecase**
In the Covax demo app, allow a user to submit the location details of where the Vaccination is being done

The Widget should be able to trigger the GPS to collect Latitude and Longitude coordinates for a precise location 

_Sample location payload for an Immunization facility_
```
{
  "resourceType": "Location",
  "status": "active",
  "name": "Arundel mobile clinic",
  "description": "Vaccination Site",
  "mode": "instance",
  "address": {
    "city": "Nairobi",
    "state": "MD",
    "country": "USA"
  },
  "physicalType": {
    "coding": [ {
      "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
      "code": "bu",
      "display": "Vaccination Center"
    } ]
  },
  "position": {
    "longitude": 42.256500,
    "latitude": -83.694710
  }
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
_**Sample location payload for an Immunization facility**_ 

```
{
  "resourceType": "Location",
  "status": "active",
  "name": "Arundel mobile clinic",
  "description": "Vaccination Site",
  "mode": "instance",
  "address": {
    "city": "Nairobi",
    "state": "MD",
    "country": "USA"
  },
  "physicalType": {
    "coding": [ {
      "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
      "code": "bu",
      "display": "Vaccination Center"
    } ]
  },
  "position": {
    "longitude": 42.256500,
    "latitude": -83.694710
  }
}
```

_**Sample location payload for a Household location/home**_ 

```
{
  "resourceType": "Location",
  "status": "active",
  "name": "Kasera Village",
  "description": "The home village location",
  "mode": "instance",
  "address": {
    "city": "Nairobi",
    "state": "Kenya",
    "country": "Kenya"
  },
  "physicalType": {
    "coding": [ {
      "system": "http://terminology.hl7.org/CodeSystem/location-physical-type",
      "code": "bu",
      "display": "Kasera Village"
    } ]
  },
  "position": {
    "longitude": 42.256500,
    "latitude": -83.694710
  }
}
```

**_Sample ANC mock_** 
<img width="313" alt="Screen Shot 2021-09-07 at 11 14 23 AM" src="https://user-images.githubusercontent.com/4540684/132313947-79eef4c0-6e54-4cf2-bb47-3ffbe2574431.png">

**_NB. The accompanying details of the Location (address, display name) can be collected via a questionnaire and appended to the Questionnaire response before extraction and saving/posting/sync as a location resource_**

**Comment by jingtang10** [comment]
What would the questionnaire response look like? It should be a response item to a single questionnaire item?

**Comment by puranjayK** [comment]
Hi @f-odhiambo, I would like to work on this issue
Could you please assign it to me

**Comment by f-odhiambo** [comment]
> Hi @f-odhiambo, I would like to work on this issue Could you please assign it to me
Kindly tag me to the PR or leave a comment once a PR has been raised for this

**Comment by puranjayK** [comment]
@f-odhiambo @jingtang10  could you please help me with the questionnaire of the Location widget.

**Comment by f-odhiambo** [comment]
> @f-odhiambo @jingtang10 could you please help me with the questionnaire of the Location widget.

Here you go http://turn-fhir.smartregister.org/fhir/Questionnaire/1922

**Comment by f-odhiambo** [comment]
Hey, @puranjayK Any progress update on this ? Perhaps we can link up on this sometime this week if available for more details. Let me know

**Comment by f-odhiambo** [comment]
@puranjayK Any progress update on this?

**Comment by puranjayK** [comment]
> @puranjayK Any progress update on this?

Sorry I couldnt work on this, as the covid situation got worse in my country.
I am having issues on how to make this widget and how the questionnaire is to be used

**Comment by PallaviGanorkar** [comment]
@jingtang10 @Tarun-Bhardwaj As discussed need to hold this issue for more requirement details.

**Comment by f-odhiambo** [comment]
HI @PallaviGanorkar , Are you going to be picking this issue ?

**Comment by MnCSSJ4x** [comment]
Hello I am new to contribution and would like to contribute to this issue if no one is on it.

**Comment by f-odhiambo** [comment]
Hi @MnCSSJ4x,Thanks for this ,  how can we connect to have a brief on this issue, can we ?
CC @FikriMilano

**Comment by f-odhiambo** [comment]
> we can connect via mail : xxxxx or if there is a slack channel please share an invite

I copied and obscured your email . Thanks

**Comment by FikriMilano** [comment]
@f-odhiambo what is 'Location Details' stands for? is it the Location widget? or it's simply a container from a 'group' type Questionnaire Item?
```
{
   "linkId":"2",
   "text":"Location Details",
   "item":[
      {
         "linkId":"2.1",
         "text":"Latitude",
         "answer":[
            {
               "valueString":"52.3676"
            }
         ]
      },
      {
         "linkId":"2.2",
         "text":"Longitude",
         "answer":[
            {
               "valueString":"4.9041"
            }
         ]
      }
   ]
}
```

**Comment by FikriMilano** [comment]
@f-odhiambo does that mean, there will be 2 location widgets to populate the Latitude and Longitude? (2.1 and 2.2)

**Comment by f-odhiambo** [comment]
> @f-odhiambo does that mean, there will be 2 location widgets to populate the Latitude and Longitude? (2.1 and 2.2)

Not really the widget should allow you to invoke the get coordinated from the phone GPS and then use the results to populate the Latitude and Longitude for the specific location

**Comment by f-odhiambo** [comment]
So the response will be something like this (0.0236, 37.9062) and then will need to split this comma separated value into Lat, Long  as 
```
"position": {
    "longitude": 42.256500,
    "latitude": -83.694710
  }
```

**Comment by FikriMilano** [comment]
Some useful reference:
https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt

https://github.com/google/android-fhir/blob/master/catalog/src/main/java/com/google/android/fhir/catalog/CustomQuestionnaireFragment.kt

https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/ui/questionnaire/CustomPhotoCaptureFactory.kt

https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/QuestionnaireItemBarCodeReaderViewHolderFactory.kt

https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt

**Comment by f-odhiambo** [comment]
@MnCSSJ4x Whats the progress on this ?

**Comment by FikriMilano** [comment]
@MnCSSJ4x could you send the Questionnaire and QuestionnaireResponse that you expect to look like?
Just to make sure we have the same idea on this,

**Comment by MnCSSJ4x** [comment]
@FikriMilano I was planning to follow the sample format mentioned until and unless there is some limitation

**Comment by f-odhiambo** [comment]
Hi @MnCSSJ4x , how is the progress here ?
CC @FikriMilano

**Comment by MnCSSJ4x** [comment]
@f-odhiambo 
I am having my semester exams this week. Will definitely address the coding part of the solution next week 
@FikriMilano can you provide me how you set up the environment locally to test ?

**Comment by FikriMilano** [comment]
@MnCSSJ4x you can just simply fork the repo, build the project then try to run the demo apps

**Comment by f-odhiambo** [comment]
@Tarun-Bhardwaj I think we can close this issue as it had been implemented on FHIR Core https://github.com/opensrp/fhircore/issues/1536

**Comment by fredhersch** [comment]
Thanks @f-odhiambo - would it be worth merging this back into the SDK? @jingtang10

**Comment by f-odhiambo** [comment]
> Thanks @f-odhiambo - would it be worth merging this back into the SDK? @jingtang10

We can have a discussion on this , happy to elaborate more on the solution we took

**Comment by ageryck** [comment]
@jingtang10 this can be re-assigned since the implementation in the attached PR was something different

**Comment by LZRS** [comment]
@f-odhiambo @f-odhiambo I had a suggestion of maybe using a normal Questionnaire item of type `string ` with a custom extension to render the widget

```json
 {
          "linkId": "Location widget",
          "type": "string",
          "text": "Record GPS Location",
          "required": true,
          "extension": [
            {
              "url": "https://github.com/google/android-fhir/StructureDefinition/questionnaire-itemControl",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "https://github.com/google/android-fhir/questionnaire-item-control",
                    "code": "location-widget"
                  }
                ]
              }
            }
          ]
        }
```
and to render, instead of  having it as single "record gps location", maybe have it render similar to the datepicker populating the textview with comma-separated `latitude, longitude, altitude`. This way we would probably still be able to use the already implemented utilities for example, adding extensions for help, attachment, translations and lalso show validation error incase field is required

![image](https://github.com/google/android-fhir/assets/12814349/4430a042-ca06-4df1-bc8d-1f83835127bf)

cc: @ageryck @FikriMilano @dubdabasoduba

**Comment by LZRS** [comment]
After reviewing the above implementation idea, we felt it may have had deficiencies of may be not being able to separate between latitude and longitude in consistent way. And so, with the help of the fhir org team, we had another idea that would be viable, to use a Questionnaire item of type `group`. The Questionnaire item would have a custom extension to represent location-widget and also have child items of type `string` with custom extensions to specify `latitude`, `longitude` and `altitude` -  these would be used in the ui to render and populate the coordinates.

Essentially, it would look like 

```json
 {
          "linkId": "location-widget",
          "type": "group",
          "extension": [
            {
              "url": "https://github.com/google/android-fhir/StructureDefinition/questionnaire-itemControl",
              "valueCodeableConcept": {
                "coding": [
                  {
                    "system": "https://github.com/google/android-fhir/questionnaire-item-control",
                    "code": "location-widget"
                  }
                ]
              }
            }
          ],
        "item": [
          {
            "linkId": "latitude",
            "type": "string",
            "required": true,
            "readOnly": true,
            "extension": [
              {
                "url": "gps-coordinate",
                "value": "latitude"
              }
            ]
          },
          {
            "linkId": "longitude",
            "type": "string",
            "required": true,
            "readOnly": true,
            "extension": [
              {
                "url": "gps-coordinate",
                "value": "longitude"
              }
            ]
          }
        ]
        }
```

@jingtang10 would love to hear what you think

cc @f-odhiambo @ageryck

**Comment by jingtang10** [comment]
I think defining custom widgets (together with custom extensions) in the SDC library is a great approach. This is fine.

The important thing is documentation and making sure people using your questionnaires are aware of the extensions you define otherwise your questionnaire will not be usable.

Be good to share this with the fhir chat community as well, especially to get grahame and lloyd's opinion.

**Comment by dubdabasoduba** [comment]
> After reviewing the above implementation idea, we felt it may have had deficiencies of may be not being able to separate between latitude and longitude in consistent way. And so, with the help of the fhir org team, we had another idea that would be viable, to use a Questionnaire item of type `group`. The Questionnaire item would have a custom extension to represent location-widget and also have child items of type `string` with custom extensions to specify `latitude`, `longitude` and `altitude` - these would be used in the ui to render and populate the coordinates.
> 
> Essentially, it would look like
> 
> ```json
>  {
>           "linkId": "location-widget",
>           "type": "group",
>           "extension": [
>             {
>               "url": "https://github.com/google/android-fhir/StructureDefinition/questionnaire-itemControl",
>               "valueCodeableConcept": {
>                 "coding": [
>                   {
>                     "system": "https://github.com/google/android-fhir/questionnaire-item-control",
>                     "code": "location-widget"
>                   }
>                 ]
>               }
>             }
>           ],
>         "item": [
>           {
>             "linkId": "latitude",
>             "type": "string",
>             "required": true,
>             "readOnly": true,
>             "extension": [
>               {
>                 "url": "gps-coordinate",
>                 "value": "latitude"
>               }
>             ]
>           },
>           {
>             "linkId": "longitude",
>             "type": "string",
>             "required": true,
>             "readOnly": true,
>             "extension": [
>               {
>                 "url": "gps-coordinate",
>                 "value": "longitude"
>               }
>             ]
>           }
>         ]
>         }
> ```
> 
> @jingtang10 would love to hear what you think
> 
> cc @f-odhiambo @ageryck

@LZRS how does this look on the QR?  Do you mind sharing a sample?

**Comment by LZRS** [comment]
> > After reviewing the above implementation idea, we felt it may have had deficiencies of may be not being able to separate between latitude and longitude in consistent way. And so, with the help of the fhir org team, we had another idea that would be viable, to use a Questionnaire item of type `group`. The Questionnaire item would have a custom extension to represent location-widget and also have child items of type `string` with custom extensions to specify `latitude`, `longitude` and `altitude` - these would be used in the ui to render and populate the coordinates.
> > Essentially, it would look like
> > ```json
> >  {
> >           "linkId": "location-widget",
> >           "type": "group",
> >           "extension": [
> >             {
> >               "url": "https://github.com/google/android-fhir/StructureDefinition/questionnaire-itemControl",
> >               "valueCodeableConcept": {
> >                 "coding": [
> >                   {
> >                     "system": "https://github.com/google/android-fhir/questionnaire-item-control",
> >                     "code": "location-widget"
> >                   }
> >                 ]
> >               }
> >             }
> >           ],
> >         "item": [
> >           {
> >             "linkId": "latitude",
> >             "type": "string",
> >             "required": true,
> >             "readOnly": true,
> >             "extension": [
> >               {
> >                 "url": "gps-coordinate",
> >                 "value": "latitude"
> >               }
> >             ]
> >           },
> >           {
> >             "linkId": "longitude",
> >             "type": "string",
> >             "required": true,
> >             "readOnly": true,
> >             "extension": [
> >               {
> >                 "url": "gps-coordinate",
> >                 "value": "longitude"
> >               }
> >             ]
> >           }
> >         ]
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jingtang10 would love to hear what you think
> > cc @f-odhiambo @ageryck
> 
> @LZRS how does this look on the QR? Do you mind sharing a sample?

The QuestionnaireResponse would probably look like this

```json
{
  "linkId": "location-widget",
  "item": [
    {
      "linkId": "latitude",
      "answer": [
        {
          "valueString": "41.40338"
        }
      ]
    },
    {
      "linkId": "longitude",
      "answer": [
        {
          "valueString": "2.17403"
        }
      ]
    }
  ]
}
```
