### ISSUE TITLE
Support evaluation of FHIRPath expressions and calculation within Questionnaire

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#803]
**Is your feature request related to a problem? Please describe.**
There is a need to be able to evaluate expressions within a Questionnaire. This is currently not supported by the data-capture library

**Describe the solution you'd like**
Support for FHIRPath expressions

**Describe alternatives you've considered**
Other options include CQL.

**Additional context**
@maimoonak - can you provide some example use cases for the types of expressions you are trying to evaluate

**Comment by maimoonak** [comment]
There are multiple requirements we figured out when working on Family Registration. These are broken down in branch ???????

### EnableWhen is not working fully - [FHIR Reference](http://build.fhir.org/ig/HL7/sdc/examples.html#using-enablewhen-enablebehavior-and-enablewhenexpression) 
**EnableWhen on answerInteger (crashes when value input for integer field)**
kotlin.NotImplementedError: Enable when operator GREATER_OR_EQUAL is not implemented.
Sample Questionnaire crashes [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_enablewhen_crashing.json#L68) 

**Alternate enableExpression is also not working**
An alternate is to use enableExpression which also does not work and can be seen [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_enablewhenexpression.json#L53)

### Hidden is partially working
**"hidden": true** - still not working  - [see here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_enablewhenexpression.json#L87) 
**extension hidden** - "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden" is working - [see here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_enablewhenexpression.json#L71)

### choice-orientation = horizontal - not working       
[see here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_enablewhenexpression.json#L16)

### Slider not working - [FHIR Reference](http://build.fhir.org/ig/HL7/sdc/examples.html#using-sliderstepvalue)
Exmple can be seen [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_slider.json#L46)

### readonly not working 
see example [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_readonly.json)

### calculated-expression and variable not working  - [FHIR Reference](http://build.fhir.org/ig/HL7/sdc/examples.html#using-calculatedexpression-and-variable)
see example where we want to take age OR birthdate as input and calculate the other from one which was input [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_calculatedexpression.json)

You can run app from branch and see different questionnaires created
<img src="https://user-images.githubusercontent.com/4829880/136003993-b0582a2b-a062-4a68-98f7-4a4c54923992.jpg" width="400" height="600"> <img src="https://user-images.githubusercontent.com/4829880/136004006-8db1e1ce-d940-42f2-8d7d-7262a513a670.jpg" width="400" height="600">

@f-odhiambo @fredhersch

**Comment by jingtang10** [comment]
Thanks for this @maimoonak. I'll reply to these one separetely.

First, about the hidden extension - there is only an extension: http://build.fhir.org/ig/HL7/sdc/rendering.html#hidden I don't see the `hidden` field in the questionnaire definition. So I think the usage [here](https://github.com/google/android-fhir/blob/mssng-quest-feat/datacapturegallery/src/main/assets/sample_family_member_registration_enablewhenexpression.json#L87) is incorrect.

**Comment by maimoonak** [comment]
@jingtang10 I could not figure out **calculated-expression and variable** - [FHIR Reference](http://build.fhir.org/ig/HL7/sdc/examples.html#using-calculatedexpression-and-variable) that this issue is tracking into roadmap [here](https://github.com/google/android-fhir/wiki/Structured-Data-Capture-Library-Developer's-Guide). Could you please guide which point reflects this and if this is under progress.

**Comment by jingtang10** [comment]
@maimoonak - given that all the other issues are being tracked/closed i'm goign to close this bug. For the issue with enable when expressions let's continue the discussion in #819
