### ISSUE TITLE
Setup benchmark module

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#825]
This is really good work @epicadk! 🎉

Can we set up the benchmark module in a separate PR?

_Originally posted by @jingtang10 in https://github.com/google/android-fhir/pull/773#pullrequestreview-774805695_

**Comment by epicadk** [comment]
@Tarun-Bhardwaj Don't know why this fails on the CI. I tried running the tests locally through Android Studio and it works. Even in the official [performance samples](https://github.com/android/performance-samples) the benchmarks/profiling isn't done in the CI. 

Do we want the benchmarks to run on CI or can we create a separate issue for this seeing as this is blocking quite a lot of issues?

**Comment by f-odhiambo** [comment]
Any update on this @epicadk @Tarun-Bhardwaj  ?

**Comment by jingtang10** [comment]
#1489
