### ISSUE TITLE
Patient data is not reflecting on "Registered Patient" List when user add patient details with city as "nairobi" and country as "Ke" (Lowercase), 

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#832]
**Describe the bug**
Patient data is not reflecting on "Registered Patient" List when user add patient details with city as "nairobi" and country as "Ke" (Lowercase), 

**Component**
Core library, reference app

**To Reproduce**
1. Go to 'Reference app'
2. Click on '+' icon 
3. Enter patient details: First name, full name, date of birth,Gender
4. Enter city as 'nairobi'
5. Enter country as 'ke'
6. Click on submit button
7. Search patient in "Registered patient" list
8. Observe behavior

**Expected behavior**
It should show newly added patient details in Registered patient list

**Smartphone (please complete the following information):**
 - Device: Redmi note 7 pro
 - Android version: 10
 - Build number: [e.g. Settings -> About phone -> Build number]

@jingtang10 @Tarun-Bhardwaj @aditya-07

**Comment by PallaviGanorkar** [comment]
Search is done on city name using modifier as StringFilterModifier.MATCHES_EXACTLY and value is "NAIROBI".
So its strictly filtering as per hardcoded city value in capital letters.

To fix this , there are 2 more enum values in StringFilterModifier like STARTS_WITH and CONTAINS.
But, after using these values search result will contain any city name having "NAIROBI" as substring. which breaks requirement of city name.

So to fix this either we need to add extra enum value as case insensitive. So please update on this what is the requirement.

**Comment by aditya-07** [comment]
Fhir spec for string search specifies the three matching modifiers MATCHES_EXACTLY, STARTS_WITH and CONTAINS. We should use STARTS_WITH in this case. See http://www.hl7.org/fhir/search.html#string .
