### ISSUE TITLE
Required field overlaps drop-down list arrow in sdc Gallery app

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#840]
**Describe the bug**
Required field marker/option overlaps drop-down list option arrow.

**Component**
 SDC gallery app

**To Reproduce**
1. Go to data capture library
2. Click on "Hiv risk assessment"
3. Scroll down to question 3

**Expected behavior**
Both the field should be displayed seperately.

**Screenshots**
![Screenshot_2021-10-16-08-55-58-34_7a7e5d6d016f02b1944ad7d1dd25f1ac](https://user-images.githubusercontent.com/26630009/137571979-6202c3a2-1dc0-4730-9bd0-8cdc82367aa3.jpg)

**Smartphone (please complete the following information):**
 - Device:  Realme narzo 10
 - Android version:  android 11
 - Build number: RMX2191_11_C._12
 - 
**Additional context**

**Would you like to work on the issue?**
not sure

**Comment by jingtang10** [comment]
#878

**Comment by jingtang10** [comment]
Closing since this was resolved in #878
