### ISSUE TITLE
Support patient resource deletion operation in reference app.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#855]
**Describe the bug**
As of now reference app does not support patient delete operation.

**Component**
Core library, reference app

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel4a emulator]
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Tarun-Bhardwaj** [comment]
Closing the issue as this feature is not needed.
