### ISSUE TITLE
Handle deleted resource in the engine

### ISSUE THREAD

**Issue by aditya-07** [google/android-fhir#856]
**Describe the bug**
For fhir-engine, there is no way to purge a Fhir Resource like Patient that is already synced on to the device via engine and later deleted on the server (maybe by some other client).

**Component**
Core library

**Comment by Tarun-Bhardwaj** [comment]
@jingtang10 to review reference documentation.

**Comment by fredhersch** [comment]
This issue should be closed now with Purge API. The action is to update the wiki documentation to ensure there is good exmaple for how to do this using the Purge API. @Tarun-Bhardwaj can you please create a new issue for this
