### ISSUE TITLE
After submitting complete survey, Questionnaire in observations is missing

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#859]
**Describe the bug**
After submitting complete survey, Questionnaire in observations is missing. It is only showing answer

**Component**
SDC library, reference app

Precondition:
Patient should already added

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Reference App'
2. Search for Patient already added
3. Click on 'Complete survey'
4. Add all details and click on submit
5. Observe "observation section" on patient card

**Expected behaviour**
It should show observations with Questionnaire

**Screenshots**
![Screenshot_2021-10-25-16-42-24-951](https://user-images.githubusercontent.com/64417713/138685996-9c849182-ec12-48c3-a31c-35af791aa814.jpeg)

**Smartphone (please complete the following information):**
 - Device: Lenovo Tab
 - Android version: 10
 - Build number: TB-8505X-S320017_210427_BMP

**Comment by santosh-pingle** [comment]
@anita-vadverao 
Can you please provide more details with example what is missing and expected?

**Comment by anita-vadverao** [comment]
In attached screenshot, It shows "Yes" but what is the question for which it is showing "Yes" is missing.
Also it is showing "ValueQuantity" text
![138685996-9c849182-ec12-48c3-a31c-35af791aa814](https://user-images.githubusercontent.com/64417713/146177395-96031aa0-fcf0-4abc-a2e7-7f456fca0636.jpeg)
.

**Comment by santosh-pingle** [comment]
@anita-vadverao 
Regarding `No ValueQuantity` text, some observations does not have value, the only have code.
e.g symptoms, medical history, risk factors.
In that case as per existing code we are showing `No ValueQuantity`.

do you think, we should show something else if observation does not have value.

**Comment by santosh-pingle** [comment]
If you see a risk factor questionnaire answer options, some of them have display value either yes or no.
e.g
```
"valueCoding": {
 "code": "Y",
 "display": "Yes"
}
```

This answer option is the code for creating an Observation resource.
On the Patient details card, Observation display text  is shown.

Just for reference
With Observation, the focus is only on the meaning of the answer, not what question was asked (assuming a question was even asked at all).  https://www.hl7.org/fhir/questionnaireresponse.html#bnr

**Comment by santosh-pingle** [comment]
One of the approaches is to modify the questionnaire such that the answerOption valueCoding display element will contain short version of question text along with answer.

**Comment by santosh-pingle** [comment]
cc @jingtang10

**Comment by jingtang10** [comment]
@shelaghm
