### ISSUE TITLE
Stop using AppCompatActivity in the reference app

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#86]
with our min sdk version 21, we probably don't need to use AppCompatActivity in the reference app

**Comment by maanuanubhav999** [comment]
I would like to work on this @jingtang10 @fredhersch @epicadk

**Comment by maanuanubhav999** [comment]
Will it be beneficial if I am removing AppCompactActivity and adding FragmentActivity.

**Comment by Anshul-9923** [comment]
@jingtang10 I would like to work on this issue, can you please assign it to me?

**Comment by jingtang10** [comment]
Looking at the documentation here https://developer.android.com/training/appbar/setting-up.html it appears that we should just use app compat activity anyway.

Let's just close this issue.
