### ISSUE TITLE
Reference app crashed on launch

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#864]
**Describe the bug**
App is crashing after launched

**Component**
Core library, reference app

**To Reproduce**
In android-fhir-master project,
1. change the BASE_URL in HapiFhirService.kt file to http://<local:system:ip>:8080/fhir/ for a phone.
2. In FhirPeriodicSyncWorker.kt, remove NAIROBI so your sync-data looks like  mapOf("address-city" to "").Incase you need all observations or other resources, just add them to the map like ResourceType.Observation to mapOf("subject" to "Patient/1") to get observations for a particular patient or ResourceType.Observation to mapOf() to get all observations in the server. Just remember that it might take a long time to sync everything in case the server has a lot of data.
3. In PatientListViewModel.kt comment-out code inside private fun filterCity(search: Search) so that we don't just search for patients from "NAIROBI".
private fun filterCity(search: Search) {
  search.filter(
     Patient.ADDRESS_CITY,
     {
//        modifier = StringFilterModifier.MATCHES_EXACTLY
//        value = "NAIROBI"
     }
    )
  }
4. network_security_config.xml add the following line with appropriate ip for your local server. <domain includeSubdomains="true"><local:system:ip></domain>
5. Run reference App
6. Observe App Launch in device
7. 
**Expected behavior**
App should not crashed.

**Smartphone (please complete the following information):**
Device: Lenovo Tab
Android version: 10
Build number: TB-8505X-S320017_210427_BMP

**Comment by epicadk** [comment]
Can you share the log?

**Comment by santosh-pingle** [comment]
@anita-vadverao 
Can you please check whether issue is still reproducible at your end and also can you please share the log?
Actually, I am trying to reproduce it but do not see any crash..

**Comment by santosh-pingle** [comment]
Issue is not seen on the latest build beta 03.
