### ISSUE TITLE
On click sync button, It shows "Sync: Failed at <Date and time>" and showing sockettimeouterror

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#865]
**Describe the bug**
On click sync, It is failing
It is showing below three toast messages
Sync: Unkown state
Sync: In progress with patient
Sync: Failed sync at <date and time>

**Component**
Core library, reference app, or SDC gallery app

Precondition:
2 patients are added in reference app

**To Reproduce**
1. Go to 'Reference App'
2. Click on Menu on left hand side
3. Click on Sync
4. Observe error

**Expected behaviour**
It should sync data successfully

Smartphone (please complete the following information):
Device: Lenovo Tab
Android version: 10
Build number: TB-8505X-S320017_210427_BMP

**Comment by jingtang10** [comment]
obsolete. closing.
