### ISSUE TITLE
Allows screener survey submission though risk factors form inputs are not answered.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#866]
**Describe the bug**
As per screener survey questionnaire, it is mandatory to provide input to risk factors questionnaire items.
Though, these questionnaire items are not answered and if user click on Submit button then survey get submitted.  

**Component**
 reference app

**To Reproduce**
1. Open reference app
2. Click on patient row item, it shows patient details screen
3. Click on `Complete Survey`, it shows survey questionnaire form
4. Do not provide answers on risk factors screen, 
5. Provide input to vital signs.
6. Click on submit button, it submits the survey.  

**Expected behavior**

If risk factors answers are mandatory as per questionnaire then it need to be answered, if not then it should not allow to submit the survey.
Or
As of now, we are not considering risk factors while assessing patient risk assessment, then in that case we should not make it mandator.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: [e.g. Settings -> About phone -> Android version]
 - Build number: [e.g. Settings -> About phone -> Build number]

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Manikant25** [comment]
@santosh-pingle Can I take this?

**Comment by santosh-pingle** [comment]
Just check with @jingtang10 before to start working on it, in case if Jing has any plan.

**Comment by jingtang10** [comment]
I don't think we have a clear action plan for this issue.

The problem is that the submit button is entirely in the control of the app developer. So it's really up to the app to decide if they want to accept a questionnaire response even if the validation fails.

so i think this might be working as intended. but we should also explore different validation apis and options.

**Comment by santosh-pingle** [comment]
Let me verify whether issue is already fixed?

**Comment by jingtang10** [comment]
i think this is now controled by the entry-mode. if it's sequential, you cannot progress to the next page without completing required questions on the current page. but if it's not sequential, you can, and should be able to submit after the popup on the last page. See #1671.
