### ISSUE TITLE
Added patient on one device, it is not reflecting on other device

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#873]
**Describe the bug**
Patient is added on one device and it is not reflecting on other device

**Component**
Core library,reference app

Precondition:
One two devices reference app is installed with same Database ( local hapi server database)

**To Reproduce**
1. On device one, Go to 'Reference app'
2. Click on '+'
3. Enter all valid details and click on submit button
4. On device two, Go to reference app
5. Click on Menu button on left top corner
6. Click Sync button
7. Observe sync
8. After successful sync, Search for patient added from device one
9. Observe search result

**Expected behavior**
Patient added from device one should get reflect on device two

**Screenshots:**
SamSung: Added patient from this device
![Screenshot_20211026-150828](https://user-images.githubusercontent.com/64417713/138853655-a5a160f1-e035-452e-99e0-578b33fcadff.jpg)
Lenovo: Sync on this device
![Screenshot_2021-10-26-15-09-22-656](https://user-images.githubusercontent.com/64417713/138853647-e2e99777-60d1-4fe1-bd4d-3b42509c780e.jpeg)
Lenovo: search on this device
![Screenshot_2021-10-26-15-09-33-560](https://user-images.githubusercontent.com/64417713/138853652-e19bbac7-ad16-4470-8aec-fdfed323840e.jpeg)

**Smartphone (please complete the following information):**
**Device one:**
Device: Lenovo Tab
Android version: 10
Build number: TB-8505X-S320017_210427_BMP
**Device Two:**
Device: Nokia 3.4
Android version: 11
Build number: 00WW_2_410

**Comment by santosh-pingle** [comment]
This issue is no more visible on latest build beta 03, so closing it. thanks!
