### ISSUE TITLE
Reference App crashed on search

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#877]
**Describe the bug**
Reference app is getting crashed on searching data

**Component**
Core library,reference app

Precondition:
In fhirEngine database, under ResourceEntity table, Update patient id in seralizedResource section

**To Reproduce**
1. Go to 'Reference App'
2. Tap on search, enter patient name whose patient id is updated in precondition
3. Observe behaviour

**Expected behavior**
App should not get crashed

**Logs**
[CRASH.log](https://github.com/google/android-fhir/files/7418295/CRASH.log)

**Smartphone (please complete the following information):**
 Device: Lenovo Tab
 Android version: 10
 Build number: TB-8505X-S320017_210427_BMP

**Comment by santosh-pingle** [comment]
There are two fatal exceptions.
1. As per the attached log, exception is dataformat exception which was caused at the time of json parsing, because of corrupted json string.

2.  If you update the patient resource id to the new value which is not present in existing database in resource entity table under the serialized resource section, and when you click on patient item which has old value then it throws ResourceNotFoundException.

**Comment by jingtang10** [comment]
thanks @santosh-pingle for looking into this. 1) which json string is corrupt? can you post the json itself? 2) how can you update the patient id in the app?

**Comment by santosh-pingle** [comment]
@jingtang10 
It was already mentioned in the issue under the **precondition** section that you have to modify/edit patient id in application local database in ResourceEntity table.

1. In application local database through database inspector remove entity separator `,`
   something like
  ```
       {
  "resourceType": "Patient",
  "id": "2"
   meta": {
    "versionId": "1",
    "lastUpdated": "2021-10-25T07:11:46.619+00:00",
    "source": "#FX9VKkcbVaDbgkW4"
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Generated by <a href=\"https://github.com/synthetichealth/synthea\">Synthea</a>.Version identifier: v2.4.0-404-ge7ce2295\n .   Person seed: 6457100290386878904  Population seed: 0</div>"
  },

```

2. You have to modify application local database ResourceEntity table seralizedResource  column using application inspection through **database inspector.**

**Comment by santosh-pingle** [comment]
As per offline discussion with @jingtang10, we should not modify local resources, if we modify it then app will start behaving inconsistently.
Therefore we are closing it .
