### ISSUE TITLE
Quantity type is not supported yet for minValue and MaxValue extension

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#881]
**Is your feature request related to a problem? Please describe.**
It gives error not implemented yet.

Implemented below unit test, but it had thrown quantity type is not implemented yet.

```
@Test
  @UiThreadTest
  fun displayValidationResult_validValue_shouldAssignErrorNull() {
    viewHolder.bind(
      QuestionnaireItemViewItem(
        Questionnaire.QuestionnaireItemComponent().apply {
          addExtension().apply {
            url = "http://hl7.org/fhir/StructureDefinition/minValue"
            setValue(Quantity(2.2))
          }
          addExtension().apply {
            url = "http://hl7.org/fhir/StructureDefinition/maxValue"
            setValue(Quantity(4.4))
          }
        },
        QuestionnaireResponse.QuestionnaireResponseItemComponent().apply {
          addAnswer(
            QuestionnaireResponse.QuestionnaireResponseItemAnswerComponent().apply {
              value = Quantity(3.3)
            }
          )
        }
      ) {}
    )

    assertThat(viewHolder.itemView.findViewById<TextInputEditText>(R.id.textInputEditText).error).isNull()
  }

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by epicadk** [comment]
> Can't we jut mark this ticket invalid and also not include test? as you rightly mentioned [minValue](http://hl7.org/fhir/R4/extension-maxvalue.html) and [maxValue](http://hl7.org/fhir/R4/extension-minvalue.html) supported types.

The `notImplementedError` thrown may be confusing. Maybe we could replace that with an `IllegalArgumentException`? Apart from that I agree.

**Comment by jingtang10** [comment]
> Isn't this because minValue is suppose to be applied only to date, dateTime, time, decimal, integer? As mentioned [here](http://hl7.org/fhir/R4/extension-minvalue.html).
> 
> I think we could improve the error message to say quantity type is not supported by the min/maxvalue extensions.

yeah i don't undrestand why shouldn't the min/max value validation support quantity - i kinda feel like we should propose a change to the standard. can you do that please @epicadk (if you agree)?

i kinda think we should at least try to compare on a best-effort basis and in this case the unit test shouldn't throw exception.

**Comment by jingtang10** [comment]
please see http://build.fhir.org/ig/HL7/sdc/behavior.html

**Comment by epicadk** [comment]
> please see http://build.fhir.org/ig/HL7/sdc/behavior.html

that's interesting, so we probably want to  support `minQuantity` and `maxQuantity` extensions. I would be open to working on this.

**Comment by jingtang10** [comment]
@epicadk you already have a few things on your plate. If you don't mind let's let @juanchazo work on this and for you for focus on the other issues? Thanks

**Comment by epicadk** [comment]
> @epicadk you already have a few things on your plate. If you don't mind let's let @juanchazo work on this and for you for focus on the other issues? Thanks 

Oh sure

**Comment by delcroip** [comment]
linked to https://github.com/google/android-fhir/issues/1849
