### ISSUE TITLE
Use ICU library to format date

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#898]
**Describe the Issue**
We use hardcoded date time format strings in the code, but we reall should use icu:

https://developer.android.com/guide/topics/resources/internationalization

**Would you like to work on the issue?**
NA

**Comment by maanuanubhav999** [comment]
Hey, @jingtang10  Can I work on this issue?

**Comment by jingtang10** [comment]
@maanuanubhav999 given you're working on a number of other issues i'm going to try to assign this to vvikramraj@.

thanks for volunteering. once you're done with the current prs let's find you something else to do.
