### ISSUE TITLE
[Apple Silicon] Cannot connect to SQLite datasource on M1

### ISSUE THREAD

**Issue by f-odhiambo** [google/android-fhir#914]
**Describe the bug**
Issues around SQLite loaders while trying to run apps on M1 based macs. No native library to support 

**Component**
Reference app or SDC gallery app

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to build and run the Android FHIR SDK sample apps on M1 silicon 
2. See error 

```
Error opening connection
No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64.

Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64)
	at androidx.room.verifier.DatabaseVerifier.<clinit>(DatabaseVerifier.kt:71)

```
**Suggested behavior** 

Open `build.gradle.kts` in engine 
Add 
 ` kapt("org.xerial:sqlite-jdbc:3.34.0")`
Before
`  kapt(Dependencies.Room.compiler)`

**Expected behaviour**
The application should build normally similar to intel based macs

**Screenshots**
N/A

**Smartphone (please complete the following information):**
Try running on Emulator or Physcicsla device API 25 and above 

**Additional context**
See more here https://youtrack.jetbrains.com/issue/DBE-12342
**Would you like to work on the issue?**
N/A

**Comment by jingtang10** [comment]
are you still experiencing this issue?

i'm not sure if apple silicon or m1 is the issue. it's probably more likely the android sdk in android studio. can you please share your gradle jdk setup and the project structure set up in android studio?

**Comment by epicadk** [comment]
@f-odhiambo room 2.4.0 solves this issue according the the release notes. See 2.4.0-alpha03 https://developer.android.com/jetpack/androidx/releases/room#version_240_2

**Comment by Tarun-Bhardwaj** [comment]
@f-odhiambo , can this issue be closed based on the comments above?

**Comment by f-odhiambo** [comment]
yes
