### ISSUE TITLE
SDK to allow evaluation of CQL against a FHIR resource

### ISSUE THREAD

**Issue by litlfred** [google/android-fhir#915]
In application logic, it would be desirable expose and API to allow execute a CQL expression against a FHIR resource.

General Workflow:
 * A) (optional) application refreshes cache of FHIR Library resources containing CQL from a remote server.    
 * B) application populates a FHIR library resource with required data fields
 * C) application executes a CQL expression or Library resource against the context of the populated resource    
 * D) resultant content is returned to application for further processing.  content could be a FHIR data type or a FHIR resource
 
 Specific Use Case Workflow:  
Verification App for Digital Documentation of Covid Certificates.  The application:
 *  B.0) end user selects which business rule (decision support) workflow (e.g. vaccination check, negative test result check) 
 *  B.1) end user scans a QR code
 *  B.2) application determines type of QR code and de-serializes appropriately
 *  B.3)  applications creates and populates a DDCC Document Resource with deserialized content https://worldhealthorganization.github.io/ddcc/StructureDefinition-DDCCDocument.html 
 *  C.0) application determines appropriate business rule (e.g. does the course of vaccination meet jurisdiction requirements, was there a negative test results within the last X hours) based on workflow and retrieves appropriate Library resource from cache
 *  C.1) application evaluates the business rule as CQL via Library resource
 *  D.0) CQL expression results in a codableConcept (e.g. Yes/No) 
 *  D.1) application displays pass / not-pass status to end user

**Comment by fredhersch** [comment]
@pld Are you able to share more details about the CQL use case you had. We are trying to understand if there is a generic operation that could be developed for CQL evaluation and estimate effort

**Comment by pld** [comment]
Sure, there are some details in this discussion https://github.com/opensrp/fhircore/discussions/659, and specifically this comment relates to a pipeline with a CQL step, https://github.com/opensrp/fhircore/discussions/659#discussioncomment-1548255

**Comment by djritz** [comment]
Hi all -- I'm not sure if it is applicable to the use cases Carl described, but there is a javascript implementation of a CQL engine that has been developed by Mitre. It is found, here: https://www.npmjs.com/package/encender

**Comment by fredhersch** [comment]
@jingtang10 can you comment on this one. Thanks

> @fredhersch you mentioned that in the interim, we can load the CQL engine library in the app, outside of the SDK. Given your experience, any additional guidance you can offer here? Flagging for @vitorpamplona

**Comment by jingtang10** [comment]
@litlfred @fredhersch yeah you can depend on the CQL engine java library in the app and we had a demo actually: https://github.com/google/android-fhir/tree/f871788b18e35bcd20b1c4f3d9b02daeed9082cf/cqlreference

I think in the issue @pld linked above there are some updates on using this approach.

The point of the workflow library is to support operations wrt workflows such as evaluate measure, such as care plan generation. For a specific cql evaluation I think we haven't really spoken a lot about if there's any generic API we can provide beyond CQL engine/evaluator @brynrhodes -- this is probably something we should catch up on next time as well.

**Comment by vitorpamplona** [comment]
Hi all! 

Thanks for the tips! 

Is anyone working on a better implementation to convert CQL to ELM on Android? On my tests, it's taking at least 2 seconds to convert using [cql2elm](https://github.com/DBCG/cql-evaluator/), sometimes more than 4s.  :( 

I am starting to wonder if I should make the conversion on a Server and only load ELM files directly on Android

Full app is here if anyone wants to check the implementation out: 
https://github.com/Path-Check/who-verifier-app/

There is a JUnit test class CQLTest that simply loads a CQL file and applies expressions against FHIR Bundle.

**Comment by citizenrich** [comment]
Hi, if you don't mind a lurker's opinion... The FHIR Library resources types are meant to be quite portable and should not contain sensitive information. So, I would anticipate that on-device CQL->ELM conversion can be unnecessary and sharing Libraries can be in centralized datastores would not compromise PII.

**Comment by pld** [comment]
Very cool, thanks for sharing the link! Pre-computing makes sense to me too. If you don't want to do server-side, you could memoize cql2elm and keep it warm by calling it for any CQL that arrives on device, to it stays out of the user interaction loop

We haven't gotten to this optimization yet, but pretty sure we'd want to do something like this as well, 2-4s is quite a delay

**Comment by litlfred** [comment]
I believe that the ideal intent is to pre-compile CQL to ELM and put that in the Library.  Sorry if I confused matters in this regard.

**Comment by fredhersch** [comment]
@pld @vitorpamplona Checking in here. Has this issue been mostly resolved now? Is there further discussion about SDK API to enable general CQL evaluation?

**Comment by Tarun-Bhardwaj** [comment]
> @pld @vitorpamplona Checking in here. Has this issue been mostly resolved now? Is there further discussion about SDK API to enable general CQL evaluation?

@vitorpamplona , are we progressing with this issue?

**Comment by fredhersch** [comment]
@vitorpamplona Is this issue now resolved as we are able to compile and execute CQL. Is that correct?

cc: @jingtang10

**Comment by vitorpamplona** [comment]
We are just waiting for this PR to be merged https://github.com/google/android-fhir/pull/1603

**Comment by vitorpamplona** [comment]
Fixed on https://github.com/google/android-fhir/pull/1603
