### ISSUE TITLE
`Observation.effective` not available in Date Index

### ISSUE THREAD

**Issue by deepankarb** [google/android-fhir#92]
We need to implement mapping of Search Parameters to the underlying data type of the property. Currently, we are assuming the accessors are named `getXXElement` for `date` and `getXX` for all other `SearchParamDefinition` types. For example `Patient.birthDate` has `getBirthDateElement()`. However, this is not universally true in HAPI FHIR. E.g. `Observation.effective` does not have a getEffectiveElement method.

**Comment by jingtang10** [comment]
I believe this would be resolved by #281. @deepankarb can you verify please?

**Comment by deepankarb** [comment]
Thanks @jingtang10 I am looking at #281.
