### ISSUE TITLE
Handle Insurance-plan name in indexing

### ISSUE THREAD

**Issue by epicadk** [google/android-fhir#921]
**Is your feature request related to a problem? Please describe.**
https://github.com/google/android-fhir/pull/905#discussion_r746935852

**Describe the solution you'd like**
Handle insurance-plan in the indexing.

**Describe alternatives you've considered**

**Additional context**
This is happening because the expression for is simply `name | alias` as opposed to `InsurancePlane.name | InsurancePlan.alias` 

![image](https://user-images.githubusercontent.com/56596662/141281221-a92de62a-41b5-41b3-a87e-3f0c2e931aad.png)

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by jingtang10** [comment]
@epicadk have you raised an issue to fix the standard?

**Comment by epicadk** [comment]
We should still merge the fix till the issue is solved right?

**Comment by jingtang10** [comment]
actua

> We should still merge the fix till the issue is solved right?

yes - but please add a comment in the code to link the jira issue.
