### ISSUE TITLE
Internationalisation for the Questionnaire answerOption item using Translation Extensions

### ISSUE THREAD

**Issue by ndegwamartin** [google/android-fhir#929]
**Is your feature request related to a problem? Please describe.**
We currently do not have internationalisation for the [Questionnaire item answer options](https://www.hl7.org/fhir/questionnaire-definitions.html#Questionnaire.item.answerOption) 

**Describe the solution you'd like**
Support for multiple translations can be added using _Extensions_ by implementing the [HL7 FHIR spec here](http://hl7.org/fhir/languages.html##ext) _(Translation Extensions)_

**Describe alternatives you've considered**
The alternatives for translations include `CodeSystem` and `ValueSet` designations as defined in [the spec here](http://hl7.org/fhir/languages.html##term). Those will be implemented/tracked as a separate ticket here #552 

**Additional context**
We already have _Translation Extensions_ implemented on the FHIR SDK for the `QuestionnaireItemComponents`. See #465

**Would you like to work on the issue?**
Yeah

**Comment by jingtang10** [comment]
Can you provide some questionnaire examples with answer options with translation?

The only one I found is here: https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Coding-uv-ips.html

and according to this it seems the translation is on the `display` field rather than the `Coding` itself.

**Comment by ndegwamartin** [comment]
@jingtang10 you're right, the implementation is now refactored to use translation extensions on the display field. See [PR#927](https://github.com/google/android-fhir/pull/927)
