### ISSUE TITLE
Add an empty option for DropDown Widget

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#940]
**Is your feature request related to a problem? Please describe.**
Error correction for the [DropDown Widget](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt) 

**Describe the solution you'd like**
I was planning to have something similar to #781 so that clicking on the drop-down choice would clear the answer.

**Describe alternatives you've considered**

**Additional context**
[ Choice questions should have clear options](https://github.com/google/android-fhir/pull/546#issuecomment-872723271
)

**Would you like to work on the issue?**
yes

**Comment by maanuanubhav999** [comment]
Hey @shelaghm
Do you have any input on the UX/UI for the drop-down error correction 

CC @jingtang10

**Comment by maanuanubhav999** [comment]
![sample screenshot](https://user-images.githubusercontent.com/26630009/145459023-3c56c256-0a32-4448-91cd-76e7cc51618f.jpg)

Maybe we can make it more intuitive by adding None instead of adding an empty option? @jingtang10

**Comment by jingtang10** [comment]
Thanks for the screenshot @maanuanubhav999!

I would rather not use the word "none". Reason being I would love to avoid having another string to translate...

I think either empty or a "-" is good. @shelaghm  @fredhersch fyi

Also can we have this as the first option rather than last please?

**Comment by maanuanubhav999** [comment]
@jingtang10 sure

**Comment by shelaghm** [comment]
Agreed to make this first option. One more idea is to do "- Select -" instead of "-" to make the action more obvious? 

Screenshot from eBay below that uses this pattern.
![Screen Shot 2021-12-13 at 12 35 54](https://user-images.githubusercontent.com/86378921/145885023-63b38df9-9512-4335-885c-8527d7228607.png)

**Comment by maanuanubhav999** [comment]
thanks @shelaghm will do the same.
