### ISSUE TITLE
Exclude contrib packages from code coverage report

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#942]
**Describe the Issue**

We are adding code to the contrib package in the sdc lib which will decrease the test coverage. We should exclude such packagesin the jacoco report. 

**Would you like to work on the issue?**

no thanks but happy to guide

**Comment by Harsh9149** [comment]
@jingtang10 @Tarun-Bhardwaj  I would like to work on this issue. Please assign this issue to me.

**Comment by Harsh9149** [comment]
@jingtang10 @Tarun-Bhardwaj its been 6 days and I have not get any reply from your side. Please assign it to me. I already started working on this issue.
