### ISSUE TITLE
Adapt Patient card color according to dark/light theme

### ISSUE THREAD

**Issue by maanuanubhav999** [google/android-fhir#960]
**Is your feature request related to a problem? Please describe.**
The patient card color concept needs to be adaptable in light/dark themes in the reference app

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[Discussion](https://github.com/google/android-fhir/pull/762#discussion_r764430924)

**Would you like to work on the issue?**
sure

**Comment by jingtang10** [comment]
With @shelaghm working on updated design, we need to think about dark/light theme for the entire app and not just the patient cards. Let's put this on the backlog until the new design is finalized before we start the work.

**Comment by shelaghm** [comment]
Thanks for looping me in @jingtang10, I'll add dark/light theme to the UX request list.

**Comment by jingtang10** [comment]
we need to
- [ ] document what's not working in dark mode
- [ ] verify if @santosh-pingle 's work has fixed some of the dark theme issues
- [ ] add dark mode to the QA test cases

**Comment by santosh-pingle** [comment]
Let me check whether issue is already fixed?

**Comment by santosh-pingle** [comment]
<img width="403" alt="Screenshot 2024-02-07 at 12 52 58" src="https://github.com/google/android-fhir/assets/86107848/7add410e-03fe-4ad0-bf3e-eaf15fbabe08">

**Comment by santosh-pingle** [comment]
With recent changes, issue is fixed.
