### ISSUE TITLE
In "Real-world lifelines questionnaire" under data capture library, it is showing number picker without any question name 

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#964]
**Describe the bug**
In "Real-world lifelines questionnaire" under data capture library, it is showing number picker without any question name 

**Component**
SDC gallery app

**To Reproduce**
1. Go to 'Data Capture Gallery'
2. Click on 'Real-world lifelines questionnaire'
3. Observe number picker below Marital status question

**Expected behavior**
It should have question title and alignment should be in line with other questions

**Screenshots**
![Screenshot_20211213-111208](https://user-images.githubusercontent.com/64417713/145758744-14300945-d3ee-46f9-9d32-875779379627.png)

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 11

**Comment by jingtang10** [comment]
This number picker is a custom widget and doesn't have a text view that displays the question. This is not a bug of the sdc lib, but an issue with the reference app.

**Comment by jingtang10** [comment]
this is working as intended. the widget itself is a custom widget. and we will be removing the questionnaire in @santosh-pingle and @shelaghm's work on the catalog app.
