### ISSUE TITLE
In data capture gallery app, in Questionnaire there is no place for user to provide answer

### ISSUE THREAD

**Issue by anita-vadverao** [google/android-fhir#966]
**Describe the bug**
In data capture gallery app, in Questionnaire there is no place for user to provide answer

**Component**
SDC gallery app

**To Reproduce**
1. Go to 'Data Capture Gallery'
2. Click on 'HIV Case Report'
3. in Personal information section, for "Gender" there is no place to provide answer
4. Please see attached screenshots

**Expected behavior**
Each Questionnaire should have answer section

**Screenshots**
![Screenshot_2021-12-14-11-24-43-532](https://user-images.githubusercontent.com/64417713/145941676-463b07b8-cdd1-4277-a487-0993ef929cd4.jpeg)
![Screenshot_2021-12-14-11-24-53-488](https://user-images.githubusercontent.com/64417713/145941678-803deb2e-a846-4b3a-88f2-1c6ed92cc0d1.jpeg)
![Screenshot_2021-12-14-11-25-38-846](https://user-images.githubusercontent.com/64417713/145941681-aee0d139-e0ab-446f-af73-b1752df1b198.jpeg)
![Screenshot_2021-12-14-11-25-47-924](https://user-images.githubusercontent.com/64417713/145941685-7d04260a-248a-4b81-8057-abcfc6aa828a.jpeg)

**Smartphone (please complete the following information):**
 - Device: Nokia 3.4
 - Android version: 11

**Comment by jingtang10** [comment]
There is an issue with this particular questionnaire. We will address this in: #928
