### ISSUE TITLE
Auto complete widget behaves strangely

### ISSUE THREAD

**Issue by jingtang10** [google/android-fhir#978]
**Describe the bug**

The auto complete widget has two problems

1. It's very difficult to focus on it, you have to click the very left side of it
2. Once you've input a chip, the text box disappears, which looks very odd

**Component**
Core library, SDC library, reference app, or SDC gallery app

**To Reproduce**
1. Go to SDC gallary app
2. Click on General Health Assessment Questionnaire
3. Try to focus on Q4: Do you have any existing conditions

**Expected behavior**
Focuse on the text input, and once typed in "asthma" and created the chip, the border of the input box still be there

**Actual behavior**
Cannot focus unless you click the very left side of the input box, and the border of the input box disappears once chip is created

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel6
 - Android version: 12
 - Build number: SD1A.210817.036

**Additional context**
NA

**Would you like to work on the issue?**
@aditya-07 can you take a look please?

**Comment by jingtang10** [comment]
Uploading autocomplete.mp4…

**Comment by Tarun-Bhardwaj** [comment]
@aditya-07 , could you pleaes provide an effort estimate to fix this issue?

**Comment by KhumboLihonga** [comment]
Just highlighting that this is a feature we really need. We have dropdowns that may contain over 100 answer options and being able to filter those items as the user types will be very useful.
