### ISSUE TITLE
SDC demo app landing page.

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#988]
**Is your feature request related to a problem? Please describe.**
1. Show Bottom navigation bar with Components and Layouts menus.  
2. On components menu click show component landing page. 
3. On layouts menu click show layout landing page.
4. On components landing page, show SDC supported components
5. On layout landing page, show layout items.  

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
In progress.

**Comment by santosh-pingle** [comment]
@shelaghm 
We need single drawable image for below icons, so that it can be set to the view.
 
Components :
Single choice, Open choice, Text field, Date Picker, Time picker, Modal, Slider, drop down, Image, Date Of birth, Date Range Picker, Unit options.

Layouts:
Default, Rea Only, Review, Paginated

We can refer bottom navigation menu icons as reference.

**Comment by shelaghm** [comment]
@santosh-pingle Done. I've sent you a message with link to Drive folder with svg files for each icon.

**Comment by santosh-pingle** [comment]
Icons are updated with vectors drawables. Thanks!

**Comment by shelaghm** [comment]
I've added the Boolean svg to the drive folder. @santosh-pingle

**Comment by santosh-pingle** [comment]
@shelaghm 
We need to add auto complete component to the component list, could please share the icon?

**Comment by shelaghm** [comment]
Sent via PM, also shared updated icons for the icons that previously had shadows

**Comment by Muakamas** [comment]
Hi!, I need good attractive and intuitive design for my new app, can you suggest me some examples ?
