### ISSUE TITLE
Sdc gallery app boolean choice component workflow

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#992]
**Is your feature request related to a problem? Please describe.**
1. Design boolean choice questionnaire json  without required fields. (error message will not be shown as field is not mandatory)
2. Api to retrieve single choice questionnaire json from model view.
3. Handle single choice item click
4. Implement questionnaire fragment and model view to show questionnaire json
5. Show action bar, update title as per screen, align title text.
6. Update color palette hex codes.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by santosh-pingle** [comment]
Continuing implementation ...

**Comment by santosh-pingle** [comment]
@shelaghm 
Sdc library has two views which support a single choice component (radio button).

- **QuestionnaireItemRadioGroupViewHolderFactory** : type is choice as per fhir specification, which can have a number of radio button options, and the user can select one out of them.

- **QuestionnaireItemBooleanTypePickerViewHolderFactory** : type is boolean as per fhir specification, which will have two radio button options `yes and no`.  And the user can select one out of them.

I am thinking of having 2 separate single choice components for `choice and boolean` type in the components list. Is it okay?

cc @jingtang10 @aditya-07

**Comment by shelaghm** [comment]
@santosh-pingle this makes sense to me to show both options as separate components. Please create a new githib issue and tag me.

Based on this I'll create a new icon for the Boolean choice and will use different example content for the two different components. I'll update the figma file to reflect this.

**Comment by santosh-pingle** [comment]
@shelaghm 
Thanks for sharing color palette!
Can you please also share color PrimaryVariant and color SecondaryVariant color hex code.

**Comment by shelaghm** [comment]
@santosh-pingle Decided we will not use PrimaryVariant and color SecondaryVariant color. Just posting it here so we close the loop on the decision.
