### ISSUE TITLE
Sdc gallery app, show bottom sheet. 

### ISSUE THREAD

**Issue by santosh-pingle** [google/android-fhir#997]
**Is your feature request related to a problem? Please describe.**
1. Show bottom sheet when user click on gear icon.
2. Show selection options on bottom sheet.  e.g show errors.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Would you like to work on the issue?**
Please state if this issue should be assigned to you or who you think could help to solve this issue.

**Comment by Manikant25** [comment]
@santosh-pingle  Can I do that gear button and bottom sheet?

**Comment by santosh-pingle** [comment]
@Manikant25 
Sure, these are p2 task as of now, you can work on it, if possible also check with @jingtang10
